LibOS/Makefile
LibOS/shim/test/Makefile
LibOS/shim/test/regression/Makefile
Pal/Makefile
Pal/ipc/linux/Makefile
Pal/lib/Makefile
Pal/regression/Makefile
Pal/src/Makefile
Pal/src/Makefile.Host
Pal/src/host/FreeBSD/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/sgx-driver/Makefile
Pal/src/host/Linux/Makefile
Pal/src/host/Skeleton/Makefile
Pal/src/security/Linux/Makefile
Pal/test/Makefile
Runtime/Makefile

There seems to be many build targets which lack .PHONY marker. Please check if I marked all of them correctly ;)

Add lacking .PHONY to Makefiles

---

LibOS/shim/src/shim_parser.c

Fix variadic functions implementation

---

Jenkinsfiles/Linux-SGX
Jenkinsfiles/ubuntu-16.04.dockerfile
LibOS/shim/test/apps/ltp/FLAKY
LibOS/shim/test/apps/ltp/PASSED

Add unit tests for Graphene-SGX to jenkins.

New Jenkinsfile for SGX enabled Graphene

---

LibOS/shim/include/shim_internal.h
LibOS/shim/src/shim_init.c
LibOS/shim/src/utils/printf.c

Fixes the pid printing bug mentioned in #100.

Fix numeric base confusion in pid printing

---

Pal/ipc/linux/graphene-ipc.c

This PR fixes the portability issues on Linux 4.11~4.15, due to 4 major changes:
(1) Adding a new argument `uf` to `do_mmap()`: https://elixir.bootlin.com/linux/v4.11/source/include/linux/mm.h#L2110
(2) Changing 4-level page table to 5-level: https://elixir.bootlin.com/linux/v4.11/source/include/asm-generic/5level-fixup.h#L12
(3) Renaming `SLAB_DESTROY_BY_RCU` to `SLAB_TYPESAFE_BY_RCU` (Linux 4.12+)
(4) `signal_pending()` moved to `linux/sched/signal.h`.

Porting PAL GIPC module to Linux 4.11~4.15

---

LibOS/shim/test/native/Makefile
LibOS/shim/test/native/shared_object.c
LibOS/shim/test/native/shared_object.manifest.template

This can be used to test if #54 is fixed.

Add shared_object to test/native

---

Tools/README
Tools/gen_manifest
Tools/gsce

This PR is adding a new tool named GSC (Graphene-SGX Secure Container), which seamlessly integrating Graphene-SGX and Docker Container such that the containerized application can be easily protected by Graphene-SGX while running inside Docker Container. 
For more details, check out at https://github.com/sslab-gatech/sgx-tutorial-ccs17. GSC is at page 38 – 41 of the libos slides.

Graphene-SGX Secure Container: Seamless Integration of Docker Container and Graphene-SGX

---

LibOS/shim/src/bookkeep/shim_vma.c

This assertion was useful to identify bugs (e.g, #159 ), even if they were hard to actually solve.  This code was not connected to anything after PR #183, and I think we should put it back.  
This assertion is only enabled with DEBUG=1, as it is rather expensive.  
I'm also hoping it will not actually show any bugs in CI.

Restore VMA list assertions, at least for the debug build.

---

Pal/src/host/Linux-SGX/sgx_main.c

The config variable points to a new allocated memory block inside of load_manifest() but it isn't cleaned up on two error handling branches.
also the mapped config_raw is not unmapped on last error handling branch before return.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/248)

Not clean up "config" and "config_raw" in error handling code

---

README.md

Changing the email address to support@grapehen-project.io.
Also fixing some formatting issue on the section headers (e.g., 2.1.1).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/284)

Update contact info in README.md

---

.clang-format
Pal/src/host/Linux/db_devices.c

This is primarily to get a stake in the ground for the automated formatting rules for the project.
Please take a look and review.  I plan to roll this out in phases (the next one being make rules to apply/check the changes).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/283)

First cut at a .clang-format for the project

---

LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/test/regression/80_epoll_wait_timeout.py
LibOS/shim/test/regression/epoll_wait_timeout.c

A trivial fix and a (less trivial) unit test for regression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/249)

Fixes oscarlab/graphene#239 (shim_do_epoll_wait ignores user-supplied timeout)

---

LibOS/Makefile
LibOS/shim/Makefile
Makefile
Pal/Makefile
Runtime/Makefile

Please double check if I didn't omit something or included some external dependencies (we don't want to reformat e.g. glibc source).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/331)

Add `make format` (clang-format support)

---

Pal/src/host/Skeleton/db_events.c
Pal/src/host/Skeleton/db_exception.c
Pal/src/host/Skeleton/db_ipc.c
Pal/src/host/Skeleton/db_memory.c
Pal/src/host/Skeleton/db_object.c
Pal/src/host/Skeleton/db_rtld.c
Pal/src/host/Skeleton/db_streams.c
Pal/src/host/Skeleton/host_endian.h

This makes the Skeleton PAL buildable on macOS for the OS-dependent part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/257)

Make the Skeleton PAL buildable again

---

CODESTYLE.md
CONTRIBUTING.md

Code style, for now only for C. Created according to what we decided in the policy doc, with additional formatting rules section.
Please verify if it's in line with our previous discussions and whether it's written in correct Am English.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/336)

Add CODESTYLE.md

---

Pal/ipc/linux/graphene-ipc.c

Botched totally the other request so this is it made again...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/269)

Fix kernel warning with CONFIG_DEBUG_VM on

---

.github/PULL_REQUEST_TEMPLATE.md

This a draft for the pull request template.
Here is a demo: https://github.com/chiache/graphene/pull/2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/285)

Creating a pull request template

---

.gitignore
LibOS/shim/test/Makefile
LibOS/shim/test/benchmark/.gitignore
LibOS/shim/test/benchmark/Makefile
LibOS/shim/test/benchmark/manifest.template
LibOS/shim/test/native/Makefile
LibOS/shim/test/regression/Makefile
Runtime/pal_loader

This patch series makes shim/test/benchmark build and run.
+ some minor trivial cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/273)

make Shim test benchmark work

---

LibOS/shim/src/fs/shim_fs.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/374)

Fix error propagation in __mount_others()

---

.github/PULL_REQUEST_TEMPLATE.md

In #285, I accidentally squashed a commit which addresses the suggestions of reviewers. This PR will reverse that squash. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/429)

Fix a few wording issues in the PR template

---

LibOS/shim/src/sys/shim_mmap.c

When pal mapping(DkVirtualMemoryAlloc or fs_ops->mmap) fails, vma is leaked.
free vma correctly in such case.
vma leak in shim_do_mmap() in error recovery path.
issue mmap() and debug_print_vma_list() to check vma list
--- …

[LibOS] shim_do_mmap leaks vma when pal mapping fails

---

LibOS/shim/test/apps/ltp/README

Old instructions didn't work because of wrong CWD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/458)

[LibOS] Fix commands in LTP readme

---

LibOS/shim/src/shim_checkpoint.c

restore_context() happens to use %rsp - 8 to return which is in redzone.
which clobbers redzone. It shouldn't be clobered.
So far it seems we're simply lucky.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/346)

LibOS: restore_context() clobbers redzone accidentally

---

LibOS/shim/src/shim_parser.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/350)

TIOCGPTN is missing a comma to separate it from other items

---

Pal/src/Makefile
Pal/src/host/FreeBSD/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux/Makefile

Some files are missed when "make clean"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/364)

Pal/Makefile: add more files to be cleaned

---

LibOS/Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/343)

LibOS/glibc: add glibc dependencies to Makefile

---

Pal/src/host/Linux-SGX/sgx_main.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/376)

Pal/Linux-SGX: remove unnecessary goto in initialize_enclave()

---

Pal/src/host/Linux-SGX/db_exception.c
Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/sgx_entry.S

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/386)

Pal/Linux-SGX: typo: externel -> external

---

Pal/src/host/FreeBSD/db_main.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_misc.c
Pal/src/host/Linux/pal.map
Pal/src/host/Linux/pal_linux.h
Pal/src/pal.h

Implements DkCpuIdRetrieve for Pal/Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/349)

Pal/Linux: support DkCpuIdRetrieve()

---

Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_pages.c
Pal/src/host/Linux/db_exception.c
Pal/src/pal_internal.h

Add __attribute__((format (printf, ))) to functions where appropriate.
and fix found format mismatch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/379)

Pal: add __attribute__((format (printf, )))

---

Pal/src/host/Linux-SGX/sgx_framework.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/signer/pal-sgx-get-token

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/528)

[Pal/Linux-SGX] debug print of token and secs::miscselect

---

LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/shim_malloc.c
LibOS/shim/src/sys/shim_mmap.c
Pal/lib/graphene/config.c
Pal/lib/list.h
Pal/lib/memmgr.h
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/slab.c

See commits.
Run regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/600)

Small fixes from ITL repo

---

Jenkinsfiles/ubuntu-16.04.dockerfile
LibOS/shim/test/regression/00_bootstrap.py
LibOS/shim/test/regression/30_futex.py
LibOS/shim/test/regression/30_mmap.py
LibOS/shim/test/regression/40_proc_path.py
LibOS/shim/test/regression/80_epoll_wait_timeout.py
LibOS/shim/test/regression/80_sockets.py
LibOS/shim/test/regression/90_large-mmap.py
LibOS/shim/test/regression/Makefile
Pal/regression/00_Atomics.py
Pal/regression/00_Bootstrap.py
Pal/regression/00_Symbols.py
Pal/regression/01_Exception.py
Pal/regression/02_Directory.py
Pal/regression/02_File.py
Pal/regression/02_Memory.py
Pal/regression/02_Misc.py
Pal/regression/02_Pipe.py
Pal/regression/02_Semaphore.py
Pal/regression/02_Socket.py
Pal/regression/02_Thread.py
Pal/regression/03_Process.py
Pal/regression/04_Ipc.py
Pal/regression/04_SendHandle.py
Pal/regression/05_Process.py
Pal/regression/05_Reference_Monitor.py
Pal/regression/06_AvxDisable.py
Pal/regression/Makefile
Scripts/regression.py

[*/regression] Migrate to Python 3
Run regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/605)

[*/regression] Migrate to Python 3

---

.github/PULL_REQUEST_TEMPLATE.md

Previous version emits unnecessary noise into the final PR description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/629)

[PR template] Turn filling instructions into a comment

---

LibOS/shim/src/elf/shim_rtld.c

pointer l was assigned by new_elf_object, which utilizes malloc to allocate memory buffer.
in the branch of call_lose, before returning NULL, allocated memory buffer l should be released to prevent resource leakage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/352)

[LibOS] Fix a memory leak in __map_elf_object() about variable pointer l

---

Pal/src/host/FreeBSD/db_files.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux/db_files.c

the memory allocation size is insufficient because of omitting the null termination.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/403)

[PAL] Fix insufficient allocation for uri with null termination

---

LibOS/shim/src/shim_init.c

when release allocated pointer array, current implementation didn't loop through the paths[i] but keep freeing paths[cnt].
This needs to be corrected. In addtion, after paths[i] is released, paths alse needs to be released
[482673]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/357)

[LibOS] Array of paths resources leak

---

Pal/src/host/Linux-SGX/db_threading.c

For now pal_thread_handle:tid isn't initialized.
Initialize pal_thread_handle:tid for debug purpose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/584)

[Pal/Linux-SGX] assign tid to pal_thread_handle

---

.github/PULL_REQUEST_TEMPLATE.md

Those are actually hints for the author of a PR, not for the later reader/reviewer, so they should be comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/701)

[PR template] Move more text into comments

---

LibOS/shim/src/shim_parser.c

Fixes #714.
In inline-debug mode (`debug = inline` in the manifest), the `Execve with invalid pointers in arguments` regression test failed.
The issue is that `parse_syscall_before()` and `parse_syscall_after()` functions were not hardened against invalid pointers and strings. These funcs are used in inline-debug mode and print out syscalls with their arguments in a user-friendly manner. However, these funcs did not test that pointers/strings are correct memory address/ranges. This PR adds such tests.
1. Set `debug=inline` in `manifest.template` for regression tests (`LibOS/shim/test/regression`).
2. Run the tests (`make regression`).
3. With this PR, all tests succeed. Previously, `Execve with invalid pointers in arguments` failed.
--- …

[LibOS] Test syscall arguments during parsing (in inline-debug mode)

---

Pal/regression/AvxDisable.manifest.template
Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/sgx_arch.h
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/657)

[Pal/Linux-SGX] use more symbolic value to pal-sgx-sign

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_table.h
LibOS/shim/src/Makefile
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_exit.c
LibOS/shim/src/sys/shim_poll.c
Makefile.rules
Pal/lib/Makefile
Pal/lib/assert.h
Pal/src/db_exception.c
Pal/src/db_process.c
Pal/src/db_threading.c
Pal/src/host/FreeBSD/db_process.c
Pal/src/host/Linux-SGX/Makefile.am
Pal/src/host/Linux-SGX/db_process.c
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux/Makefile.am
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Skeleton/db_process.c
Pal/src/pal.h
Pal/src/pal_internal.h
Pal/src/security/Linux/main.c

enable compiler option of -Wnull-dereference
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/719)

enable -Wnull-dereference

---

LibOS/shim/include/shim_profile.h
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/ipc/shim_ipc_child.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_malloc.c
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_msgget.c
LibOS/shim/src/sys/shim_poll.c
LibOS/shim/src/sys/shim_semget.c
LibOS/shim/src/sys/shim_wait.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/721)

[LibOS] fix typo CATAGORY to CATEGORY

---

Pal/lib/api.h
Pal/lib/network/inet_pton.c
Pal/src/host/Linux/Makefile
Pal/src/host/Linux/db_devices.c
Pal/src/host/Linux/db_exception.c
Pal/src/host/Linux/db_files.c
Pal/src/host/Linux/db_memory.c
Pal/src/host/Linux/db_misc.c
Pal/src/host/Linux/db_object.c
Pal/src/host/Linux/db_pipes.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/db_sockets.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Linux/db_threading.c
Pal/src/host/Linux/sysdep-x86_64.h
Pal/src/security/Linux/manifest.c

This PR enables -Wsign-compare in Linux PAL and fixes produced warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/722)

[Pal/Linux] Turn on -Wsign-compare and fix warnings

---

Pal/src/db_main.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/731)

[Pal] remove abused goto from db_main.c

---

HACKING.md

The purpose of this PR is to get rid of modelines eventually.
Add a `HACKING.md` to suggest editor configurations for Emacs and VIM. For Emacs, nothing needs to be done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/742)

Add suggestion for editor configuration

---

LibOS/shim/src/Makefile
LibOS/shim/src/shim.lds
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/Makefile.am
Pal/src/host/Linux-SGX/enclave.lds
Pal/src/host/Linux/Makefile.am
Pal/src/host/Linux/pal.lds

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/761)

enable read only relocation

---

LibOS/shim/src/shim_checkpoint.c

During checkpointing, qstr->oflow was redirected to point to the memory
region in the checkpoint but the old memory region was not freed. This
commit fixes this memory leak. It also removes unnecessary check for the
case when qstr->oflow and qstr->len are set incorrectly.
Regression tests must not fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/775)

[LibOS] Fix memory leak of qstr->oflow string during checkpointing

---

LibOS/shim/include/shim_table.h
LibOS/shim/include/shim_types.h
LibOS/shim/include/shim_unistd.h
LibOS/shim/include/shim_vma.h
LibOS/shim/src/shim_syscalls.c
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux/pal_linux.h

This code is tested to pass compilation on both 18.04 on 16.04. Will test with Jenkins 18.04 later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/792)

[Pal, LibOS] Fix compilation errors in Ubuntu 18.04

---

LibOS/shim/src/Makefile
Makefile.rules
Pal/lib/Makefile
Pal/src/Makefile
Pal/src/host/FreeBSD/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/Makefile.am
Pal/src/host/Linux/Makefile
Pal/src/host/Skeleton/Makefile
Pal/src/security/Linux/Makefile

refactor Makefile to utilize Makefile.rules
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/732)

Makefile refactoring

---

LibOS/shim/src/elf/shim_rtld.c

Fixes #473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/823)

Fix memory leak in __map_elf_object

---

Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX-18.04
Jenkinsfiles/ubuntu-18.04.dockerfile
Pal/regression/Bootstrap.c

This PR saves what I have done to set up jenkins files for 18.04, as well as fixes a unit test's compatibility with 18.04.
These jenkins tests will not pass, and should not be enabled yet.  This is just a checkpoint so that others can follow in finishing the debugging work.  There are several other unit tests that have minor incompatibilities with 18.04 like this one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/400)

Some work on 18.04 compatibility (and jenkins files)

---

LibOS/shim/src/sys/shim_mmap.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/822)

[LibOS/mmap] disallow mapping outside user address range

---

LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_fs.c
LibOS/shim/src/sys/shim_ioctl.c
Pal/src/host/Linux-SGX/enclave_pages.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/773)

code clean up: remove abused goto

---

.dir-locals.el

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/844)

[.dir-locals.el] add shell script mode

---

Tools/README

Added instructions for setting up Dockerfile before converting to a GSC image. 
Included a list of common errors and their respective resolutions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/835)

Updated GSC Readme

---

LibOS/shim/include/shim_checkpoint.h
LibOS/shim/include/shim_internal.h
LibOS/shim/src/fs/shim_namei.c
Pal/src/host/FreeBSD/db_files.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux/db_files.c
Pal/src/host/Skeleton/db_files.c
Pal/src/pal_internal.h

Popping up some typos in comments from my todolist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/853)

Fix some typos

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-Debug

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/839)

Update LTP tests to the upstream version

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

This PR reduces the run time of LMBench in Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/866)

Tune the run time of LMBench

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile

Build the graphene IPC kernel module in Jenkins, to curb risk of bitrot.
Run Jenkins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/703)

[CI] Test the build of graphene-ipc module

---

Pal/src/host/Linux-SGX/enclave_framework.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/918)

[Pal] Fix typos

---

.gitignore
Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
LibOS/Makefile
LibOS/shim/Makefile
LibOS/shim/src/Makefile
LibOS/shim/src/vdso/.gitignore
LibOS/shim/test/Makefile
LibOS/shim/test/native/Makefile
Makefile
Makefile.rules
Pal/Makefile
Pal/lib/Makefile
Pal/regression/Makefile
Pal/src/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux/Makefile
Pal/test/Makefile
Runtime/Makefile

See commit messages for description of the changes.
Fixes #189 and fixes #204.
Builds should work as before (note that building tests has been moved to a separate target).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/759)

Misc Makefile improvements

---

README.md

Add python3-pytest to the list of required packages on a new system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/914)

Add some documentation about required packages on a new system

---

LibOS/shim/test/native/Makefile
LibOS/shim/test/native/pie.c
LibOS/shim/test/native/static.c
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/test_libos.py
Makefile.configs
Makefile.rules

generate state-% from %.c to test static binary support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/563)

[LibOS/test/native] create static-xxx binary for test

---

Tools/gen_manifest
Tools/gsce

Several fixes on GSC including: 
- Forward container LD_LIBRARY_PATH to generated manifest
- Handle some special library names when generating trusted files (libxxx-xxx.so)
- Add missed files/fs to generated manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/816)

Some fixes on GSC for better handling container image

---

Pal/src/host/Linux-SGX/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/932)

[Pal/Linux-SGX] Makefile cleanup

---

LibOS/shim/test/Makefile
Makefile.rules
Pal/regression/Makefile
Pal/src/host/Linux-SGX/Makefile.Test
Pal/src/host/Linux/Makefile.test
Pal/test/Makefile

calculate bulidl dependency of .sgx, .sig, .token
so that make is able to rebuild those files..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/925)

Calculate build dependency of .sgx, .sig and .token

---

LibOS/shim/test/Makefile
LibOS/shim/test/Makefile.Test
LibOS/shim/test/benchmark/Makefile
LibOS/shim/test/inline/Makefile
LibOS/shim/test/native/Makefile
LibOS/shim/test/regression/Makefile
Pal/regression/Makefile
Pal/src/Makefile.Host
Pal/test/Makefile

Now all the Makefiles are converted to use Makefile.rules
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/929)

makefile cleanup

---

LibOS/shim/test/Makefile
LibOS/shim/test/Makefile.Test
LibOS/shim/test/benchmark/Makefile
LibOS/shim/test/inline/Makefile
LibOS/shim/test/native/Makefile
LibOS/shim/test/regression/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/931)

shim test makefile simplification

---

Pal/src/host/Linux-SGX/enclave_framework.c

Might help someone not familiar with all SGX related manifest entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/963)

[Pal/SGX] Add a helpful debug message when enclave attestation fails

---

LibOS/shim/src/Makefile
LibOS/shim/src/ipc/shim_ipc_pid.c
Pal/src/host/FreeBSD/Makefile.am
Pal/src/host/Linux-SGX/Makefile.am
Pal/src/host/Linux/Makefile.am

Issue described in #946
Fixes #946
Related issue #532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/947)

[LibOS] Fix nested function callbacks segfaulting

---

Pal/lib/graphene/path.c
Pal/regression/normalize_path.c

Improper macro caused most of the test cases not being run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/964)

[Pal] Fix normalize_path.c test bugs

---

README.rst

The code blocks in the Remote Attestation section is mistaken as quotes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/991)

[README] Fix the remote attestation section in README.rst

---

Pal/src/host/Linux-SGX/Makefile

Updated the IAS Root Cert URL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/993)

Update IAS root CA URL.

---

LibOS/shim/src/fs/proc/fs.c

Previously, there was a bug in `proc_match_name()`: iteration over a `proc_dir` array relied on `proc_dir.name == proc_dir.nm_ops == NULL`. However, there is no sentinel NULL item in actual arrays, which led to undefined behavior. This commit changes the for-loop condition to
check `proc_dir.size` and not rely on the NULL item.
This bug doesn't manifest in our current Graphene code (we are lucky that the pre-defined `proc/...` entries are stored somewhere in zeroed-out memory). However, this bug manifested when I tried to add emulation for `/proc/sys/vm/overcommit_memory`. If you want to test the bug and this fix, you can apply this patch:
```
diff --git a/LibOS/shim/src/fs/proc/fs.c b/LibOS/shim/src/fs/proc/fs.c
index 8e3ae55..bb24af2 100644
--- a/LibOS/shim/src/fs/proc/fs.c
+++ …
```

[LibOS] fs/proc/fs.c: Use proc_dir.size instead of proc_dir.name == NULL

---

Pal/src/host/Linux-SGX/enclave_ocalls.c

Previously, ocall_sock_recv() and ocall_sock_recv_fd() had a bug exposed when the underlying host recv/recvmsg syscall returned 0. Return value of 0 led to sgx_copy_to_enclave() to also return 0 which is treated as EPERM error. This commit omits calls to sgx_copy_to_enclave() when return value is 0 (since there is nothing to copy anyway).
Fixes #1001.
Build and start lighttpd: `make start-graphene-server` and run `./benchmark-http.sh 0.0.0.0:8000`. Should work flawlessly with this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1006)

[Pal/Linux-SGX] Fix OCALLs returning EPERM when recv returns 0

---

Documentation/howto-doc.rst
Jenkinsfiles/Docs-18.04
Jenkinsfiles/ubuntu-18.04.dockerfile

This would also require reconfiguring Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/968)

[Doc, Jenkins] Build documentation in Jenkins

---

Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/962)

[App] Clean up the Apache example

---

Pal/src/host/Linux-SGX/signer/pal-sgx-get-token

Cleanups
Before the patches applied:
```
Attributes:
mrenclave: 88e5c9a136b219dbec49c3b260adfb9a2b160476c05ccb726a80b956ac44fd9a
isvprodid: 0
isvsvn:    0
flags:     0600000000000000
xfrms:     0300000000000000
miscs:     00000000
miscmask:  00000000
modulus:   190e2d49ccda2097efa00061aa028d1e...
exponent:  3
signature: 98424dd3393c31b6f1bc36a39d88572a...
```
After the patches applied:
```
Attributes:
mrenclave: 88e5c9a136b219dbec49c3b260adfb9a2b160476c05ccb726a80b956ac44fd9a
isvprodid: 0
isvsvn:    0
flags:     0600000000000000
xfrms:     0300000000000000
miscs:     00000000
miscmask:  00000000
modulus:   190e2d49ccda2097efa00061aa028d1e...
exponent:  3
signature: 98424dd3393c31b6f1bc36a39d88572a...
date:      2019.9.25
```
--- …

[Pal/Linux-SGX] Cleanups for pal-sgx-get-token

---

Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Cleanup
make SGX=1 clean
make SGX=1 -j32
make SGX_RUN=1 -j32
./pal_loader SGX helloworld
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1021)

[Pal/Linux-SGX] Cleanups for pal-sgx-sign

---

Makefile.rules
Pal/regression/Makefile
Pal/src/host/Linux-SGX/Makefile.Test
Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/945)

[Makefile.rule, Pal/Linux-SGX]: pythonize dependency calculation of manifest

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-SGX
LibOS/Makefile
LibOS/shim/test/Makefile.Test
LibOS/shim/test/regression/Makefile
Makefile
Pal/ipc/linux/Makefile
Pal/regression/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Skeleton/Makefile
Pal/test/Makefile
Scripts/Makefile
Scripts/clean-check
Scripts/clean-check-prepare
Scripts/clean-check-test-copy

Fix make clean. There were a bunch of files which weren't cleaned up. This also adds a test to CI to check for such error in the future.
Depends on
https://github.com/oscarlab/graphene-sgx-driver/pull/6
https://github.com/oscarlab/graphene-tests/pull/31
See included test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/950)

Fix make clean

---

Pal/src/host/Linux-SGX/sgx_main.c

Bug fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1037)

[Pal/Linux-SGX] Trivial fixes

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/973)

[App] Clean up lighttpd example

---

README.rst

Just some light English polishing on the documentation.  I had an outstanding request to do this,
and thought I'd start with one to get used to any reST issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1015)

Polish the top-level README

---

LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/src/ipc/shim_ipc_sysv.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_parser.c
LibOS/shim/src/sys/shim_msgget.c
LibOS/shim/src/sys/shim_semget.c
LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/regression/large_dir_read.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/995)

remove warnings

---

Documentation/oldwiki/Introduction-to-Graphene.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1081)

[Doc] Fix using python-protobuf for Graphene-SGX build

---

LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/shim_async.c

To be fair, right now I don't see any path that would break anything, but that might change someday.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1074)

[LibOS] Move thread status checking after lock acquisition

---

Pal/src/host/Linux-SGX/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1087)

Fix sgx driver build failure

---

Pal/lib/api.h
Pal/src/host/Linux-SGX/sgx_main.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1086)

[Pal] Return false if zero is fed to IS_POWER_OF_2()

---

Pal/src/host/Linux-SGX/enclave_framework.c

`allowed_files` entries in sgx manifests are now properly normalized allowing for e.g. `sgx.allowed_files.whatever = file:./somefile`
Fixes #1044
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1078)

[Pal/SGX] Add path normalization to allowed files handling

---

README.rst

In my last PR, I intended to hide the url for the papers in the readme.  I believe this PR changes this behavior.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1111)

[Doc] Minor markup fix for README

---

Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_process.c
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1102)

Trivial fixes

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

Matching PR for https://github.com/oscarlab/graphene-tests/pull/49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1096)

Rewrite/update gcc (graphene-tests)

---

LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/spinlock.c
LibOS/shim/test/regression/test_libos.py
Pal/lib/spinlock.h

Spinlocks implementation, will come in handy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1098)

Add spinlocks

---

Pal/src/host/Linux-SGX/enclave_pages.c

Trivial fix to avoid future confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1130)

Fix comment on vma list

---

Pal/regression/File.c
Pal/regression/File.manifest.template
Pal/regression/test_pal.py
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1118)

[Pal/Linux-SGX] Fix sgx allow file creation

---

LibOS/shim/test/benchmark/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1154)

[LibOS/benchmark] Fix being unable to generate SGX tokens

---

CONTRIBUTING.md

This is a small correction to `CONTRIBUTING.md`. Copy-pasted commands didn't work.
Make sure that copy-pasting commands from the file work. This cannot be tested automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1160)

[Docs] fix test commands in CONTRIBUTING.md

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/956)

[App] Clean up the Python example

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

This PR adds a rewrite of Curl plus it adds Curl to Jenkins tests.
The corresponding PR is https://github.com/oscarlab/graphene-tests/pull/56.
Curl test must run correctly in Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1178)

[LibOS] test/apps: Rewrite Curl example

---

LibOS/shim/src/fs/chroot/fs.c

Actual `fsync` was never called during syscall handling. This change fixes it.
Fixes #1175 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1183)

[LibOS] Add DkStreamFlush() call in chroot_flush()

---

Documentation/howto-doc.rst
Documentation/oldwiki/Debugging-Graphene.md
Documentation/oldwiki/Graphene-Manifest-Syntax.md
Documentation/oldwiki/Graphene-Quick-Start.md
Documentation/oldwiki/Graphene-SGX-Manifest-Syntax.md
Documentation/oldwiki/Graphene-SGX-Quick-Start.md
Documentation/oldwiki/Implementing-New-System-Calls-in-Graphene.md
Documentation/oldwiki/Introduction-to-Graphene-SGX.md
Documentation/oldwiki/Introduction-to-Graphene.md
Documentation/oldwiki/PAL-Host-ABI.md
Documentation/oldwiki/Porting-Graphene-PAL-to-Other-hosts.md
Documentation/oldwiki/Process-Creation-in-Graphene-SGX.md
Documentation/oldwiki/Run-Applications-in-Graphene-SGX.md
Documentation/oldwiki/Run-Applications-in-Graphene.md
Documentation/oldwiki/Signal-Handling-in-Graphene.md
Documentation/oldwiki/Supported-System-Calls-in-Graphene.md

Fixed some links so they work on [readthedocs](https://graphene.readthedocs.io/en/latest/index.html) + working main menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1167)

[Doc] Fix main menu and links

---

LibOS/shim/src/Makefile
LibOS/shim/test/Makefile
LibOS/shim/test/native/Makefile
Pal/lib/Makefile
Pal/src/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1173)

[LibOS] Fix clean failure

---

LibOS/shim/include/shim_ipc.h
LibOS/shim/include/shim_ipc_ns.h
LibOS/shim/include/shim_sysv.h
LibOS/shim/include/shim_thread.h
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_poll.c

Make LibOS build with gcc-9 and linux 5.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1186)

[LibOS] make LibOS build with gcc-9 and linux 5.3.0

---

LibOS/shim/src/shim_async.c

- don't trigger callback during list traverse to avoid race
- fix memory leak in the case of install_async_event(object != NULL)
This case is used for AIO signaling. which is one shot.
async_list is protected by async_list_lock.
async_helper unoock async_list_lock before calling callback.
Once the lock is released, the list is unstable. install_async_event
may delete/append the entry. If next of FOR_EACH_LIST_SAFE
points can be freed while trigering callback. then next iteration may
reference freed pointer.
create a temporal list of triggered entry, and then trigger
callback after list traverse.
--- …

[LibOS] async helper: race on async_list

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/958)

[App] Cleanup the LMBench 2.5 example

---

Makefile.rules
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1204)

[Pal] insert "do not modify" line to generated file

---

LibOS/shim/src/sys/shim_clone.c

code clean up
no functional change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1223)

[LibOS] clone: remove stale comment

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_tcb.h
LibOS/shim/include/shim_thread.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_clone.c
Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/sgx_entry.S
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_thread.c
Pal/src/host/Linux-SGX/sgx_tls.h

See commit messages.
Fixes #1226.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1227)

[LibOS] shim tcb cleanup

---

LibOS/shim/src/sys/shim_socket.c

1. set address_received to true after receiving the address
2. avoid gap if pal_ret is less than iov_len.
Signed-off-by: jack.wxz <jack.wxz@alibaba-inc.com>
1. set address_received to true after receiving the address
2. avoid gap if pal_ret is less than iov_len
3. DkStreamRead will not return 0, so bytes must be greater than 0, so delete judgment (!bytes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1221)

[Libos] fix do_recvmsg()

---

LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/sys/shim_exit.c

Fixes #1249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1263)

[LibOS] Add error handling to helper threads

---

LibOS/shim/src/sys/shim_futex.c
Pal/lib/spinlock.h
Pal/src/host/Linux/db_threading.c

This PR adds debug functions to assert the state of a lock and makes use of them in futex implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1251)

[LibOS] Make spinlocks assertable

---

LibOS/shim/test/regression/test_libos.py
Pal/regression/test_pal.py

pylint on test_pal.py and test_libos.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1275)

pylint cleanup of test_pal.py and test_libos.py

---

LibOS/shim/test/regression/test_libos.py

Just a minor simplification.
`.ci/run-pylint` should pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1278)

[LibOS] test_libos.py: Simplify test_001_strict_fail

---

Pal/src/host/Linux-SGX/sgx_thread.c

There was a redundant spinlocks implementation, used only in one file.
This PR removes it in favor of the one from `Pal/lib`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1283)

[Pal-SGX] Remove redundant spinlocks implementation in sgx_thread.c

---

LibOS/shim/test/fs/Makefile
LibOS/shim/test/regression/Makefile
Pal/regression/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1295)

[LibOS] regression/Makefile: add dependency tokens to regression

---

.ci/run-shellcheck
Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
Jenkinsfiles/Linux-SGX-18.04-apps
Jenkinsfiles/Linux-SGX-apps
LibOS/shim/test/fs/.gitignore
Scripts/gitignore-test

Check for missing gitignores and fix found issues
Run Jenkinsfiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1287)

[Jenkins] Check for missing gitignores and fix found issues

---

Pal/src/host/Linux/db_main.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1311)

[Pal/Linux] 16-align stack before calling pal_linux_main

---

LibOS/Makefile
LibOS/shim/src/Makefile
LibOS/shim/test/benchmark/Makefile
LibOS/shim/test/fs/Makefile
LibOS/shim/test/inline/Makefile
LibOS/shim/test/native/Makefile
LibOS/shim/test/regression/Makefile
Pal/lib/Makefile
Pal/regression/Makefile
Pal/src/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux/Makefile
Pal/src/host/Skeleton/Makefile
Pal/test/Makefile
Runtime/Makefile
Scripts/Makefile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1303)

use $(RM) in Makefile and explicit list target

---

Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux-SGX/sgx_api.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux/db_files.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Linux/pal_host.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1322)

[Pal/{Linux, Linux-SGX}] use pread/pwrite instead of lseek + read/write

---

LibOS/shim/src/ipc/shim_ipc_sysv.c
LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/regression/large_dir_read.c
Pal/src/host/Linux/db_main.c

monir code cleanup as follow up of #976 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1134)

followup makefile cleanup

---

Pal/include/lib/pal_crypto.h
Pal/lib/crypto/adapters/mbedtls_adapter.c
Pal/src/host/Linux-SGX/db_devices.c
Pal/src/host/Linux-SGX/db_eventfd.c
Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux-SGX/db_process.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1342)

[Pal/Linux-SGX] make ocall_{read,write,recv,send}() return ssize_t

---

Pal/src/host/Linux-SGX/enclave_framework.c

Previously, Linux-SGX PAL performed a duplicated-files check in `register_trusted_file()` both during enclave initialization and at runtime (when creating a new file). This check involves full traversal of the trusted-files list which is slow in cases of huge number of trusted files (50K files). Moreover, this check is performed twice, for correctness in multi-threaded cases.
This commit keeps this check only during runtime and skips it during initialization (because manifest is assumed to have no duplicates). Skipping it significantly improves startup time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1362)

[Pal/Linux-SGX] Check for duplicated files only at runtime

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX-18.04-apps
Jenkinsfiles/Linux-SGX-apps
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile

This PR adds blender to CI
Matching PR in graphene-tests: https://github.com/oscarlab/graphene-tests/pull/75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1357)

[Jenkins] Add blender app to Jenkins

---

Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/sgx_api.h

make ustack allow nested by AEX.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1341)

[Pal/Linux-SGX] ocall: make ustack allow AEX

---

Documentation/glossary.rst
Documentation/sgx-intro.rst

This is very much work in progress, but comments are welcome (here or on #developers).
This is split from #1225.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1247)

Woju's SGX intro playground

---

Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux/db_pipes.c

Cleanup of the pipes' implementation in both PALs, including better comments and small fixups (proper `pipe_delete()`, proper error handling, proper nonblocking option).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1379)

[Pal/{Linux,Linux-SGX}] Refactor db_pipes.c code

---

Pal/include/lib/avl_tree.h
Pal/include/pal/pal_debug.h
Pal/lib/Makefile
Pal/lib/avl_tree.c
Pal/regression/.gitignore
Pal/regression/Hex.c
Pal/regression/Makefile
Pal/regression/avl_tree_test.c
Pal/regression/test_pal.py
Pal/src/pal-symbols

This PR adds trees (AVL) implementation to Graphene.
Added simple unit test to `Pal/regression`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1386)

[Pal/lib] Add generic trees (AVL)

---

Pal/include/lib/avl_tree.h
Pal/lib/avl_tree.c
Pal/regression/avl_tree_test.c

This PR adds two useful functions to avl trees.
There's a newly added code testing those functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1415)

[Pal/lib] Add avl_tree_first and avl_tree_last

---

LibOS/shim/include/shim_internal.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/shim_init.c
Pal/include/lib/api.h
Pal/src/host/Linux-SGX/db_exception.c

Fixes #597. No idea why this hack was needed for anything, everything seems to work correctly without it.
Jenkins + check if debugging and breakpoints on SGX still work for you (for me nothing has changed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1412)

[Linux-SGX] Don't skip int3

---

LibOS/shim/test/fs/.gitignore
LibOS/shim/test/fs/Makefile
LibOS/shim/test/fs/common.c
LibOS/shim/test/fs/open_close.c
LibOS/shim/test/fs/open_flags.c
LibOS/shim/test/fs/test_fs.py

9aaf1aa [LibOS] Fix read/write return check in FS tests
4beb2a8 [LibOS] Make open_close FS test more modular
5caf807 [LibOS] Add size checks to seek_tell FS test
8e88373 [LibOS] Add open_flags FS test
Run the tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1420)

Fixes/additions to LibOS FS tests

---

LibOS/glibc-patches/liblibos.patch
LibOS/shim/include/shim_checkpoint.h
LibOS/shim/include/shim_defs.h
LibOS/shim/include/shim_table.h
LibOS/shim/include/shim_unistd.h
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/shim_table.c
LibOS/shim/src/sys/shim_migrate.c

Current implementation isn't finished, doesn't have a single test and has quite bad code quality. If we decide we want to implement this feature, it will be easier to just implement it from scratch.
Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1424)

[LibOS] Remove checkpointing to files

---

README.rst

Hope this is the last survivor after #1422...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1437)

[Docs] Fix email formatting in README.rst

---

Examples/tensorflow/.gitignore
Examples/tensorflow/Makefile

Just some small fixups.
Build&run TensorFlow example and check `git status` afterwards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1459)

[Examples] TensorFlow: Fix Makefile and .gitignore

---

LibOS/shim/src/sys/shim_wait.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1465)

[LibOS] Add flags checking in wait4 syscall

---

LibOS/shim/src/sys/shim_brk.c

Fixes #1472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1475)

[LibOS] Disable reinitialization of brk after fork

---

LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/sys/shim_mmap.c

This is basically a port of #1344 to the new master.
Closes #1344 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1477)

[LibOS] Add checks of user address in mmap with MAP_FIXED

---

LibOS/shim/include/shim_thread.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/ipc/shim_ipc_child.c
LibOS/shim/src/sys/shim_sigaction.c

Removed simple threads:
- they are some issues with them (tho all fixable)
- they are not really used anywhere
- they seem useless
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1497)

[LibOS] Remove simple threads and shim_thread.c small cleanup

---

Examples/python-scipy-insecure/Makefile
Examples/python-scipy-insecure/python.manifest.template
LibOS/Makefile
Pal/crt_init/Makefile
Pal/lib/Makefile
Pal/lib/crypto/adapters/mbedtls_adapter.c
Scripts/Makefile.Host
Scripts/Makefile.configs

This PR addresses several x86_64 conditional build issues, such as building certain files and setting compile time flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1523)

[PAL+LibOS] x86_64 conditional builds  issues

---

Pal/lib/stdlib/printfmt.c

See this discussion: https://reviewable.io/reviews/oscarlab/graphene/1509#-M7Oaveu0kNi9uJ0NTiu
Changes:
- ifdefs for 32-bit x86 were removed, as they seem to actually break %ll* on 32-bit instead of fixing it.
- Two helper functions were modified to support weird `va_list` definitions (e.g. as an array, as it is on GCC for PPC64).
- Some other minor cleanups.
Closes #1509.
@stefanberger Please take a look and check if this resolves the `va_list` problem on PPC64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1524)

[Pal] Clean up *printf formatting utilities

---

Documentation/index.rst
Documentation/sgx-intro.rst

My notes from LKML.
build docs-18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1540)

Documentation: SGX patchset chronicles and list sgx-intro in TOC

---

LibOS/shim/include/shim_table.h
LibOS/shim/include/shim_types.h
LibOS/shim/src/Makefile
LibOS/shim/src/shim_syscalls.c
LibOS/shim/test/regression/futex_bitset.c
LibOS/shim/test/regression/sigaction_per_process.c
Pal/include/arch/x86_64/dl-machine.h
Pal/include/arch/x86_64/rng-arch.h
Pal/lib/crypto/adapters/mbedtls_adapter.c
Pal/regression/Makefile
Pal/regression/Memory.c
Pal/src/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux/Makefile
Pal/src/host/Linux/db_exception.c
Pal/src/host/Linux/db_misc.c
Pal/src/host/Skeleton/Makefile

This series of patches addresses as series of nits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1526)

[PAL+LibOS] Address a series of nits

---

CONTRIBUTING.rst

This adds the current management team membership and adding/joining procedures to our contributing document.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1493)

[Doc] Import policies on the management team

---

LibOS/shim/src/shim_parser.c

Change 'va_list ap' to 'va_list *ap' where necessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1527)

[LibOS] Change 'va_list ap' to 'va_list *ap' where necessary

---

README.rst

We should be more explicit about the state of the project and its problems.
Related PR: https://github.com/oscarlab/graphene-sgx-driver/pull/20.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1556)

Add non-production disclaimers

---

Pal/include/host/Linux-common/bogomips.h
Pal/include/lib/api.h
Pal/lib/Makefile
Pal/lib/string/strstr.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-common/bogomips.c
Pal/src/host/Linux/db_main.c

Refactor the code for getting bogomips from the host's proc filesystem so that some functions can be reused for other architectures that will parse the same type of file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1557)

[PAL] Refactor code getting bogomips from host's proc filesystem

---

Pal/include/arch/x86_64/Linux/ucontext.h
Pal/src/host/Linux-SGX/sgx_exception.c
Pal/src/host/Linux/db_exception.c

Implement pal_ucontext_get_ip().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1567)

[PAL] Implement pal_ucontext_get_ip()

---

Pal/src/host/Linux/db_exception.c

Previously, the Linux PAL invoked signal handlers on pending signals on the leaving-PAL-function code path. However, the code forgot to "hide" pending signals before invocation. Since LibOS signal handlers may call back into PAL and trigger leaving-PAL-function code path again, the PAL would try to deliver the same pending signals again. This led to an infinite loop.
This PR removes this nesting by simply "hiding" pending signals before the first invocation.
All tests must pass. Also, dummy HTTP server in `python-simple` must be terminated by SIGTERM now. See also #1576 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1579)

[Pal/Linux] Avoid invoking signal handlers in a nested fashion

---

LibOS/shim/src/bookkeep/shim_signal.c
Pal/include/arch/x86_64/pal-arch.h

Implement pal_context_has_user_pagefault
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1582)

[PAL+LibOS] Implement pal_context_has_user_pagefault

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_thread.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/fs/eventfd/fs.c
LibOS/shim/src/fs/pipe/fs.c
LibOS/shim/src/fs/socket/fs.c
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/ipc/shim_ipc_nsimpl.h
LibOS/shim/src/shim_async.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_malloc.c
LibOS/shim/src/shim_object.c
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_eventfd.c
LibOS/shim/src/sys/shim_ioctl.c
LibOS/shim/src/sys/shim_mmap.c
LibOS/shim/src/sys/shim_msgget.c
LibOS/shim/src/sys/shim_pipe.c
LibOS/shim/src/sys/shim_socket.c
LibOS/shim/src/sys/shim_time.c

A few small things which accumulated on my todolist.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1590)

[LibOS] A few minor cleanups

---

Pal/src/host/Linux-SGX/db_events.c
Pal/src/host/Linux-SGX/db_mutex.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux/db_events.c
Pal/src/host/Linux/db_mutex.c
Pal/src/host/Linux/pal_host.h

This PR converts futexes from int64_t to int's.
Fixes #1485.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1574)

[PAL/PAL-SGX] Convert futexes to ints

---

Pal/src/host/Linux-SGX/sgx_enclave.c

Previously, the Exitless feature forced all untrusted RPC threads to spin forever while waiting for new syscall requests from enclave threads. This led to constant high CPU utilization even on idle workloads.
This PR adds simple logic for RPC threads to first spin for a while and then perform short nanosleeps. This heuristic significantly reduces CPU utilization at the penalty of increased latency in case when syscall request arrives when RPC thread is sleeping.
All tests must pass. You can try out this PR with Memcached and Redis (don't forget to add `sgx.rpc_thread_num = 123` in the manifest template). With this PR, idle Memcached/Redis server consumes very little CPU (20-40%). Without this PR, it was 600-800% (depending on the number of untrusted RPC threads).
--- …

[Pal/Linux-SGX] Exitless: let untrusted RPC threads sleep

---

LibOS/shim/include/shim_checkpoint.h
LibOS/shim/include/shim_defs.h
LibOS/shim/include/shim_utils.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/fs/shim_dcache.c
LibOS/shim/src/fs/shim_fs.c
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_debug.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_brk.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_fork.c

This PR mostly renames and simplifies the logic inside `shim_checkpoint.{c,h}`.
This PR still leaves checkpointing macros as-is; this will be fixed in a folow-up PR.
All tests must run. This PR is pure refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1591)

[LibOS] Refactor checkpointing code

---

LibOS/shim/include/arch/x86_64/shim_tcb-arch.h
LibOS/shim/include/shim_tcb.h
LibOS/shim/include/shim_thread.h
LibOS/shim/src/shim_init.c

Make update_fs_base an inline function with an arch-specific part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1603)

LibOS: Make update_fs_base an inline function with an arch-specific part

---

Pal/src/host/Linux-SGX/db_main-x86_64.c
Pal/src/host/Linux-SGX/db_misc.c
Pal/src/host/Linux/db_main-x86_64.c
Pal/src/host/Linux/db_misc.c

Move x86_64-specifics from db_misc.c to db_main-x86_64.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1604)

PAL: Move x86_64-specifics from db_misc.c to db_main-x86_64.c

---

LibOS/shim/include/arch/x86_64/shim_tcb-arch.h
LibOS/shim/include/arch/x86_64/shim_vdso-arch.h
LibOS/shim/include/shim_unistd_defs.h
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/test/ltp/ltp.cfg
LibOS/shim/test/native/clone.c
LibOS/shim/test/regression/proc_cpuinfo.c
LibOS/shim/test/regression/unix.c

Various small changes to LibOS and LibOS test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1611)

[LibOS] Various changes/improvements

---

LibOS/shim/test/ltp/Makefile
LibOS/shim/test/ltp/Makefile.Test
LibOS/shim/test/ltp/Makefile.testcases
LibOS/shim/test/ltp/manifest.template

This PR enables running LTP on Fedora. (also using #1470)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1617)

[LTP] Enable running LTP on Fedora

---

LibOS/shim/src/elf/shim_rtld.c

Enabling this macro breaks the build due to a typo: `OBJECT_INTERNVAL`. `git blame` points to "The first official release" commit, which means that no one used it since at least 2014. We can safely get rid of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1635)

[LibOS] Drop broken BOOKKEEP_INTERNAL_OBJ

---

Examples/python-simple/run-tests.sh
LibOS/shim/test/ltp/ltp.cfg

Two small fixes for recent problems noticed in our tests.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1669)

Misc fixes for tests

---

README.rst

Move "not production-ready" warning up to make it more visible.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1684)

[README] Move "not production-ready" warning up to make it more visible

---

Documentation/manifest-syntax.rst
Documentation/manpages/gsc.rst
Pal/src/host/Linux-SGX/protected-files/README.rst

Now that Protected Files are merged into master, we need to add info on Protected Files in GSC and manifest syntax to our documentation.
readthedocs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1679)

[Docs] Add info on Protected Files in GSC and manifest syntax

---

LICENSE.addendum.txt
Pal/include/lib/api.h
Pal/lib/string/memcmp.c
Pal/lib/string/memcpy.c
Pal/lib/string/memset.c
Pal/lib/string/strcmp.c

Follow-up to #1637, this time for `memset()`, plus some minor clean-ups.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1708)

[Pal] Simplify memset and clean up other string ops

---

Examples/r/Makefile
Examples/r/R.manifest.template
Examples/r/rm.manifest.template
Examples/r/sh.manifest.template
LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_ipc.h
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/ipc/shim_ipc_nsimpl.h
LibOS/shim/src/ipc/shim_ipc_pid.c
LibOS/shim/src/ipc/shim_ipc_sysv.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/utils/printf.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_thread.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_threading.c

Fixes partially #1390 ("[Examples] R is broken").
I started working on fixing this example, but it turned out to be a complex task, so I'm dumping my current progress. There are a few unrelated fixes/refactors in this PR (but in separate commits), I can split it into smaller PRs if anyone prefers.
The reason I didn't add R example to the CI is that it triggers one more bug in Graphene, which I gave up fixing because Graphene's IPC code is obfuscated :) More about this in #1724. Anyway, this happens during the clean-up, so the main R's functionality should work now.
```Bash
cd Examples/r
make SGX=1 DEBUG=1
SGX=1 ./pal_loader R.manifest --slave --vanilla -f scripts/sample.r
```
--- …

A step towards making R example work

---

Documentation/index.rst
Documentation/perf-practices.rst

This PR adds a document with performance tuning and analysis of Graphene with the SGX backend. This document should be a live document and updated when new features are introduced or performance bugs in Graphene are fixed or new SGX hardware/software is released.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1720)

[Docs] Add document with Graphene performance tuning and analysis

---

LibOS/shim/src/utils/printf.c

Now it looks like this for app threads:
`[P30658:T1:multi_pthread] ---- return from shim_futex(...) = 0`
And like this for internal Graphene threads:
`[P30658:i2:multi_pthread] Async helper thread terminated`
Check debug output. Example:
```
...
[P30658:T1:multi_pthread] Deleting port 0xa9c6048 (handle 0xb996efb) of process 30658
[P30658:i1:multi_pthread] New IPC event was requested (port was added/removed)
[P30658:T1:multi_pthread] process 30658 exited with status 0
[P30658:i1:multi_pthread] IPC helper thread terminated
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1756)

[LibOS] Improve PID+TID prefix in debug output

---

Tools/gsc/templates/manifest.template

This PR updates GSC to follow the renaming of commit [324b248852e12f31ff8c42691f68339b9dd28c58](https://github.com/oscarlab/graphene/commit/324b248852e12f31ff8c42691f68339b9dd28c58).
Run regular Jenkins testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1753)

Follow rename of execname to arg0_override in GSC

---

LibOS/shim/include/shim_handle.h
LibOS/shim/src/sys/shim_fcntl.c

Fix a bug introduced in #1754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1760)

Fix a bug introduced in 2abb2f325e7431c4726d207a0a335e16f4db7f0e

---

.github/ISSUE_TEMPLATE.md

We had a few issues reported recently about bugs which were already fixed on master, let's make this requirement clear in the issue template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1751)

[Docs] Ask issue reporters to use up-to-date master

---

LibOS/shim/include/shim_handle.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/fs/shim_dcache.c
LibOS/shim/src/fs/shim_fs.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_fork.c
LibOS/shim/src/utils/strobjs.c
LibOS/shim/test/regression/.gitignore
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/pipe_ocloexec.c
LibOS/shim/test/regression/test_libos.py
Pal/include/lib/memmgr.h

Miscellaneous fixes, mostly in ref-counting and epoll areas. Refer to each commit message for the description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1763)

Miscellaneous reference counting and epoll fixes

---

Jenkinsfiles/Linux-SGX-gsc
Tools/gsc/templates/apploader.template
Tools/gsc/test/Makefile
Tools/gsc/test/ubuntu18.04-python3-trusted-args.dockerfile

Changed GSC Jenkins tests to include testing of Linux PAL integration of GSC and the use of trusted arguments.
Run GSC Jenkins pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1755)

Improve testing of GSC

---

LibOS/shim/src/Makefile
LibOS/shim/src/syscallas-x86_64.S
Pal/include/lib/hex.h
Pal/include/pal/generated-offsets-build.h
Pal/src/host/Linux-SGX/Makefile.am
Pal/src/host/Linux/Makefile.am
Scripts/Makefile.rules

See #1794.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1801)

More clang fixes

---

README.rst

Adjust language in the readme to be more clear about the state of the project, per last team discussion.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1808)

[Doc] Adjust language in the readme

---

Documentation/devel/howto-doc.rst
Documentation/requirements.txt

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1730)

[Documentation] Add README.md and change requirements.txt

---

.github/PULL_REQUEST_TEMPLATE.md

A small tweak suggested by @bigdata-memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1824)

[Docs] Mention "Fixes #xyz" in GitHub's PR template

---

LibOS/shim/include/arch/x86_64/shim_syscalls.h
LibOS/shim/include/shim_table.h
LibOS/shim/src/Makefile
LibOS/shim/src/shim_parser.c
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/shim_table-x86_64.c
LibOS/shim/src/sys/shim_getrandom.c
LibOS/shim/test/ltp/ltp.cfg

Fixes #1829.
LTP tests enabled in this PR should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1838)

[LibOS] Implement getrandom syscall

---

Examples/memcached/Makefile
Examples/memcached/README
Examples/memcached/memcached.manifest.template
Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX-18.04-apps
Jenkinsfiles/Linux-SGX-apps
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile

Tried Memcached on Ubuntu 18.04 and found out it doesn't build correctly. Updated everything.
Also removed "unset environment variables" from the manifest because this is done by default in modern Graphene.
This PR adds Memcached to our Jenkins CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1807)

[Examples] Update Memcached to run on Ubuntu 18.04 and build correctly

---

LibOS/shim/test/ltp/Makefile
LibOS/shim/test/ltp/ltp-bug-1248.cfg
LibOS/shim/test/ltp/ltp.cfg
LibOS/shim/test/ltp/makevars.mk

I noticed that some LTPs are actually working or don't require extended timeout.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1845)

[LibOS] test/ltp: Enable more tests

---

Documentation/cloud-deployment.rst

This PR updates the description of cloud deployments in Azure confidential compute VMs, due to a recent update in their kernel and SGX driver.
Jenkens should test the document generation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1860)

Update Azure confidential compute VM deployment description

---

LICENSE.addendum.txt
Pal/include/lib/api.h
Pal/lib/Makefile
Pal/lib/string/strcmp.c
Pal/lib/string/strspn.c

These functions are required by the TOML C source code, which will be embedded into Graphene in a future PR.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1888)

[Pal/lib] Add strncmp() and strspn() string manipulation funcs

---

LibOS/shim/test/ltp/Makefile
LibOS/shim/test/ltp/contrib/conf_lint.py
LibOS/shim/test/ltp/ltp-bug-1075.cfg
LibOS/shim/test/ltp/ltp-sgx.cfg
LibOS/shim/test/ltp/ltp.cfg
LibOS/shim/test/ltp/runltp_xml.py

I ran into several issues while running the LTP tests manually. This PR contains mostly tweaks so that it's easier to run LTP locally and analyze the results.
Jenkins should still pass LTP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1899)

LTP tweaks

---

LibOS/shim/include/shim_handle.h
LibOS/shim/include/shim_ipc.h
LibOS/shim/include/shim_thread.h
LibOS/shim/include/shim_types.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/ipc/shim_ipc_child.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/ipc/shim_ipc_pid.c
LibOS/shim/src/ipc/shim_ipc_ranges.c
LibOS/shim/src/ipc/shim_ipc_sysv.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/sys/shim_msgget.c
LibOS/shim/src/sys/shim_semget.c

Just stuff that was annoying to work with in other PRs. For description about changes refer to specific commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1912)

[LibOS] Small random IPC cleanups

---

Tools/gsc/templates/apploader.template

I guess this has never worked?
CC: @vahldiek
Try to use `GSC_PAL` env.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1896)

[GSC] Fix a bug in apploader's arguments testing

---

Pal/src/slab.c

The PAL slab memory allocator is used for internal PAL memory objects, in particular, for parsing the manifest. The allocator mostly allocates from a 64MB static array. Previously, the allocator dind't free memory at all. This led to PAL using too much memory (especially in GSC where manifests are huge). This commit adds a couple simple tricks to allow for freeing memory in typical cases (especially realloc).
All tests must pass. I haven't noticed regression in performance. And I see much lower peak memory utilization (in my TOML manifest experiments).
```
$ /usr/bin/time -v ~/graphene/Runtime/pal_loader Bootstrap7
Maximum resident set size (kbytes): 4084  # BAD
$ /usr/bin/time -v ~/graphene/Runtime/pal_loader Bootstrap7
Maximum resident set size (kbytes): 15996 # REALLY BAD
$ …
```

[Pal] Add poor-man's deallocation in slab's memory management

---

LICENSE.addendum.txt
Pal/include/lib/api.h
Pal/lib/Makefile
Pal/lib/string/atoi.c
Pal/lib/string/ctype.c

These functions are required by the TOML C source code, which will be embedded into Graphene in a future commit.
All tests must pass. TOML is coming soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1926)

[Pal/lib] Add strtoll() and funcs from ctype.h for string manipulation

---

LibOS/shim/test/ltp/Makefile
LibOS/shim/test/ltp/README.rst
LibOS/shim/test/ltp/contrib/conf_lint.py
LibOS/shim/test/ltp/contrib/conf_subtract.py
LibOS/shim/test/ltp/ltp-all.cfg
LibOS/shim/test/ltp/ltp-sgx.cfg
LibOS/shim/test/ltp/ltp.cfg

I went through about 30% of LTP failures and documented them. I also collapsed some test groups for features that we don't implement (e.g. `[statfs*]` or `[symlink*]`).
In addition, this makes `ltp-sgx.cfg` an override of `ltp.cfg`, so that the configurations are not duplicated.
I might continue it if there is time later, but I hope this is already worth merging. After this PR, I will upgrade LTP to newest version (and also go through the new failures).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1906)

LTP cleanup

---

LibOS/shim/include/shim_utils.h
LibOS/shim/src/shim_init.c

Just a bit of refactoring. This code annoyed me too much.
All tests must work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1929)

[LibOS] Remove create_{dir,file,handle}() and refactor create_pipe()

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile
LibOS/shim/test/ltp/ltp-bug-1075.cfg
LibOS/shim/test/ltp/ltp-sgx.cfg
LibOS/shim/test/ltp/ltp.cfg
LibOS/shim/test/ltp/runltp_xml.py

Based on #1906.
Some interesting failures that can be investigated (marked with TODO).
Important also because the older LTP fails to compile with new GCC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1907)

Upgrade LTP to 20200930

---

Pal/include/lib/slabmgr.h

Slab memory manager logic uses enlarge_slab_mgr() (renamed to more accurate maybe_enlarge_slab_mgr()) to allocate a new chunk of memory for its slab objects. For allocation itself, slab manager must release the lock before system malloc and then re-acquire it. At this point other threads may allocate memory for the same slab level. Also, system malloc may fail to allocate large memory region, and slab logic will fall back to allocating smaller memory region. These two issues were not properly handled; this commit fixes these bugs.
Interestingly, this fix is exactly the same as in Isaku's #1347.
Closes #1347 (with my current PR, we'll merge all bug fixes that Isaku introduced in that PR).
This bug was detected and debugged on a large application running with >160 threads. Here is a …

[Pal/lib] Fix data race on memory allocation in slab memory manager

---

.pylintrc

quick pylint fix, needed for #1909 and #1876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1936)

pylint: add some overrides

---

LibOS/shim/include/shim_internal.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_epoll.c

They all lacked error checking and `wait_event` was completely broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1953)

[LibOS] Fix wait_event

---

LibOS/shim/src/sys/shim_futex.c

…structure in order to improve futex search times when there are a lot of threads in operation.
This results in specjbb benchmark improvements of upto 22x with pure graphene, and upto 65% with graphene sgx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1921)

[LibOS] Move from linked list to avl trees for managing futexes

---

LibOS/shim/src/sys/shim_fs.c

Current Graphene sendfile implementation doesn't check O_APPEND flag and tries to transfer data and transfers wrong data.
This commit updates sendfile to align with manual
"EINVAL out_fd has the O_APPEND flag set.  This is not currently supported by sendfile()."
Also fixes not matched get_handle/put_handle. It can cause memory leak when only one of ofd/ifd is invalid.
fixes #1967
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1969)

[LibOS] fix sendfile to return EINVAL when out_fd has O_APPEND flag

---

LibOS/shim/include/arch/x86_64/shim_internal-arch.h
LibOS/shim/include/shim_internal.h
Pal/include/lib/api.h

This PR has some minor architecture cleanups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1987)

[Pal,LibOS] Minor architecture cleanups

---

.ci/lib/config.jenkinsfile
.ci/linux-direct-ubuntu16.04-gcc-debug.jenkinsfile
.ci/linux-direct-ubuntu16.04-gcc-glibc223.jenkinsfile
.ci/linux-direct-ubuntu16.04-gcc-release.jenkinsfile
.ci/linux-direct-ubuntu18.04-gcc-debug.jenkinsfile
.ci/linux-direct-ubuntu18.04-gcc-glibc227.jenkinsfile
.ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
.ci/linux-sgx-ubuntu16.04-gcc-release-apps.jenkinsfile
.ci/linux-sgx-ubuntu16.04-gcc-release.jenkinsfile
.ci/linux-sgx-ubuntu18.04-gcc-release-apps.jenkinsfile
.ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile

This is needed for testing arbitrary /dev passthrough.
Needed for #1959.
@dimakuv
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1992)

[CI] Add /dev/kmsg device to docker

---

.ci/linux-direct-ubuntu16.04-gcc-debug.jenkinsfile
.ci/linux-direct-ubuntu16.04-gcc-glibc223.jenkinsfile
.ci/linux-direct-ubuntu16.04-gcc-release.jenkinsfile
.ci/linux-direct-ubuntu18.04-gcc-debug.jenkinsfile
.ci/linux-direct-ubuntu18.04-gcc-glibc227.jenkinsfile
.ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
.ci/linux-sgx-ubuntu16.04-gcc-release-apps.jenkinsfile
.ci/linux-sgx-ubuntu16.04-gcc-release.jenkinsfile
.ci/linux-sgx-ubuntu18.04-gcc-release-apps.jenkinsfile
.ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
Jenkinsfiles/.gitignore
Jenkinsfiles/Docs-18.04
Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
Jenkinsfiles/Linux-SGX-18.04-apps
Jenkinsfiles/Linux-SGX-apps
Jenkinsfiles/Linux-SGX-gsc

See #1858 for explanation. To be merged after that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1859)

Modular Jenkins, stage 2

---

Pal/include/lib/slabmgr.h
Pal/src/slab.c

Add proper size alignment in slabmgr.h and slab.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2010)

[Pal/LibOS] Add proper size alignment in slabmgr.h and slab.c

---

LibOS/shim/src/fs/shim_namei.c

Found out that following a link was broken. Looks like it was a typo. Fixing the typo made my rework of `/proc` FS work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2015)

[LibOS] Fix following the link in FS subsystem

---

LibOS/shim/src/shim_async.c

The Async helper thread traverses through the `async_event` list of scheduled events and copies the triggered events in the `triggered` list. Theoretically, each event may be present in both lists at the same time, so the event struct must have two `LIST_TYPE` fields. However, there was a bug: both lists were described by a single `list` field. In cases where the event's `list` was rewired to the `triggered` list, it suddenly disappeared from the `async_event` list, which led to a hang of Graphene.
All tests must pass. Try running Nginx and then doing Ctrl-C: without this PR it hangs, with this PR it terminates gracefully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/ …

[LibOS] Fix incorrect use of LISTP macros in Async helper thread

---

Pal/include/host/Linux-SGX/host_endian.h
Pal/include/host/Linux/host_endian.h
Pal/include/host/Skeleton/host_endian.h
Pal/lib/network/hton.c
Pal/src/pal_rtld.h

`host_endian.h` is not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2042)

[Pal/include] Remove not needed host_endian.h

---

Pal/src/host/Linux-SGX/db_files.c

Previously, Linux-SGX PAL turned out to call `ocall_mmap_untrusted()` twice: first during `file_open()` and then during `file_map()`. This hurts performance and not needed, so this PR removes one mmap.
Co-authored-by: Isaku Yamahata <isaku.yamahata@gmail.com>
Closes #1324 (this PR corresponds to the last commit of that series; the first commit there is already fixed on master, the second and third commits are unneeded optimizations).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2048)

[Pal/Linux-SGX] Do not call redundant ocall_mmap_untrusted() on file_map()

---

Examples/gcc/Makefile

In case one mirror is down, as it is happening right now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2088)

[Examples/gcc] Add more mirrors for downloading static files

---

LibOS/shim/include/arch/x86_64/shim_internal-arch.h
LibOS/shim/include/shim_internal.h
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/ipc/shim_ipc_child.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/ipc/shim_ipc_pid.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_exit.c
LibOS/shim/src/utils/printf.c
Pal/include/arch/x86_64/cpu.h
Pal/regression/Hex.c
Pal/src/db_exception.c
Pal/src/db_process.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_process.c
Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_exception.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux/db_exception.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Skeleton/db_process.c
Pal/src/host/Skeleton/db_threading.c
Pal/src/slab.c

This is a couple of simple commits stashed together (not to spam with PR, for easier merging - they are really simple).
For details check commit descriptions.
Normal tests + run some long living app spawning some temporary processes and observe lack of zombies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2083)

Reap zombies + miscellaneous fixes around exit calls

---

LibOS/shim/include/shim_checkpoint.h
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/src/fs/shim_fs_hash.c
LibOS/shim/src/fs/shim_fs_pseudo.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/sys/shim_open.c

This PR contains 2 UBSAN fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2089)

UBSAN fixes

---

Pal/regression/File.c
Pal/regression/test_pal.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2085)

[PAL] Make test case work with PAGE_SIZE != 4096

---

Examples/gcc/Makefile
Examples/ra-tls-mbedtls/Makefile
Examples/ra-tls-secret-prov/Makefile
Examples/redis/Makefile
Pal/lib/Makefile
Pal/src/host/Linux-SGX/tools/common/Makefile

We've experienced intermittent github.com outage, so add our own mirror.
CI should stop failing for network/DNS problems with github.com.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2119)

[CI] Add download mirror

---

Documentation/quickstart.rst
Examples/pytorch/Makefile
Examples/pytorch/README.md
LibOS/shim/include/shim_fs.h
LibOS/shim/include/shim_handle.h
LibOS/shim/src/fs/chroot/fs.c
Pal/src/host/Linux-SGX/db_exception.c
Pal/src/host/Linux-SGX/sgx_framework.c
Pal/src/pal_internal.h
README.rst

Just another bunch of little changes which has accumulated on my todolist.
FYI: the comment reformatting was motivated by Sublime Text wrongly autodetecting indentation in `pal_internal.h`. Reformatting to our official style fixes the problem.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2125)

Misc fixes

---

Documentation/devel/performance.rst

Some new manifest options were added. Also, we now know that spreading across NUMA domains are quite bad for SGX.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2167)

[Docs] Add some new info on performance tuning

---

.ci/lib/config.jenkinsfile
.ci/lib/stage-build-sgx.jenkinsfile

See individual commits.
Jenkins should pass on both old and new nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2192)

CI fixes after kernel 5.4-fsgs

---

Pal/src/host/Linux-SGX/db_exception.c

Untrusted PAL can inject an external event (e.g. `PAL_EVENT_INTERRUPTED`). Such events need to be validated against a white list of valid events.
Fixes #598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2197)

[PAL/Linux-SGX] Add external event sanitization

---

CONTRIBUTING.rst
LibOS/shim/include/shim_sysv.h
LibOS/shim/include/shim_utils.h
LibOS/shim/src/sys/shim_msgget.c
LibOS/shim/src/sys/shim_socket.c
LibOS/shim/src/utils/printf.c
Pal/include/lib/api.h
Pal/include/lib/memmgr.h
Pal/include/lib/slabmgr.h
Pal/lib/stdlib/printfmt.c
Pal/src/db_streams.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux-SGX/enclave_untrusted.c
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux-SGX/sgx_graphene.c
Pal/src/host/Linux/db_sockets.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Linux/pal_linux.h
Pal/src/host/Skeleton/db_streams.c
Pal/src/pal_internal.h
Pal/src/printf.c
Pal/src/slab.c

As usual, a bunch of fixes for things which annoyed me recently enough to create a PR. If some of the changes will turn out to be controversial, a can split this into smaller PRs.
No functional changes, except that some functions will properly support big buffers now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2181)

Misc fixes, including using size_t for sizes

---

LibOS/shim/include/shim_defs.h
LibOS/shim/src/fs/chroot/fs.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_pf.c

See commits messages.
Normal test suite + overflow repro from @mkow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2209)

[LibOS] Increase internal stack size

---

CONTRIBUTING.rst

As decided with the maintainers, let's add @pwmarcz to the group.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2219)

[Docs] Update maintainers list

---

LibOS/shim/src/utils/printf.c
Pal/include/host/Linux-common/linux_utils.h
Pal/include/pal/pal.h
Pal/lib/crypto/adapters/mbedtls_adapter.c
Pal/lib/crypto/adapters/mbedtls_dh.c
Pal/regression/Bootstrap.c
Pal/src/db_streams.c
Pal/src/host/Linux-SGX/db_misc.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux-SGX/db_threading.c
Pal/src/host/Linux-SGX/sgx_framework.c
Pal/src/host/Linux-SGX/sgx_platform.c
Pal/src/host/Linux-SGX/sgx_process.c
Pal/src/host/Linux-common/file_utils.c
Pal/src/host/Linux/db_misc.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Skeleton/db_misc.c
Pal/src/host/Skeleton/db_streams.c
Pal/src/pal_internal.h

I triggered this bug when implementing directory support in trusted files.
Generate a huge manifest and try Bash example with iteration count 100.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2232)

[Pal] Introduce EINTR-safe {read,write}_all wrappers

---

Documentation/tutorials/pytorch/index.rst

Signed-off-by: Unnikrishnan Nair, Rahul <rahulunair@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2240)

update sgx install doc link

---

LibOS/shim/include/shim_handle.h
LibOS/shim/include/shim_ipc.h
LibOS/shim/include/shim_sysv.h
LibOS/shim/include/shim_utils.h
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/ipc/shim_ipc_pid.c
LibOS/shim/src/ipc/shim_ipc_ranges.c
LibOS/shim/src/ipc/shim_ipc_sysv.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_exit.c
LibOS/shim/src/sys/shim_msgget.c
LibOS/shim/src/sys/shim_semget.c

For details please refer to commit messages. All changes are loosely connected - it's all preparation for removing `shim_ipc_info`.
As usual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2263)

[LibOS] Some IPC changes

---

Documentation/attestation.rst

Just a couple tiny fixes for the Attestation document. People from Intel asked me to fix these bugs.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2271)

[Docs] Add tiny changes to Attestation document

---

LibOS/shim/include/shim_ipc.h
LibOS/shim/include/shim_signal.h
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/ipc/shim_ipc_pid.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/sys/shim_sigaction.c
LibOS/shim/test/regression/.gitignore
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/kill_all.c
LibOS/shim/test/regression/test_libos.py

Described in commit messages.
New LibOS regression test added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2276)

[LibOS] IPC kill messages and broadcast minor cleanup

---

LibOS/shim/include/shim_process.h
LibOS/shim/src/bookkeep/shim_process.c
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/src/shim_init.c

Signed-off-by: Sankaranarayanan Venkatasubramanian <svenkat9>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2180)

[LibOS] procfs: Add support for /proc/self/cmdline

---

Documentation/manifest-syntax.rst

Fixes #2284.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2285)

Fix ISV SVN typo in docs

---

LibOS/shim/include/shim_checkpoint.h
LibOS/shim/include/shim_ipc.h
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/ipc/shim_ipc_pid.c
LibOS/shim/src/ipc/shim_ipc_ranges.c
LibOS/shim/src/ipc/shim_ipc_sysv.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/sys/shim_clone.c

Actually it was moved into `shim_ipc_ranges.c`, but is now private to that file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2290)

[LibOS] Remove `shim_ipc_info`

---

README.rst

Kudos for @monavij and @donporter for refreshing the text!
Use GitHub's rich diff to check if it renders correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2300)

[Docs] Update the main readme

---

Pal/include/lib/pal_crypto.h
Pal/lib/crypto/adapters/mbedtls_adapter.c

Seems like the RSA crypto functions are legacy. They are not used anywhere, so let's just remove them.
All tests should work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2310)

[Pal/lib] Remove unused RSA crypto

---

.ci/lib/config-ubuntu20.04.jenkinsfile
.ci/linux-direct-ubuntu20.04-gcc-debug.jenkinsfile
.ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
.ci/linux-sgx-ubuntu20.04-gcc-release-apps.jenkinsfile
.ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
.ci/ubuntu20.04.dockerfile
Documentation/devel/packaging.rst
Documentation/index.rst
Examples/blender/Makefile
Examples/memcached/Makefile
LibOS/shim/test/regression/Makefile
Pal/regression/Makefile
Tools/gsc/gsc.py

This adds pipelines for testing Ubuntu 20.04.
20.04 pipelines should pass (I shall add them shortly).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2272)

[CI] Add Ubuntu 20.04 LTS (focal) pipelines

---

LibOS/shim/include/shim_handle.h
LibOS/shim/include/shim_internal.h
LibOS/shim/src/fs/eventfd/fs.c
LibOS/shim/src/fs/pipe/fs.c
LibOS/shim/src/fs/socket/fs.c
LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/regression/.gitignore
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/epoll_epollet.c
LibOS/shim/test/regression/test_libos.py

Description of implementation in the code.
Added a new test. ~Currently does not work due to #1717~ Added an if to work even with that bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2338)

[LibOS] Add EPOLLET implementation

---

LibOS/shim/include/shim_fs.h
LibOS/shim/src/fs/shim_namei.c

Applying feedback left by @boryspoplawski in #2333 (after we merged it). It's mostly TODOs for various corner cases, and one fix to how we count references.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2354)

[LibOS] Update for path lookup functions

---

Documentation/pal/host-abi.rst
LibOS/shim/include/shim_lock.h
LibOS/shim/include/shim_thread.h
LibOS/shim/src/shim_object.c
Pal/include/host/Linux-common/linux_utils.h
Pal/include/lib/api.h
Pal/include/pal/pal.h
Pal/regression/Event.c
Pal/regression/Symbols.c
Pal/regression/test_pal.py
Pal/src/db_events.c
Pal/src/db_object.c
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/db_events.c
Pal/src/host/Linux-SGX/db_object.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-common/timespec_utils.c
Pal/src/host/Linux/Makefile
Pal/src/host/Linux/db_events.c
Pal/src/host/Linux/db_object.c
Pal/src/host/Skeleton/db_events.c
Pal/src/host/Skeleton/db_object.c
Pal/src/pal-symbols
Pal/src/pal_internal.h

These changes are needed to correctly emulate `nanosleep` syscall.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2368)

[Pal] Return remaining time in DkEventWait

---

LibOS/shim/include/shim_ipc.h
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/ipc/shim_ipc_child.c
LibOS/shim/src/ipc/shim_ipc_pid.c
LibOS/shim/src/ipc/shim_ipc_ranges.c
LibOS/shim/src/ipc/shim_ipc_sysv.c
LibOS/shim/src/ipc/shim_ipc_worker.c
LibOS/shim/src/sys/shim_semget.c

This is a split of from a follow-up PR, which reworks IPC message responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2424)

[LibOS] Split header from IPC messages

---

Documentation/tutorials/pytorch/index.rst

This is a re-implementation of #2307. Unfortunately, the original author (@ltinerary) didn't finish the PR, so I just created a new one. I don't know how to add @ltinerary as the original author in the commit message, since there is no name and email.
Closes #2307.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2431)

[Docs] Fix library paths in the PyTorch tutorial

---

Pal/src/db_rtld.c
Pal/src/db_streams.c
Pal/src/host/Linux-SGX/db_eventfd.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_misc.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/db_threading.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c
Pal/src/host/Linux-SGX/protected-files/protected_files.c
Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
Pal/src/host/Linux/db_eventfd.c
Pal/src/host/Linux/db_files.c
Pal/src/host/Linux/db_sockets.c
Pal/src/host/Linux/db_threading.c

See commit messages for the details.
Read the fixes carefully, almost all of them are on error paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2441)

Fixes for issues found by Klocwork

---

Documentation/devel/coding-style.rst
LibOS/shim/include/shim_table.h
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_rtld.c
LibOS/shim/src/sys/shim_wrappers.c
LibOS/shim/test/regression/bootstrap.c
LibOS/shim/test/regression/poll.c
LibOS/shim/test/regression/ppoll.c
LibOS/shim/test/regression/pselect.c
LibOS/shim/test/regression/select.c
Pal/include/pal_internal.h
Pal/regression/File.c
Pal/src/db_rtld.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_misc.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux/arch/x86_64/db_arch_misc.c
Pal/src/host/Linux/db_sockets.c
Pal/src/host/Skeleton/db_sockets.c

Finally fixes #152. I omitted some places in FS, which Paweł is now rewriting, to avoid conflicts.
Just review + CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2445)

Fix names and types used for memory sizes

---

Documentation/conf.py

Just a simple fixup, the footnote on RTD was quite outdated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2469)

[Docs] Update copyright years range

---

LICENSE.addendum.txt

We forgot to add the TOML license to our licenses file.
The TOML library we use is this: https://github.com/cktan/tomlc99
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2464)

Add TOML license to `LICENSE.addendum.txt`

---

Documentation/building.rst
Documentation/index.rst
Documentation/manifest-syntax.rst

Small changes to our Building doc + link to https://graphene-contrib.readthedocs.io/en/latest/
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2460)

[Docs] Add link to graphene-contrib docs and improve Building

---

Pal/src/host/Linux-SGX/sgx_profile.c
common/include/api_fortified.h

Fixes #2456.
Build with `SGX=1 DEBUGOPT=1` and test if profiling works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2476)

[Pal/Linux-SGX] Fix building with DEBUGOPT=1

---

LibOS/shim/src/ipc/shim_ipc.c

If an error occurred while sending an IPC message, the connection was removed (which could happen twice due to buggy implementation).
Now in such case the connection is not removed, but the error is saved and any further writes to that connection will immediately return the saved error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2487)

[LibOS] Do not remove IPC connection on errors

---

Documentation/attestation.rst
Documentation/manifest-syntax.rst
Pal/src/host/Linux-SGX/protected-files/README.rst

This PR was split from #2328. Contains only simple changes to documentation.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2482)

[Docs] Update documentation on Protected Files and the PF wrap key

---

meson.build

This is the proposed commit for v1.2-rc1 tagging. Please validate the current state carefully and check if there aren't any blockers. If not, this will be the release candidate for 1.2.
There will also be a changelog, but this will be added to GitHub release notes when we publish it.
Run everything you know :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2518)

Version v1.2-rc1

---

README.rst

Time to refresh the readme :)
Check "Rich diff" on GitHub to see if its renderer works fine with this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2523)

[Docs] Update README.rst after publishing v1.2rc1

---

Documentation/tutorials/pytorch/index.rst
Examples/pytorch/Makefile
Examples/pytorch/README.md

corrected command to download the pretrained model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2502)

[Examples,Docs] Fix pytorch download-model instructions

---

Pal/include/host/Linux-common/linux_utils.h
Pal/include/pal_internal.h
Pal/src/db_main.c
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux-SGX/db_process.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/pal_security.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_process.c
Pal/src/host/Linux-common/graphene_unix_socket_addr.c
Pal/src/host/Linux-common/meson.build
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_pipes.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/pal_host.h
Pal/src/host/Linux/pal_linux.h

Check each commit message for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2525)

[Pal] Make Graphene UNIX socket paths unique

---

Pal/src/host/Linux-SGX/enclave_ocalls.c

Now on each `ocall_gettime` we compare the returned value with the one returned in a previous call and bail out if it's smaller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2554)

[Pal/SGX] Sanitize `ocall_gettime` return value

---

Pal/src/host/Linux-SGX/sgx_main.c

The code relied on the assumption that the program headers will fit within FILEBUF_SIZE bytes from beginning of file. This is usually true in practice, but is not guaranteed, and as a result Graphene could read outside of the allocated buffer.
Instead, we perform two reads: first for the ELF header, then for the program headers.
Existing tests should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2562)

[Pal/Linux-SGX] Allocate program headers when reading ELFs

---

LibOS/meson.build
meson.build

Sort out some x86_64-specific stuff in the meson build files.
Run the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2569)

Sort out some x86_64 stuff from the meson build

---

Documentation/quickstart.rst
Examples/gcc/README.md

This is in response to https://github.com/oscarlab/graphene/issues/2605 and https://github.com/oscarlab/graphene/issues/2489. Adding some notes on known issues on RedHat, CentOS, Fedora family of OS distros.
Fixes #2605. Fixes #2489.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2611)

[Docs,Examples] Add notes on RHEL/CentOS/Fedora

---

Pal/src/host/Linux-SGX/enclave_ocalls.c

As part of OCALL hardening, on OCALL return, we now verify and restrict possibly malicious return values. In most OCALL cases, we check against the set of permissible error codes (taken from corresponding syscall man pages and combined together for multi-syscall OCALLs).
Fixes #634.
All tests must pass. Must run several times to be sure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2621)

[Pal/Linux-SGX] Restrict possible error codes on OCALL returns

---

LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/shim_rtld.c

Should help in cases like #2632 and #2633.
Try to run invalid/non-existent executables and check the errors printed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2634)

Improve errors in the loader

---

.ci/lib/stage-build-nosgx.jenkinsfile
.ci/lib/stage-build-sgx.jenkinsfile
Documentation/building.rst
Documentation/cloud-deployment.rst
Documentation/devel/coding-style.rst
Documentation/devel/debugging.rst
Documentation/manpages/gsc.rst
Documentation/quickstart.rst
Documentation/tutorials/pytorch/index.rst

Add missing dependencies (Ubuntu-specific) and add a note on Meson reconfiguration after the first `meson build`.
Fixes #2627.
Fixes #2623.
Read the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2629)

[Docs] Improve QuickStart guide

---

LibOS/shim/src/shim_rtld.c

See #2639.
Fixes #2639.
Run `execve03` from LTP tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2640)

[LibOS] Adjust errors in execve()'s corner cases

---

README.rst

This will be probably the last PR merged in this repo :) CU at https://github.com/gramineproject/gramine!
Render the new text using GitHub Markdown renderer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/graphene/2683)

[Docs] Add repo migration note to the README
