Pal/src/host/Linux-SGX/db_streams.c, Pal/src/host/Linux/db_streams.c
This PR contains two commits dealing with `_DkSendHandle()` and `_DkReceiveHandle()` -- the first function serializes a given PAL handle and sends to the child process, the second function receives this serialized PAL handle and deserializes it.
- [Pal/{Linux,Linux-SGX}] Refactor _DkSendHandle() and _DkReceiveHandle(). In Graphene, these two functions are used to serialize the PAL handle and send it on a process stream (socketpair) to another (usually child) process, and vice versa. This commit simply refactors their code without any logic changes.
- [Pal/Linux-SGX] Encrypt messages in _DkSendHandle()/_DkReceiveHandle(). Previously, _DkSendHandle() and _DkReceiveHandle() of Linux-SGX PAL sent serialized PAL handles (with their metadata like paths, socket addresses, etc.) in plaintext via …
=> [Pal/{Linux,Linux-SGX}] Refactor _DkSendHandle() and _DkReceiveHandle() and encrypt

Documentation/conf.py, Documentation/manpages/ias_request.rst, Documentation/manpages/is_sgx_available.rst, Documentation/manpages/quote_dump.rst, Documentation/manpages/verify_ias_report.rst, LICENSE.addendum.txt, Pal/lib/Makefile, Pal/src/host/Linux-SGX/sgx_arch.h, Pal/src/host/Linux-SGX/sgx_attest.h, Pal/src/host/Linux-SGX/tools/Makefile, Pal/src/host/Linux-SGX/tools/README.rst, Pal/src/host/Linux-SGX/tools/common/Makefile, Pal/src/host/Linux-SGX/tools/common/attestation.c, Pal/src/host/Linux-SGX/tools/common/attestation.h, Pal/src/host/Linux-SGX/tools/common/ias.c, Pal/src/host/Linux-SGX/tools/common/ias.h, Pal/src/host/Linux-SGX/tools/common/util.c, Pal/src/host/Linux-SGX/tools/common/util.h, Pal/src/host/Linux-SGX/tools/ias-request/.gitignore, Pal/src/host/Linux-SGX/tools/ias-request/Makefile, Pal/src/host/Linux-SGX/tools/ias-request/ias_request.c, Pal/src/host/Linux-SGX/tools/is-sgx-available/.gitignore, Pal/src/host/Linux-SGX/tools/is-sgx-available/Makefile, Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, Pal/src/host/Linux-SGX/tools/quote-dump/.gitignore, Pal/src/host/Linux-SGX/tools/quote-dump/Makefile, Pal/src/host/Linux-SGX/tools/quote-dump/quote_dump.c, Pal/src/host/Linux-SGX/tools/verify-ias-report/.gitignore, Pal/src/host/Linux-SGX/tools/verify-ias-report/Makefile, Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c
Added standalone (non-graphene) SGX utilities:
- `is_sgx_available` for checking environment for SGX compatibility
- `quote_dump` for displaying internal quote structure
- `ias_request` for sending IAS requests (SigRL retrieval and quote verification)
- `verify_ias_report` for verifying IAS attestation reports (and quote contents)
- `libsgx_util.so` shared library with functionality of these tools (see `.h` files)
- run `make install` to install tools and the library
Run the tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1371)
=> [SGX] Add standalone SGX utilities

LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/echo.manifest.template, LibOS/shim/test/regression/eventfd.manifest.template, LibOS/shim/test/regression/exec_victim.manifest.template, LibOS/shim/test/regression/exit_group.manifest.template, LibOS/shim/test/regression/file_check_policy_allow_all_but_log.manifest.template, LibOS/shim/test/regression/file_check_policy_strict.manifest.template, LibOS/shim/test/regression/futex_bitset.manifest.template, LibOS/shim/test/regression/futex_requeue.manifest.template, LibOS/shim/test/regression/futex_wake_op.manifest.template, LibOS/shim/test/regression/getdents.manifest.template, LibOS/shim/test/regression/host_root_fs.manifest.template, LibOS/shim/test/regression/init_fail.manifest.template, LibOS/shim/test/regression/large-mmap.manifest.template, LibOS/shim/test/regression/mmap-file.manifest.template, LibOS/shim/test/regression/multi_pthread.manifest.template, LibOS/shim/test/regression/multi_pthread_exitless.manifest.template, LibOS/shim/test/regression/openmp.manifest.template, LibOS/shim/test/regression/proc-path.manifest.template, LibOS/shim/test/regression/sh.manifest.template, LibOS/shim/test/regression/shared_object.manifest.template, LibOS/shim/test/regression/system.c, LibOS/shim/test/regression/test_libos.py
Glibc 2.31 implements system() POSIX function call via a combination of `clone(CLONE_VM|CLONE_VFORK|SIGCHLD, <child_stack_addr>, ...)` and `execve()`. This special case was not supported by Graphene. Moreover, Glibc 2.31 allocates a child stack and puts some variables on this child stack. After clone, the child process tries to access these variables on the child stack. However, previously Graphene always assumed that the child process returns on the same (parent) stack. Therefore, restored RSP in the child did not point to the child stack but to the parent stack, which triggered segfaults in Glibc.
This PR fixes this by temporarily rewiring the current thread (the one issuing `clone(VFORK, ...)`) so that it points to the provided child stack, and then rewiring it back to the original …
=> [LibOS] Introduce test for system() and fix bug with Glibc 2.31

LibOS/shim/include/shim_internal.h, LibOS/shim/src/sys/shim_futex.c, Pal/include/lib/spinlock.h
If a thread was killed during critical section in our futexes implementation, it would not release a global lock (`g_futex_list_lock`). Later, at program exit, one thread would call `release_clear_child_id` which would hang trying to acquire that lock.
This PR disables all signals when inside the critical section in `shim_futex.c`.
I was able to trigger this bug running blender example, with SGX and no debug - without this patch hitting a bug once in ~10 runs (hang after blender exit).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1393)
=> [LibOS] Disable signals in critical section in shim_futex.c

LibOS/shim/include/shim_fs.h, LibOS/shim/src/Makefile, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/dev/fs.c, LibOS/shim/src/fs/dev/null.c, LibOS/shim/src/fs/dev/random.c, LibOS/shim/src/fs/dev/std.c, LibOS/shim/src/fs/dev/zero.c, LibOS/shim/src/fs/proc/fs.c, LibOS/shim/src/fs/proc/info.c, LibOS/shim/src/fs/proc/ipc-thread.c, LibOS/shim/src/fs/proc/thread.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/dev.c, LibOS/shim/test/regression/proc.c, LibOS/shim/test/regression/test_libos.py
Previously, `/proc` and `/dev` pseudo-filesystems were implemented in completely different ways. This PR introduces a set of generic functions for all pseudo-FSs (based on previous implementation of `/proc`) and refactors both `/proc` and `/dev` to use these functions.
This PR also expands a LibOS test `proc` to cover more cases and pseudo-files, as well as introduces a new LibOS test `dev`. Several bugs in pseudo-FSs were detected and fixed in the process.
Also bug https://github.com/oscarlab/graphene/issues/1387 was found while working on this PR. This PR however does *not* fix it, merely circumvents it.
LibOS test `proc` was significantly expanded. New LibOS test `dev` was added.
--- …
=> [LibOS] Refactor implementation of /proc and /dev pseudo-FSs

LibOS/shim/src/sys/shim_clone.c, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux/db_main.c
This series of patch fixes some minor issues:
- returns proper CPU count on single CPU machines
- reports only those clone parameters in debug output that actually matter due to flags being set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1395)
=> [LibOS+PAL] Fix minor issues

LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/sighandler_reset.c, LibOS/shim/test/regression/test_libos.py
This patch prevents a signal handler that has the SA_RESETHAND flag set
from disappearing when a signal is appended. We do this by passing an
additional boolean to the __get_sighandler() function that allows us to
control whether the signal handler may be reset or not. It is only
desirable to reset the signal handler if an actual invocation of the
handler function occurs, not when only asking 'where is the handler?'
I noticed signals not being handled anymore while porting Graphene to PowerPC64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1401)
=> LibOS: Prevent signal handler from disappearing due to SA_RESETHAND

LibOS/shim/include/shim_types.h, LibOS/shim/src/sys/shim_socket.c
This series of patches reworks inet_copy_addr() to be more careful in writing the response into a buffer that is big enough particularly when using IPv6. Previously an IPv6 socket would write into a 'struct sockaddr' and cause stack corruption because this data structure is to small to be casted to sockaddr_in6!
I detected this problem during my port of Graphene to PowerPC64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1396)
=> [LibOS] Avoid stack smashing when a socket is an IPv6 socket

Documentation/building.rst, Documentation/oldwiki/Introduction-to-Graphene-SGX.rst, Documentation/quickstart.rst, Jenkinsfiles/Linux-SGX-18.04, Pal/lib/Makefile, Pal/src/host/Linux-SGX/generated-offsets.c, Pal/src/host/Linux-SGX/sgx_framework.c, Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
Corresponding SGX driver PR is https://github.com/oscarlab/graphene-sgx-driver/pull/7.
Closes #881. Fixes #1403. 
I have tested this code on Azure’s Confidential Compute VM Deployment instance (Ubuntu 18.04).
DCAP driver does not have `einittoken` in `struct sgx_enclave_init` ([Link](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/driver/linux/include/uapi/asm/sgx.h)), so related codes must be modified accordingly.
Before running `make` in `$GRAPHENE_DIR/Pal/src/host/Linux-SGX/sgx-driver/`, `sgx_user.h` must be symlinked as follows:
```
cp -r /usr/src/sgx-1.10 ~/
cd ~/sgx-1.10
ln -s include/uapi/asm/sgx.h sgx_user.h
```
Also, input `~/sgx-1.10` when "Enter the Intel SGX driver directory" is prompted in the following step.
Note that graphene driver must be modified …
=> [SGX] Add DCAP support

LibOS/shim/test/ltp/ltp-sgx.cfg, LibOS/shim/test/ltp/ltp.cfg, Pal/regression/Exception.c, Pal/regression/test_pal.py, Pal/src/host/Linux-SGX/enclave_ecalls.c, Pal/src/host/Linux-SGX/enclave_entry.S, Pal/src/host/Linux-SGX/pal_linux_defs.h, Pal/src/host/Linux-SGX/sgx_exception.c, Pal/src/host/Linux-SGX/sgx_thread.c, Pal/src/host/Linux/db_exception.c, Pal/src/host/Linux/db_threading.c, Pal/src/host/Linux/pal_linux_defs.h
Untrusted stack is used for ocall. The argument is allocated by subtracting
from untrusted stack. which is managed by enclave_tls::ustack.
On the other hand, for AEX, GPR::ursp is used. As result the area below
the untrusted stack can be clobbered by signal handler in untrusted code.
Use sgx_pal_gpr_t::ursp instead of enclave_tls::ustack to manage the argument
for ocall so that signal handler for AEX doesn't clobber them.
I guess that the reason why this doesn't matter much is, usually the size
of argument is less than red zone (128 bytes). So the signal frame doesn't
overlap with it.
(Other option is, allocate dedicated stack for ocall.)
Closes #527. Closes #1025. Fixes #486.
--- …
=> [Pal/Linux-SGX] resolve race condition to use ustack for ocall and AEX

Pal/src/host/Linux-SGX/tools/common/attestation.c
#1406 accidentally broke debug builds with SGX PAL. This was possible because unfortunately we don't test this configuration on Jenkins. This PR fixes this regression.
Just build with `SGX=1 DEBUG=1`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1409)
=> [Linux-SGX] tools: Fix debug builds

LibOS/shim/test/ltp/manifest.template, LibOS/shim/test/regression/exec_victim.manifest.template, LibOS/shim/test/regression/proc-path.manifest.template
Because of https://github.com/oscarlab/graphene/issues/1408 (Elf relocations do not work correctly for small base addresses) a few tests were crashing from time to time on Linux-SGX. This workaround stabilizes them until we fix the bug.
Large brk limit seems to trigger this bug from time to time (for `proc-path` about 15 runs are needed). I ran `proc-path` and `exec` 300 times on this path and they didn't crash anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1410)
=> [LibOS] regression: Workaround for #1408

LibOS/shim/include/shim_handle.h, LibOS/shim/include/shim_table.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/shim_syscalls.c, LibOS/shim/src/sys/shim_dup.c, LibOS/shim/test/ltp/ltp.cfg
Fixes:
* Correct syscall argument signess,
* Correct invalid arg handling (e.g. previously negative fd caused memory corruption inside LibOS),
* Correct handling of O_CLOEXEC flag,
* Checking `RLIMIT_NOFILE` when enlarging fd array.
Some of those issues were randomly triggered by an unrelated PR #1412 - seems that `dup201` was always crashing after the first two tests, but because it was marked as "selectively passing" only those two tests were checked and the return code wasn't checked.
Run LTP on the newly enabled tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1413)
=> [LibOS] Multiple fixes for dup* syscalls

LibOS/shim/include/shim_handle.h, LibOS/shim/include/shim_internal.h, LibOS/shim/include/shim_types.h, LibOS/shim/include/shim_utils.h, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/src/sys/shim_socket.c, Pal/include/lib/hex.h, Pal/include/pal/pal.h, Pal/src/host/Linux-SGX/db_pipes.c, Pal/src/host/Linux-SGX/pal_host.h, Pal/src/host/Linux/db_pipes.c, Pal/src/host/Linux/pal_host.h, Pal/src/host/Linux/pal_linux.h, Pal/src/host/Linux/pal_security.h, Pal/src/host/Skeleton/db_pipes.c
Previously, Graphene used the notation "pipe:<uint32_t>" to emulate pipes, socketpairs, and UNIX domain sockets. In particular, pipes and socketpairs received random integer IDs, and sockets received deterministic integer IDs. However, 32-bit IDs are bad for crypto. This commit changes pipe IDs (pipeid) from `uint32_t` to `char[96]` that can hold a 256-bit random sequence sufficient for crypto.
This is a prerequisite for #1400.
All tests must pass. If you do smth like `strace -ff Runtime/pal_loader Pal/regression/Pipe`, you'll see much longer names now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1407)
=> [LibOS,Pal] Replace 32-bit pipeid with 256-bit pipe name

LibOS/shim/src/shim_async.c
This patch fixes occasional hangs at termination of programs with threads.
These hangs occurred since the async helper thread did not properly account
for installed cleanup events but exited instead due to its idle counter
reaching the limit. This happened occasionally.
When the cleanup function wasn't called, a thread's clear_tid pointer
wasn't reset and the futex wasn't WAKE'ed and then the main thread would
end up WAITing on the futex (which still had the original thread id as its
value) and then never received the WAKE.
This patch fixes #1416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1419)
=> [LibOS] Account for cleanup events when walking list of events - fixes hangs

LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/pipe.c, LibOS/shim/test/regression/test_libos.py, Pal/include/lib/pal_crypto.h, Pal/lib/Makefile, Pal/lib/crypto/adapters/mbedtls_adapter.c, Pal/lib/crypto/mbedtls-2.21.0.diff, Pal/regression/SendHandle.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_pipes.c, Pal/src/host/Linux-SGX/db_process.c, Pal/src/host/Linux-SGX/db_streams.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/pal_host.h, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux/db_pipes.c
Previously, Linux-SGX PAL did not encrypt pipe/socketpair communication (only process checkpoint send/receive was encrypted). This PR encrypts all pipe/socketpair IPC between threads of
the same enclave and between enclave processes. In particular, all offsprings of the "first" enclave inherit the same master key and derive IPC session keys from this master key based on pipe ID. When two pipe/socketpair endpoints are first created, they establish a TLS-PSK session via intra-enclave handshake (requires a spawn of an intermediate enclave thread). During clone/fork/exec, endpoints' TLS contexts are serialized and sent to the child that deserializes them (using `mbedtls_ssl_context_{save,load}` functions).
Note that multicast pipes (with more than two communicating entities) are not supported …
=> [Pal/Linux-SGX] Encrypt all pipes/socketpairs with TLS-PSK

Documentation/pal/host-abi.rst, Pal/include/pal/pal.h, Pal/regression/.gitignore, Pal/regression/AttestationReport.c, Pal/regression/Makefile, Pal/regression/test_pal.py, Pal/src/db_misc.c, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux/db_misc.c, Pal/src/host/Skeleton/db_misc.c, Pal/src/pal-symbols, Pal/src/pal_internal.h
New `DkAttestationReport()` API retrieves the attestation report (local) from the local attestation mechanism. Currently, it is implemented only for Linux-SGX PAL and stubbed for all other PALs. The Linux-SGX implementation retrieves the SGX report via EREPORT instruction.
The caller of this new API may learn sizes of report_data, target_info, and report structs. The caller may also obtain current target info. Finally, the caller may obtain the report for use in local attestation.
This PR is a prerequisite for pseudo-FS PR (currently #1392, but I may close that one and open a new one since changes will be pretty significant).
All tests must pass. No new tests are added (will be in a follow-up PR on pseudo-FS).
--- …
=> [Pal] Introduce DkAttestationReport() API for local report retrieval

Pal/include/lib/avl_tree.h, Pal/lib/avl_tree.c, Pal/regression/avl_tree_test.c
This PR fixes lack of tree root update in `avl_tree_swap_node` and adds a test case for such scenario.
After removing fix added to `Pal/lib/avl_tree.c` provided test case will fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1425)
=> [Pal/lib] Add missing root node update to avl_tree_swap_node

Pal/include/lib/pal_crypto.h, Pal/lib/crypto/adapters/mbedtls_adapter.c, Pal/src/host/Linux-SGX/db_pipes.c, Pal/src/host/Linux-SGX/enclave_framework.c
mbedTLS configuration used in Graphene is not thread-safe (because this would require the use of a threading library like pthread which is not possible in the LibOS/Pal layers). However, some mbedTLS functions use shared state, in particular TLS context initialization functions. This led to data races during encrypted-pipe creation, since it requires two threads performing a TLS handshake. This PR adds spinlocks to protect the racy mbedTLS logic.
All tests must pass. I tested for ~1 hour with:
```
echo "= PAL pipe ="; while [ $? -eq 0 ]; do SGX=1 ~/graphene/Runtime/pal_loader ./Pipe; done
echo "= LibOS pipe ="; while [ $? -eq 0 ]; do SGX=1 ./pal_loader ./pipe; done
```
--- …
=> [Pal/{lib,Linux-SGX}] Put mbedTLS TLS-context init logic in critical section

Pal/src/host/Linux-SGX/tools/common/attestation.c, Pal/src/host/Linux-SGX/tools/common/attestation.h, Pal/src/host/Linux-SGX/tools/common/ias.c, Pal/src/host/Linux-SGX/tools/common/ias.h, Pal/src/host/Linux-SGX/tools/common/util.c, Pal/src/host/Linux-SGX/tools/common/util.h, Pal/src/host/Linux-SGX/tools/verify-ias-report/verify_ias_report.c
Previously, APIs `verify_ias_report()`, `verify_quote()`, `ias_verify_quote()` used hex/decimal strings as arguments and saved IAS response contents to files. This is not convenient for library usage.
This PR allows to pass raw-data arguments to `verify_ias_report()` and `verify_quote()`, as well as adds `ias_verify_quote_raw()` to output IAS response contents in memory.
Old interfaces are tested as usual. A follow-up PR on RA-TLS will test the new interfaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1426)
=> [Linux-SGX] tools: improve APIs to simplify usage in libraries

LibOS/shim/test/native/tcp.c, LibOS/shim/test/regression/udp.c
`udp` LibOS regression test failed with exit code `1` on normal Linux (without Graphene). This happened because of the `waitpid(..., -1)` code -- this `-1` is an impossible value for the `options` argument. Graphene's emulation of waitpid ignored that, but normal Linux failed. Interestingly, since our testing Python framework never tests native apps, it required a manual invocation to spot this bug.
Similar in `tcp` LibOS deprecated test. Fixed it just in case.
Kudos to @boryspoplawski for finding this.
All tests must run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1433)
=> [LibOS/test] Fix incorrect options arg for waitpid() in udp.c and tcp.c

Pal/src/db_rtld.c, Pal/src/pal_internal.h
Previously, the PAL layer would put an executable at a first unoccupied address range if the executable was position-independent (PIE). This could lead to the same executable being located at different addresses across forks (Graphene correctly checkpoints shared libraries but has separate handling for the executable). This is a rare scenario since the PAL initialization code is typically deterministic across forks. However, rarely there would be small difference in allocations which would lead to different base addresses for executable segments in parent and child processes, and segfaults and data corruptions
happened (this was the case for Nginx on Ubuntu 18.04 with change in the manifest file processing). 
This PR simply forces executables to always be loaded at a predefined address …
=> [Pal] Enforce that executable is always located at a predefined address

LibOS/shim/test/fs/Makefile, LibOS/shim/test/fs/common_copy.c
LibOS fs tests tried mapping a file opened with `O_WRONLY` which is disallowed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1432)
=> [LibOS/test/fs] Remove invalid mmap on file opened write-only

Pal/lib/Makefile
This PR fixes the issue of not-accounted-for mbedTLS patch (the `Pal/lib/crypto/mbedtls-*.diff` file). Previously, when this file was added/updated, mbedTLS was not rebuilt, which led to cryptic errors in Graphene (in particular, creation of pipes failed because mbedTLS failed on TLS-context serialization).
Everything must work. Try to update `Pal/lib/crypto/mbedtls-*.diff` and rebuild -- you'll notice that mbedTLS is rebuilt now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1436)
=> [Pal/lib] Makefile: add dependency on mbedTLS patch (.diff)

Pal/include/lib/api.h, Pal/lib/graphene/path.c, Pal/regression/normalize_path.c, Pal/src/db_main.c, Pal/src/db_rtld.c, Pal/src/db_streams.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/pal_security.h, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_process.c, Pal/src/host/Linux/db_files.c, Pal/src/host/Linux/db_main.c, Pal/src/host/Linux/db_process.c, Pal/src/host/Linux/pal_linux.h, Pal/src/host/Linux/pal_security.h, Pal/src/pal_internal.h, Runtime/pal_loader, Scripts/regression.py
While preparing protected argv/env PR it turned out that everything around argv passing is in a terrible state. This is the first PR in a series which will try to untangle this mess.
The biggest change in this PR is refactoring main functions and interfaces of PAL binaries. Now they take an explicit argument informing them in which mode they start (initial process vs child) and in the latter case, fd number with a pipe to the parent. Previously this differentiation was done by checking a magic fd number.
Reviewing commit-by-commit is recommended.
Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1428)
=> Argument-passing-related cleanup

LibOS/shim/src/Makefile, LibOS/shim/src/fs/dev/attestation.c, LibOS/shim/src/fs/dev/fs.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/attestation.c, LibOS/shim/test/regression/attestation.manifest.template, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/sgx_attest.h, Pal/src/host/Linux-SGX/sgx_platform.c
This PR adds a new subdirectory in the `/dev` pseudo-FS and new pseudo-files to allow applications and helper libraries on top of Graphene to perform attestation. The currently exposed  primitives are tailored to the Intel SGX local and remote EPID attestation. App developer writes attestation logic against this pseudo-FS interface by opening and reading/writing the following files:
- `/dev/attestation/report_data`: write SGX report data used in `report` and `quote` pseudo-files
- `/dev/attestation/target_info`: write SGX target info used in `report` and `quote` pseudo-files
- `/dev/attestation/my_target_info`: read this enclave's target info
- `/dev/attestation/report`: read SGX report
- `/dev/attestation/quote`: read SGX quote
~~**Depends on …
=> [LibOS] Add attestation pseudo-filesystem under /dev/attestation

Pal/src/pal_internal.h
Previously, we forced PIE executables to be located at address `0x00400000` (4MB). However, there is a bug in the ELF relocation code in LibOS that leads to double-relocation. To circumvent this bug,
relocation code checks if the offset was already relocated. But if the offset itself exceeds the base address of PIE executable (i.e., exceeds 4MB), then the offset is not relocated and segfaults follow.
This PR changes base address from `0x00400000` to `0x555555554000`, similar to what Linux does.
Run NodeJS example manually. It will work now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1443)
=> [Pal] Force PIE executable to be located at address 0x555555554000

Pal/lib/crypto/adapters/mbedtls_adapter.c
Linux-SGX PAL uses mbedTLS sessions for encrypted IPC. This requires a TLS handshake on pipe/socketpair creation. Previously, if the pipe was created with `O_NONBLOCK`, read/write callbacks for mbedTLS session could return `EAGAIN` or `EWOULDBLOCK` if the pipe was occupied. We forgot to check for these error codes, and TLS handshake failed as a result on the first `EAGAIN/EWOULDBLOCK` (detected on NodeJS example). These error codes are actually benign, and Graphene should simply ask mbedTLS to retry read/write.
Run NodeJS example with SGX. Without this PR, it fails on `failed to created encrypted pipe`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1444)
=> [Pal/lib] Continue TLS handshake if read/write failed with EAGAIN/EWOULDBLOCK

Runtime/pal_loader
GDB is so awesome that it has to print 14 lines of useless information about itself on each run. This isn't actually configurable in `.gdbinit` (or at least I couldn't find any way to do this), so we need to fix it via the commandline.
Just try `GDB=1 ./pal_loader <binary>` now and enjoy slightly better experience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1447)
=> pal_loader: Disable the annoying GDB banner

Pal/src/host/Linux-SGX/sgx_main.c
Just a small fix for a path in an error message.
Fixes #1451.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1452)
=> [Linux-SGX] Fix path to pal-sgx-get-token in error message

Documentation/devel/new-syscall.rst, LibOS/shim/include/shim_internal.h, LibOS/shim/src/shim_syscalls.c
The old name was very misleading, there wasn't any "passthrough" happening.
Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1458)
=> [LibOS] Rename SHIM_SYSCALL_PASSTHROUGH to SHIM_SYSCALL_RETURN_ENOSYS

Documentation/building.rst, Documentation/quickstart.rst
Building Graphene-SGX using the commands in the documentation (Documentation/quickstart.rst or Documentation/building.rst) fails during `make SGX=1`:
```
gcc -Wall -std=c11 -O2 -I../.. -I../../../../../include/lib -I../../../../../lib/crypto/mbedtls/install/include -I../../../../../lib/crypto/mbedtls/crypto/include -DCRYPTO_USE_MBEDTLS -D_POSIX_C_SOURCE=200809L -fPIC   -c -o ias.o ias.c
ias.c:17:23: fatal error: curl/curl.h: No such file or directory
```
The culprit is the description of required software packages which misses `libcurl4-openssl-dev`.
This PR adds the library to the description in quickstart.rst and building.rst.
Test the document generation. No changes to the Graphene sources where made.
--- …
=> Add a missing prerequisite (libcurl4-openssl-dev) to build and quick start documentation

LibOS/Makefile, LibOS/shim/include/shim_flags_conv.h, LibOS/shim/src/ipc/shim_ipc_pid.c, Pal/regression/AttestationReport.c, Pal/regression/Directory.c, Pal/regression/File.c, Pal/regression/Hex.c, Pal/regression/Makefile, Pal/regression/Tcp.c, Pal/regression/Udp.c, Pal/regression/normalize_path.c, Pal/src/db_rtld.c, Pal/src/host/Linux-SGX/Makefile.am, Pal/src/host/Linux/Makefile.am, Pal/src/host/Linux/db_sockets.c, Pal/src/host/Skeleton/Makefile.am
This PR makes Graphene to correctly build and run (most) tests on Clear Linux with GCC 9.3. In particular:
- [Makefiles] Make Graphene build on Clear Linux. Clear Linux ships with Glibc built with `-Wp,-DFORTIFY_SOURCE=2`. This overwrites Graphene's `-UFORTIFY_SOURCE` because of the quirk in how GCC applies arguments (first without Wp, then with Wp). This commit updates Makefiles to use `-Wp,-UFORTIFY_SOURCE`.
- [LibOS,Pal] Make Graphene build with GCC 9.3. GCC 9.3 adds more static checks on C headers and sources. This commit fixes all detected issues (mainly possible NULL pointer dereferences).
**NOTE:** Some tests (especially LibOS tests) require changes in manifests to correctly run on Clear Linux. In particular, some paths in mount points are different, as well as some library names. …
=> [LibOS,Pal] Make Graphene build on Clear Linux and GCC 9.3

Examples/pytorch/Makefile
The pytorch example can also run on Fedora, so remove the Ubuntu check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1460)
=> [Examples] Remove Ubuntu check from pytorch example

Examples/bash/Makefile, Examples/capnproto/Makefile, Examples/curl/Makefile, Examples/nodejs-express-server/Makefile, Examples/nodejs/Makefile, Examples/openvino/Makefile
The documentation [1] currently specifies SGX_SIGNER_KEY
as the parameter to enable Graphene to find your keys.
Some examples doesn't use this environment parameter,
this pull request fixes that.
[1] https://graphene.readthedocs.io/en/latest/building.html#id2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1468)
=> [Examples] Makefiles now use SGX_SIGNER_KEY

LibOS/shim/include/shim_fs.h, LibOS/shim/src/sys/shim_msgget.c, LibOS/shim/src/sys/shim_socket.c, LibOS/shim/test/ltp/README.rst, LibOS/shim/test/ltp/ltp.cfg
I debugged a few cases LTP cases where Graphene was crashing.
Unfortunately, currently AF_UNIX sockets migration is broken and would require much more work to fix, so a bunch of currently disabled socket-related tests are crashing and can't be easily enabled.
Run newly enabled LTP tests in Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1457)
=> Fix a bunch of crashes found by socket-related LTP tests

Examples/lmbench/Makefile
The one lmbench download source we have is very unstable and downloading
often fails. This commit adds more urls that will be iteratively
fetched.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1474)
=> [Examples/lmbench] Add more lmbench download urls

Pal/include/lib/api.h, Pal/include/lib/atomic.h, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/linux_types.h, Pal/src/host/Linux-SGX/ocall_types.h
When doing an ocall, untrusted part could return an invalid value for
example `write` could return size bigger than passed to it. This commit
adds checks for such invalid values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1466)
=> [Pal/Linux-SGX] Sanitize return values of ocalls

Examples/python-simple/Makefile
Remove the apt_pkg.cpython library from PY_LIBS since it isn't needed
and this allows it to run the test on Fedora as well.
I split this off into a separate PR since this patch only touches non-SGX Makefile code. I have previously tried to remove the apt_pkg.cpython. library from the SGX part but this had failed then. My guess is that SGX requires a dependency of apt_pkg.cpython for some reason but I do not have access to an SGX system to be able to try this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1461)
=> [Examples] Remove apt_pkg.cpython... library from PY_LIBS

Documentation/quickstart.rst, Jenkinsfiles/Linux-SGX, Jenkinsfiles/Linux-SGX-18.04, Jenkinsfiles/Linux-SGX-18.04-apps, Jenkinsfiles/Linux-SGX-apps, Pal/src/host/Linux-SGX/generated-offsets.c, Pal/src/host/Linux-SGX/sgx_framework.c
The DCAP SGX driver v1.6+ closely follows the in-kernel SGX driver v28+. This version changes the driver path to `/dev/sgx/enclave` and changes argument struct of the `SGX_IOC_ENCLAVE_ADD_PAGE` ioctl.
The corresponding PR is https://github.com/oscarlab/graphene-sgx-driver/pull/16.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1467)
=> [Pal/Linux-SGX] Add support for the DCAP SGX driver versions 1.6+

LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_handle.h, LibOS/shim/include/shim_table.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/pipe/fs.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/shim_parser.c, LibOS/shim/src/shim_syscalls.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/test/ltp/ltp-sgx.cfg, LibOS/shim/test/ltp/ltp.cfg, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/mkfifo.c, LibOS/shim/test/regression/test_libos.py, Pal/lib/crypto/adapters/mbedtls_adapter.c
This PR adds support for FIFOs and the corresponding syscalls `mknod()` and `mknodat()`. Internally, FIFOs are emulated as pseudo-files in chroot mount points (not visible in host FS). FIFOs' read/write operations are emulated via pipes at PAL level (this means that they are transparently encrypted under SGX PAL). Generally, emulation of FIFOs is similar to emulation of named UNIX domain sockets, i.e., they are "ephemeral" and only allow communication between two related processes. FIFOs cannot be O_RDWR (opening fails with EINVAL).
FIFOs can be blocking and non-blocking. The only caveat with non-blocking FIFOs is that `open(O_WRONLY)` doesn't fail with ENXIO if the other end is not opened yet (but this is a rare corner-case probably not used by real-world apps).
New LibOS test is added: …
=> [LibOS] Add support for FIFOs (named pipes)

LibOS/shim/include/shim_internal.h, LibOS/shim/src/shim_parser.c, LibOS/shim/src/sys/shim_poll.c
Running Erlang workload (helloworld) revealed two bugs in Graphene:
- [LibOS] Force `select(0, NULL, NULL, NULL, NULL)` to sleep indefinitely. Previously, Graphene returned -EINVAL for select() with all zeroes. This behavior was chosen due to man page of select: "Some code calls select() with all three sets empty, nfds zero, and a non-NULL timeout" (notice "non-NULL timeout"). In reality, Linux allows to specify timeout as NULL, which leads to indefinite sleep, same as pause(). This commit forces select() with all zeroes to perform shim_do_pause() to comply with Linux behavior.
- [LibOS] Remove DkSynchronizationObjectWait() from wait_event(). LibOS events create_event() / set_event() / wait_event() are emulated as reads/writes on a private pipe. On the other hand, PAL API …
=> [LibOS] Fixes for two bugs revealed on Erlang workload

LibOS/shim/src/elf/shim_rtld.c, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/pipe/fs.c, LibOS/shim/src/fs/proc/ipc-thread.c, LibOS/shim/src/fs/proc/thread.c, LibOS/shim/src/fs/socket/fs.c, LibOS/shim/src/fs/str/fs.c, LibOS/shim/src/shim_parser.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_exit.c, LibOS/shim/src/sys/shim_fork.c, LibOS/shim/src/sys/shim_getpid.c, LibOS/shim/src/sys/shim_vfork.c, LibOS/shim/src/sys/shim_wait.c
This is a toned-down PR for removing only the prctl.h include in all c files. It's really not needed anywhere in those files in the shim and no shim header file includes it, either, so that it would be indirectly included now. shim_syscall.c is the only file where it is actually needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1482)
=> [LibOS] Remove unnecessary include of asm/prctl.h where possible

Pal/src/host/Linux/db_mutex.c
Rather than passing the mutex_handle's address, which happens to have the
futex variable as its first variable, properly calculate the address of the
futex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1484)
=> [Pal] Properly calculate address of futex variable

Pal/include/arch/x86_64/pal-arch.h, Pal/regression/File.c, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux/pal_linux.h
Move page size definitions to a new pal_user.h , which would be similar to sys/user.h where this definition would typically be found.
Define PAGE_SIZE and use it in a regression test that maps memory of a page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1491)
=> [Pal] Move page size definitions to new pal_user.h

Pal/include/arch/x86_64/pal-arch.h, Pal/include/pal/pal.h
Factor out the TCB part from pal.h into pal_tcb_common.h. Have applications
now include the processor specific pal_tcb.h, which was previously called
pal-arch.h.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1486)
=> [Pal] Factor out TCB part from pal.h

Pal/src/host/Linux-SGX/db_sockets.c, Pal/src/host/Linux-SGX/linux_types.h, Pal/src/host/Linux/db_sockets.c
This series of patches fixes more IPv6 related stack buffer overflows . We first add checks to the size of the passed buffers, which requires each caller to pass in the size of the buffer. If the buffers are too small for what they are used for, we fail the function before touching the buffer. Adapt all callers and extend their buffers by using sockaddr_storage, which also fits a sockaddr_in6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1487)
=> [Pal] Fix more IPv6 related stack buffer overflows

LibOS/shim/include/shim_table.h, LibOS/shim/include/shim_types.h, LibOS/shim/src/shim_syscalls.c, LibOS/shim/src/sys/shim_socket.c, Pal/src/host/Linux-SGX/db_pipes.c, Pal/src/host/Linux-SGX/db_sockets.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/linux_types.h, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux/db_sockets.c
This contains two socket-related changes, which would be hard to factor out into two commits: (because of compilation warnings)
- Making ocalls use `size_t` in their interface. It's not the same as Linux syscall interface anyway, so why not make it sane?
- Fixing sycalls arguments types to match the ones use by kernel. Note: there's no such type as `socklen_t` in the kernel, so it got removed.
This is an SGX follow-up to #1487. It's also a small step towards resolving #152.
Just Jenkins, I guess.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1501)
=> Use proper integer types in socket-related syscalls and ocalls

Pal/src/host/Linux/db_exception.c
The PAL_CONTEXT is larger than uc_mcontext.gregs, so be careful in
copying the precise number of bytes out of uc_mcontext.gregs and
back into them to avoid reading from or writing into unrelated memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1502)
=> [Pal] Copy precise number of bytes into PAL_CONTEXT

LibOS/shim/include/shim_signal.h, LibOS/shim/include/shim_thread.h, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/sys/shim_futex.c, LibOS/shim/src/sys/shim_sigaction.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/sigaction_per_process.c, LibOS/shim/test/regression/test_libos.py
This is one of a series of PR trying to fix the mess with threads.
On Unix signal disposition is a per-process attribute, graphene had it per-thread.
Added a new test, which will fail on current master (actually hangs, but that's another bug).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1500)
=> [LibOS] Make the signal disposition a per-process attribute

Pal/src/host/Linux-SGX/db_sockets.c, Pal/src/host/Linux/db_sockets.c
Relax the addrlen check in inet_create_uri to only ensure that the passed buffer is large enough but doesn't need to be precise the needed size. This addresses the caller from udp_receivebyaddr that calls us like this:
```C
struct sockaddr_storage conn_addr;
socklen_t conn_addrlen = sizeof(conn_addr);
struct msghdr hdr;
struct iovec iov;
iov.iov_base       = buf;
iov.iov_len        = len;
hdr.msg_name       = &conn_addr;
hdr.msg_namelen    = conn_addrlen;
[...]
int ret = inet_create_uri(addr_uri, addr + addrlen - addr_uri,
(struct sockaddr*)&conn_addr, hdr.msg_namelen);
```
hdr.msg_namelen indicates a buffer that is bigger than needed, so we should be able to accept it.
--- …
=> [Pal] Relax addrlen check to require buffer to be 'large enough'

LibOS/shim/src/sys/shim_pipe.c
This PR fixes a blooper in `socketpair()`. Graphene worked correctly despite this blooper because (apparently) `flags` are not really checked/enforced on UNIX domain sockets.
All tests must run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1506)
=> [LibOS] Fix typo "hdl1" to "hdl2" in socketpair()

LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/test/ltp/ltp.cfg, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/sighandler_sigpipe.c, LibOS/shim/test/regression/test_libos.py, Pal/include/pal/pal.h, Pal/src/db_exception.c, Pal/src/host/Linux/db_exception.c
This PR extends the Pal and LibOS to deliver SIGPIPE to an application if it has a signal handler installed or it terminates the applications with the expected termination code (141) if no signal handler has been installed. A test case is provided. One more test case of LTP now passes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1495)
=> [Pal & LibOS] Deliver SIGPIPE to an application or terminate it if no handler installed

Pal/include/arch/x86_64/Linux/ucontext.h, Pal/src/host/Linux/db_exception.c
Define a macro for copying CPU context between PAL_CONTEXT and
ucontext_t. Add an assert to make sure that the number of registers
in both contexts is the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1505)
=> [PAL] Define a macro for copying to and from PAL_CONTEXT

LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, LibOS/shim/include/arch/x86_64/shim_types-arch.h, LibOS/shim/include/shim_tcb.h, LibOS/shim/include/shim_types.h, LibOS/shim/test/inline/Makefile
Split off x86_64 specific data structures and move them into x86_64 specific header files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1499)
=> [LibOS] Split off x86_64 specifics from common header files

LibOS/shim/src/Makefile, LibOS/shim/test/inline/Makefile, Pal/include/arch/x86_64/Linux-SGX/pal_host-arch.h, Pal/include/arch/x86_64/Linux/pal_host-arch.h, Pal/include/arch/x86_64/Linux/sysdep-arch.h, Pal/include/arch/x86_64/Skeleton/pal_host-arch.h, Pal/include/arch/x86_64/pal-arch.h, Pal/lib/Makefile, Pal/regression/Makefile, Pal/src/Makefile, Pal/src/host/Linux/db_threading.c, Pal/src/host/Skeleton/Makefile
Move the x86_64 specific syscall arch_prctrl into a new inline function
pal_set_tcb located in include/arch/x86_64/Linux/pal_host-arch.h
The SGX build also needs a pal_host-arch.h, which can be empty at this
point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1504)
=> [Pal] Move x86_64 syscall arch_prctl into pal_set_tcb

LibOS/shim/src/bookkeep/shim_signal.c
Previously, Graphene showed debug message "illegal instruction at" on every trapped instruction, including syscall inst (trapped in SGX PAL). This message is confusing, do not show it on emulated
instructions and rephrase.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1516)
=> [LibOS] Do not show "illegal instruction" message on syscall instruction

LibOS/shim/src/fs/shim_fs.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/proc_common.c, LibOS/shim/test/regression/test_libos.py
Previously, `find_mount_from_uri()` assumed that the URI of executable is an absolute path. This is not true in general case, so this commit removes this assumption. This bug fix allows to correctly follow symlink `/proc/self/exe` (previously it returned -EINVAL). LibOS's `proc` test is updated to verify this.
`proc` LibOS test is updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1515)
=> [LibOS] Fix bug to set exec handle's dentry to executable file

Documentation/manifest-syntax.rst, LibOS/shim/test/regression/multi_pthread.manifest.template, LibOS/shim/test/regression/multi_pthread_exitless.manifest.template, Pal/regression/Thread2.manifest.template, Pal/regression/Thread2_exitless.manifest.template, Pal/src/host/Linux-SGX/generated-offsets.c, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_entry.S, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_thread.c, Pal/src/host/Linux-SGX/sgx_tls.h, Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py
New manifest option `sgx.print_stats=[1|0]` specifies whether to print SGX enclave-specific statistics, both per-thread and per-process.
The currently supported stats are:
- number of EENTERs (corresponds to ECALLs plus returns from OCALLs),
- number of EEXITs (corresponds to OCALLs plus returns from ECALLs),
- number of AEXs (corresponds to interrupts/exceptions/signals during enclave execution).
A couple multi-threaded tests among Pal and LibOS regression tests are built with `sgx.print_stats = 1`. Check it out manually via e.g. `SGX=1 ./pal_loader multi_pthread_exitless.manifest.sgx`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1519)
=> [Pal/Linux-SGX] Add sgx.print_stats manifest option to display SGX stats

Documentation/manifest-syntax.rst, LibOS/shim/src/fs/dev/attestation.c, LibOS/shim/test/regression/attestation.c, LibOS/shim/test/regression/attestation.manifest.template, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux-SGX/quote/aesm.proto, Pal/src/host/Linux-SGX/sgx_attest.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_platform.c, Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py
Previously, `DkAttestationQuote()` was able to retrieve only EPID based SGX quotes (with explicit messages to talk to AESM via Google Protobuf). This PR allows `DkAttestationQuote()` to retrieve ECDSA/DCAP based SGX quotes (so called version 3). This is implemented via new Protobuf
messages to talk to AESM (with "_ex" suffix).
Since DCAP based attestation doesn't require SPID and linkable, we introduce a new manifest syntax `sgx.attestation`. To enable DCAP attestation, it is enough to set `sgx.attestation = 1`.
The `attestation` LibOS test works both with EPID and DCAP based attestations, and retrieves quotes v2 (EPID) and v3 (ECDSA/DCAP). (But you need an FLC/ECDSA/DCAP enabled machine with SGX SDK 2.9.1 and SGX DCAP 1.6 installed.)
--- …
=> [LibOS,Pal/Linux-SGX] Allow DkAttestationQuote() to get SGX DCAP quote

LibOS/shim/include/shim_types.h, LibOS/shim/src/bookkeep/shim_signal.c
On some architecture sa_mask may not be a simple field, so we have to use memset to clear it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1522)
=> [LibOS] Use memset to clear sa_mask

LibOS/shim/src/bookkeep/shim_vma.c, LibOS/shim/src/sys/shim_mmap.c
This PR solves the following issues related to mmap operations
- MAP_32BIT is only useful on x86_64 platforms, anywhere else it cannot be used
- if MAP_FIXED is not set we set address to NULL so it's ignored in alignment checks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1521)
=> [LibOS] Conditionally compile MAP_32BIT code and reset address if MAP_FIXED is not set

LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/sigaction_per_process.c, Pal/include/arch/x86_64/cpu.h, Pal/include/lib/spinlock.h, Pal/src/host/Linux-SGX/db_exception.c, Pal/src/host/Linux-SGX/db_pipes.c, Pal/src/host/Linux-SGX/sgx_enclave.c
This PR creates an inline function (in Pal/include/arch/x86_64/cpu.h) cpu_pause() for the asm instruction 'pause'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1531)
=> [PAL+LibOS] Use function for x86_64 pause

LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, LibOS/shim/include/arch/x86_64/shim_types-arch.h, LibOS/shim/include/shim_tcb.h, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_sigaction.c, Pal/include/arch/x86_64/pal-arch.h
To factor out x86_64 specific names of fields in data structure accesses, implement inline functions that allow us to set and get the stack pointer, orig_rax, and the instruction pointer.
Implement a function to copy shim_regs to ucontext_t, similar to what we have in the PAL when copying between ucontext_t and PAL_CONTEXT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1514)
=> [LibOS] Wrap shim_context and shim_regs accesses in functions

Pal/src/host/Linux-SGX/debugger/sgx_gdb.c, Pal/src/host/Linux-SGX/debugger/sgx_gdb.h, Pal/src/host/Linux-SGX/sgx_entry.S, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c
Commit 3178e26 "Add sgx.print_stats manifest option to display SGX stats" broke the SGX-GDB ptrace wrapper by adding a new instruction to the Asynchronous Exit Pointer assembly. This new instruction confused the GDB wrapper when it tried to single-step using ptrace's SINGLESTEP command: it assumed that the only instruction in AEP is ERESUME. This commit adds new function entry to the AEP assembly so that the GDB wrapper moves RIP to ERESUME and continues single-
stepping from the correct position. This commit also fixes small bug with thread_stepping by converting it to a proper bit vector.
Run GDB and try to single-step through the enclave.
--- …
=> [Pal/Linux-SGX] sgx-gdb: Fix single-stepping by jumping to ERESUME

Documentation/cloud-deployment.rst, Documentation/index.rst
Adding documentation about deployment of Graphene in Cloud VMs. In particular, the deployment with Azure Confidential Compute VMs which are the first generally available Intel SGX enabled VMs.
Please build documentation. The remainder of Graphene tests is not impacted by this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1518)
=> Documentation for deployment of Graphene in Cloud VMs

LibOS/shim/src/fs/dev/fs.c, LibOS/shim/test/regression/attestation.c, LibOS/shim/test/regression/test_libos.py
Previously, `dev_truncate()` callback in the attestation pseudo-FS returned -EACCES for any attempt to truncate an attestation pseudo-file. This is not needed since attestation pseudo-files are anyhow
pre-populated. This commit simply ignores truncate attempts on attestation pseudo-files. This enables stdio-based fopen("w") APIs.
LibOS test `attestation` is amended to test this bug fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1545)
=> [LibOS] Allow fopen("/dev/attestation/<file>", "w") to succeed

LibOS/shim/include/shim_signal.h, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/exec_fork.c, LibOS/shim/test/regression/test_libos.py
Previously, Graphene forgot to reset signal handlers to defaults. This led to segfaults when parent process installed a signal handler (e.g., SIGCHLD), spawned a child via execve(), and the child spawned a grand-child via e.g. fork(). When the grand-child terminated, the child noticed that it had some SIGCHLD handler installed and tried to call it, but the memory region where the handler was in parent didn't exist any more, so Graphene crashed with segfault.
This PR resets signal handlers on execve() to fix this bug.
Kudos to Manoj Gopalakrishnan for reporting this bug.
New LibOS test `exec_fork` is added. Without this PR, this test crashed Graphene.
--- …
=> [LibOS] Do not inherit signal handlers on execve()

LibOS/shim/src/shim_parser.c
Make the shim_parser array independent of the order of syscalls. Use #ifdef's on obviously architecture dependent syscalls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1553)
=> [LibOS] Make shim_parser array indep. of order of syscalls

LibOS/shim/src/shim_parser.c
This patch fixes this ppc64 compiler warning and also works on x86_64.
shim_parser.c: In function \u2018parse_ioctlop\u2019:
shim_parser.c:1184:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (op >= TCGETS && op <= TIOCVHANGUP) {
^~
shim_parser.c:1219:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (op >= FIONCLEX && op <= TIOCSERSETMULTI) {
^~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1559)
=> [LibOS] Use unsigned int for ioctl ops in shim_parser

Examples/lmbench/Makefile, Examples/lmbench/manifest.template, Examples/lmbench/patches/llseek.patch, Examples/lmbench/patches/tirpc.patch, Examples/lmbench/sh.manifest.template
Patch lmbench for distros where the is no rpc/rpc.h from glibc but
needs tirpc. Also patch llseek to use lseek64. This is now working
on Fedora and Ubuntu-18.04 and it works also when libtircp is not
installed, so we can patch unconditionally.
Add the new library to the sgx trusted libraries in the manifest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1476)
=> [Examples] Patch lmbench for distros without rpc/rpc.h and llseek

LibOS/shim/include/shim_table.h, LibOS/shim/src/shim_parser.c, LibOS/shim/src/shim_syscalls.c, LibOS/shim/src/sys/shim_sched.c
This commit adds dummy implementation for getcpu, which is needed at the
beginning of OpenJDK 11 runtime.
Fixes #1552.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1554)
=> [LibOS] Add dummy implementation of getcpu

Pal/src/host/Linux-SGX/sgx_framework.c, Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
Standardize prints of MRENCLAVE. Also print MRSIGNER in output of the `pal-sgx-get-token` script, so it can be used to retrieve SGX measurements from the SIGSTRUCT (.sig) file for manual inspection.
To see MRENCLAVE, MRSIGNER, ... of a particular app, use its SIGSTRUCT file:
```
graphene/LibOS/shim/test/regression$ make SGX=1
...
graphene/LibOS/shim/test/regression$ ~/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token --sig multi_pthread.sig
Attributes:
mr_enclave:  0d34e21e9a3796b503760d454c7bf33aa186ba7daf2c62d8e96bcf1b4da05890
mr_signer:   2521f4b9d2f0338db3bf3f913444e5b8fca76e93948613483f3ccf9ac55c742d
isv_prod_id: 0
isv_svn:     0
...
```
--- …
=> [Pal/Linux-SGX] Improve printing of MRENCLAVE and MRSIGNER

Pal/src/db_object.c, Pal/src/db_streams.c
Fix several bugs in incorrectly set errno and return values without changing the logic. These bugs led to e.g. periodic hangs of LTP tests.
Without this PR, `fork11` LTP test periodically hanged. With this PR (+ https://github.com/oscarlab/graphene/pull/1542), `fork11` doesn't hang or fail.
Tested like this: `i=0; while [[ $i == 0 ]]; do ./pal_loader ./fork11; i=$?; done`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1572)
=> [Pal] Return correct errno and return value in Dk* APIs

Examples/ra-tls-mbedtls/.gitignore, Examples/ra-tls-mbedtls/Makefile, Examples/ra-tls-mbedtls/README.md, Examples/ra-tls-mbedtls/server.manifest.template, Examples/ra-tls-mbedtls/src/client.c, Examples/ra-tls-mbedtls/src/server.c, Jenkinsfiles/Linux-SGX-18.04-apps, Pal/src/host/Linux-SGX/tools/Makefile, Pal/src/host/Linux-SGX/tools/README.rst, Pal/src/host/Linux-SGX/tools/common/attestation.c, Pal/src/host/Linux-SGX/tools/common/attestation.h, Pal/src/host/Linux-SGX/tools/ra-tls/Makefile, Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls.h, Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_attest.c, Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_common.c, Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c, Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c
~~Depends on https://github.com/oscarlab/graphene/pull/1471!~~
RA-TLS integrates Intel SGX remote attestation into the TLS connection setup. Conceptually, it extends the standard X.509 certificate with SGX-related information. The additional information allows the receiver (verifier) of the certificate to verify that it is indeed communicating with an SGX enclave (attester). RA-TLS is shipped as three libraries:
- `ra_tls_attest.so`: creates self-signed RA-TLS X.509 certificate with SGX quote embedded; typically linked into server apps.
- `ra_tls_verify_epid.so`: verifies RA-TLS certificate by sending SGX quote to IAS and verifying attestation report from IAS; typically linked into client apps.
- `ra_tls_verify_dcap.so`: verifies RA-TLS certificate by providing SGX quote v3 to the …
=> [SGX] Add RA-TLS utility libraries

Documentation/manifest-syntax.rst, LibOS/shim/include/shim_defs.h, LibOS/shim/src/bookkeep/shim_vma.c, LibOS/shim/src/sys/shim_brk.c, LibOS/shim/test/regression/large_mmap.manifest.template, Pal/include/pal/pal.h, Pal/src/db_main.c
Previously, Graphene always performed ASLR at the LibOS layer. ASLR may lead to a situation when one mmap allocates an object in the middle of address space, and there is no space for a later mmap of a large object. This is problematic in restricted environments such as SGX enclaves. In particular, `large_mmap` LibOS test failed occasionally because it only has 8GB of enclave size and it may mmap first objects somewhere in the middle (around 4GB address) and then fail to find any space for a large 4GB mmap.
This commit adds "loader.insecure__disable_aslr" manifest option. If it set to one, ASLR is disabled and mappings become deterministic which guarantees programs like `large_mmap` never fail due to ENOMEM.
`large_mmap` should always pass now.
--- …
=> [LibOS,Pal] Introduce "loader.insecure__disable_aslr" manifest option

LibOS/shim/src/elf/shim_rtld.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/shim_async.c, LibOS/shim/src/sys/shim_exit.c, Pal/regression/Event.c, Pal/regression/Event2.c, Pal/regression/Thread.c, Pal/regression/Thread2.c, Pal/src/db_rtld.c, Pal/src/db_threading.c, Pal/src/host/Linux-SGX/db_threading.c
Almost everything in this test was wrong:
- race on `count = 100` in the main thread and `count++` in the worker thread
- using volatile as atomic
- dead code after `DkThreadExit`, which is `noreturn`
- checking if noreturn function didn't actually return
- doing the above with 500 loop iterations...
Additionally, I added 'UNREACHABLE' annotations after DkThreadExit calls.
Fixes  #1573.
In `Pal/regression`, run:
```fish
for i in (seq 400000)
echo "[$i]"
../../Runtime/pal-Linux init Thread ^stderr.txt >stdout.txt; and grep -q 'Child Thread Exited' stderr.txt; or break
end
```
After this patch I ran this test 400000 times without errors (previously it was failing after ~10k run).
See #1573.
--- …
=> Fix test_pal.py::TC_20_SingleProcess::test_500_thread

LibOS/shim/src/sys/shim_sigaction.c, LibOS/shim/test/regression/sigaction_per_process.c, LibOS/shim/test/regression/signal_multithread.c
Previously, Graphene didn't handle special case of kill()/tkill() with signal equal to zero. This signal is used to check for existence of processes and threads. However, Graphene tried to send/append it
which led to segfaults. This PR correctly handles signal equal to zero and improves LibOS tests to verify this fix.
This PR adds some more cases in LibOS tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1584)
=> [LibOS] Do not try to send signal 0 in kill()/tkill()

Pal/src/db_main.c
Previously, if running like `pal_loader /bin/true` without a corresponding manifest file, Graphene would try to continue execution without a manifest. This led to segfaults. This commit loudly fails in such cases.
With this PR:
```
$ ./pal_loader /bin/true
PAL failed at db_main.c:pal_main:254 (exitcode = 6, reason=cannot find manifest file)
```
Without this PR the same would segfault.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1587)
=> [Pal] Loudly fail if no manifest file found for executable

LibOS/shim/include/arch/x86_64/shim_internal-arch.h, LibOS/shim/src/elf/shim_rtld.c, LibOS/shim/src/shim_init.c
This PR makes use of current_stack() to get rid of inline assembly and moves some other inline assembly into a header file (as macro).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1577)
=> [LibOS] Replace and move inline assembly

LibOS/shim/test/benchmark/manifest.template, LibOS/shim/test/inline/manifest.template, LibOS/shim/test/native/exec_fork.manifest.template, LibOS/shim/test/native/ls.manifest.template, LibOS/shim/test/native/manifest.template, LibOS/shim/test/native/script.manifest.template, LibOS/shim/test/native/static.manifest.template
As part of Protected Argv feature, Graphene now requires an explicit manifest option to pass command-line arguments, either `loader.argv_src_file` or `loader.insecure__use_cmdline_argv`. As
part of that change, most manifests were updated to include these options, but not all. This PR fixes this for the rest of manifests.
All tests must run. With this PR, manually running HelloWorld from `LibOS/shim/test/native/` would fail. With this PR, it correctly prints `Hello world (helloworld)!`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1592)
=> [LibOS,Pal] Add "loader.insecure__use_cmdline_argv" to more manifests

Pal/src/host/Linux-SGX/sgx_enclave.c
Newer GCC complained about non-constant initialization:
```
sgx_enclave.c: In function ‘rpc_thread_loop’:
sgx_enclave.c:729:47: error: initializer element is not constant
static const uint64_t SLEEP_TIME_STEP   = SLEEP_TIME_MAX / 100;
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1596)
=> [Pal/Linux-SGX] Fix "initializer element is not constant" error

Pal/src/host/Linux-SGX/sgx_framework.c, Pal/src/host/Linux-SGX/sgx_main.c
This PR adds support for the DCAP 1.35 driver (https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/e3998c5fbd5d3fd065436b934b53822120e67be6/driver/linux). The PR makes changes to mmap and mprotect to support newer protection setting requirements. Supposed to be backward compatible with prior releases of other Intel SDK drivers.
More context: the DCAP driver (https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/driver/linux) follows the upstreaming Intel SGX driver for Linux (https://lkml.org/lkml/2020/6/1/165). It was recently rebased to v32 of the upstreaming driver (see links), which has changes to mmap and mprotect. Thus, Graphene failed to correctly create, add-pages, and init the SGX enclave. This PR fixes these problems.
Run any Graphene app using SGX …
=> [Pal/Linux-SGX] Support DCAP 1.35 driver

Pal/src/host/Linux-SGX/sgx_framework.c, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c
Add support to handle either the gsgx module or the proposed Linux kernel support for fsgsbase.  
This is a more polished version of the code originally proposed by @dimakuv . 
I am also testing these changes on a patched kernel in #1555, but wanted to separate out this change from other, incidental changes to make Jenkins work.  This should be backward compatible with code that uses gsgx as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1583)
=> [SGX] Dynamically determine whether FSGSBASE is supported

Scripts/clean-check, Scripts/clean-check-prepare, Scripts/clean-check-test-copy, Scripts/download, Scripts/gitignore-test
Unlike /usr/bin/env which is a Posix standard, there is no guarentee
that /bin/bash exists. This is the case for operating systems such
as FreeBSD, NixOS and Guix. By using /usr/bin/env we also give
the user the option to provide their own bash in a different path
by setting the $PATH environemnt variable.
Distributions usually provide their own packaging wrappers
to fixup shebangs upon installation, however those are not convienent
to use when developing in the source tree.
See also other upstream discussions about the topic:
- https://github.com/systemd/systemd/pull/5816
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1616)
=> portable bash shebangs

LibOS/shim/test/ltp/ltp-sgx.cfg, LibOS/shim/test/ltp/ltp.cfg
This PR simply enables now-working `lseek02` test. It also removes mentions of non-existing tests.
Closes #1027.
LTP must pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1614)
=> [LibOS] ltp: Enable lseek02 test and remove non-existing lseek* tests

LibOS/shim/include/arch/x86_64/shim_internal-arch.h, LibOS/shim/include/shim_checkpoint.h, LibOS/shim/include/shim_internal.h, LibOS/shim/include/shim_thread.h, LibOS/shim/include/shim_utils.h, LibOS/shim/src/elf/shim_rtld.c, LibOS/shim/src/shim_checkpoint.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_fork.c
Previously, Graphene sent arguments to a child process (spawned via `execve()` syscall) in the clear. This was insecure. This PR fixes it by always spawning a new child process without arguments and then sending the arguments in the checkpoint (which is securely encrypted on Linux-SGX PAL). The new logic is the same as with environ.
This PR also refactors stack initialization on new process and on execve as a pre-requisite.
Fixes #1561.
All tests must pass. You can manually check that `execve()` spawns a child without the arguments now.
Here is an example without this PR:
```
SGX=1 strace -s 256 -ff ./pal_loader ./exec 2>&1 | tee log
...
[pid 20115] execve("/home/dimakuv/graphene/Pal/src/../../Runtime/pal-Linux-SGX", 
["/home/dimakuv/graphene/Pal/src/../../Runtime/pal-Linux-SGX", …
```
=> [LibOS] Hide arguments from host OS and send them in checkpoint

LibOS/shim/test/ltp/Makefile
Currently, we build all of LTP, even though we only use the syscall tests.  On a 5.7 kernel, some the test cases we don't use also do not build.
The simple answer is to be more targeted in our makefile, and not build code that is neither ours nor code we particularly care about.
Just run the CI pipeline.  Or build and run LTP manually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1608)
=> [Testing] Only build the part of LTP we care about

Documentation/building.rst, Documentation/quickstart.rst
This PR adds instructions on how to build and install Linux 5.7 with the FSGSBASE patch.
Fr more info, see https://lwn.net/Articles/821719. Recall that Graphene requires FSGSBASE to be enabled in user-space.
The old way of enabling FSGSBASE (via a custom Graphene SGX driver) is deprecated.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1606)
=> [Docs] Add instructions to install Linux 5.7 with FSGSBASE patch

Pal/src/host/Linux-SGX/db_misc.c
The gsgx.h header is not actually needed to compile db_misc.c under SGX.  Remove this requirement,
pruning needless dependencies on the gsgx driver.
Build graphene for SGX
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1620)
=> [SGX] The gsgx.h header is not needed in db_misc

Pal/regression/Makefile, Pal/regression/Symbols.c, Pal/regression/test_pal.py, Pal/src/db_misc.c, Scripts/regression.py
Compile the DkSegmentRegister function only on x86_64 and adapt a test case looking for this symbol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1619)
=> PAL: Compile DkSegmentRegister only on x86_64 and adapt test case

LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/poll_closed_fd.c, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/db_object.c, Pal/src/host/Linux/db_object.c
poll() syscall on Linux and Linux-SGX have different behavior from native program. See #1600.
It also blocks multi-thread Python script. See #1539.
This PR updates poll() to find FD marked as failed then return positive number and pollfd with proper revents field.
Fixes #1600.
`poll_closed_fd` regression test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1607)
=> PAL:Fix poll() syscall to return POLLHUP on closed FD

LibOS/shim/src/bookkeep/shim_signal.c
Avoid random crashes in getcwd04 LTP test (on ppc64 at least) using
this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1624)
=> LibOS: Initialize shim->pal_context to avoid crashes

Pal/src/host/Linux-SGX/db_threading.c
The order of header files in db_thread.c is not well organized,
It got sorted to comply with GSGX code style.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1625)
=> [PAL/Linux-SGX] The header files got sorted in db_thread.c

Pal/include/elf/elf.h
when compiling sgx_main.c this directory is preferred over glibc,
with as a result will lead to glibc's elf.h skipped during
header inclusion. Since sgx_main.c also requires AT_HWCAP2, include
it in this header.
Fixes the following bug:
```
make[3]: Entering directory '/home/joerg/git/graphene/Pal/src/host/Linux-SGX'
gcc -MD -MP -Wall -std=c11 -Wmissing-prototypes -gdwarf-2 -g3 -DDEBUG -fPIC -maes -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -fno-builtin -Wtrampolines -Wextra -Wnull-dereference -DCRYPTO_USE_MBEDTLS -I. -Iinclude -I../.. -I../../../include -I../../../include/pal -I../../../include/arch/x86_64 -I../../../include/arch/x86_64/Linux -I../../../include/host/Linux-SGX -I../../../include/host/Linux-common -I../../../include/lib -I../../../lib/crypto/mbedtls/include …
```
=> [Pal] add AT_HWCAP2 to elf.h

Documentation/manifest-syntax.rst, LibOS/shim/test/regression/multi_pthread.manifest.template, LibOS/shim/test/regression/multi_pthread_exitless.manifest.template, Pal/regression/Thread2.manifest.template, Pal/regression/Thread2_exitless.manifest.template, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_thread.c, Pal/src/host/Linux-SGX/sgx_tls.h, Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py
This commit renames manifest option `sgx.print_stats` into `sgx.enable_stats` and adds enabling `TCS.FLAGS.DBGOPTIN` for all enclave threads when this manifest option is set. This allows to collect performance counters and generally enable debug and profiling features of enclaves (built in debug SGX mode).
I modified `multi_pthread` locally to do a busy loop in threads (to have a clear distinction between no-debug-optin enclaves and debug-optin enclaves). Here are the results:
```
Performance counter stats for '/home/dimakuv/graphene/Runtime/pal_loader ./multi_pthread':
91,814,185,486      cycles                    #    4.379 GHz
4,097,663,570      instructions              #    0.04  insn per cycle
659,929,532      branches                  #   31.472 M/sec …
```
=> [Pal/Linux-SGX] Enable TCS.FLAGS.DBGOPTIN for HW perf monitoring

LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/sys/shim_futex.c, Pal/include/lib/spinlock.h, Pal/src/host/Linux-SGX/db_events.c, Pal/src/host/Linux-SGX/db_mutex.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux/db_events.c, Pal/src/host/Linux/db_mutex.c
The 'weak' parameter may not have any influence on x86, but on ppc64 it
does cause 'spurious faults' due to a missing check on flags (missing
'bne' instruction). The weak parameter is described in the gcc atomics
operations documentation like this:
"[...] weak is true for weak compare_exchange, which may fail spuriously, and
false for the strong variation, which never fails spuriously."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1630)
=> PAL+LibOS: Set 'weak' parameter in atomics operations to 'false'

Runtime/pal_loader
On NixOS/Guix tools are not installed into /usr/bin but come from
are composed as symlink trees from immutable packages in the /nix/store:
i.e. /home/joerg/.nix-profile/bin/bash -> /nix/store/hgplspyw16amnbhlbi7qa2938w8i0rz6-bash-interactive-4.4-p23/bin/bash
Due it's immutable nature they are a perfect fit for graphene-sgx since
libraries store paths won't change unlike their traditional /usr/lib
equalivalents and hence don't break code signing.
One might argue that using for absolute paths makes it possible without a PATH
set, however this is not really true, since make in this case relies on other
tools. Also the whole script relies on bash to be in PATH for it's shebang.
--- …
=> [Pal] don't depend on absolute PATH for tools

Pal/lib/Makefile
Also scripts/config.pl has a sane shebang `/usr/bin/env perl`,
we don't provide `/usr/bin/env` in the [nix](https://nixos.org) sandbox.
Usually we have ways of patching those shebangs however in this case
it is hidden in a tarball therefore not so easy to patch.
For other platforms this patch is not necessary however it should not break
anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1639)
=> [Pal] invoke mbedtls with perl directly

LibOS/shim/include/shim_flags_conv.h, LibOS/shim/src/bookkeep/shim_vma.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/shim_parser.c, LibOS/shim/src/sys/shim_mmap.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/mprotect_prot_growsdown.c, LibOS/shim/test/regression/test_libos.py
This PR adds support for `PROT_GROWSDOWN` to `mprotect`. Not this does not implement `MAP_GROWSDOWN` itself, i.e. memory won't get automatically extended.
Closes #1615
Fixes #1612
New test added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1636)
=> [LibOS] Add support for PROT_GROWSDOWN

LibOS/shim/src/shim_parser.c
Display missing PROT flags, such as PROT_GROWSDOWN.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1613)
=> LibOS: Display missing PROT flags

LibOS/shim/src/shim_parser.c
Print missing MAP_XYZ flags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1634)
=> LibOS: Print missing MAP_XYZ flags

LibOS/shim/include/arch/x86_64/shim_internal-arch.h, LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_internal.h, LibOS/shim/include/shim_ipc.h, LibOS/shim/include/shim_thread.h, LibOS/shim/include/shim_utils.h, Pal/include/lib/hex.h, Pal/src/pal_internal.h
No reason to force inline in those places. There are also some functions allocating buffers on parent's stack frame (sic!) which require this, but unhacking them requires more work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1644)
=> Remove always_inline where not needed

Pal/lib/string/memcpy.c
This patch fixes the following compile error:
string/memcpy.c: In function \u2018memcpy\u2019:
string/memcpy.c:32:16: warning: dereferencing \u2018void *\u2019 pointer
*d++ = *src++;
^~~~~~
string/memcpy.c:32:14: error: void value not ignored as it ought to be
*d++ = *src++;
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1646)
=> PAL: Fix non-x86 implementation of memcpy

LibOS/shim/src/sys/shim_open.c, LibOS/shim/test/regression/test_libos.py
This fixes two things:
- LibOS regressions wasn't passing on Glibc 2.23 which uses `open` syscall to implement C's `open()` function. Newer Glibcs use `openat` syscall instead. Turns out our `shim_do_open` doesn't handle empty paths correctly (but `shim_do_openat` does).
- `test_201_exec_same` test was failing if the output was interleaved with debug logs. Current fix is rather a workaround until we split Graphene logs from app output.
Run LibOS regression with glibc 2.23 (`GLIBC_VERSION=2.23` specified to `make`) and with `loader.debug_type = none` in `manifest.template`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1648)
=> [LibOS] Regression tests fixes

Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/enclave_pages.c
Previously, Linux-SGX PAL initialized the whole heap to zero from within the enclave at startup. This led to significant slowdown on large-sized enclaves. This commit removes the old proactive logic and instead zeroes-out the heap lazily, when enclave pages are actually requested.
This does not change the security guarantees because the whole heap is anyway RWX on SGX v1, and the attacker may exploit app vulnerabilities (if any) by supplying malicious data within the enclave during runtime.
All tests must pass. Below are some of my quick tests. Enclave sizes: 8GB for `Bootstrap6`, 2x 256MB for `fork_and_exec`, and 1GB for `Redis`.
The CPU has 128MB of EPC. The SGX driver adds *one* page per IOCTL.
- Without this PR:
```
Command being timed: "/home/dimakuv/graphene/Runtime/pal_loader …
```
=> [Pal/Linux-SGX] Lazily zero-out the heap instead of proactively on init

Documentation/conf.py, Documentation/manpages/gsc.rst, Jenkinsfiles/Linux-SGX-gsc, README.rst, Tools/gsc/.gitignore, Tools/gsc/config.yaml.template, Tools/gsc/finalize_manifests.py, Tools/gsc/gsc, Tools/gsc/gsc.py, Tools/gsc/sign_manifests.py, Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, Tools/gsc/templates/apploader.template, Tools/gsc/templates/manifest.template, Tools/gsc/test/Makefile, Tools/gsc/test/README.rst, Tools/gsc/test/bash.manifest, Tools/gsc/test/ls.manifest, Tools/gsc/test/sh.manifest, Tools/gsc/test/ubuntu18.04-bash.dockerfile, Tools/gsc/test/ubuntu18.04-hello-world.dockerfile, Tools/gsc/test/ubuntu18.04-nodejs.dockerfile, Tools/gsc/test/ubuntu18.04-nodejs.manifest, Tools/gsc/test/ubuntu18.04-numpy.dockerfile, Tools/gsc/test/ubuntu18.04-numpy.manifest, Tools/gsc/test/ubuntu18.04-python3.dockerfile, Tools/gsc/test/ubuntu18.04-python3.manifest, Tools/gsc/test/ubuntu18.04-pytorch.dockerfile, Tools/gsc/test/ubuntu18.04-pytorch.manifest, Tools/gsc/test/uname.manifest
Recreation of PR #1345.
Tooling to automatically translate docker images to graphenized docker image using Linux-SGX Pal.
Implemented in the folder Tools/gsc in a python script called gsc.py. Tools/gsc/README.md describes the implementation of the tool gsc.py (or gsc). Its usage is described in the Documentation in Documentation/manpages/gsc.rst. The gsc command line tool follows the common docker approach to first build an image and subsequently run a container of an image. 
GSC build: gsc prepares the a two stage dockerfile, manifest files, and an application loader. The Docker file is split into two stages. The first stage compiles Graphene based on the provided configuration (see config.json) which includes the Ubuntu version, the Intel SGX driver, and Graphene repository. The second …
=> Docker integration via Graphene Shielded Containers 

Pal/src/host/Linux-SGX/tools/common/Makefile
download: Found 'v1.7.12.tar.gz' (76068766...) in cache.
download: Found 'v1.7.12.tar.gz' (76068766...) in cache.
cp: cannot create regular file 'v1.7.12.tar.gz': Permission denied
make[5]: *** [Makefile:25: cJSON.c] Error 1
make[5]: *** Waiting for unfinished jobs....
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1633)
=> [pal] fix parallel build

Jenkinsfiles/Linux, Jenkinsfiles/Linux-18.04, Jenkinsfiles/Linux-Debug, Jenkinsfiles/Linux-Debug-18.04
I noticed that "normal" CI jobs were being run on a test machine where we were experimenting with a different kernel.  This was mostly fine, but I cannot easily reboot and mess with the machine while unrelated jobs are running.
To fix this, we need to add an explicit agent label to every pipeline and to the workers; the non-sgx jobs are unconstrained and have no label.  I have already added a 'nonsgx_slave' label to any workers we expect to be stable, and this PR adds it to the pipeline definition as well.
This may take a bit to percolate through all of the pending PRs.
Just run the non-SGX Jenkins pipelines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1662)
=> [CI] Add a label to non-SGX jobs

Pal/src/host/Linux-SGX/enclave_entry.S, Pal/src/host/Linux-SGX/sgx_entry.S, Pal/src/host/Linux-SGX/sgx_exception.c, Pal/src/host/Linux-SGX/sgx_internal.h
This PR fixes two very subtle bugs in our assembly code for SGX EENTER/EEXIT/AEX flows:
Previously, Linux-SGX PAL checked RIP of the interrupted normal context only against the first instruction of the AEP trampoline code (recall that SGX passes control to AEP on AEX). In Graphene, this is the asm function `async_exit_pointer()`. However, Linux may deliver signal (as response to AEX) at any point during AEP trampoline. Thus,PAL code incorrectly checked RIP and wrongly assumed that there was no AEX but instead an exception in PAL code itself, which led to rare Graphene failures. This commit fixes this bug by checking RIP against the whole range of function `async_exit_pointer()`.
Previously, Linux-SGX PAL did not clear `SSA.GPRSGX.EXITINFO` while in signal handler (which Graphene enters in …
=> [Pal/Linux-SGX] Fix super-subtle bugs in SGX enter/exit/AEX flows

Documentation/manifest-syntax.rst, Pal/regression/Bootstrap6.manifest.template, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/enclave_pages.c, Pal/src/host/Linux-SGX/pal_security.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py
Commit 647bca34 changed the old logic of "zero the whole heap during enclave initialization" to "zero the heap pages on demand". This led to better start-up times of enclaves (without any significant security drawbacks). However, this change has a trade-off: some applications (Redis in particular) have worse run-time performance.
To allow users to choose between faster start-up time vs better run-time performance, this commit introduces "sgx.zero_heap_on_demand" manifest option. It is zero by default, meaning zero-out of whole heap during enclave initialization; i.e., by default enclaves take longer to start, but have better run-time performance.
See https://github.com/oscarlab/graphene/pull/1640 for the context.
We observed 5-10% runtime performance overhead with highly-loaded Redis …
=> [Pal/Linux-SGX] Introduce manifest option "sgx.zero_heap_on_demand"

LibOS/glibc-patches/glibc-2.23.patch, LibOS/glibc-patches/glibc-2.27.patch, LibOS/glibc-patches/glibc-2.31.patch
The LibOS managed glibc compiling reports the following message
during glibc building.
```*** errlist.c count 134 inflated to GLIBC_2.12 count 135 (old errno.h?)```
It may confuses user as the GSGX compilation issue.
The defined error counting is greater than actual one from it.
it is just used for future expansion.
Fixes #1653
make
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1654)
=> [LIBOS] Fix errlist.c error counting not matching issue

LibOS/Makefile
That isn't the best idea, especially when a single build generates 13MB of logs :)
Build a few different versions of GLIBC (or modify one of our patches to cause it to rebuild itself).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1670)
=> [LibOS] glibc: Overwrite instead of appending to build.log

Documentation/manifest-syntax.rst, Examples/blender/blender.manifest.template, Examples/python-scipy-insecure/python.manifest.template, Examples/python-simple/python.manifest.template, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/bootstrap.c, LibOS/shim/test/regression/env_from_file.manifest.template, LibOS/shim/test/regression/env_from_host.manifest.template, LibOS/shim/test/regression/test_libos.py, Pal/include/lib/api.h, Pal/lib/graphene/config.c, Pal/src/db_main.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux/db_main.c, Pal/src/host/Linux/db_process.c, Pal/src/host/Linux/pal_linux.h
This is similar to #1562, but for environment variables. It implements a way to pass environment variables from a file, with intention to use it in conjunction with either trusted or protected files.
Fixes #508.
Two new tests were added for the new functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1667)
=> Protected env

Examples/ra-tls-mbedtls/Makefile, Examples/ra-tls-mbedtls/README.md, Examples/ra-tls-mbedtls/server.manifest.template, Examples/ra-tls-mbedtls/src/client.c, Examples/ra-tls-mbedtls/src/server.c, Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls.h, Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c, Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c
Previously, RA-TLS was recommended to be used with LD_PRELOAD trick. However, LD_PRELOAD is too hacky and shouldn't be used to preload libraries to an executable (in contrast to its normal use of replacing functions from one library with another).
This PR removes any mentions of LD_PRELOAD trick from RA-TLS, and replaces LD_PRELOAD with `dlopen()` in ra-tls-mbedtls example.
All tests must pass (including the ra-tls-mbedtls example).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1655)
=> [Examples,Pal/Linux-SGX] Replace LD_PRELOAD with dlopen in RA-TLS

LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/rdtsc.c, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/db_exception.c, Pal/src/host/Linux-SGX/db_misc.c
Under SGX PAL, if the CPU doesn't support RDTSC/RDTSCP inside SGX enclave, Graphene uses trap-and-emulate on these instructions. Previously, Graphene only emulated RDTSC and not RDTSCP. Moreover, Graphene emulated RDTSC by simply returning zeros, which could lead to faults in applications not expecting a zero value. 
This PR emulates (imprecisely) both RDTSC and RDTSCP via `gettime()` syscall.
For historical context, see https://github.com/oscarlab/graphene/pull/424.
Thanks to Shaopu Yan <shaopu.yan@intel.com> for pointing out this issue and providing a test case.
New LibOS test `rdtsc` is added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1660)
=> [Pal/Linux-SGX] Correctly emulate RDTSC and RDTSCP instructions

Pal/src/host/Linux-SGX/db_exception.c
There is a chance the enclave prohibits the instructions of wrfsbase / rdfsbase at runtime
because the CPU FSGSBASE has been disabled for some reasons e.g. suspend, hibernate.
This patch identified and captured this case and also provided
the following useful debug info to users
"Please re-load Graphene SGX kernel module"
Fixes #1664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1665)
=> PAL/Linux-SGX] Identify Unknown or illegal instruction caused by WRFSBASE or RDFSBASE instruction

LibOS/shim/test/regression/Makefile
Only compile cpuid and attestation test cases on x86
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1675)
=> LibOS: Only compile cpuid and attestation test cases on x86

LibOS/shim/test/regression/proc_common.c
Null terminate buffer before printing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1676)
=> LibOS: Null terminate buffer before printing

Pal/include/arch/x86_64/cpu.h, Pal/src/db_misc.c, Pal/src/host/Linux-SGX/db_exception.c, Pal/src/host/Linux-SGX/db_main-x86_64.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux/db_misc.c, Pal/src/host/Skeleton/db_misc.c, Pal/src/pal_internal.h
This patch optimizes the function _DkSystemTimeQuery()
by using RDTSC instead of gettimeofday ocall/syscall.
This optimization won't take effect if there is no reliable
TSC source available to use i.e. nonstop TSC.
The TSC drift has been bound by resetting baseline timestamp
and tsc cycle aligned with system clock periodically.
Fixes #1598 
the existing time related test cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1621)
=> [Pal/Linux-SGX] Optimize the system time function using TSC cycles

Pal/regression/Makefile
Use executables-x86_64 for x86_64-specific executables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1677)
=> PAL: Use executables-x86_64 for x86_64-specific executables

Pal/src/host/Linux-SGX/protected-files/protected_files.c, Pal/src/host/Linux-SGX/tools/common/pf_util.c
This PR fixes two bugs in Protected Files:
- mbedTLS source of entropy (`mbedtls_entropy_context`) was allocated on the stack and thus destroyed after return from init function; in reality, this object must live for the whole duration of execution (this bug led to spurious segfaults due to overwritten stack).
- MHT nodes of protected files must be updated and flushed to disk in reverse order of sorting, from bottom layers to upper layers (this bug led to outdated MHT key/MAC values in resulting encrypted file, so the file could not be correctly decrypted).
Note that both bugs crept into our port of Intel SGX SDK. The first bug is absent from SDK because it doesn't use mbedTLS. The second bug is actually a blunder of porting (we even had the comment to sort in reverse order!), and SDK does …
=> [Pal/Linux-SGX] Fix bugs in protected files that broke large files

Examples/busybox/Makefile
Using busybox 1.32.0 on more recent distros (Fedora 32) avoids linker
issues like the following ones:
/usr/bin/ld: coreutils/lib.a(mktemp.o): in function `mktemp_main':
mktemp.c:(.text.mktemp_main+0xd0): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/usr/bin/ld: util-linux/lib.a(rdate.o): in function `rdate_main':
rdate.c:(.text.rdate_main+0x150): undefined reference to `stime'
/usr/bin/ld: coreutils/lib.a(date.o): in function `date_main':
date.c:(.text.date_main+0x2a4): undefined reference to `stime'
collect2: error: ld returned 1 exit status
Note: if build needs additional libraries, put them in CONFIG_EXTRA_LDLIBS.
Example: CONFIG_EXTRA_LDLIBS="pthread dl tirpc audit pam"
make[1]: *** [Makefile:718: busybox_unstripped] Error 1
--- …
=> Examples: Upgrade to busybox 1.32.0 (latest) to avoid linker issues

Examples/redis/Makefile
Using redis 6.0.5 on more recent distros (Fedora 32) avoids linker
issues like the following ones:
LINK redis-server
/usr/bin/ld: server.o:/home/stefanb/pef-dev/graphene/Examples/redis/src/src/sds.h:37: multiple definition of `SDS_NOINIT'; quicklist.o:/home/stefanb/pef-dev/graphene/Examples/redis/src/src/sds.h:37: first defined here
/usr/bin/ld: sds.o:/home/stefanb/pef-dev/graphene/Examples/redis/src/src/sds.h:37: multiple definition of `SDS_NOINIT'; quicklist.o:/home/stefanb/pef-dev/graphene/Examples/redis/src/src/sds.h:37: first defined here
[...]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1682)
=> Examples: Upgrade to redis 6.0.5 to avoid linker issues

Examples/ra-tls-mbedtls/Makefile, Examples/ra-tls-mbedtls/README.md, Examples/ra-tls-mbedtls/client.manifest.template, Examples/ra-tls-mbedtls/src/client.c, Pal/src/host/Linux-SGX/tools/ra-tls/Makefile, Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap_urts.c
Add options to allow RA TLS client to run in SGX as well. It can be used as an example of in-enclave remote attestation and verification, both EPID and ECDSA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1657)
=> [Examples] Add option to run RA TLS client in SGX

.ci/run-pylint, LibOS/shim/test/ltp/.gitignore, LibOS/shim/test/ltp/Makefile, LibOS/shim/test/ltp/Makefile.Test, LibOS/shim/test/ltp/Makefile.testcases, LibOS/shim/test/ltp/README.rst, LibOS/shim/test/ltp/makevars.mk, LibOS/shim/test/ltp/runltp_xml.py
Our LTP makefiles are a huge and complicated mess. I tried to fix them, but gave up at some point and did just a few changes.
Changes:
- `make all` previously rebuilt everything each time, now it doesn't.
- Using out-of-tree build.
- Unfortunately we have to build the whole LTP now (minus modules), so the build is slower.
- But: `make -jX` works, previously was broken because of missing dependencies.
- Not using symlinks as targets anymore - Make is broken and checks the timestamp of the *destination*, not the symlink itself. Previously the links were recreated on each `make` call.
- `make regression` printed `/bin/sh: 1: test: Illegal number: ` and now it doesn't.
I'll create a follow-up PR which adds more parallelism to our Jenkinsfiles (but only to building tests, not running). This …
=>  [LibOS] test/ltp: Try to deobfuscate Makefiles 

Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/protected-files/protected_files.c, Pal/src/host/Linux-SGX/protected-files/protected_files.h, Pal/src/host/Linux-SGX/tools/common/pf_util.c
Previously, `pf_file_read()`/`pf_read()` in Protected Files disallowed reading less than the requested number of bytes. This is incorrect semantics, and these functions must return the actually read number of bytes instead of loudly failing. This bug leads to e.g. errors in Python scripts (Python's `read()` reads one byte past the end of file
for whatever reason).
Thanks to @dayeol for finding this issue and pair-debugging it.
We found it when working on the PyTorch examples with protected-files input and output. The example will soon be submitted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1693)
=> [Pal/Linux-SGX] Allow reads of less bytes than requested in protected files

LibOS/shim/src/shim_init.c, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/init_fail2.manifest.template, LibOS/shim/test/regression/test_libos.py
See https://github.com/oscarlab/graphene/issues/1688. Graphene hanged if an error was detected very early (before IPC initialization) in the LibOS init process. With this PR, Graphene doesn't attempt to do cleanup and simply loudly exits the process.
Fixes #1688.
All tests must pass. New test `init_fail2` is added to LibOS regression suite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1691)
=> [LibOS] Do not clean-up if LibOS initialization failed

Documentation/building.rst
This PR updates instructions to install Linux 5.4 LTS (supported till the end of 2021) instead of non-LTS 5.7.
The backported FSGSBASE patch for 5.4 was contributed by Chang S. Bae.
Corresponding PR is https://github.com/oscarlab/graphene-sgx-driver/pull/26.
Manually install Linux 5.4 following the instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1683)
=> [Docs] Add instructions to install Linux 5.4 with backported FSGSBASE patch

Pal/src/host/Linux-SGX/db_exception.c
Previously, Graphene-SGX printed a confusing error messages if some exception happened inside the PAL code (which is fatal in Graphene). The error message always printed out the SSA.EXITINFO information even when the exception happened due to software (and thus SGX HW didn't populate SSA.EXITINFO).
This PR improves the error message so that it distinguishes between SGX HW-recognized exception (and prints out SSA.EXITINFO) and SW-sent signal (and prints just the signal number).
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1697)
=> [Pal/Linux-SGX] Improve debug message on fatal exception in PAL code

Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/enclave_pf.c
Current code generates tons of not-too-useful debug logs about files being opened, even with `loader.debug_type = none`.
This is because `SGX_DBG` macro disrespects debug logging settings from the manifest, but fixing this properly is a much bigger task (the whole logging subsystem should be redesigned), so I just dropped these annoying prints.
Run something compiled with DEBUG=1 but with `loader.debug_type = none` in the manifest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1699)
=> [PAL] protected files: Remove too-noisy debug prints

Examples/redis/redis-server.manifest.template
When I tried the steps in the Examples/redis/README file,  launch of redis-server failed, due to additional
dependencies that were not listed as trusted files in the manifest template.
Reason being this change->https://github.com/oscarlab/graphene/pull/1681,  updated, the version of redis-server in the Makefile, which has additional dependencies.
With this updated redis-server manifest file, able to launch redis-server and run benchmarks on Ubuntu 18.04 system.
Need to check if redis-server gets tested as part of Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1700)
=> Updated redis-server manifest template file with additional dependancies for  redis-server version 6+.

LibOS/shim/src/sys/shim_pipe.c
Although Graphene supports `SOCK_NONBLOCK` and `SOCK_CLOEXEC`, it disallowed for those flags in `type` argument to `socketpair`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1704)
=> [LibOS] Fix incorrect argument check in socketpair

LibOS/shim/src/shim_parser.c
MAP_SHARED_VALIDATE has a value of 3 and aliases with MAP_SHARED and
MAP_PRIVATE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1707)
=> [LibOS] Fix debug mmap flags parser

Pal/src/host/Linux-SGX/sgx_exception.c, Pal/src/host/Linux-SGX/sgx_thread.c, Pal/src/host/Linux-SGX/sgx_tls.h
This PR introduces new SGX-specific stats. The new stats are:
- number of synchronous signals (corresponds to SIGILL/SIGSEGV/..)
- number of asynchronous signals (corresponds to SIGINT/SIGCONT/..)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1706)
=> [Pal/Linux-SGX] Add more SGX-specific stats

Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/pal_host.h, Pal/src/host/Linux/db_files.c, Pal/src/host/Linux/pal_host.h
This patch aims to support applications running in Graphene-SGX to process FIFO files which exist in host.
I have two test applications which use FIFO to communicate with each other. The FIFO file has been created on the host OS with mknod. When trying to run the two applications in Graphene "Linux-SGX" PAL, I meet below problems, which cause communication failure:
a. when application running in Graphene-SGX ("Linux-SGX" PAL) tries to open FIFO file (which exists in host) with O_WRONLY access, Graphene-SGX instance would get hang. This is because PAL would try to open the file with all-zero flag so to get file stat, but this API would get hung when the file is FIFO.
b. when application running in Graphene-SGX tries to read on FIFO file, PAL would would call pread(), however, this API …
=> support applications running in Graphene-SGX to process FIFO files which exist in host

Examples/tensorflow/Makefile
The commit: [Examples] tensorflow: Fix default `make` target
replaced the target 'default' with 'all'.
However, the targets 'run-graphene', 'run-native' and 'check'
still depend on 'default', so it is not possible to run
make run-native
make run-graphene
make run-graphene SGX=1
as documented in the README.md file.
To fix this, modify these targets to depend on 'all' instead, as the target
'default' was replaced by 'all'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1711)
=> [Examples] tensorflow: Fix non-existing target 'default'

Pal/src/host/Linux-SGX/sgx_framework.c
At the suggestion of @woju, I manually tested the error message on a system with a 5.8+rc1 kernel with v13 of fsgsbase patch (and no gsgx module and fsgsbase support disabled at the kernel command line).  The current message encourages people to load the gsgx module without mentioning the security issues.
This patch updates the text that one sees to be more informative/clear about the issues.  Probably opportunities to improve this further.
On a system without fsgsbase support (just unload gsgx on most systems), run a pal unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1694)
=> [SGX] Update error message if fsgsbase support is not present

Tools/gsc/test/Makefile
Prints intermediate files during GSC testing
Closes #1710 .
Changed `Tools/gsc/test/Makefile` to print intermediate output files immediately to display possible failures.
Run regular GSC Jenkins pipeline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1719)
=> Change print behavior of GSC tests to print any intermediate test results

LibOS/Makefile, LibOS/shim/src/Makefile, Pal/src/Makefile, Scripts/Makefile.rules
This PR makes all symlinks in `Runtime` directory relative. Absolute paths are not really useful and this allows for moving or bind-mounting Graphene directory after compilation. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1721)
=> Make symlinks in Runtime directory relative

Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, Tools/gsc/test/Makefile
This PR fixes two issues.
1. A recent change which made all Runtime folder Symlinks relative results in `gsc build` command failing. As part of `gsc build` command all symlinks in /graphene/Runtime are converted to real files by iterating over all symlinks and copying them over. When the change was made to make the symlinks relative, the copy command no longer finds the file to copy and hence, the Docker `build` fails.
2. The failure of 1. was not discovered, since the Jenkins test ran on the master branch instead of the PR. The test makefile of GSC includes a `sed` command to create the required GSC `config.yaml`. This `sed` command was ignoring the Graphene branch input which is set in the Jenkins script.
To fix 1.:
Changed `Tools/gsc/templates/Dockerfile.build.ubuntu18.04.template` to …
=> Fix GSC testing Makefile and build template

LibOS/shim/include/shim_types.h
Define struct __kernel_itimerspec for kernel < 4.19.0 rather than < 4.18.0
This patch fixes #1718. It now builds on RHEL/CentOS 8.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1733)
=> LibOS: Define struct __kernel_itimerspec for kernel < 4.19.0

Pal/src/host/Linux-SGX/db_process.c
Remove reference to print_alloced_pages() which no longer exists.
Remove calling of print_alloced_pages() from _DkProcessExit()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1738)
=> Fix compilation error with PRINT_ENCLAVE_STAT enabled

LibOS/shim/src/shim_parser.c
Previously the syscall logging used a wrong name for this flag.
Run anything with debug type set to "inline" and look at the output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1744)
=> [LibOS] Correct logging of mmap with MAP_ANONYMOUS

Documentation/cloud-deployment.rst, Documentation/quickstart.rst, Pal/src/host/Linux-SGX/sgx_framework.c
Previously, Graphene-SGX required `vm.mmap_min_addr` equal to `0x0` for non-PIE executables (this is due to the SGX hardware requirement of enclave base being aligned on enclave size, coupled with non-PIE requirement of starting the code section at address `0x400000`).
The legacy Intel SGX driver required a device-file-backed mmap starting at address `0x0`. The newer DCAP/in-kernel SGX drivers don't require this, so Graphene-SGX can create the enclave at non-zero starting address and deprecate the hack of `vm.mmap_min_addr == 0x0`.
1. Use a machine with DCAP/in-kernel driver (DCAP v1.6+ and in-kernel v1.32+).
2. Reset `mmap_min_addr` like this: `echo 65535 | sudo tee /proc/sys/vm/mmap_min_addr`.
3. Manually build and run one of the LibOS regression tests (they are built with …
=> [Pal/Linux-SGX] Allow starting enclave address space with non-zero

LibOS/shim/src/sys/shim_mmap.c
Address hint should be ignored if it's lower than `PAL_CB(user_address.start)` in `shim_do_mmap`
Fixes #1743
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1747)
=> [LibOS] Add missing check for user_address.start in shim_do_mmap

Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/enclave_ecalls.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/sgx_api.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_tls.h
Problems fixed:
* handle_ecall incorrectly checked ms_sec_info argument (missing address verification and potential TOCTOU problem).
* init_xsave_size argument was taken from an untrusted source, while it can be retrieved from the CPU directly.
* A lot of ocalls used wrong types for sizes.
* `noinline` hack for sgx_copy_to_enclave and sgx_copy_ptr_to_enclave is not needed anymore as we use READ_ONCE and WRITE_ONCE now.
Read the code carefully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1750)
=> [Pal/Linux-SGX] Fix and refactor untrusted API code

LibOS/shim/include/shim_handle.h, LibOS/shim/src/sys/shim_fcntl.c, LibOS/shim/src/sys/shim_ioctl.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/pipe_nonblocking.c, LibOS/shim/test/regression/test_libos.py
Specifying O_NONBLOCK flag in the call to pipe2 applied it only to one
end of the pipe.
Fixes #1752
New regression test added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1754)
=> [LibOS] Fix setting O_NONBLOCK flag in pipe2

Documentation/building.rst, Documentation/quickstart.rst
This PR allows to use the in-kernel Intel SGX driver, by simply skipping the prompt (by pressing ENTER).
See the corresponding PR https://github.com/oscarlab/graphene-sgx-driver/pull/27.
Clone and build Graphene on a machine with in-kernel SGX driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1737)
=> [Docs,Pal/Linux-SGX] Allow to use the in-kernel SGX driver

Examples/tensorflow/Makefile
This is a repost of #1759.
The commit f895e0d below updates Makefile prerequisites, and accordingly $< needs to be updated.
```diff
diff --git a/Examples/tensorflow/Makefile b/Examples/tensorflow/Makefile
index 2439a1bc..247397d4 100644
--- a/Examples/tensorflow/Makefile
+++ b/Examples/tensorflow/Makefile
@@ -58,7 +58,7 @@ label_image.manifest: label_image.manifest.template
-e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
$< > $@
-label_image.manifest.sgx: label_image.manifest
+label_image.manifest.sgx: label_image label_image.manifest inception_v3.tflite labels.txt
$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
-libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
-key $(SGX_SIGNER_KEY) \
```
Run make SGX=1 in Examples/tensorflow.
--- …
=> [Examples] Fix tensorflow Makefile

LibOS/shim/include/shim_types.h, LibOS/shim/src/sys/shim_socket.c, LibOS/shim/test/regression/tcp_msg_peek.c
This PR adds dummy emulation (simply ignoring) the flag `MSG_DONTWAIT` in `recv/recvmsg/recvmmsg`. This logic is partially taken from #1511 .
It is much more complicated (probably impossible?) to add the real emulation of `MSG_DONTWAIT` in Graphene. So for now we ignore this flag to make applications like Erlang and Apache Flink to work.
This PR also adds checks for supported flags in sendto/sendmsg and allows only MSG_DONTWAIT and MSG_NOSIGNAL.
Fixes #1764. See this issue for more context.
Fixes #752.
`tcp_msg_peek` LibOS test was augmented with this flag, just for testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1766)
=> [LibOS] Allow but ignore MSG_DONTWAIT flag on recvfrom/sendto

Examples/ra-tls-secret-prov/Makefile, Examples/ra-tls-secret-prov/src/secret_prov_pf_client.c, Pal/src/host/Linux-SGX/db_process.c, Pal/src/host/Linux-SGX/enclave_pf.c, Pal/src/host/Linux-SGX/protected-files/protected_files.h
Trusted child enclaves must inherit the provisioned master (wrap) key for protected files from the parent enclave on fork/clone. This commit adds this functionality and modifies the RA-TLS secret provisioning PF client to test this (including in Jenkins).
Kudos to Li Xun for reporting this bug and proposing a solution. See #1762 for more details.
Fixes #1762.
`Examples/ra-tls-secret-prov` test in Jenkins is modified to test this in parent and child enclaves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1765)
=> [Pal/Linux-SGX] Preserve wrap key for protected files across forks

Pal/src/slab.c
If PAL memory allocator depleted the pre-allocated memory pool of `POOL_SIZE`, then previously PAL would allocate more pages (for its internal purposes e.g. for event objects), but LibOS had no idea about it. This led to LibOS allocating pages at same addresses and ultimately to subtle memory corruptions.
Fixing it requires complete re-write of PAL memory allocation. This PR simply modifies slab allocator to loudly terminate.
It also fixes small bug of lock-unprotected search in memory pool.
See https://github.com/oscarlab/graphene/issues/1072 for additional context.
This was found (again) on a very intensive PyTorch workload with many threads created and destroyed many-many times. This is hard to reproduce.
--- …
=> [Pal] Loudly fail if depleted POOL_SIZE in slab memory allocator

Examples/pytorch/pytorch.manifest.template, LibOS/.gitignore, LibOS/Makefile, LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, LibOS/shim/test/regression/openmp.manifest.template
Many multi-threaded applications rely on OpenMP for efficient parallelism. Such applications link against the `libgomp.so` lib. Unfortunately, the native `libgomp.so` uses a raw `SYSCALL` instruction to issues `futex()` syscalls instead of `syscall()` Glibc wrapper (for performance reasons).
`SYSCALL` instructions are executed on hot paths of OpenMP, but they are forbidden inside SGX enclaves, so Graphene traps-and-emulates them. This is very expensive, so this commit introduces an optional `make -C LibOS gcc` to build `libgomp.so` where `SYSCALL` is replaced by direct call into Graphene, similar to how we
patch Glibc. See `openmp` LibOS regression manifest for example.
This patched `libgomp.so` significantly improves SGX performance of Machine Learning workloads like PyTorch, TensorFlow, …
=> [LibOS] Build GCC with patched libgomp.so (OpenMP runtime library)

Examples/python-sh-insecure/.gitignore, Examples/python-sh-insecure/Makefile, Examples/python-sh-insecure/README.md, Examples/python-sh-insecure/python3.6.manifest.template, Examples/python-sh-insecure/python3.manifest.template, Examples/python-sh-insecure/scripts/callprocess.py, Examples/python-sh-insecure/scripts/helloworld.py, Examples/python-sh-insecure/sh.manifest.template, Jenkinsfiles/Linux-18.04, Jenkinsfiles/Linux-Debug-18.04, Jenkinsfiles/Linux-SGX-18.04-apps, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/shim_dcache.c
This PR adds the Python multi-process example and fixes the bug triggered by this example (incorrect checkpointing of "directory" handles/dentries). The two commits are:
- [LibOS] Mark checkpointed dir handle and dentry as not listed. The "directory" shim_handle and its associated dentry are marked as "listed" on `getdents()`, caching the contents of the directory as a list of dentries. However, Graphene doesn't checkpoint these contents (unless they were actually opened). Previously, there was a bug of not cleaning up the "listed" state of dir dentry and associated pointers of dir shim_handle on fork/clone. This led to `getdents()` in the child process showing empty directory contents. This commit fixes this bug.
- [Examples] Add Python3 multi-process (python -> shell ->python) example. …
=> Add Python3 multi-process (python -> shell ->python) example

LibOS/shim/src/sys/shim_fs.c, LibOS/shim/test/fs/.gitignore, LibOS/shim/test/fs/Makefile, LibOS/shim/test/fs/README.md, LibOS/shim/test/fs/common.c, LibOS/shim/test/fs/common.h, LibOS/shim/test/fs/copy_sendfile.c, LibOS/shim/test/fs/test_fs.py, LibOS/shim/test/fs/test_pf.py, Pal/src/host/Linux-SGX/db_files.c
Previously, Graphene would fail if application uses `sendfile()` on a protected file. This happened because LibOS's emulation of sendfile relies on PAL to allocate a temporary buffer for mmapped contents, however mmap implementation in PFs did not allocate this buffer. This commit adds logic in PFs to allocate the buffer (it is the
responsibility of LibOS to free it later). Also, since PFs propagate changes to writable files only on flush/close, sendfile is augmented with a forced flush.
Fixes https://github.com/oscarlab/graphene/issues/1769.
A sendfile test is added to FS/PF tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1774)
=> [LibOS,Pal/Linux-SGX] Fix sendfile() on protected files

Documentation/manpages/gsc.rst, Tools/gsc/gsc.py, Tools/gsc/test/Makefile
When building graphenized docker image, some build-time variables
like http_proxy, https_proxy, no_proxy are required for private
network behind proxy.
So this commit enable --build-arg for proxy configurations via
GSC_BUILD_FLAGS.
When building graphenized docker image, some build-time variables
like http_proxy, https_proxy, no_proxy are required for private
network behind proxy.
1. On a development machine behind firewall, assume the "http_proxy=http://<some-http-proxy>, https_proxy=http://<some-https-proxy>, no_proxy=<no-proxy>"
2. set the envornment variable GSC_BUILD_FLAGS via command "export GSC_BUILD_FLAGS=--rm --no-cache --build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy}"
3. Build graphenized docker image via "make" under the directory Tools/gsc/test.
--- …
=> [GSC] Support build-time variable via --build-arg.

LibOS/shim/include/shim_utils.h, LibOS/shim/src/shim_malloc.c, Pal/include/lib/memmgr.h, Pal/include/lib/slabmgr.h
In particular, this PR:
- Removes SLAB_DEBUG macros and corresponding code.
- Removes unused, commented out and outdated `realloc()` code.
- Fixes memory leak in memmgr's enlarge_mem_mgr() by removing  `__set_free_mem_area()` call.
- Fixes bug of double-free of the very first memmgr area in `destroy_mem_mgr()`.
- De-duplicates "get new memory object" code by changing `get_mem_obj_from_mgr()` to call `get_mem_obj_from_mgr_enlarge()`.
- Simplifies and improves performance of `free_mem_obj_to_mgr()` since there is no need to double-check that the object belongs to one of the memmgr's areas because we already check `memory_migrated()`.
- Fixes bug of free of wrong object in slabmgr's `destroy_slab_mgr()`.
This is a partial recreation of #1347. Unfortunately, that PR became too stale and too …
=> [LibOS,Pal/lib] Partially refactor slabmgr and memmgr in Pal/lib

Pal/src/host/Linux/db_rtld.c, Pal/src/host/Linux/pal_security.h
Linux PAL communicates the newly loaded libraries to GDB via the `_r_debug` special symbol. This symbol is actually an alias to Linux PAL's `g_pal_r_debug`. The alias is created via macro `symbol_version_default()` which injects assembly `.symver @@`.
This asm directive `.symver name, name2@@nodename` is defined as "the symbol name must exist and be defined within the file being assembled". However, this injected assembly ended up in files that did not have symbol `g_pal_r_debug` defined. Older versions of as (GCC's utility to generate object code from assembly) didn't
care about this missing symbol, but newer versions loudly fail with "invalid attempt to declare external version name as default". This commit fixes this bug by moving `symbol_version_default()` to the only relevant file -- …
=> [Pal/Linux] Fix "invalid attempt to declare..." with newer as

LibOS/shim/src/ipc/shim_ipc_pid.c, LibOS/shim/src/sys/shim_sigaction.c
Previously, Graphene not only broadcasted the KILL_ALL message via its IPC mechanism to direct children and parent (and they broadcasted to their children and parent in turn), but also sent additional KILL messages to all processes. These additional KILL messages triggered the FINDNS/TELLNS IPC mechanism to find the corresponding PID leaders. However, FINDNS/TELLNS are sent with acknowledgements, forcing the sending thread to wait on futex. This led to segfaults/hangs due to recursive IPC (e.g., in Apache web server after user sends SIGINT to terminate the process).
This PR fixes this bug by *not* sending additional KILL messages to other processes (the process already broadcasted KILL_ALL).
Manually start our Apache web server example:
```sh
~/graphene/Examples/apache$ make …
```
=> [LibOS] Do not recursively send KILL messages via Graphene's IPC

Pal/src/host/Linux-SGX/enclave_framework.c, Tools/gsc/finalize_manifests.py
Previously, Linux-SGX PAL allocated 4KB of memory for URI (filename) of any trusted/allowed file or directory. This led to "out of PAL memory" errors in Graphene if there are 100,000s of trusted files, as is the case for complex workloads in GSC/Docker. This PR removes the static 4KB buffer in file's metadata and instead
allocates the minimum required buffer. This PR also cleans up `register_trusted_file()` code a bit.
@vahldiek must test this with Python Docker image in GSC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1786)
=> [Pal/Linux-SGX] Allocate min required memory for file's filename

LibOS/shim/src/sys/shim_exit.c
This PR disables handling signals when the whole process is exiting. Previously we could get a signal (e.g. SIGCHLD) after ipc_helper thread was killed, which lead to crashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1789)
=> [LibOS] Disable preemption at process exit

LibOS/shim/include/shim_checkpoint.h, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/shim_checkpoint.c
Previously memory content was sent inside a checkpoint and counted
towards the checkpoint size in the child process, but not in the parent
process. The child allocated the checkpoint at the same address as in
the parent, but it had a different size, so it could colide with another
memory mapping. This commmit fixes it by making checkpointing code
receive the memory directly to destination addresses (which additionally
saves an unnecessary copy).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1788)
=> [LibOS] Rework sending memory content in checkpoints

Examples/openvino/Makefile, Examples/openvino/README.md, Examples/openvino/openvino.manifest.template
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
Current version of openVINO present in the code base is more than a year old and there has been some major updates to the benchmark. On ICX server the newer version 2020.4 shows ~63% improvement in frames/sec and ~5% improvement in latency vs 2019_R2 version.
One thing to note is that the latest version uses TBB/HWLOC libraries to get the platform topology. But due to this issue https://github.com/oscarlab/graphene/issues/1783, this PR forces openVINO to use OMP thread library instead of TBB. Once the issue is resolved, plan to update the makefiles to use TBB.
Please follow README file on how to test the changes.
--- …
=> [Examples] Update openVINO benchmark to 2020.4 version

LibOS/Makefile, LibOS/shim/include/shim_thread.h, LibOS/shim/include/shim_utils.h, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/elf/shim_rtld.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/ipc/shim_ipc_ranges.c, LibOS/shim/src/shim_async.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/test/native/get_time.c, LibOS/shim/test/native/test_start_pthread_m.c
See #1794.
Remaining:
- remove use of alloca in `dentry_get_path`
- segmentation fault when running `getdents` regression tests under gdb (likely because of the above)
- `IS_ARRAY` macro: clang complains about `static_assert` with `((void *) &(arg)) == ((void *) (arg))`
- `generated_offsets`: clang does not recognize `%p0` in assembly, generates source with a tab (`.ascii\tGENERATED_INTEGER`)
- `cfi_offset` (and others) does not work with `%rflags` ([bug](https://bugs.llvm.org/show_bug.cgi?id=33633)), need `#ifdef`
- clang does not recognize `-Wtrampolines`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1795)
=> clang fixes

Examples/r/Makefile, Examples/r/R.manifest.template, Examples/r/scripts/sample.r, Jenkinsfiles/Linux, Jenkinsfiles/Linux-18.04, Jenkinsfiles/Linux-Debug, Jenkinsfiles/Linux-Debug-18.04, Jenkinsfiles/Linux-SGX-18.04-apps, Jenkinsfiles/Linux-SGX-apps, Jenkinsfiles/ubuntu-16.04.dockerfile, Jenkinsfiles/ubuntu-18.04.dockerfile, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/shim_checkpoint.c
Previously, when Graphene migrated process metadata to a new host-OS process on `exec()` syscalls, the logic simply copied IPC information from the parent to the child via new object `shim_process* process`, including PAL handles for "self" and "parent" communication pipes. However, Graphene's LibOS doesn't have a notion of refcounts for corresponding PAL handles, so the copied PAL handles were still freed when freeing the not-used-anymore `process` object.
This PR fixes this by explicitly copying the PAL handles' pointers before migration and clearing them after migration. This PR also contains tiny bug fixes in the R example.
Fixes #1724. Fixes #1390.
Run R example manually.
--- …
=> [LibOS] Correctly set/unset PAL handles for IPC objects on exec()

LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/getsockname.c, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/db_sockets.c, Pal/src/host/Linux/db_sockets.c, Pal/src/pal_defs.h
This PR removes `ALLOW_BIND_ANY` and `check_any_addr()` logic. Removing this logic also fixes the bug in Linux PAL of binding on port 0 (previously it stayed as "0" instead of actual new port).
Fixes https://github.com/oscarlab/graphene/issues/1713.
Closes https://github.com/oscarlab/graphene/pull/1714. (This PR is a recreation of that PR with all fixes applied.)
New test is added to LibOS regression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1798)
=> [Pal/{Linux,Linux-SGX}] Remove ALLOW_BIND_ANY and check_any_addr() logic

LibOS/shim/include/shim_fs.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/proc/thread.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/ipc/shim_ipc_pid.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_getcwd.c, LibOS/shim/src/sys/shim_socket.c
Instead, require the user to always provide a big enough buffer.
For clang support, see #1794.
- Create a convenience "into qstr" wrapper
- Eliminate the only instances where the function was called with
on_stack == false (they were leaking memory)
- Remove a few null checks that are impossible now
- Fix possible overflow in unix_copy_addr() (truncate the address
instead)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1800)
=> [LibOS] Remove stack allocation from dentry_get_path()

Examples/pytorch/pytorch.manifest.template
This patch fix makes the file /etc/fstab to be accessible when running in SGX mode.
The following command can be used to test this PR
```SGX=1 ./pal_loader ./pytorch.manifest ./pytorchexample.py```
Fixes #1804
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1805)
=> [Examples] Fix Pytorch accessing file file:/etc/fstab denied issue

Examples/memcached/memcached.manifest.template, Examples/redis/redis-server.manifest.template, LibOS/shim/test/benchmark/manifest.template, LibOS/shim/test/native/manifest.template, LibOS/shim/test/regression/futex_bitset.manifest.template, LibOS/shim/test/regression/manifest.template, LibOS/shim/test/regression/mmap_file.manifest.template, Pal/regression/File.manifest.template, Pal/regression/Process.manifest.template, Pal/regression/SendHandle.manifest.template, Pal/regression/manifest.template
There were some lingering mentions of `net.{allow_bind,allow_peer,rules}` left from the times when reference monitor was a part of the codebase.
Graphene is not a sandbox and such rules most likely will never be implemented.
Closes #63.
CI. The changes should have no effect on anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1812)
=> Remove all mentions of unimplemented net.* manifest options

Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/sgx_api.h
See #646. Turns out that there's no need to drop consts from the structs, only `sgx_copy_to_enclave()` needs to be fixed. I guess the ticket was created when this wasn't possible, but our code has changed a lot since then.
Fixes #646.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1813)
=> [Pal/Linux-SGX] Don't cast off `const` in sgx_copy_to_enclave

LibOS/shim/test/regression/test_libos.py
Previously, running LibOS regression tests left a 4 GB file in FS until calling `make clean`. This PR fixes the problem.
Run LibOS regression and look at the regression directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1826)
=> [LibOS] regression: Don't leave a 4GB file on FS after tests

Documentation/cloud-deployment.rst
We used the wrong link to an AKS guide in our documentation for cloud deployments. This PR changes the link to the correct version.
Usual Jenkins tests. It is only a documentation change, no source code changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1836)
=> [GSC] Fix link to AKS guide in cloud deployment documentation

Tools/gsc/finalize_manifests.py
GSC falsely removed the first character from the OS provided LD_LIBRARY_PATH. Under some circumstances this removed '/' from LD_LIBRARY_PATH. Initially it was used to avoid several consecutive ':'. This is not an issue and hence, the suggested implementation allows multiple ':' and fixes the issue with '/'.
Usual Jenkins tests. If you'd like to exercise the LD_LIBRARY_PATH generation, you have to separately generate Docker images with various LD_LIBRARY_PATH variants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1827)
=> [GSC] Fix LD_LIBRARY_PATH generation

Tools/gsc/gsc.py
This set of patches removes a comma which caused issues during use of insecure arguments which are specified as part of the Docker image. I have not found a reason for this comma and hence, it should be removed.
Typical Jenkins GSC tests, since they evaluate both insecure and secure arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1831)
=> [GSC] Fix argument extraction from Docker image

LibOS/shim/src/Makefile, LibOS/shim/test/benchmark/test_start.c, Pal/regression/Makefile, Pal/src/host/Linux-SGX/Makefile, Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/tools/ias-request/Makefile, Pal/src/host/Linux-SGX/tools/pf_crypt/Makefile, Pal/src/host/Linux-SGX/tools/quote-dump/Makefile, Pal/src/host/Linux-SGX/tools/verify-ias-report/Makefile, Scripts/Makefile.configs
Issue: https://github.com/oscarlab/graphene/issues/1794.
After this batch of fixes:
* both Linux and Linux-SGX compile without warnings,
* Linux passes all tests,
* Linux-SGX still fails a few tests: https://leeroy.cs.unc.edu/job/graphene-sgx-18.04/3461/#showFailuresLink
All of this works under Ubuntu 18.04, because you can install Clang 10 there without adding any extra repositories.
I recommend **enabling Clang builds for Linux** on Jenkins now, and leave Linux-SGX until we manage to debug it.
However, I'm a bit hesitant to propose copy-pasting another set of Jenkinsfiles... I tried using a matrix build:
* [Matrix feature introduction](https://www.jenkins.io/blog/2019/11/22/welcome-to-the-matrix/) on Jenkins blog
* [Jenkinsfile](https://github.com/pwmarcz/graphene/blob/de8ed1560fc0baa913 …
=> Clang fixes: get Linux-18.04 to compile and test

LibOS/shim/include/shim_handle.h, LibOS/shim/include/shim_internal.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/sys/shim_epoll.c, LibOS/shim/src/sys/shim_socket.c
This PR unifies logic of counting handles in an epoll instance. Additionally adds a callback function used at every update to a `handle->pal_handle`, to wakup potential threads blocked at `epoll`.
Kudos to @lejunzhu for pinpointing the issue. 
Fixes #1810
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1849)
=> [LibOS] Unify logic of counting handles in epoll

LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_fork.c, LibOS/shim/src/sys/shim_getpid.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/groups.c, LibOS/shim/test/regression/test_libos.py
Supplementary groups IDs are not often used inside Graphene, yet there was a global statically allocated buffer for them, which unnecessarily took a lot of space in binaries and was sent in checkpointing code.
This PR fixes that by making this buffer dynamically allocated on demand.
Added a new test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1850)
=> [LibOS] Make list of supplementary group ids dynamically allocated

LibOS/shim/src/sys/shim_exit.c, LibOS/shim/test/ltp/ltp.cfg
Linux masks exit codes in `exit` and `exit_group` syscalls, so we should do the same. This should lower the count of `Saturation error in exit code -1, getting rounded down to 255` warnings in the logs.
Also, I removed the timeout extension from LTP's exit test, no idea why it was there.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1855)
=> [LibOS] Correctly mask exit codes in exit{,_group} syscalls

Documentation/libos/shim-init.rst, Documentation/manifest-syntax.rst, LibOS/shim/include/shim_internal.h, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_brk.c, Pal/include/lib/api.h, Pal/lib/graphene/config.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/enclave_pages.c, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/slab.c
**UPDATE:** Renamed `sgx.internal_size` to `loader.pal_internal_mem_size`.
Previously, Graphene preallocated 64MB for PAL internal metadata like trusted/protected files metadata, handles metadata, etc. If this limit was depleted, Graphene loudly failed, and the user had no option but to change constant in source code and rebuild Graphene.
This PR adds the manifest option `sgx.internal_size` to allow increasing this limit in the manifest.
See https://github.com/oscarlab/graphene/issues/1792 and https://github.com/oscarlab/graphene/pull/1768 and https://github.com/oscarlab/graphene/issues/1072 for more context.
Fixes https://github.com/oscarlab/graphene/issues/1792.
This solution is still not the best. Ideally, we want LibOS to be aware of what memory regions PAL takes for itself during …
=> [Pal/Linux-SGX] Add manifest option `sgx.internal_size`

LibOS/shim/src/sys/shim_exit.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/sighandler_divbyzero.c, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/enclave_entry.S
This PR has two bug fixes:
1. [LibOS] Wake up parent thread on SIGCHLD from child. Previously, Graphene had a bug of trying to wake up the (remote) child thread on SIGCHLD. This was a nop. It also meant that the parent thread, who was waiting on the child, wasn't interrupted and continued hanging instead of handling SIGCHLD.
2. [Pal/Linux-SGX] Save XSAVE area of normal app context on sync signals. Previously, when a synchronous signal like SIGFPE/SIGILL happened in the application (e.g., due to div-by-zero or SGX-prohibited SYSCALL instruction), Linux-SGX assembly routine incorrectly saved the XSAVE area (containing among other things FP/SSE/AVX registers) of the signal context. This commit fixes this bug by extracting the XSAVE area of the normal app context, i.e., XSAVE of SSA 0.
This …
=> [LibOS, Pal/Linux-SGX] Signal handling bug fixes

LibOS/shim/test/regression/openmp.c
Seems that `test_libos.py::TC_02_OpenMP::test_000_simple_for_loop` didn't work on systems with too many cores - OpenMP tried to spawn too many workers, thus exceeding the TCS limit hardcoded in the test's manifest.
Run LibOS regression with SGX on a system with more than 32 logical cores.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1854)
=> [LibOS] regression: Fix OpenMP test on systems with a lot of cores

LibOS/Makefile
Unfortunately, specifying environment variables like CC, CXX, AS during GCC build leads to strange errors. The official GCC docs simply state "defining certain environment variables such as CC can interfere with the functioning of make". See https://gcc.gnu.org/install/build.html.
That particular change (that broke GCC builds) was introduced recently in https://github.com/oscarlab/graphene/commit/2a1859184841f1ab902e6cf8d3aaacc008b75260. This PR simply reverts this change.
Try `make -C LibOS gcc` in the root dir of Graphene. Without this PR (and after commit 2a1859184), it fails with funny errors. With this PR, the build of GCC is successful.
Kudos to Shih-han (Hans) Wang for reporting the bug and testing it!
--- …
=> [LibOS] Makefile: Revert commit 'Make sure to build GCC with GCC'

Pal/src/host/Linux-SGX/db_rtld.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb, Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx_gdb.py, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_gdb_info.c, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_rtld.h
See https://github.com/oscarlab/graphene/issues/1814.
The old integration was based on directly executing GDB commands.
Instead, we maintain a linked list of debug sections, and notify
GDB using a breakpointed function.
In addition, make sure to read the structure when we attach to a
new process, by hooking the GDB stop event.
From my testing, this also solves the problem with breakpoints not
working until you break (Ctrl-C) inside an enclave. Adding a
breakpoint to a specific file (`break foo.c:main`) also seems to
work correctly, even before the process is started (the breakpoint
is conditional on a file load).
Starting a new process:
* Compile Graphene with `SGX=1 DEBUG=1`
* Compile LibOS/test/regression with `SGX=1 DEBUG=1`
* Start GDB: `GDB=1 SGX=1 ./pal_loader bootstrap`
* Add a …
=> [Pal/Linux-SGX] Rewrite GDB symbol file updates

LibOS/glibc-patches/syscalldb-api.patch, Pal/src/db_rtld.c
This fixes the backtrace in Linux when calling LibOS syscalls (though not Linux-SGX yet, there is some issue with CFI mentioned in #1814).
* Prepare a program that uses `getchar()` (or `read()`, for a simpler stack)
* Run in GDB, hit Ctrl-C while the program is waiting
* Run `backtrace`, the backtrace should be unbroken from `char_read` all the way to `main`, `__libc__start_main` and `_start`.
(On master, the backtrace ends on `__GI___libc_read`).
* Run `disassemble __GI__libc_read`, on my system it starts with `mov %fs:0x18,%eax` and `test %eax, %eax`. (On master, the debug information is misaligned and GDB claims that the function starts earlier).
--- …
=> Fix stack walking in Linux

Documentation/devel/howto-doc.rst, Documentation/requirements.txt
In trying to build the html docs on my system, I ran into several issues following the current docs.  A lot boiled down to (a) that python2 just doesn't work and I had some conflicting packages installed (b) sphinx needs to be 1.8 or higher, and (c) I needed to install sphinx_rtd_theme.
I updated the instructions to be more clear about this, and added sphinx_rtd_theme to requirements.txt.
Documentation only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1867)
=> [Docs] Clarify build requirements

Documentation/cloud-deployment.rst, Documentation/manifest-syntax.rst, Documentation/tutorials/pytorch/index.rst, Examples/openvino/openvino.manifest.template, Examples/pytorch/pytorch.manifest.template, LibOS/shim/test/regression/fopen_cornercases.c, LibOS/shim/test/regression/manifest.template, Pal/regression/File.c, Pal/regression/File.manifest.template, Pal/regression/test_pal.py, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py, Tools/gsc/test/ubuntu18.04-nodejs.manifest, Tools/gsc/test/ubuntu18.04-numpy.manifest, Tools/gsc/test/ubuntu18.04-python3.manifest, Tools/gsc/test/ubuntu18.04-pytorch.manifest
The manifest option "sgx.allow_file_creation" is useless (most real-world apps will set it to "1" anyway). So this PR simply removes this option and always allows to create files.
All tests must pass (removed this option from some regression tests). Also I manually tested PyTorch, it still works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1865)
=> [Pal/Linux-SGX] Remove "sgx.allow_file_creation" and always allow it

Jenkinsfiles/Linux-SGX, Jenkinsfiles/Linux-SGX-18.04, Jenkinsfiles/Linux-SGX-18.04-apps, Jenkinsfiles/Linux-SGX-apps
We are still using v1.9 of the Intel SGX driver; there is no good reason not to test with the latest v2.6.  
Moreover, the OOT SGX driver is not well-maintained.  To compile against a 5.8 kernel or newer, the isgx driver needs some patches.  Although I have sent a PR several weeks ago, it has gotten no attention from any maintainers.
This PR moves us to a local mirror repo, and includes the needed build fixes.  
The PR also includes an agent label for machines with 2.6 installed, so that we can gradually migrate SGX machines to v 2.6.  The host configuration and the pipeline need to move in lockstep.  Initially, we just have uncledeadly on isgx v2.6; after this lands we may need to keep one non-v2.6 worker for older PRs or ask them to rebase to master.
Run a jenkins pipeline.
---
This …
=> [CI, SGX] Migrate the pipeline to a patched 2.6 Intel driver

LibOS/shim/src/sys/shim_exit.c, LibOS/shim/src/sys/shim_sigaction.c
When a signal arrives, it must have a meaningful value in its `siginfo_t::si_code` field. Previously, Graphene set this value correctly for SIGFPE, SIGILL, SIGSEGV, SIGBUS, and for SIGCHLD during `waitid()`. However, it was not set during `kill()`, `tkill()`, `tgkill()`, and when parent thread/process was notified about the child's termination on `thread_destroy()`. This commit adds these last two scenarios; this is required for correct Glibc's pthread
cancellation via `sigcancel_handler()`.
All tests must pass. Didn't add a new test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1870)
=> [LibOS] Fill si_code field in siginfo_t struct in kill/tkill/tgkill

Jenkinsfiles/ubuntu-16.04.dockerfile, Jenkinsfiles/ubuntu-18.04.dockerfile, LibOS/shim/test/fs/test_pf.py, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/debug.c, LibOS/shim/test/regression/debug.gdb, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/db_rtld.c, Pal/src/host/Linux-SGX/enclave_entry.S, Pal/src/host/Linux-SGX/sgx_entry.S, Runtime/pal_loader, Scripts/Makefile.configs, Scripts/regression.py
This is based on https://github.com/oscarlab/graphene/pull/1864, so I'm marking it as draft until the other PR is merged.
SGX backtraces should now work, i.e. it's possible to break in an ocall, and see the backtrace up to the code inside enclave. Unfortunately, the backtrace doesn't go any further (to program startup outside the enclave).
There is also a simple regression test for GDB that checks if:
* breakpoints work (which should catch problems with symbol loading),
* backtraces look sane (`_start`, no `??`).
See https://github.com/oscarlab/graphene/pull/1864 but should work also in Linux-SGX.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1868)
=> Fix stack walking in Linux-SGX + add test for GDB

LibOS/shim/include/arch/x86_64/shim_syscalls.h, LibOS/shim/include/shim_defs.h, LibOS/shim/src/Makefile
When compiling against v5.8 (or later) kernel headers, we encounter
compilation errors such as:
In file included from /usr/include/asm/unistd.h:13,
from shim_parser.c:11:
shim_parser.c:408:10: error: array index in initializer exceeds array bounds
[__NR_io_uring_setup]    = {.slow = 0, .parser = {NULL}},
The remedy is to extend "syscall_parser_table" by modyfing the
definition of LIBOS_SYSCALL_BOUND so the offending system calls fit in the table.
While at it, also fix the actual values for syscall numbers in "shim_syscalls.h"
(The numbers are not sequential, there is an intentional gap between the numers)
Fixes #1878.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1882) …
=> [LibOS] Use correct v5.8 x86 syscall numbers

.ci/run-shellcheck, .dir-locals.el, CONTRIBUTING.rst, LibOS/shim/test/fs/Makefile, LibOS/shim/test/regression/Makefile, Pal/regression/Makefile, Scripts/run-pytest
Running a subset of regression tests, or a single test, is
currently rather annoying, as you cannot simply run 'pytest':
you need to override PYTHONPATH and specify several environment
variables.
Instead, move the whole boilerplate to a wrapper scripts that
allows running pytest with any command line options. Use it in
Makefiles as well, so that it doesn't go out of sync with CI.
Try to follow the instructions for `run-pytest` added in `CONTRIBUTING.rst`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1881)
=> Create a helper script for running pytest

LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/debug_regs-x86_64.c, LibOS/shim/test/regression/debug_regs-x86_64.gdb, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c
Issue: https://github.com/oscarlab/graphene/issues/1814
On top of https://github.com/oscarlab/graphene/pull/1868.
This allows reading/writing XMM0 etc. by passing XSAVE data when GDB requests it. There is also a test for that.
Check if `print $xmm0` and `set $xmm0 = ...` work.
You can use the provided test program (`tdebug_regs.c`) for that. In `LibOS/shim/test/regression`:
* Run the test script: `SGX=1 GDB=1 GDB_SCRIPT=debug_regs.gdb pal_loader ./debug_regs`
* Or play with the program in GDB: `SGX=1 GDB=1 pal_loader ./debug_regs`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1874)
=> GDB: support extended registers

LibOS/shim/include/shim_checkpoint.h, LibOS/shim/include/shim_fork.h, LibOS/shim/include/shim_ipc.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/ipc/shim_ipc_child.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/ipc/shim_ipc_ranges.c, LibOS/shim/src/ipc/shim_ipc_sysv.c, LibOS/shim/src/shim_checkpoint.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_fork.c, LibOS/shim/src/sys/shim_getpid.c, LibOS/shim/src/sys/shim_semget.c, LibOS/shim/src/utils/printf.c
This PR renames `shim_process` to `shim_process_ipc_info` to better reflect it's purpose (+ I want to use `shim_process` in another PR) and removes unused `exit_code` field from it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1887)
=> [LibOS] Rename shim_process

LibOS/shim/test/ltp/ltp-sgx.cfg, LibOS/shim/test/ltp/ltp.cfg, LibOS/shim/test/ltp/runltp_xml.py
From now you can write * into section names in ltp.cfg, but such
sections can only contain "skip".
This is in order to make the configuration file more usable: in
many cases, we want to skip a whole class of tests, because a given
feature/syscall is not supported by Graphene.
Two such groups are "collapsed" as a proof of concept. A more thorough cleanup of LTP configuration will follow later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1886)
=> [test] allow skipping LTP tests by fnmatch

LibOS/shim/include/shim_thread.h, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_fork.c
This PR removes unneeded checkpointing of `running_thread` (merging necessary parts with checkpointing of `thread`). Cloning a new thread does not use checkpointing. fork and execve checkpoint only information about the new thread to be run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1889)
=> [LibOS] Consolidate and remove unused code in thread checkpointing

.gitignore, Runtime/meson.build, Runtime/pal_loader, meson.build
This adds a possibility to actually install graphene in the system, and make packages for distributions.
This also might be a beginning of switching build system to meson. See #760 for a discussion of alternative build system, which I hope to revive.
Compile as usual with and without SGX (this is important that both variants are built together). Prepare some `helloworld` executable with manifest, signatures etc.
After that:
```sh
sudo apt install ninja-build
python3 -m pip install meson
meson setup build --prefix "$HOME"/tmp
ninja -C build # currently no-op, this is where any compilation would happen
ninja -C build install
export PATH="$HOME"/tmp/bin:"$PATH"  # or wherever you chose the prefix
cd "$HOME"/my-example-programs # with manifests and signatures and tokens already prepared …
```
=> Add first meson.build for installing

LibOS/shim/include/shim_fs.h, LibOS/shim/src/fs/dev/null.c
Glibc function daemon() checks `st_rdev` field in struct stat of `/dev/null`. However current  pseudo dev_null_fs doesn't fill  `st_rdev` field. This PR updates `dev_null_stat` to fill `st_rdev` field with hard code value and leaves `dev_tty_fs_ops` unchanged.
Fixes #1891
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1911)
=> [LibOS] Enhance /dev/null stat

Documentation/manifest-syntax.rst, Documentation/pal/host-abi.rst, Pal/regression/Bootstrap5.manifest.template, Pal/regression/Makefile, Pal/regression/test_pal.py, Pal/src/db_main.c, Pal/src/host/Linux-SGX/Makefile.manifest, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux/db_main.c, README.rst, Scripts/Makefile.rules
Previously, it was possible to use Graphene without the main executable (e.g. having only preloaded libraries). We aren't aware of anyone using this weird option, but worse, it led to a very bad UX when the user made mistakes - e.g. having a typo in the manifest or executable name could lead to Graphene starting without errors, but doing nothing.
Fixes #1905.
See #1905 for reproduction steps for an example of a problem fixed by this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1915)
=> Loader rework part 3: Disallow starting without an executable

LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/sys/shim_socket.c, LibOS/shim/src/sys/shim_stat.c, LibOS/shim/test/regression/unix.c
When connecting on a named UNIX domain socket, the `connect()` syscall checks if the socket path exists via `path_lookupat(&dent)`. However, `path_lookupat()` may return error and *not* update `dent` allocated on stack. In this case, `dent` contains garbage, and Graphene fails.
This PR fixes this via explicit `dent = NULL`.
A `unix` LibOS test is updated to test this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1913)
=> [LibOS] Fix dangling pointer `dent` on connect(AF_UNIX)

Pal/src/host/Linux-SGX/sgx_platform.c
Previously, if Graphene-SGX couldn't talk to AESM for whatever reason, it simply printed:
```
load_enclave() failed with error -2
```
This is not helpful. This PR prints a better message like this:
```
Cannot connect to aesm_service (tried sgx_aesm_socket_base and /var/run/aesmd/aesm.socket UNIX sockets).
Please check its status (`service aesmd status` on Ubuntu)!
load_enclave() failed with error -2
```
You can try manually by temporarily stopping the AESM service:
```
sudo service aesmd stop
LibOS/shim/test/regression$ SGX=1 ~/graphene/Runtime/pal_loader attestation
... fails! ...
sudo service aesmd start
LibOS/shim/test/regression$ SGX=1 ~/graphene/Runtime/pal_loader attestation
... works! ...
```
--- …
=> [Pal/Linux-SGX] Better error messages if can't talk to AESM

LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, LibOS/shim/include/shim_context.h, LibOS/shim/include/shim_thread.h, LibOS/shim/src/Makefile, LibOS/shim/src/shim_context-x86_64.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/fp_multithread.c, LibOS/shim/test/regression/test_libos.py
Previously, LibOS (shim) layer of Graphene didn't support XSAVE area.
The XSAVE area stores FP, XMM, YMM, ZMM, etc. registers and control states and is handled via FXSAVE/XSAVE and FXRSTOR/XRSTOR x86-64 instructions.
This PR is the first step towards adding full-fledged XSAVE support to LibOS. It adds XSAVE related structs and functions to LibOS code, and propagates XSAVE regs/states from parent to child on thread creation via `clone()`.
This PR is a partial recreation of #1218. My PR borrows the XSAVE structs and functions (but renames them for uniformity) from #1218. But XSAVE on signal-handling is not yet implemented; this is for the future.
Future commits will add XSAVE handling on syscall transitions and arriving signals.
New test `fp_multithread` is added to LibOS regression suite. …
=> [LibOS] Add XSAVE area handling and save/restore it on child thread creation

Jenkinsfiles/Linux-SGX-gsc, Tools/gsc/test/Makefile
This PR fixes issues in the test Makefile of GSC. 
1) One issue was introduced when the Makefile switched to using dedicated configuration files per distribution. As a result some Makefile targets include the test case in the configuration file name which should not be the case.
2) The second issue was around building the `python3` example based on a Graphene base image. This test case is called `base-python3` and previously had issues when building multiple times in a row.
Use a test case that does not have a specific Makefile target like `hello-world` and then run the respective test for this test case. In addition, Jenkins can be used to run the regular GSC pipeline.
--- …
=> [GSC] Fix test makefile to correctly use configuration files and build base images

Jenkinsfiles/Linux-SGX-18.04, Pal/src/host/Linux-SGX/sgx_framework.c
SGX driver v39 removes `count` field and returns "number of bytes added" as return value of the SGX_IOC_ENCLAVE_ADD_PAGES ioctl. It also caps the maximum number of bytes to be added as 1MB, or 256 pages. Thus, we must loop on the ADD_PAGES ioctl until all pages are added and first check `ret > 0` and only then check `count` field (to support all versions of the SGX driver).
For additional details, see:
- https://lore.kernel.org/linux-sgx/20200908190042.24895-1-jarkko.sakkinen@linux.intel.com/#r
- https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-sgx.git/tree/arch/x86/kernel/cpu/sgx/ioctl.c?h=v39
- https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-sgx.git/tree/arch/x86/include/uapi/asm/sgx.h?h=v39
I only tested on older (v33 and v36) out-of-kernel DCAP SGX drivers. …
=> [Pal/Linux-SGX] Support in-kernel SGX driver v39

Documentation/manifest-syntax.rst, Examples/ra-tls-mbedtls/Makefile, Examples/ra-tls-secret-prov/Makefile, Jenkinsfiles/Linux-SGX, Jenkinsfiles/Linux-SGX-18.04, LibOS/shim/test/regression/Makefile, Pal/regression/Makefile, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/sgx_attest.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_platform.c, Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py, Pal/src/host/Linux-SGX/tools/README.rst
Previously, Graphene assumed that if it was built with the DCAP SGX driver or in-kernel SGX driver, then it should use DCAP/ECDSA based attestation. In fact, the SGX driver has nothing to do with the attestation scheme. This commit allows to use EPID based attestation even when Graphene is built with the DCAP SGX driver.
See #1914 for more context.
Fixes #1914.
All tests must pass (we have Attestation tests in PAL, LibOS, ra-tls-mbedtls, and ra-tls-secret-prov regressions).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1917)
=> [Pal/Linux-SGX] Allow EPID attestation even with DCAP SGX driver

LibOS/shim/include/arch/x86_64/shim_internal-arch.h, LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/sys/shim_exec.c, Pal/include/arch/x86_64/cpu.h, Pal/include/arch/x86_64/pal-arch.h, Pal/include/arch/x86_64/pal_internal-arch.h, Pal/include/lib/spinlock.h, Pal/lib/string/memcpy.c, Pal/lib/string/memset.c, Pal/regression/Memory.c, Pal/src/db_rtld.c, Pal/src/host/Linux-SGX/db_pipes.c, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_exception.c, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_thread.c, Pal/src/host/Linux-SGX/sgx_tls.h, Pal/src/host/Linux/db_exception.c, Pal/src/host/Linux/db_threading.c
Mostly adds missing "memory" clobber which caused some nasty bugs - gcc
optimized those inline asms and assumed values returned by them never
change.
Don't ask me how long it took me to debug this ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1938)
=> Miscelaneous inline asm fixes

LibOS/shim/src/shim_checkpoint.c, LibOS/shim/src/shim_init.c, Pal/include/pal/pal.h, Pal/src/host/Linux-SGX/db_process.c, Pal/src/host/Linux-SGX/db_streams.c, Pal/src/host/Linux-SGX/pal_host.h
Previously, process communication (channel between parent and newly created child) was protected via TLS only during send/receive of the checkpoint; after that the channel was downgraded from TLS to plaintext. The reason for this downgrade is historical (IPC was complicated, and we wanted to have at least some TLS at the time).
This PR fixes this issue: Graphene now always uses TLS on IPC.
For more context see https://github.com/oscarlab/graphene/issues/1235.
All tests must pass. One can manually check that messages between parent and child (including forked-execed child) are encrypted: `SGX=1 strace -ff graphene/Runtime/pal_loader ./vfork_and_exec`.
--- …
=> [Pal/Linux-SGX] Do not downgrade IPC plaintext after checkpoint

LibOS/shim/src/sys/shim_access.c, LibOS/shim/src/sys/shim_fs.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/src/sys/shim_stat.c, LibOS/shim/test/ltp/ltp.cfg
As per linux man-pages, dirfd can be ignored if an absolute path is provided when invoking *at() calls. But in graphene many of the *at() calls require a valid dirfd even when an absolute path is provided. If not, the call fails. This PR fixes the issue by ignoring dirfd if an absolute file path is provided.
Fixes #1877
no new tests are added as part of this PR. Tested using `make regression` and LTP tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1933)
=> [LibOS]: Fix *at() syscalls

LibOS/shim/include/shim_ipc.h, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/ipc/shim_ipc_ranges.c, LibOS/shim/src/shim_checkpoint.c
Previously, `IPC_PORT_SERVER` meant "listening port", and the actual communication ports had several types. Only two of these types were used for differentiation during IPC broadcast (direct-child and direct-parent types). All other types denoted who is the remote party this port connects to, but this info is superfluous. So this commit replaces all these types with a generic `IPC_PORT_CONNECTION`, and renames `IPC_PORT_SERVER` to a more familiar `IPC_PORT_LISTENING`.
Cosmetic change, all tests must pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1942)
=> [LibOS] Remove unused IPC port types

LibOS/shim/src/fs/proc/info.c, LibOS/shim/src/sys/shim_sched.c, Pal/include/arch/x86_64/pal-arch.h, Pal/regression/Bootstrap.c, Pal/src/host/Linux-SGX/db_main-x86_64.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/pal_security.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux/db_main-x86_64.c, Pal/src/host/Linux/db_main.c, Pal/src/host/Linux/pal_linux.h
Applications tend to use `/proc/cpuinfo` to get the `cpu cores` and `physical id` for computing the number of physical cores in a
socket. Currently `cpu cores` field is incorrectly implemented as it is set to the number of logical processors online and `physical id` isn't implemented. This patch addresses both of these issues.
For example, openVINO these fields in the following way to decide how many threads it should use for its inference engine.
https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/inference_engine/os/lin/lin_system_conf.cpp#L24
We have `proc_common.c` regression test which already covers `/proc/cpuinfo`.
--- …
=> [Pal/LibOS] Add `physical id` and fix `cpu cores` in `/proc/cpuinfo`

Pal/regression/test_pal.py
This test started to work correctly some time ago, probably after we began to fix the loader (most likely after #1915).
FYI: I removed matching of the stderr, because on Linux PAL we have a totally different message logged and it's hard to match both.
Fixes #860.
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1946)
=> [Pal] regression: reenable test_140_missing_executable_and_manifest

Documentation/devel/new-syscall.rst, LibOS/shim/include/shim_table.h, LibOS/shim/include/shim_types.h, LibOS/shim/src/shim_syscalls.c, LibOS/shim/src/sys/shim_sched.c, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/manifest.template, LibOS/shim/test/regression/pthread_set_get_affinity.c, LibOS/shim/test/regression/sched.c, LibOS/shim/test/regression/sched_set_get_affinity.c, LibOS/shim/test/regression/test_libos.py, Pal/include/arch/x86_64/Linux/sysdep-arch.h, Pal/include/lib/api.h, Pal/include/pal/pal.h, Pal/src/db_threading.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux-SGX/db_threading.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_thread.c, Pal/src/host/Linux/db_threading.c, Pal/src/host/Skeleton/db_threading.c, Pal/src/pal-symbols, Pal/src/pal_internal.h
[LibOS,PAL] Add sched_setaffinity/sched_getaffinity syscall support
This patch addresses 2 things,
1. Adds syscall support for setting/getting CPU affinity of thread
for graphene and graphene+SGX.
2. Fixes CPUID leaf B implementation to retrieve correct CPU topology
for graphene+SGX support.
Co-authored-by: Gary gordon.king@intel.com
Fixes #788
Fixes #1563
Closes #1580 
Please use the following newly added regression tests to validate the PR.
1. LibOS/shim/test/regression/sched_set_get_cpuaffinity.c
2. LibOS/shim/test/regression/pthread_set_get_affinity.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1866)
=> [LibOS,PAL] Add sched_setaffinity/sched_getaffinity syscall support

LibOS/shim/test/regression/pthread_set_get_affinity.c
Remove unnecessary asm from test case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1955)
=> LibOS: Remove unnecessary asm from test case

Pal/lib/Makefile
'make -jN' is not respected otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1964)
=> [Pal/lib] Use the right make invocation for mbedtls

LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/test/regression/debug.gdb, LibOS/shim/test/regression/test_libos.py, Pal/src/db_main.c, Pal/src/host/Linux-SGX/db_devices.c, Pal/src/host/Linux-SGX/db_streams.c, Pal/src/host/Linux-SGX/pal_host.h, Pal/src/host/Linux/db_devices.c, Pal/src/host/Linux/db_streams.c, Pal/src/host/Linux/pal_host.h, Pal/src/host/Skeleton/db_devices.c, Pal/src/host/Skeleton/pal_host.h
This PR refactors the source code of `pal_type_device` PAL handle (currently used only for `/dev/tty` STDIN/STDOUT streams). As a side effect, it also slightly refactors the corresponding code in LibOS.
All tests must pass. Only refactoring, no change in logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1951)
=> [Pal/{Linux,Linux-SGX}] Refactor "device" PAL handles

Documentation/manifest-syntax.rst, LibOS/shim/src/fs/shim_fs.c
Sometimes users may try to add `/dev` or root (`/`) mounts to the manifest file, but these paths are already automatically mounted by Graphene on startup. Previously, Graphene failed on assert in such cases, now it prints a meaningful error message.
Didn't want to introduce a negative test case for this. But try manually by simply adding these lines to `LibOS/shim/test/regression/manifest.template`:
```
fs.mount.dev.type = chroot
fs.mount.dev.path = /dev
fs.mount.dev.uri = file:/dev
```
Without this PR, Graphene mysteriously fails on assert (rebuild and run any LibOS test). With this PR, Graphene says something reasonable:
```
[P15650:T1:spinlock] Mount /dev already exists, verify that there are no duplicate mounts in manifest
[P15650:T1:spinlock] (note that /proc and /dev are …
```
=> [LibOS] Gracefully exit with message on duplicate mounts in manifest

LibOS/shim/include/shim_signal.h, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/sys/shim_sigaction.c
Always clear SIGSTOP and SIGKILL from signals mask.
Restore the signal action to the default when `SA_RESETHAND` is set only if a signal handler is called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1966)
=> [LibOS] Miscellaneous sigaction fixes

LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/bookkeep/shim_vma.c, LibOS/shim/src/fs/dev/null.c, LibOS/shim/src/fs/dev/random.c, LibOS/shim/src/fs/dev/zero.c, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/shim_debug.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_sigaction.c
Get rid of a few memcpy's to preserve the type checking when copying
structures around.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1962)
=> [LibOS] Preserve type checking when copying equivalent structures

.ci/lib/stage-test-all-nosgx.jenkinsfile, .ci/lib/stage-test-simple-sgx.jenkinsfile, LibOS/shim/test/regression/.gitignore
Removed by mistake in abe3d77552cd8b0579d4687cd93c860188d4d2f1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1971)
=> [CI] Add back gitignore-test to all configurations

Documentation/manifest-syntax.rst, Documentation/pal/host-abi.rst, LibOS/shim/include/shim_internal.h, LibOS/shim/include/shim_thread.h, LibOS/shim/include/shim_utils.h, LibOS/shim/src/shim_init.c, LibOS/shim/src/shim_parser.c, LibOS/shim/src/sys/shim_exit.c, LibOS/shim/src/utils/printf.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/debug_log_file.manifest.template, LibOS/shim/test/regression/debug_log_inline.manifest.template, LibOS/shim/test/regression/test_libos.py, Pal/include/pal/pal.h, Pal/regression/Bootstrap.c, Pal/regression/test_pal.py, Pal/src/db_main.c, Pal/src/db_streams.c, Pal/src/host/Linux-SGX/db_streams.c, Pal/src/host/Linux/db_streams.c, Pal/src/host/Skeleton/db_streams.c, Pal/src/pal-symbols, Pal/src/pal_internal.h
See https://github.com/oscarlab/graphene/issues/1947.
This makes `loader.debug_type = "file"` usable again by introducing a new `DkDebugLog` call.
Run a program with:
```toml
loader.debug_type = "file"
loader.debug_file = "graphene.log"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1965)
=> [Pal,LibOS] Fix loader.debug_type = file

LibOS/shim/src/sys/shim_poll.c
During poll/select emulation, Graphene incremented refcount of polled handles, but forgot to decrement it in case poll timed out or failed.
In a particular long-running application, this led to an FD leak of pipes (the pipe FD is actually closed on the host only after `handle.refcount == 0`). This led to Linux failing to allocate new FDs at some point (`-EMFILE` on `pipe2()`).
Fixes #1960.
No new test, since this is an FD leak that happens only in long-running apps and only in rare cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1980)
=> Fix ref counting bug in shim_do_poll()

LibOS/shim/test/regression/exit_group.c, LibOS/shim/test/regression/exit_group.manifest.template, LibOS/shim/test/regression/test_libos.py
~This fixes #1937, but more importantly, makes sure that any thread calling `exit()` will cause the correct exit code to be reported.~
The issue has been fixed by threads rework in #1949, this adds a test for `exit()` from a thread.
The `exit_group` test is a test for this scenario:
```sh
cd LibOS/shim/test/regression
make exit_group exit_group.manifest
../../../../Scripts/run-pytest -k test_401_exit_group -v
./exit_group 3 100; echo $?
./pal_loader exit_group 3 100; echo $?
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1943)
=> Fix exit_group test

Pal/src/host/Linux-SGX/db_process.c
OCALLs in Linux-SGX PAL return UNIX error codes on failure. These error codes must be converted to PAL error codes.
This conversion was done almost everywhere in Linux-SGX PAL, except `ocall_create_process()`. I fixed this in this PR. From my manual audit, this seems to be the only instance of non-conversion.
Fixes #1977.
All tests must pass. One can manually fail the creation of a child process and notice the incorrect error code returned to the application (for me it was `-99 == EADDRNOTAVAIL`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1985)
=> [Pal/Linux-SGX] Convert UNIX error code to PAL on ocall_create_process() fail

LibOS/shim/include/shim_table.h, LibOS/shim/src/shim_syscalls.c, LibOS/shim/src/sys/shim_ioctl.c
This PR refactors the `ioctl()` emulation. Basically, removes a lot of dummy code.
No change in logic, all tests must pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1990)
=> [LibOS] Refactor and simplify ioctl() emulation

LibOS/shim/src/bookkeep/shim_process.c, LibOS/shim/src/ipc/shim_ipc_ranges.c, LibOS/shim/src/sys/shim_clone.c
This PR has one caveat: it makes pids reusable i.e. they might not be
growing (Graphene might reuse old, freed pids).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1999)
=> [LibOS] Fix `shim_ipc_info` leak

LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/device.c, LibOS/shim/test/regression/manifest.template, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/db_devices.c, Pal/src/host/Linux-SGX/pal_host.h, Pal/src/host/Linux/db_devices.c, Pal/src/host/Linux/pal_host.h
Previously, Graphene supported only `/dev/tty` (stdin/stdout terminal) device. This PR introduces support for other, arbitrary host devices. The devices must be explicitly allowed in the manifest via a mount point like this:
```
fs.mount.devkmsg.type = chroot
fs.mount.devkmsg.path = /dev/kmsg
fs.mount.devkmsg.uri  = dev:/dev/kmsg
```
Currently only `open/read/write/close/fstat` are supported. Support for IOCTLs and mmaps will be introduced in future PRs.
~~Needs to be rebased on top of #1951.~~
A simple test that opens `/dev/kmsg` and reads from it is added to LibOS regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1959)
=> [Pal/{Linux,Linux-SGX}] Allow communication with host devices

LibOS/shim/include/shim_fs.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/sys/shim_access.c, LibOS/shim/src/sys/shim_fs.c
Previously Graphene never deleted dentries. This PR adds possible dentry
deletion on `unlink` and handle close. It also fixes some dentry
reference counting bugs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2006)
=> [LibOS] Add opportunistic dentry removal and fix some refcount issues

LibOS/shim/include/shim_handle.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/sys/shim_open.c
Functions `flush_handle()` and `flush_handle_map()` are not used. The function `flush_handle()` was used in the `truncate()` syscall emulation for no good reason.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2005)
=> [LibOS] Remove unused flush_handle() and flush_handle_map()

Pal/src/host/Linux-SGX/signer/pal-sgx-get-token, Pal/src/host/Linux-SGX/signer/pal-sgx-sign
Unfortunately this warning was triggered too often (including when building tests) and it's not terribly important, so let's just drop it.
Build regression tests and look at the cleaner logs :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2011)
=> [Pal/Linux-SGX] Remove too noisy deprecation warning from signing tools

Pal/src/host/Linux-SGX/sgx_main.c
Previously, Linux-SGX PAL's untrusted loader removed "LD_PRELOAD=..." string from environment variables via `memmove(environ)` (writing the rest of envvars over "LD_PRELOAD=..."). However, the corresponding `environ` pointers were never updated, so all pointers after "LD_PRELOAD" envvar pointed to wrong addresses. This memmove trick is actually not needed because `gdb_integration/graphene_sgx.gdb` script already resets LD_PRELOAD variable, so we simply remove it.
This bug is only visible during GDB debugging. The bug manifested in one of the more complex workloads, and prevented me from debugging normally (the child process exited with error message). I manually looked at `env` in the parent process and then child and found out that `env` in the child got corrupted. After I removed the …
=> [Pal/Linux-SGX] Remove memmove() of environ on LD_PRELOAD

Documentation/pal/porting.rst, Pal/include/pal/pal.h, Pal/include/pal/pal_error.h, Pal/regression/Bootstrap.c, Pal/regression/normalize_path.c, Pal/src/db_main.c, Pal/src/db_rtld.c, Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/enclave_pf.c, Pal/src/host/Linux/db_main.c, Pal/src/host/Skeleton/db_main.c, Pal/src/pal_error.c, Pal/src/pal_internal.h
Two small things I noticed when implementing the next iteration of loader rework, which can be merged separately:
* Removal of unused and not implemented `DkGetHostId()`
* Fixing error explanation printing in `print_error()` and `pal_strerror()` callsites (see commit message for more details).
Trigger an error in PAL and enjoy an explanation instead of "Unknown error" message :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2018)
=> Misc PAL fixes (removing unused code + fixing error explanation printing)

README.rst
Seems that GitHub reST parser is somehow limited and as a result, #2008 broke its rendering in one place (the emitted text was literally ":program:\`pal_loader\`").
Check rich diff on GitHub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2012)
=> [Docs] Fix reST in README.rst to work with GitHub

Documentation/pal/host-abi.rst, LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, LibOS/shim/src/shim_syscalls.c, Pal/include/pal/pal.h, Pal/regression/Segment.c, Pal/regression/Symbols.c, Pal/regression/Thread.c, Pal/regression/test_pal.py, Pal/src/db_misc.c, Pal/src/host/Linux-SGX/db_main-x86_64.c, Pal/src/host/Linux/db_main-x86_64.c, Pal/src/host/Skeleton/db_misc.c, Pal/src/pal-symbols, Pal/src/pal_internal.h
On x64 DkSegmentRegister had weird semantics which also disabled some
usages like `0` as fsbase. This is now fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2032)
=> [Pal] Fix semantics of DkSegmentRegister

LibOS/shim/src/bookkeep/shim_signal.c
This message appeared even if there were no pending signals, and its "(2)" part was confusing (it showed incremented-preempt-level and not the more intuitive pending-signal number).
Check e.g. Nginx with `loader.debug_type = "inline"`. Without this PR, it shows a lot of bogus `signal delayed (2)` messages upon Ctrl-C.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2029)
=> [LibOS] Remove bogus "signal delayed (2)" message

Documentation/devel/performance.rst, Documentation/manifest-syntax.rst, LibOS/shim/src/Makefile, Pal/include/pal/pal_debug.h, Pal/src/host/Linux-SGX/Makefile, Pal/src/host/Linux-SGX/Makefile.am, Pal/src/host/Linux-SGX/db_rtld.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_entry.S, Pal/src/host/Linux-SGX/sgx_graphene.c, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_perf_data.c, Pal/src/host/Linux-SGX/sgx_profile.c, Pal/src/host/Linux-SGX/sgx_thread.c, Pal/src/host/Linux-SGX/sgx_tls.h, Pal/src/host/Linux/Makefile.am, Pal/src/host/Skeleton/Makefile.am
New version of https://github.com/oscarlab/graphene/pull/2001 (closes #2001).
Includes `eh_frame_hdr` fix (#2026, can be merged faster) (closes #2026).
This generates a file with samples readable by `perf`. After recording, you can view a report with `perf record`. The samples can include stack: a snapshot of up to 8192 bytes is recorded, and `perf record` will try to walk it based on DWARF info.
Basically, this replaces the kernel part of `perf` for SGX.
- **Hand-rolled statistics/report** (as in #2001): I got stuck trying to add stack traces. You can follow frame pointers (`RBP`) quite easily, but that works more or less only in Graphene code, as even glibc is compiled without frame pointers nowadays.
- **Parsing the stack ourselves**: I tried to use `libunwind` (not very flexible) and …
=> SGX profiling based on perf

LibOS/shim/include/shim_tcb.h, LibOS/shim/src/generated-offsets.c, LibOS/shim/src/shim_context-x86_64.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/syscallas-x86_64.S
Previously, Graphene saved and restored only the GP registers of the CPU context on entering and leaving syscall emulation in `syscalldb()`. In reality, the CPU context must also contain FP control word (fpcw) and the SSE/AVX/... control word (mxcsr). This commit preserves these control words across app-to-Graphene context switches.
During syscall emulation, Graphene may clobber the FP/SSE/AVX/... state (except the control words). We rely on the fact that apps do *not* assume that this state is preserved across syscalls (except the control words). Thus, it is enough to save/restore only the control words on each syscall. This commit also removes previous hack of performing expensive xsave/xrstor instructions on `clone()`.
Note the performance regression: we add 4 instructions on each …
=> [LibOS] Save/restore FP/SSE/AVX/... control words on syscalls

.ci/lib/stage-build-sgx.jenkinsfile, .ci/run-pylint, .gitmodules, Documentation/building.rst, Documentation/cloud-deployment.rst, Documentation/quickstart.rst, LICENSE.addendum.txt, Pal/Makefile, Pal/src/host/Linux-SGX/.gitignore, Pal/src/host/Linux-SGX/Makefile, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux-SGX/generated-offsets.c, Pal/src/host/Linux-SGX/gsgx.h, Pal/src/host/Linux-SGX/gsgx.h.in, Pal/src/host/Linux-SGX/link-intel-driver.py, Pal/src/host/Linux-SGX/sgx_framework.c, Pal/src/host/Linux-SGX/sgx_in_kernel.h, Tools/gsc/images/graphene_aks.latest.dockerfile, Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template
- `link-intel-driver.py` is imported from oscarlab/graphene-sgx-driver and the submodule is removed.
- Interactive `input()` is removed, because it is unwieldy in build system.
- There are some changes in includes and include dirs, to include only the new file.
Jenkins, as usual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1997)
=> [Pal/Linux-SGX] Get rid of sgx driver submodule

Documentation/manifest-syntax.rst, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/pal_linux_defs.h, Pal/src/host/Linux-SGX/pal_security.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux/db_main.c, Pal/src/pal_internal.h
Adds enclave loading time if `sgx.enable_stats = 1`. This PR also removes the macro PRINT_ENCLAVE_STAT (now user must use `sgx.enable_stats = 1`) and moves all logic to untrusted PAL.
Fixes #2034.
All tests must pass. We have PAL regression test `Thread2` is enabled stats, run it manually to see the statistics. Something like this:
```
~/graphene/Pal/regression$ SGX=1 ~/graphene/Runtime/pal_loader ./Thread2
Manifest file: ./Thread2.manifest.sgx
...
enclave initializing:
enclave id:   0x000000000ffff000
mr_enclave:   a635aa1e681bf5910716a1f01b1231a6ff9955ea6628dd304dc622667be8a1c9
----- SGX enclave loading time =     991851 microseconds -----
...
```
--- …
=> [Pal/Linux-SGX] Add enclave loading time if sgx.enable_stats = 1

LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, LibOS/shim/include/shim_tcb.h, LibOS/shim/src/generated-offsets.c, LibOS/shim/src/shim_context-x86_64.c, LibOS/shim/src/sys/shim_clone.c
Move the x86-specific registers fpcw and mxcsr into their
own structure.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2041)
=> LibOS: Move x86-specific context registers into own struct

LibOS/shim/src/bookkeep/shim_handle.c
`struct shim_handle_map` has a member field `map`, which is a pointer to an array of element of type `struct shim_fd_handle *` . 
The original code `handle_map->map = calloc(size, sizeof(struct shim_fd_handle));` has an type error and may malloc more memory than needed.
Fixes #2022
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2024)
=> [LibOS] Fix a type error in memory allocation for shim_handle_map

LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, LibOS/shim/include/shim_tcb.h, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/shim_async.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/shim_syscalls.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_exec.c
This PR now renames fs_base to tls_base to be more generic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2045)
=> [LibOS] Rename fs_base to tls_base to be more generic

Pal/include/arch/x86_64/Linux/ucontext.h, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/sgx_exception.c
Untrusted Linux-SGX PAL handles host-level asynchronous signals by emulating the interrupt (-EINTR) of the pending OCALL. Unfortunately, there was a type cast issue such that int32_t -EINTR (`-4`) was casted to a positive uint64_t and then OCALL consumed this positive number instead of erroring out on -EINTR. This PR adds explicit type casting to fix this bug.
After the above was fixed (in the first commit of this PR), I debugged a small data race and fixed it. It goes like this. Graphene internal logic as well as application logic relies on most OCALLs being "uninterruptible", e.g., `recv()` OCALL is assumed to be interruptible but `mmap()` OCALL is assumed to be uninterruptible. At the same time, Linux-SGX PAL always injects `-EINTR` in OCALLs when an async signal arrives from host OS, …
=> [Pal/Linux-SGX] Fix type cast issue during async signal handling and also retry OCALLs on EINTR

LibOS/shim/src/shim_context-x86_64.c, Pal/include/lib/assert.h
This helps with catching errors like `assert(x = y)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2051)
=> Remove parentheses from assert argument evaluation

Pal/src/host/Linux-SGX/db_exception.c, Pal/src/host/Linux-SGX/enclave_entry.S, Pal/src/host/Linux-SGX/generated-offsets.c
`event` was passed to `_DkHandleExternalEvent` without sanitization and later used as an array index.
Apply the following patch and run any application.
```
diff --git a/Pal/src/host/Linux-SGX/sgx_entry.S b/Pal/src/host/Linux-SGX/sgx_entry.S
index eeb15535..0588caa6 100644
--- a/Pal/src/host/Linux-SGX/sgx_entry.S
+++ b/Pal/src/host/Linux-SGX/sgx_entry.S
@@ -150,6 +150,7 @@ sgx_raise:
movq %rax, %rdi
xorq %rsi, %rsi
+       movq $0x1337, %rsi
.global sgx_entry_return
.type sgx_entry_return, @function
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2053)
=> [Pal/Linux-SGX] Add value checking of external events

Documentation/pal/host-abi.rst, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/shim_init.c, Pal/include/pal/pal.h, Pal/regression/Event.c, Pal/regression/Exception.c, Pal/regression/Exception2.c, Pal/regression/Failure.c, Pal/regression/Memory.c, Pal/regression/Symbols.c, Pal/regression/test_pal.py, Pal/src/db_exception.c, Pal/src/host/Linux-SGX/db_exception.c, Pal/src/host/Linux/db_exception.c, Pal/src/host/Skeleton/db_exception.c, Pal/src/pal-symbols, Pal/src/pal_internal.h
This function was empty and it is responsibility of the caller (Pal
level) of specific exception handling function (LibOS level) to return
from the exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2054)
=> [Pal] Remove empty DkExceptionReturn function

Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/db_rtld.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/enclave_untrusted.c, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_tls.h
This PR allows `ocall_mmap_untrusted()` to be used with a fixed address (aka `MAP_FIXED`). This can be used to allocate untrusted memory at specific untrusted addresses.
This functionality is currently not used by Linux-SGX PAL but will be required in the IOCTL emulation in future PRs. (Some devices require allocating shared untrusted memory with `MAP_FIXED`.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1991)
=> [Pal/Linux-SGX] Allow ocall_mmap_untrusted() with fixed address

LibOS/shim/src/fs/shim_fs.c
Sometimes users erroneously try to add `fs.mount.blabla.path = "."` into the manifest, which doesn't make sense. This PR prevents this and writes a meaningful error message. Fixes #2052.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2056)
=> [LibOS] Do not allow "." and ".." mount points in manifest

Pal/src/host/Linux-SGX/sgx_framework.c
Some versions of the Intel SGX driver have a 1MB (256 pages) cap enforced on `ioctl(SGX_IOC_ENCLAVE_ADD_PAGES)`. Such versions must return how many pages were actually added in `ret` or `count` fields; Graphene supports this. However, some version of the driver are buggy and do not report any error or how many pages were added, but instead silently skip all enclave pages past 1MB. This confuses Graphene (it re-tries the EADD), which leads to `-EBUSY` from the driver (it sees that Graphene wants to add already added enclave pages).
This is a bug in the driver which was introduced in some intermediate commits between v40 and v41 (and unfortunately was/is used in some systems). We simply error out with a message to update the driver when we detect this bug.
Closes #2049 . See the discussion …
=> [Pal/Linux-SGX] Print error message if buggy SGX driver is detected

LibOS/shim/src/sys/shim_socket.c
`shim_do_accept()` locks `hdl->lock` first then wait for client to connect.  accept() blocks the caller until a connection is present.
It's a deadlock When one thread call fork() while another thread blocked in socket accept().
`BEGIN_MIGRATION_DEF(fork)` also locks `hdl->lock`.
Java API ProcessBuilder.start() fork explicitly then execve, triggers the deadlock.
fixes #1842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1996)
=> [LibOS] Fix deadlock in shim_do_accept()

Pal/include/pal/pal.h, Pal/src/db_events.c, Pal/src/host/Linux-SGX/db_events.c, Pal/src/host/Linux/db_events.c, Pal/src/host/Skeleton/db_events.c, Pal/src/pal_internal.h
If futex wait returns -EINTR, but the waiting condition no longer holds,
we ignore EINTR and treat that as successful wait.
This commit also removes redundant, copy-pasted code (_DkEventWait).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2060)
=> [Pal] Handle EINTR in _DkEventWaitTimeout

LibOS/shim/src/Makefile, LibOS/shim/src/shim_init.c, Pal/include/arch/x86_64/Linux/pal_host-arch.h, Pal/include/arch/x86_64/pal-arch.h, Pal/include/host/Linux-common/linux_utils.h, Pal/lib/Makefile, Pal/regression/Makefile, Pal/src/Makefile, Pal/src/host/Linux-SGX/Makefile, Pal/src/host/Linux-SGX/Makefile.am, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_threading.c, Pal/src/host/Linux-SGX/generated-offsets.c, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_tls.h, Pal/src/host/Linux-common/stack_protector.c, Pal/src/host/Linux/Makefile, Pal/src/host/Linux/Makefile.am, Pal/src/host/Linux/db_main.c, Pal/src/host/Linux/db_threading.c, Pal/src/host/Linux/pal_linux.h, python/graphenelibos/sgx_sign.py
GCC (and other compilers, e.g. Clang) provide a **stack protector** feature to detect stack corruptions. This is achieved by storing a 64-bit canary value on the stack frame on function entry and verifying this value on function exit.
Previously, Graphene disabled stack protector completely. This PR enables it in LibOS and PAL code (only if `-mstack-protector` feature is supported by compiler).
The stack protector uses a random per-thread canary stored in the TLS/TCB of each thread. Each PAL implementation must follow the rule that TLS/TCB is accessed via the GS register and that the offset of canary in TLS/TCB is 0x8. Since LibOS re-uses TLS/TCB of the PAL, there is no need for additional enabling at the LibOS layer.
Since `-mstack-protector` feature is architecture-specific, it is …
=> [LibOS,Pal] Use GCC's stack protector in LibOS and PAL functions

LibOS/shim/src/sys/shim_socket.c, LibOS/shim/src/sys/shim_wait.c, LibOS/shim/test/ltp/ltp.cfg
This commit additionally fixes bugs in shim_do_sendmmsg and
shim_do_recvmmsg - `vlen` argument is the number of items in the array,
not size (in bytes) of it, as previous code assumed.
This change is important in a follow up PR, which causes LibOS to use internally allocated stack.
Fixes #1931
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2061)
=> [LibOS] Do not call test_user_memory on LibOS allocated memory

LibOS/shim/src/shim_context-x86_64.c, Pal/include/arch/x86_64/pal-arch.h, Pal/src/host/Linux/db_main.c, Pal/src/host/Linux/db_threading.c, Pal/src/host/Linux/pal_linux.h
This PR creates an inline function for initializing the pal_linux_tcb structure and an architecture-specific inline function for setting the stack canary. For the latter it turned out to be sufficient to use PAL_TCB, rather than PAL_LINUX_TCB, to also set the stack canary on the ppc64 port [On ppc64 the stack canary must be at the 2nd last 64 bit entry in the PAL_TCB structure, so at offset -0x10].
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2065)
=> [PAL] Some cleanups around pal_linux_tcb and pal_tcb structures

LibOS/Makefile
This patch compiles glibc in x86_64 with the stack protector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2073)
=> [LibOS] Compile glibc on x86_64 with stack protector

LibOS/shim/include/shim_internal.h, LibOS/shim/include/shim_table.h, LibOS/shim/src/shim_parser.c, LibOS/shim/src/shim_syscalls.c, LibOS/shim/src/sys/shim_wrappers.c
See the commit messages.
This is split from #2071 
Run some apps with `debug = inline` in manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2077)
=> [LibOS] Remove types from syscalls debug printing

LibOS/shim/test/regression/mmap_file.c, Pal/include/arch/x86_64/cpu.h, Pal/include/arch/x86_64/pal-arch.h
This PR moves the PAGE_SIZE to cpu.h and uses it in a test case to make this test case work on other architectures as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2080)
=> [PAL, LibOS] Move PAGE_SIZE to cpu.h and use it in LibOS test case

Pal/regression/File.c
buffer[ret = 40] overflows the buffer of size 40. It's not necessary to
NULL terminate this buffer, so just remove the offending statements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2094)
=> [PAL] Fix buffer overflow in testcase (UBSAN)

Documentation/cloud-deployment.rst, Documentation/devel/debugging.rst, Documentation/devel/performance.rst, Documentation/quickstart.rst, LibOS/shim/test/native/.gitignore, LibOS/shim/test/native/Makefile, LibOS/shim/test/native/helloworld.c, LibOS/shim/test/native/system.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/helloworld.c, LibOS/shim/test/regression/test_libos.py
Applications under `native/` cannot be built after commit "Introduce one, central manifest, zero-config children and constant MRENCLAVE". Instead of fixing `native/`, this commit simply moves `helloworld` and all its mentions under `regression/`.
New test `helloworld` is added to the LibOS regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2092)
=> [Docs,LibOS] Move helloworld example from native/ to regression/

Runtime/pal_loader
Previously (i.e.: before #2050), if the user used the old way of calling `pal_loader` they just got "Reading manifest failed" and that was all. Let's try to fix this.
I thought about moving this to PAL code, but the error handling on SGX currently doesn't allow for nice output formatting, and also this is just an UX improvement for the users of `pal_loader`, so I think it's fine to "pre-check" it on this layer.
Run `pal_loader` with invalid arguments (both in SGX and non-SGX mode).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2100)
=> pal_loader: Print clearer error on invalid invocations

LibOS/shim/src/sys/shim_poll.c
We need to cast the mask used in select() to an unsigned int, otherwise UBSAN complains about it being a negative number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2097)
=> [LibOS] Cast mask to unsigned long (UBSAN)

LibOS/shim/src/shim_debug.c, Pal/gdb_integration/debug_map_gdb.py
Follow-up to #2044.
- The GDB command for removing a symbol file takes text address
(or any address inside the mapped memory area), not load offset
(which might be before the area). Because of that, removing a 
map in GDB did not actually work, and displayed a warning.
- The remove_r_debug() function in LibOS did not actually remove
the map from list in LibOS. As a result, LibOS attempted to
report the removal to PAL more than once, causing a harmless but
annoying warning message.
Compile with `DEBUG=1` and run a test case with exec, e.g. `./pal_loader exec_same 1 2 3` (in LibOS/shim/test/regression).
There should be no console warnings (on master, it says `debug_map_remove(...) failed: -22` multiple times).
When running the same example under GDB, there should also be no failure messages …
=> [Pal,LibOS] Fix GDB integration in case of removing maps

LibOS/shim/include/shim_ipc.h
The msg field of 'struct shim_ipc_msg' will for example be cast to
'struct shim_ipc_sysv_tellkey*' (in ipc_sysv_tellkey_callback()) and
needs to be properly aligned. There are also casts to other ipc
related structures that also require alignment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2103)
=> [LibOS] Align char msg[] in shim_ipc_msg to 8-bytes (UBSAN)

Pal/src/db_rtld.c, Pal/src/host/Linux-SGX/db_rtld.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_profile.c
The _DkDebugMapAdd function looked for executable program segments
and reported them using ocall_report_mmap(). Unfortunately, the
code incorrectly assumed the ELF header is located at load address
and not start of the map, which is not true for some binaries
(e.g. Ubuntu build of Python), and segfaulted on these binaries.
Because the information about the segments is only important for
SGX profiling, this change simplifies things by removing
the ocall_report_mmap() path and parsing the ELF file in the SGX
subsystem itself.
Having this code directly in `_DkDebugAddMap` was already kind of a hack. We could avoid re-parsing the ELF file by hooking all the places that do the actual mapping, but that's not a very good solution: there is PAL rtld, LibOS rtld, and also the application ld.so. We …
=> [Pal/Linux-SGX] Fix GDB integration for some binaries

Documentation/manifest-syntax.rst, LibOS/shim/test/regression/test_libos.py, Pal/regression/Symbols.c, Pal/regression/test_pal.py, Pal/src/host/Linux-SGX/db_memory.c, Pal/src/pal_internal.h
This seems to be the usual default. It's better because it allows easier separation of application output from logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2110)
=> [Pal] Log to stderr, not stdout

LibOS/shim/src/fs/dev/fs.c, LibOS/shim/src/fs/dev/null.c, LibOS/shim/src/fs/dev/random.c, LibOS/shim/src/fs/dev/zero.c, LibOS/shim/test/regression/dev.c, LibOS/shim/test/regression/test_libos.py
Some apps (e.g., Python Dill module) perform a dummy `lseek()` on these `/dev/` files.
Added more sub-tests in `dev` LibOS regression test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2122)
=> [LibOS] Add dummy lseek emulation for /dev/{zero,random,null}

Documentation/manifest-syntax.rst, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/test/regression/openmp.manifest.template
Previously, LibOS always checked whether user-supplied buffers for syscalls are invalid and generated `EFAULT` error codes if so. Since the invalid-buffer check needed to touch memory/traverse VMAs, it could affect performance of certain workloads.
This PR adds a manifest option to disable this behavior: most real-world applications never supply invalid buffers in syscalls.
The manifest for the LibOS regression test `openmp` was modified to test this option. Use GDB to make sure there are no checks in `test_user_memory()` and `test_user_string()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2121)
=> [LibOS] Add manifest option libos.check_invalid_pointers

LibOS/shim/src/bookkeep/shim_signal.c
This patch further prepares to enable UBSAN in Graphene. It disables the UBSAN sanitizer in `test_user_memory()` so that we do not trip on writing to the NULL pointer in when some of the syscalls call this function with a NULL pointer. This now allows to pass LPC tests calling the syscalls `getrandom`, `sethostname`, `setdomainname` and the ones that are calling into `chkmsg_hdr`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2123)
=> [LibOS] Disable UBSAN sanitizer in test_user_memory to not trip on NULL pointer

Scripts/Makefile.rules
The generated-offsets headers have to depend on the code that
defines the relevant data structures. Otherwise, when the data
structures change, the code will get compiled with wrong offsets
and will crash.
Edit `shim_tcb.h` in `LibOS/shim` and run `make` there. The `asm-offsets.h` file should get rebuilt and contain the right offsets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2126)
=> [Make] Use proper dependencies for generated-offsets

Documentation/building.rst, Documentation/cloud-deployment.rst, Documentation/quickstart.rst, Pal/src/host/Linux-SGX/Makefile, Pal/src/host/Linux-SGX/link-intel-driver.py
The merged PR https://github.com/oscarlab/graphene/pull/1997 changed Graphene to always require `ISGX_DRIVER_PATH=<path-to-sgx-driver-sources>` to be set, otherwise the SGX build fails.
Unfortunately, we forgot to update the Quick Start and the Building documentation of Graphene.
Also, the Makefile created an empty `gsgx.h` out of `gsgx.h.in` even if the Python script failed, which led to other parts of Graphene sources doing `#include "gsgx.h"` which didn't make sense (the file was empty), and this led to bizarre build errors that users don't understand and complain about.
This PR fixes this.
All tests must work. Following the build docs must actually work now.
--- …
=> [Docs,Pal/Linux-SGX] Improve build and documentation on ISGX_DRIVER_PATH

Documentation/sgx-intro.rst, Pal/src/host/Linux-SGX/link-intel-driver.py
1. Intel SGX driver has been upstreamed to mainline from kernel version 5.11. To sync with upstreamed SGX in-kernel driver, as SGX device in the kernel is exposed to "/dev/sgx_enclave" instead of "/dev/sgx/enclave", graphene needs to support the upstreaned in-kernel SGX device node "dev/sgx_enclave" in link_intel_driver.py
Fixes #2007
2. Also we need to update documentation on sgx_intro.html for the upstreamed in-kernel SGX driver in linux mainline, exposed as /dev/sgx_enclave. And additional steps for user if they want the compatibility with OOT SGX driver exposed as /dev/sgx/enclave
3. For OOT drivers in DCAP from version 1.10, the header file is also changed, we need to sync with it. see:
https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/155
1. the 1st time rebooting to …
=> sync with upstreamed SGX in-kernel driver from mainline 5.11

Documentation/building.rst, README.rst
Seems that no one has used this feature since its deprecation 1.5 year ago. Let's not clutter the main readme with it.
Also dropped a section from building instructions, as it was quite useless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2133)
=> [Docs] Drop "Deprecated Code" sections

LibOS/shim/include/shim_types.h, LibOS/shim/src/sys/shim_socket.c, LibOS/shim/test/regression/tcp_msg_peek.c
This PR adds dummy emulation (simply ignoring) the flag MSG_WAITALL in recv/recvmsg, etc. , similar to #1766.
with MSG_WAITALL, the call may still return less data than requested.
tcp_msg_peek LibOS regression test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2128)
=> [LibOS] Allow but ignore MSG_WAITALL flag in recv

Pal/src/host/Linux-SGX/db_main.c
On certain servers, the number of cache sets can be greater than
`1 << 16`. This patch increases the sanity check limit to `1 << 30`
to validate against such a large number of cache sets.
Please use the regression test "sysfs_common.c" to test the PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2136)
=> [Pal/Linux-SGX] Increase number of cache set sanity limit

LibOS/shim/src/sys/shim_epoll.c, LibOS/shim/src/sys/shim_poll.c
Previously `poll` and `epoll_wait` ignored all errors returned from `DkStreamsWaitEvents`, including `EINTR`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2135)
=> [LibOS] Make poll and epoll_wait pass errors from DkStreamsWaitEvents

LibOS/shim/test/regression/cpuid.c, Pal/src/host/Linux-SGX/db_misc.c
These CPUID leaves used by virtualization software (Hyper-V, KVM, etc.) and is zeroed out on bare metal. Some runtimes like JVM query these CPUID leaves to detect underlying virtualization software. This commit makes these leaves return zeroes ("no virtualization").
Some references:
1. Intel SDM
2. https://github.com/qemu/qemu/blob/master/docs/hyperv.txt
3. https://www.kernel.org/doc/html/latest/virt/kvm/cpuid.html
LibOS test `cpuid` was augmented to test this (the test is run only on SGX).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2134)
=> [Pal/Linux-SGX] Allow CPUID leaves 0x40000000 - 0x4FFFFFFF

Scripts/Makefile.rules
`Scripts/Makefile.rules` used MAKEFILE_LIST to obtain the current
makefile path, but it did so after including some other file, so it got
the included file path instead.
Fixes #2145 
I've also checked other makefiles, it was the only one with this issue.
Build Graphene-SGX and run make again after the first build succeeded. It will report some errors without this commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2148)
=> [Makefile] Use MAKEFILE_LIST before any includes

Pal/src/db_events.c, Pal/src/db_exception.c, Pal/src/db_memory.c, Pal/src/db_misc.c, Pal/src/db_mutex.c, Pal/src/db_object.c, Pal/src/db_process.c, Pal/src/db_streams.c, Pal/src/db_threading.c, Pal/src/host/Linux-SGX/db_exception.c, Pal/src/host/Linux/pal_host.h, Pal/src/pal_internal.h
These macros were empty and not used anymore. Additionally there was
a bug: `LEAVE_PAL_CALL` actually did not perform `return` and the
execution continued after it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2149)
=> [PAL] Remove empty `ENTER_PAL_CALL`/`LEAVE_PAL_CALL` macros

Documentation/manifest-syntax.rst, LibOS/shim/test/regression/openmp.manifest.template, Pal/src/host/Linux-SGX/db_main.c
A small performance trade-off option, allowing to "warm up" the heap during initialization.
I considered 3 different ideas for the implementation:
1. Access all the pages at enclave start.
2. Zero out and measure the whole heap.
3. Somehow pre-fault the pages from the outside of the enclave, but without measuring them.
Options 1. is pricey, because it generates a lot of enclave transitions, which are expensive. 2. doesn't have this problem, but requires hashing all the zeros. 3. should be optimal (it didn't even require zeroing out the memory), but I haven't found a way to implement it without modifying the SGX driver.
I tested 1. and 2. and got the following results: (`time ./pal_loader SGX ./pytorch ./pytorchexample.py`, `sgx.enclave_size = "4G"`, 256 threads)
| Config              | …
=> [Pal/Linux-SGX] Add sgx.preheat_enclave manifest option

LibOS/shim/src/fs/sys/cpu_info.c, LibOS/shim/src/fs/sys/fs.c, LibOS/shim/src/fs/sys/node_info.c, LibOS/shim/test/regression/sysfs_common.c
The current implementation of /sys fs will fail for paths such as
`/sys/devices/system/[cpu|node]/online` which doesn't have a
numeric value. This patch fixes this issue. This patch also adds
2 additional test cases as part of the /sys fs regression test.
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
Please run sysfs_common.c as part of LibOS regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2153)
=> [LibOS] Fix `/sys/devices/system/[cpu|node]/` path resolution

Tools/gsc/finalize_manifest.py, Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, Tools/gsc/templates/apploader.template, Tools/gsc/templates/entrypoint.manifest.template
Previously, some GSC templates and scripts that execute inside Docker containers contained relative file paths. This led to failures if a base Docker image contained WORKDIR different from root (`/`), since all GSC scripts put Graphene-related files under root dir.
GSC tests and tutorials (e.g. https://graphene.readthedocs.io/en/latest/manpages/gsc.html#example) must work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2151)
=> [GSC] Always use absolute paths inside the Docker container

Examples/blender/Makefile, Examples/gcc/Makefile, Examples/pytorch/Makefile, Examples/redis/Makefile, Examples/redis/redis-server.manifest.template
I hate Make. We should really get rid of it finally...
It turns out that Make in versions that doesn't support the `&:` operator ("Rules with Grouped Targets") silently ignores it and calls the recipe for each target separately, without even a warning. When using parallel builds (`-j`) the result is a race, because a few command invocations write to the same set of target files at the same time.
Additionally, I ported the Redis example to Ubuntu 20.04 to test the fix.
CI + build the examples manually with `-j8` and check the build log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2163)
=> Fix race condition in example's Makefiles

Pal/src/Makefile, Pal/src/host/Linux/db_exception.c, Pal/src/host/Linux/db_rtld.c, Pal/src/host/Linux/pal_linux.h
When an async exception triggers, LibOS needs to know whether it
happened while inside PAL code. Since Linux-PAL sometimes call VDSO
functions, they need to be accounted for as well.
Closes #2155.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2156)
=> [Pal/Linux] Change `ADDR_IN_PAL` to `ADDR_IN_PAL_OR_VDSO`

Pal/include/pal/pal.h, Pal/regression/Symbols.c, Pal/regression/test_pal.py, Pal/src/db_misc.c, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux/db_misc.c, Pal/src/host/Skeleton/db_misc.c, Pal/src/pal-symbols, Pal/src/pal_internal.h
It was empty and there seems to be no reason to keep it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2171)
=> [PAL] Remove unused and empty `DkInstructionCacheFlush`

Pal/src/host/Linux-SGX/enclave_entry.S
A previous change in LibOS started storing fake syscall return address in R14. This broke stack unwinding when the stack contained both LibOS syscall and SGX OCALL, because we had no CFI directives for recovering register values except for RBP, RSP and RIP, and the value of R14 was lost.
This change adds proper CFI to enclave exit code, by making sure callee-saved registers can be recovered.
Fixes #2160.
This fixes the debug regression test under SGX (we didn't notice it break because the configuration is not on Jenkins yet). 
You can run it using `SGX=1 .../graphene/Scripts/run-pytest -k TC_50_GDB` in `LibOS/shim/test/regression`. Make sure to compile with `DEBUG=1`.
--- …
=> [Pal/Linux-SGX] Fix stack unwinding on enclave exit

LibOS/shim/src/elf/shim_rtld.c
Signed-off-by: Stefan Berger <stefanb@us.ibm.com>
Replace EM_X86_64 with SHIM_ELF_HOST_MACHINE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2170)
=> [LibOS] Replace EM_X86_64 with SHIM_ELF_HOST_MACHINE

Documentation/devel/performance.rst, Documentation/manifest-syntax.rst, Pal/src/host/Linux-SGX/Makefile, Pal/src/host/Linux-SGX/enclave_entry.S, Pal/src/host/Linux-SGX/sgx_entry.S, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_profile.c, Pal/src/host/Linux-SGX/sgx_profile_glibc.c
Based on #2168, I'll rebase once that is merged.
@dimakuv You might be interested in this :)
This change extends the SGX profiler to handle OCALLs, not only asynchronous enclave exit. Depending on settings, we either record enclave state during OCALL, or the outer OCALL handler being executed.
Example output (mode = "ocall_outer"):
```
#
28.91%  pal-sgx  pal-sgx        [.] sgx_ocall_open
27.61%  pal-sgx  pal-sgx        [.] sgx_ocall_close
22.41%  pal-sgx  pal-sgx        [.] sgx_ocall_fstat
17.03%  pal-sgx  pal-sgx        [.] sgx_ocall_getdents
1.13%  pal-sgx  pal-sgx        [.] sgx_ocall_mmap_untrusted
0.90%  pal-sgx  pal-sgx        [.] sgx_ocall_cpuid
0.70%  pal-sgx  pal-sgx        [.] sgx_ocall_munmap_untrusted
0.53%  pal-sgx  pal-sgx        [.] sgx_ocall_write
0.25%  pal-sgx  pal-sgx …
```
=> [Pal/Linux-SGX] Add OCALL profiling modes

Tools/gsc/config.yaml.template, Tools/gsc/finalize_manifest.py, Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, Tools/gsc/test/Makefile
Previously, GSC required to use an out-of-tree SGX driver (either the legacy one or the DCAP one) but could not support the in-kernel SGX driver (merged into Linux 5.11). This PR allows to specify the in-kernel SGX driver in the configuration file `config.yaml` for GSC.
This PR also fixes a couple tiny bugs in the testing Makefile.
GSC in Jenkins must succeed. Manual testing on Linux 5.11 with the in-kernel SGX driver is in progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2165)
=> [GSC] Allow in-kernel Intel SGX driver; improve GSC testing

Examples/nodejs-express-server/nodejs.manifest.template, Examples/nodejs/nodejs.manifest.template
Node.js examples were broken after the recent commits. Looks like no-one tested Node.js in Graphene for the last 2-3 months. Now they are fixed (to at least run on Ubuntu 18.04 with Node.js version v13.14.0.).
Manually test Node.js.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2166)
=> [Examples] Fix up Node.js examples

Examples/apache/Makefile, Examples/apache/apache_makefile.patch, Examples/blender/Makefile, Examples/gcc/Makefile, Examples/pytorch/Makefile, Examples/redis/Makefile
Seems our Apache builds fail from time to time (see e.g. https://leeroy.cs.unc.edu/job/graphene/5981/console):
```
perl -0777 -p -i -e 's,\n(void|int) ap_expr_yy[gs]et_column[^\n]+\)\n.*?\n\},,gs' \
/home/jenkins/workspace/graphene/Examples/apache/httpd-2.4.41/server/util_expr_scan.c
/usr/share/apr-1.0/build/libtool --silent --mode=link x86_64-linux-gnu-gcc  -pthread         -o gen_test_char  gen_test_char.lo 
gawk -f /home/jenkins/workspace/graphene/Examples/apache/httpd-2.4.41/build/make_exports.awk `cat export_files` > exports.c
/home/jenkins/workspace/graphene/Examples/apache/httpd-2.4.41/server/util_expr_scan.c: In function 'ap_expr_yylex':
/home/jenkins/workspace/graphene/Examples/apache/httpd-2.4.41/server/util_expr_scan.c:1617:6: error: unterminated comment
/* Note: because we've …
```
=> [Examples] Update Apache to 2.4.46

Pal/include/lib/api.h, Pal/include/lib/spinlock.h, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_mutex.c, Pal/src/host/Linux-SGX/enclave_ocalls.c, Pal/src/host/Linux/pal_host.h
As it turns out, our READ_ONCE macro isn't strong enough to convince GCC to always emit a read.
The interesting part is that we [ported that macro from Linux v5.6](https://elixir.bootlin.com/linux/v5.6/source/include/linux/compiler.h#L182), where it seems to work correctly only for sizes 1, 2, 4 and 8 (these special cases were if-ed out there), and not for other sizes, which it also tries to support. For a demo see https://godbolt.org/z/1Gzq9c.
This implementation in Linux was recently [refactored and simplified](https://github.com/torvalds/linux/commit/a5460b5e5fb82656807840d40d3deaecad094044), because Linux dropped support for old, buggy GCC, which required such workarounds. It seems that this particular bug was fixed during the refactoring, without even noticing that it existed.
So far …
=> [Pal] Fix {READ,WRITE}_ONCE macros

LibOS/glibc-patches/glibc-2.27.patch, LibOS/glibc-patches/glibc-2.31.patch
Glibc does not properly escape path when passing it to sed in one of the makefiles. Namely it uses @ as a separator in sed and if such character happens to be part of the path (which sometimes happens on Jenkins), the build blows with wounderful and totally uninformative errors.
This commit adds a Glibc patch to properly escaper @ in paths.
Try building Graphene with `@` in any part of the path (e.g. `/tmp/wat@2/graphene`). Without this PR the build will fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2200)
=> [LibOS] Add a patch for a glibc building bug

Pal/src/db_main.c
Previously, `g_pal_control.log_level` was not explicitly initialized, so it was set to `0` which didn't print any log messages during early init phase (before parsing the manifest `log_level` setting).
Add in your manifest something like this: `sgx.trusted_files.somefile = "some-real-file"` (note the missing `file:` prefix). Graphene-SGX will fail without any error message. With this PR, the error message will be printed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2201)
=> [Pal] Set default log level early in enclave init

LibOS/shim/include/shim_handle.h, LibOS/shim/src/sys/shim_fcntl.c, LibOS/shim/src/sys/shim_ioctl.c, LibOS/shim/src/sys/shim_pipe.c
Previously, Graphene always assumed that `ioctl(fd, FIONBIO)` sets non-blocking mode. In reality, the third argument to ioctl defines whether it marks the socket as blocking or non-blocking.
I didn't find a regression test where to add this new functionality in a reasonable way. But one can try Python with: `python3 -c "import requests; req = requests.get('http://www.example.com'); print(req)"`. It doesn't work on master but works with this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2202)
=> [LibOS] Allow ioctl(fd, FIONBIO, &off)

LibOS/shim/include/shim_ipc.h, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/ipc/shim_ipc_helper.c
There is some code in IPC that is not used anymore due to different cleanups.
Additionally `shim_ipc_info::pal_handle` seems not to be needed.
This is the first in probably many PRs cleaning up/rewriting IPC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2206)
=> [LibOS] Remove dead ipc code

Pal/src/host/Linux-SGX/db_exception.c, Pal/src/host/Linux-SGX/db_main-x86_64.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_misc.c
Some Intel CPUs return ECX == 0 on CPUID 15H (TSC and Nominal Core Crystal Clock Information Leaf). Previously, Linux-SGX PAL considered this as "no support for invariant TSC" and fell back to issuing `ocall_gettime()`, which hurts SGX performance. In reality, Linux and other software devised a workaround by querying CPUID 16H (Processor Frequency Information Leaf) and calculating the TSC frequency via Processor Base Frequency. This PR adds this logic to Graphene and thus improves SGX performance.
For more context, see:
- https://github.com/torvalds/linux/blob/v5.11/arch/x86/kernel/tsc.c#L621
- https://bugzilla.kernel.org/show_bug.cgi?id=197299
- https://edk2.groups.io/g/devel/message/45750
- https://github.com/acidanthera/bugtracker/issues/448
Performance improvement on some Intel CPUs. …
=> [Pal/Linux-SGX] Fallback to calculating TSC freq from Processor freq

LibOS/shim/test/ltp/ltp.cfg
These tests are failing pretty often in CI, let's take them out until IPC subsystem is rewritten (see #2107).
CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2215)
=> [CI] LTP: Disable flaky sendfile{05,08}{,_64} tests

Documentation/manpages/gsc.rst, Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, Tools/gsc/templates/entrypoint.manifest.template
This PR makes GDB work correctly inside the Docker container. This PR also changes the log level from "debug" to "all" because it makes more sense to show the complete Graphene trace when debugging GSC.
Manually. Try things like:
```
$ SGXDRIVER_REPO=https://github.com/intel/SGXDataCenterAttestationPrimitives.git \
SGXDRIVER_BRANCH="DCAP_1.6 && cp -r driver/linux/* ." \
INTEL_SGX_DEVICE="sgx/enclave" GSC_BUILD_FLAGS="--rm --no-cache -d -L" \
make gsc-ubuntu18.04-numpy
$ docker run --device=/dev/gsgx --device=/dev/sgx/enclave \
-v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
-it --entrypoint /bin/bash gsc-ubuntu18.04-numpy
$$$ SGX=1 GDB=1 ./pal_loader entrypoint "-c print('HELLO WORLD')"
```
--- …
=> [GSC] Improve GSC debugging experience

Pal/src/host/Linux/Makefile, Pal/src/host/Linux/db_exception-x86_64.c, Pal/src/host/Linux/db_exception.c, Pal/src/host/Linux/pal_host.h
Move x86_64-specific signal functions into arch-specific file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2212)
=> [PAL] Move x86_64-specific signal functions into arch-specific file

LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/gettimeofday.c, LibOS/shim/test/regression/test_libos.py, Pal/include/lib/seqlock.h, Pal/src/host/Linux-SGX/db_misc.c
For gettime emulation, Linux-SGX PAL uses RDTSC instruction if its execution is allowed inside the SGX enclave and if the CPU supports Invariant TSC. Previously, this code path used a global spinlock to synchronize read/write accesses to shared-time-variables (threads very frequently read these shared variables and very rarely update them).
Using a spinlock led to significant performance overhead due to contention between readers (on some systems, around 140 simultaneous reader threads). This commit introduces seqlocks to allow fast lock-free readers, and replaces spinlock with a seqlock in `_DkSystemTimeQuery()`.
New test to sanity-check `gettimeofday()` emulation on Linux-SGX was added to LibOS regression suite.
--- …
=> [Pal/{lib,Linux-SGX}] Add seqlocks and use them in SGX's _DkSystemTimeQuery()

LibOS/shim/src/sys/shim_fs.c
This patch fixes the unprotected NULL pointer access on dentry
when calling function shim_do_fchmod trying to modify the permissions
of an unnamed domain socket. The fchmod function will return EINVAL
error code according to BSD style in case of no existed dentry
associated with a domain socket FD.
Fixes #2066
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2070)
=> [LibOS] Disallow changing permissions of unnamed UNIX domain sockets

.ci/lib/stage-test-direct.jenkinsfile, .ci/lib/stage-test-sgx.jenkinsfile, .ci/ubuntu16.04.dockerfile, .ci/ubuntu18.04.dockerfile, Examples/curl/Makefile, Examples/nodejs-express-server/Makefile, Examples/python-simple/run-tests.sh, Scripts/wait_for_server
Previously miscelaneous TCP servers testing scripts used sleep to wait for the server to actually start. This was very fragile and sometimes requires unnecessary long sleeps. Now we actively poll the TCP server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2227)
=> [Examples] Add a script to wait for a TCP server

Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template
After commit https://github.com/oscarlab/graphene/commit/d0d3533c348ec4c73b5f8d908390617749853b10, GSC stopped working. We forgot to do `apt-get install python3-pip` in one of the GSC files.
Fixes #2229 .
Unfortunately, our GSC pipeline is dead in Jenkins, so we missed this bug. I tested locally on my machine, with this fix everything works again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2230)
=> [GSC] Install python3-pip required to install toml Python package

Examples/bash/Makefile, Examples/bash/manifest.template, LibOS/shim/src/sys/shim_exec.c
This PR addresses issue #2185. The missing dentry is added to the shim_handle to make `/proc/self/exe` accessible. A test case is added for the bash.
Fixes #2185
Run the bash regression tests:
```
cd Examples/bash
make regression
```
Or run this 'manually':
```
~/graphene/Examples/bash$ ./pal_loader bash -c "readlink /proc/self/exe" 
WARNING: Using insecure argv source. Don't use this configuration in production!
/bin/readlink
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2228)
=> [LibOS] Fix readlink proc/self/exe

LibOS/shim/include/shim_thread.h, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_getuid.c
Previously supplementary group IDs were set process wide, while there should be set only per thread (i.e. two threads can have different sets of groups).
We already had a *groups regression test in LibOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2238)
=> [LibOS] Make supplementary group IDs a per thread attribute

LibOS/shim/src/sys/shim_wait.c
In `do_waitid` if the thread was woken up right after it enqueued itself on a wait queue, the return value was not set and hence used the default `0`, instead indicating an error or restarting the syscall.
Unfortunately I was not able to reproduce the issue locally (race window too tight probably).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2241)
=> [LibOS] Set return value on all paths in `do_waitid`

LibOS/shim/src/sys/shim_epoll.c, LibOS/shim/src/sys/shim_getrlimit.c, LibOS/shim/src/sys/shim_getuid.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/src/sys/shim_poll.c, LibOS/shim/src/sys/shim_sigaction.c, LibOS/shim/src/sys/shim_socket.c, LibOS/shim/src/sys/shim_stat.c, LibOS/shim/src/sys/shim_uname.c, LibOS/shim/src/sys/shim_wrappers.c, LibOS/shim/test/ltp/ltp.cfg
Previously `test_user_memory` was sometimes accompanied by NULL pointer checks. Those checks are not needed as `test_user_memory` is capable of noticing all kind of invalid pointers and NULL is sometimes a valid one (especially if paired with size equal to 0).
Fixes #2248
Unlocked 2 LTP tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2252)
=> [LibOS] Let `test_user_memory` check for NULL pointers

LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_handle.h, LibOS/shim/include/shim_table.h, LibOS/shim/include/shim_vma.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/bookkeep/shim_vma.c, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/sys/shim_mmap.c
On Linux `mmap` syscall takes the file offset as `unsigned long`, only the POSIX wrapper has it as `off_t` (which is signed).
Interesting fact: on powerpc the syscall signature has `off_t`, but then instantly recasts it into `unsigned long` (https://elixir.bootlin.com/linux/v5.11.6/source/arch/powerpc/kernel/syscalls.c#L71).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2244)
=> [LibOS] Change `mmap` signature so that the file offset is unsigned

Documentation/building.rst, Documentation/cloud-deployment.rst, Documentation/quickstart.rst
1. Change `libcurl4` to `libcurl4-openssl-dev` in the cloud deployment tutorial. Without the dev package, the headers for curl are missing, causing step 3 to fail. The quick start guide and the cloud deployment guide slightly differed at the listed requirements, so I basically just copy pasted the requirements from the quick start guide.
2. Add `python3-pip` as requirement. Ubuntu does not come preinstalled with pip, even when calling it as a python3 module specifically. This is listed in other places of the tutorial, but not at this point, so I added it to the building, quick start and cloud deployment guide too.
Reading and copy-pasting into a fresh Ubuntu installation, I guess?
--- …
=> [Docs] Fix libcurl requirement in cloud deployment tutorial & add python3-pip

Pal/src/host/Linux-SGX/db_main.c
In graphene, the current assumption is that number of sockets is equal to the number of nodes which is true for most Intel platforms. But virtual environments like QEMU can have each core in separate socket/package and just have one numa node. For such cases check against number of online logical processors instead of number of numa nodes.
PS: Although checking against numa nodes against socket was the intention, current code checks against num of cache index which is incorrect.
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
The figure below shows the case under virtual environment like QEMU.
vs Baremetal Server
Please run LibOS regression tests under virtual environments like QEMU.
--- …
=> [PAL/Linux-SGX] Fix sysfs socket sanitization check

LibOS/shim/include/shim_ipc.h, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/ipc/shim_ipc_pid.c, LibOS/shim/src/ipc/shim_ipc_ranges.c, LibOS/shim/src/ipc/shim_ipc_sysv.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_exit.c, LibOS/shim/test/ltp/ltp.cfg, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/double_fork.c, LibOS/shim/test/regression/test_libos.py
Previously Graphene made IPC connections on demand and there was a hidden assumption that the main process is an IPC leader that never exits. Although there was some code to find new IPC leader in case the old one dies, it was broken and only partialy used.
This commit causes Graphene processes to connect to the IPC leader on startup and disconnect of the leader is treated as a fatal error in the child process.
Added a new LibOS regression test, which checks if we have a working IPC connection even if our parent (intermediate process) dies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2225)
=>  [LibOS] Connect to IPC leader at process startup

Tools/gsc/finalize_manifest.py, Tools/gsc/test/ubuntu18.04-python3.manifest
GSC concatenates the user-provided manifest with the auto-generated manifest. Previously, the auto-generated manifest would include even those files which were already defined in the user-provided manifest. This led to runtime errors (Graphene complains about redefined manifest entries) and didn't allow to white-list files like `/etc/resolv.conf`.
This PR instructs GSC to skip already-defined files (using a heuristic that such manifest entries start with the strings "sgx.allowed_files", "sgx.trusted_files", "sgx.protected_files").
~~Must be rebased after https://github.com/oscarlab/graphene/pull/2203 is merged. First commit of this PR is from there.~~
GSC. I added some lines to the Python3 example. You can check the final manifest manually by inspecting the resulting …
=> [GSC] Ignore allowed|trusted|protected files specified in user manifest

LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/test/fs/.gitignore, LibOS/shim/test/fs/Makefile, LibOS/shim/test/fs/README.md, LibOS/shim/test/fs/manifest.template, LibOS/shim/test/fs/multiple_writers.c, LibOS/shim/test/fs/test_fs.py, LibOS/shim/test/fs/test_pf.py
Test if concurrent writes to the same file descriptor are handled correctly (for example, if they do not overlap each other). Right now, this is the case for multiple threads, but not multiple processes, so the multi-process tests are disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2264)
=> [LibOS/shim] Add tests for multiple writers

LibOS/shim/src/fs/proc/thread.c
Signed-off-by: aneessahib <anees.a.sahib@intel.com>
Currently, lstat for proc/self/exe return DIRECTORY for file type, since graphene resolves this to the actual binary and fills up the stat accordingly. The problem with returning file type as DIRECTORY for proc/self/exe is that when certain apps (eg Dotnet) attempts to locate other binaries relative to its executable path, the path resolves to "/proc/self/<binary". 
In this fix, the type is returned as SYMLINK, and hence the path to binary that the application seeks resolves to "/<binary". Support to resolve the links (readlink) to the exact paths are already present, hence no further code is needed to support the LINK status of exe. Furthermore, the pseudo entry for the same is also defined as LINUX_DT_LNK. The fix added also applies to …
=> [LibOS] Change file type of /proc/self/exe from DIRECTORY to SYMLINK

.ci/lib/config.jenkinsfile, .ci/lib/stage-test-sgx.jenkinsfile, Pal/src/host/Linux-SGX/tools/common/attestation.c, Pal/src/host/Linux-SGX/tools/common/attestation.h
In `Examples/ra-tls-mbedtls` IAS API reports quote status, and on CI machines this was always `GROUP_OUT_OF_DATE`, because, well, BIOS and/or microcode is out of date on those. But recently we've got some new machines, one among them is surprisingly updated and for this machine another error, `CONFIGURATION_AND_SW_HARDENING_NEEDED` is returned instead, which confuses our tooling. This PR makes the attestation code to ignore also this problem.
An `ias.py` python module and `graphene-ias-query` tool, which aided debugging this problem, are included. This was necessary to write, as the existing tools in `Pal/**/Linux-SGX/tools` use IAS API v3, and I needed v4 API.
For this PR only, the problematic CI pipeline was pinned to the machine in question, which for now only serves for this PR. The …
=> [CI] Fix problems with too new BIOS+microcode

LibOS/shim/src/ipc/shim_ipc_child.c
If IPC pipe is disconnected (without proper cleanup), Graphene reported that as child dying due to a SIGKILL. Now we use SIGPWR in such scenario, to be able to distinquish this case from a genuine SIGKILL.
Hopefully, SIGPWR is not used too often.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2270)
=> [LibOS] Change reported exit reason on IPC disconnection

Tools/gsc/test/ubuntu18.04-numpy.manifest, Tools/gsc/test/ubuntu18.04-pytorch.manifest
Previously, there was no restriction on the number of threads, so both NumPy and PyTorch allocated as many threads as there are CPU cores on the platform. On many-core platforms, this led to OOM errors in these examples because enclave memory was quickly depleted (each thread in Python allocates 128MB for its "memory arena").
GSC tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2275)
=> [GSC] Restrict NumPy and PyTorch examples to use only 8 threads

Examples/apache/Makefile, Examples/blender/Makefile, Examples/lighttpd/Makefile, Examples/memcached/Makefile, Examples/nginx/Makefile
We have our own mirror for projects used in Graphene examples: https://packages.grapheneproject.io/distfiles/.
However, not all example Makefiles knew about this mirror. This PR adds this mirror to the places which didn't know.
There should be no more failed downloads in Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2280)
=> [Examples] Add https://packages.grapheneproject.io/ mirror

Pal/lib/.gitignore, Pal/lib/Makefile, Pal/lib/uthash.patch, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux-SGX/protected-files/lru_cache.c, Pal/src/pal_internal.h
This change enables me to use uthash in LibOS, without additional hack with disabling `_FORTIFY_SOURCE`.
(First discussed in #2267).
If things still compile with no warnings, we should be OK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2277)
=> Patch uthash to stop using glibc headers

.ci/gsc.jenkinsfile, Documentation/manpages/gsc.rst, Tools/gsc/gsc.py, Tools/gsc/test/Makefile
This PR adds a new command to GSC called `info-image`. `info-image` command retrieves the SGX related information from the Docker image. In particular, it prints the sig struct information for each application inside the Docker image. It also adds documentation, a new test case to GSC's test makefile, and a new test to GSC's Jenkins pipeline.
Run GSC Jenkins pipeline or create a graphenized Docker image (via `gsc build-image` and `gsc sign-image`) and afterwards run `gsc info-image <image-name>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1961)
=> [GSC] New info-image command to retrieve SGX information from graphenized Docker image

.ci/lib/stage-test.jenkinsfile, Documentation/manifest-syntax.rst, Examples/lighttpd/Makefile, Examples/lighttpd/README.md, Examples/lighttpd/lighttpd-generic.conf, Examples/lighttpd/lighttpd.manifest.template, LibOS/shim/include/shim_fs.h, LibOS/shim/src/Makefile, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/str/fs.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/test/fs/.gitignore, LibOS/shim/test/fs/Makefile, LibOS/shim/test/fs/README.md, LibOS/shim/test/fs/manifest.template, LibOS/shim/test/fs/test_tmpfs.py
When temporary files contain sensitive data, it's hard to add them to manifest as sgx.protected_files because the file name is usually contain generated random string.
In-memory tmpfs can solve this problem and avoid encryption/decryption overhead. Everything in tmpfs is temporary in the sense that no files will be created on your hard drive. All files and directories are stored in memory/EPC and will lost after Graphene exit.
- Usage:
tmpfs mount point can be assigned in manifest as
```
fs.mount.[identifier].type = "tmpfs"
fs.mount.[identifier].path = "[PATH]"
fs.mount.[identifier].uri  = "[URI]"
```
`[PATH]` is the mount point. `[URI]` is ignored no matter what string it is.
Fixes #1787.
regression test.
--- …
=> [LibOS] Add tmpfs implementation that allows program to protect intermediate file

LibOS/Makefile, LibOS/shim/include/shim_checkpoint.h, LibOS/shim/src/fs/sys/fs.c, LibOS/shim/src/shim_checkpoint.c, LibOS/shim/src/shim_parser.c, LibOS/shim/test/regression/spinlock.c, Pal/include/lib/api.h, Pal/include/lib/api_fortified.h, Pal/lib/stdlib/printfmt.c, Pal/lib/string/memcpy.c, Pal/lib/string/memset.c, Pal/regression/Hex.c, Pal/regression/Makefile, Pal/regression/Process4.c, Pal/regression/abort.c, Pal/regression/avl_tree_test.c, Pal/regression/normalize_path.c, Pal/src/host/Linux-SGX/Makefile.am, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/protected-files/lru_cache.c, Pal/src/host/Linux-SGX/protected-files/protected_files.c, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/tools/common/pf_util.c, Pal/src/host/Linux/Makefile.am, Pal/src/host/Skeleton/Makefile.am
Following the discussion #2277, I'm adding support for `_FORTIFY_SOURCE`. Apart from runtime checks, this actually added some compile-time warnings related to `snprintf` buffer size.
This is on top of #2277 and will be rebased later.
By the way, does anyone know why we also disable `_FORTIFY_SOURCE` within glibc itself?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2282)
=> Enable _FORTIFY_SOURCE

Documentation/building.rst, Documentation/devel/debugging.rst, Documentation/devel/performance.rst, Documentation/manifest-syntax.rst, Scripts/Makefile.configs
This should be useful for more reliable profiling, and is necessary for debugging _FORTIFY_SOURCE runtime failures, because they are enabled only in optimized builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2283)
=> [Make] Add DEBUGOPT=1 option for optimized debug builds

LibOS/shim/include/shim_ipc.h, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/ipc/shim_ipc_ranges.c, LibOS/shim/src/shim_checkpoint.c, LibOS/shim/src/sys/shim_semget.c
The only `IPC_PORT_LISTENING` port is the handle listening for new IPC connections (it is unique to the process), rest of ipc ports are describing existing IPC connections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2281)
=> [LibOS] Remove IPC port types

LibOS/shim/test/regression/tcp_msg_peek.c, LibOS/shim/test/regression/test_libos.py, LibOS/shim/test/regression/udp.c
The `udp` LibOS test didn't have proper error checking and retrying on EINTR/EAGAIN. This led to periodic failures in Jenkins because LibOS layer doesn't yet have ERESTARTSYS handling on `recv()` family of syscalls, and sometimes Graphene sends host-level SIGCONT signals to its processes which leads to injecting an EINTR (and not restarting the syscall automatically because there is no ERESTARTSYS).
Technically there is no real issue with current-master `udp`'s recv code because there shouldn't be any EINTRs in this program (there are no signal handlers installed in the app). But Graphene's signal handling and ERESTARTSYS is not yet fully operational, thus this problem.
`udp` shouldn't fail now.
--- …
=> [LibOS] Refactor `udp` LibOS regression test

LibOS/shim/src/fs/sys/fs.c, LibOS/shim/test/regression/sysfs_common.c
This is a split-off from the UBSAN PR.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2294)
=> [LibOS] Fix alignment issued in sysfs implementation and test

LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/test_libos.py
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2295)
=> LibOS: Compile and run bootstrap_cpp only on x86_64

Documentation/building.rst, Documentation/cloud-deployment.rst, Documentation/quickstart.rst
It was missing `libunwind` installation requirement and some steps in SGX quickstart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2299)
=> [Docs] Update documentation

LibOS/shim/test/ltp/ltp.cfg
With multiple features and bug-fixes that have been pushed to Graphene, multiple of the LTP tests have been passing with Graphene non-SGX. This PR is enabling such tests and removing the skip label from ltp.cfg.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2301)
=> [LTP] Enable LTP tests that PASS but marked as skipped in ltp.cfg

LibOS/shim/include/shim_handle.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/dev/attestation.c, LibOS/shim/src/fs/dev/fs.c, LibOS/shim/src/fs/dev/null.c, LibOS/shim/src/fs/dev/random.c, LibOS/shim/src/fs/dev/zero.c, LibOS/shim/src/fs/pipe/fs.c, LibOS/shim/src/fs/proc/fs.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/socket/fs.c, LibOS/shim/src/fs/str/fs.c, LibOS/shim/src/fs/sys/fs.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/sys/shim_epoll.c, LibOS/shim/src/sys/shim_msgget.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/src/sys/shim_semget.c, LibOS/shim/src/sys/shim_socket.c
It looks like there was an assumption that `shim_handle.info` is controlled by `shim_handle.type`, and at some point it broke down because of `TYPE_DIR`. See also #810 (which adds a workaround by extracting `info.dir` outside of union) and #836 (which proposes to clean up that workaround).
This change restores that assumption and ensures it's explicit in the code. Now directories have `is_dir == true`, and are `TYPE_FILE` (in case of chroot), `TYPE_STR` (in case of tmpfs) or `TYPE_PSEUDO` (in case of pseudo FSes).
As a next step, I would like to rename `TYPE_FILE` to `TYPE_CHROOT` and `shim_file_handle` to `shim_chroot_handle` - these are specific to the "chroot" (host) filesystem, and it's not obvious because of the generic name, which causes some incorrect usages.
---
This change …
=> Clean up shim_handle types

LibOS/Makefile
This utility has a bug of linking against the host's libraries, which may mismatch from the internal Graphene Glibc version and lead to Glibc build errors. Also, this utility is useless for Graphene.
Some details:
- http://www.linuxfromscratch.org/lfs/view/6.2/chapter05/glibc.html
- https://elixir.bootlin.com/glibc/glibc-2.33.9000/source/NEWS
- https://elixir.bootlin.com/glibc/glibc-2.27/source/malloc/memusagestat.c (proof that our oldest support Glibc version also has this utility and configuration flag)
This led to build errors in #2306, see it for details.
Fixes #2306 .
Glibc build must succeed. You can check the `LibOS/build.log` that there is no `memusagestat` program being built now.
--- …
=> [LibOS] Do not build memusagestat Glibc utility

LibOS/shim/include/shim_defs.h, LibOS/shim/include/shim_internal.h, LibOS/shim/include/shim_tcb.h, LibOS/shim/include/shim_thread.h, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/fs/pipe/fs.c, LibOS/shim/src/fs/sys/fs.c, LibOS/shim/src/ipc/shim_ipc_helper.c, LibOS/shim/src/shim_async.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/shim_object.c, LibOS/shim/src/shim_parser.c, LibOS/shim/src/shim_rtld.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/utils/log.c, Pal/include/lib/api.h, Pal/include/pal/pal_debug.h, Pal/lib/stdlib/printfmt.c, Pal/src/db_exception.c, Pal/src/host/Linux-SGX/db_streams.c, Pal/src/host/Linux-SGX/sgx_log.c, Pal/src/host/Linux/db_streams.c, Pal/src/host/Skeleton/db_streams.c, Pal/src/pal_internal.h, Pal/src/printf.c
New version of #2304. Should fix test failures like this one for `send_handle` PAL test: https://leeroy.cs.unc.edu/job/graphene-sgx-18.04/5067/
This makes sure the behaviour of logging functions is consistent, but that they still output whole lines with a single syscall whenever possible.
The syscall trace (shim_parser.c), which depended on the buffering mechanism in LibOS, is converted to use its own buffer. As a result, we no longer need to keep a per-thread log buffer, just log prefix for a given thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2309)
=> [Pal,LibOS] Make the logging system always flush data

Tools/gsc/templates/entrypoint.manifest.template
This PR fixes a stupid typo which led to issues like https://github.com/oscarlab/graphene/issues/2261.
All GSC tests must work. Programs that do `execve(<my-own-argv0>)` will work now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2317)
=> [GSC] Fix typo in manifest template `arg0_override` -> `argv0_override`

LibOS/shim/src/shim_rtld.c, LibOS/shim/src/utils/log.c, Pal/include/lib/api.h, Pal/lib/stdlib/printfmt.c, Pal/src/db_main.c, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux/db_main.c
This fixes a bunch of issues around `libos.entrypoint` handling:
- Due to our old and incorrect implementation of `snprintf`, long exec names resulted in an unterminated C-strings in some places.
- Even after fixing the above, our logging didn't handle this case nicely - `] ` suffix was missing.
- Seems that one `error: ERROR: ` survived the last logging cleanup.
- `libos.entrypoint` was silently assumed to start with `file:`. So, it if wasn't a proper URI (e.g. due to a user error) it got trimmed: e.g. `my_binary` was stripped to `nary`.
Set `libos.entrypoint` to some funny things and check whether anything still blows up :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphe …
=> `libos.entrypoint` parsing fixes

LibOS/shim/src/bookkeep/shim_vma.c, Pal/include/pal/pal.h, Pal/src/host/Linux/db_rtld.c
When starting the Linux PAL, the Linux host kernel sets up the vDSO region at a random address (the application can read this address via the aux vector AT_SYSINFO_EHDR and parse this ELF for its own needs). The Linux PAL correctly parsed the vDSO ELF and memorized its memory region but forgot to propagate this info to the LibOS VMA component.
This wasn't an issue on older Linux kernels (used in our Ubuntu 18.04 Jenkins pipelines) because those kernels always put vDSO at a high address (above the main-thread stack, such that Graphene never even tries to allocate/overwrite memory there). On the newer Linux kernels (used in our Ubuntu 20.04 Jenkins pipelines), however, vDSO is put at a truly random address (frequently below the main-thread stack). Since this info was not propagated to the …
=> [LibOS,Pal] Reflect memory region used for vDSO in LibOS's initial VMAs

.ci/lib/stage-test-direct.jenkinsfile
I've seen some pipelines getting deadlocked due to lack of timeout on LTP tests. No idea how was that possible (since there should be a per test timeout in LTP).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2330)
=> [CI] Add a timeout to running the LTP tests step

LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_types.h, LibOS/shim/include/shim_utils.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/sys/shim_access.c, LibOS/shim/src/sys/shim_fs.c, LibOS/shim/src/sys/shim_socket.c
Related to issue #2321 (dentry cleanup)
See the commit message for full list.
This takes care of some low hanging fruit in the dentry cache system - the things that, hopefully, do not cascade to a bigger change.
Next steps are going to be a bit bigger:
- Rewrite `mount_fs`. The current mount semantics are pretty weird: `DENTRY_ANCESTOR` synthetic entries, confusion between parent and child filesystem dentry, deleting old dentries under a mountpoint, mountpoints are invisible in listings (`readdir("/")` doesn't contain `"proc"` even though listing `/proc` works), etc.
- Fun fact: the regression tests contain a `dev` binary which somehow gets mounted under `/dev`, alongside (???) the dev filesystem
- Rewrite `path_lookupat` / `open_namei` functions, as outlined in #2321 (saner semantics …
=> [LibOS] Simplify low-level dentry functions

LibOS/shim/src/sys/shim_open.c
A failure inside `getdents64` (for instance in `list_directory_entry`) could return the handle locked. This was fixed in `getdents` but not in `getdents64`.
Triggered while working on #2333. These functions look pretty bad, I don't want to change them yet, but this looks like an obvious fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2334)
=> [LibOS] Fix deadlock after failed `getdents64`

Examples/ra-tls-secret-prov/Makefile, Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest
Signed-off-by: Veena Saini <veena.saini@intel.com>
This PR adds dockerifle and manifest file for ra-tls-secret-prov sample inside gsc/test folder. In addition to these two files, there is a docker-entrypoint.sh file provided in the gsc/test folder itself. Also, there is a small extra PHONY included inside /Examples/ra-tls-secret-prov/Makefile.
The objective of this PR is to provide a sample implementation of how a remote client running as part of docker container can provide it's sgx-based attestation report to a verifier/server entity.
Step 0.  make sure RA-TLS DCAP libraries are built in Graphene via:
$ cd graphene/Pal/src/host/Linux-SGX/tools/ra-tls && make dcap
Step 1. $ cd graphene
$ docker build -t my_ra-tls-secret-prov:0.1 -f …
=> [GSC] Add dockerfile and manifest file for ra-tls-secret-prov sample's gsc image

Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/pal_linux.h
Previously, Graphene generated `g_enclave_key` based on Intel SGX's `EGETKEY(SEAL_KEY)`. This key was generated insecurely (it was always the same for any enclave on the platform), and it was used to generate hashes of trusted-file chunks. This was done via 128-bit AES-CMAC. However, there is no need for a key-based hash to verify the integrity of trusted-file chunks; SHA-256 (truncated to 128 bits) is sufficient.
Therefore, this PR removes `g_enclave_key` and replaces its uses with keyless SHA-256.
Fixes #2326.
All tests must pass. One can use GDB to manually flip some bits in untrusted-memory files and see how Graphene complains.
--- …
=> [Pal/Linux-SGX] Remove `g_enclave_key` and use SHA256 for file chunk hashes

Runtime/meson.build
```
Running custom install script '/bin/sh -c ln -s libpal.so "$MESON_INSTALL_DESTDIR_PREFIX"/lib/x86_64-linux-gnu/graphene/direct/loader'
ln: failed to create symbolic link '/usr/local/lib/x86_64-linux-gnu/graphene/direct/loader': File exists
FAILED: meson-install
```
```sh
make && make SGX=1 ISGX_DRIVER_PATH=...
meson build --prefix=... -Ddirect=enabled -Dsgx=enabled
ninja -C build
ninja -C build install
ninja -C build install # second install should not fail
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2349)
=> [meson] Install symlinks with -f

LibOS/shim/include/shim_fs.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/bookkeep/shim_process.c, LibOS/shim/src/fs/proc/ipc-thread.c, LibOS/shim/src/fs/proc/thread.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/shim_rtld.c, LibOS/shim/src/sys/shim_access.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_fs.c, LibOS/shim/src/sys/shim_getcwd.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/src/sys/shim_socket.c, LibOS/shim/src/sys/shim_stat.c
This is the next step in FS rewrite, after #2324 (the first commit should disappear after merging #2324).
See also the issue for dentry cleanup (#2321).
Initially, I wanted to reverse the "follow symlinks" semantics (`LOOKUP_FOLLOW` -> `LOOKUP_NO_FOLLOW`). I decided against that after seeing Linux and BSD have a flag like that, but found that FreeBSD has a convention to *also* use `NOFOLLOW` (defined as zero) to make the code clearer.
Apart from that (and general cleanup), the most important change is `LOOKUP_CREATE` and not returning `-ENOENT` when the file can be created.
Next step: rewrite `mount_fs` and make mount semantics more sane (as mentioned in #2324).
--- …
=> [LibOS] Rewrite path lookup functions

Tools/gsc/finalize_manifest.py
Signed-off-by: Veena Saini <veena.saini@intel.com>
While running gsc images as part of Azure Kubernetes Services (AKS) Cluster (kubernetes version 1.19.9), the following errors are showing up:
Could not find size of file: file:/.dockerenv
Failed to load the checksums of trusted files: -9
OR (if previous error is resolved then the next error)
Could not find size of file: file:/.dockerinit
Failed to load the checksums of trusted files: -9
OR
Could not find size of file: file:/etc/mtab
Failed to load the checksums of trusted files: -9
.dockerenv and .dockerinit are considered to be deprecated (https://superuser.com/questions/1021834/what-are-dockerenv-and-dockerinit). 
For /etc/mtab file also, there are open issues of broken symlinks (https://github.com/kubernetes/kubernetes/issues/96961). …
=> [GSC] Exclude deprecated files from trusted files list

.ci/lib/config.jenkinsfile, .pylintrc, Scripts/get-python-platlib.py, Scripts/meson.build, meson.build, python/graphenelibos/meson.build
See docstring in the committed script.
1. Install graphene using default `--prefix` of `/usr/local` (i.e., don't specify `--prefix` at all) on different distros. `graphene-manifest` should work without munging neither `$PATH` nor `$PYTHONPATH`.
2. Install graphene using `--prefix=/usr`. Also should work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2353)
=> [meson] Detect corner case of Python's platlib path

LibOS/shim/include/shim_utils.h, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/shim_async.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_exit.c, Pal/src/host/Linux-SGX/enclave_entry.S, Pal/src/host/Linux/db_threading.c
To be consistent with recent IPC worker rename.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2318)
=> [LibOS] Rename `async helper` to `async worker`

Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/enclave_pf.c, Pal/src/host/Linux-SGX/protected-files/protected_files.c, Pal/src/host/Linux-SGX/protected-files/protected_files.h, Pal/src/host/Linux-SGX/tools/common/pf_util.c, Pal/src/host/Linux-SGX/tools/pf_crypt/pf_crypt.c
The `pf_crypt` utility now highlights that the encrypted-file path must be specified exactly in the Graphene manifest (otherwise there will be a mismatch in the metadata header of the encrypted file: the embedded relative path will not match the `sgx.protected_files` path). Also, error messages are printed now instead of raw error codes.
All tests must pass, only cosmetic changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2362)
=> [Pal/Linux-SGX] Improve info and error messages in Protected Files

Documentation/devel/coding-style.rst, LibOS/Makefile, LibOS/shim/Makefile, Makefile, Pal/Makefile, Runtime/Makefile, Scripts/Makefile, Scripts/meson-clang-format.sh, Scripts/meson.build, Tools/Makefile, meson.build
This is another thing to move from make to meson.
Follow the new new reformat procedure, according to the change in documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2373)
=> [meson] Move clang-format from make

LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_handle.h, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/dev/attestation.c, LibOS/shim/src/fs/proc/info.c, LibOS/shim/src/fs/proc/ipc-thread.c, LibOS/shim/src/fs/proc/thread.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/sys/fs.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/src/sys/shim_stat.c
This change is in preparation for bigger refactoring: simplifying directory handles, `getdents` and `getdents64`.
This commit removes the `shim_dentry.ino` field, and replaces it with a function computing the dentry hash (which is what we usually did anyway).
This is to simplify the code (the inode number was computed in several places: `readdir`, `stat`, `hstat`), and to ensure that the inode number is always available for a dentry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2374)
=> [LibOS] Remove `shim_dentry.ino`

.ci/lib/stage-test.jenkinsfile, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/test/fs/Makefile, Scripts/regression.py
Due to an unfortunate accident, the FS tests `LibOS/shim/test/fs` are silently skipped on Jenkins, and filesystem refactor (#2333) got merged with some bugs. This branch fixes these bugs and un-skips the tests.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2377)
=> Fix filesystem and unskip tests

Pal/src/host/Linux-SGX/enclave_ocalls.c
Exitless feature distinguishes between normal enclave threads and untrusted RPC threads (the latter submit syscall requests on behalf of the former). Enclave threads catch all sync and async signals from the host, including SIGILL. RPC threads block all sync and async signals other than SIGUSR2.
This PR fixes a bug that clone OCALL was considered suitable for Exitless, which meant that the new enclave thread was created on behalf of the RPC tread, and thus inherited its signal mask. Thus, the new enclave thread couldn't handle e.g. SIGILL exceptions (which can happen on legit CPUID and RDTSC instructions), and Graphene terminated the whole process.
All tests must pass. This bug was found on our Redis example with Exitless enabled.
--- …
=> [Pal/Linux-SGX] Do not use Exitless for clone OCALL

LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_handle.h, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/proc/ipc-thread.c, LibOS/shim/src/fs/proc/thread.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/sys/shim_fs.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/src/sys/shim_socket.c
This change is in preparation for bigger refactoring: simplifying directory handles, `getdents` and `getdents64`. It also unblocks changing the mount semantics (indirectly: there are special files, namely Unix sockets and named pipes, that get super-special treatment in Graphene and having the `type` field will allow me to make that explicit).
In principle, this refactoring could be taken further:
* remove `mode()` callback
* remove `DENTRY_DIRECTORY`, `DENTRY_ISLINK` flags, as they're redundant now
* remove various `type` fields throughout the code
However, when I tried to do any of these, the change snowballed, so I want to make further changes gradually. The important part is that the `type` field is available as part of dentry, because it unblocks many other simplifications in the …
=> Ensure dentry type and permissions are always stored

Documentation/quickstart.rst, Pal/src/host/Linux-SGX/link-intel-driver.py, Pal/src/host/Linux-SGX/sgx_in_kernel.h, Tools/gsc/config.yaml.template, Tools/gsc/test/Makefile
Now `ISGX_DRIVER_PATH=""` correctly implies the in-kernel SGX driver `/dev/sgx_enclave` as used in Linux versions 5.11+. Documentation and GSC are updated correspondingly (to assume Linux 5.11+ by default).
Try building and installing on a Linux 5.11 machine. The rest works as usual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2387)
=> [Docs,Pal/Linux-SGX] Switch to in-kernel SGX driver as default

Pal/src/host/Linux-SGX/enclave_pf.c, Pal/src/host/Linux-SGX/protected-files/protected_files.c, Pal/src/host/Linux-SGX/protected-files/protected_files.h, Pal/src/host/Linux-SGX/tools/common/pf_util.c, Pal/src/host/Linux-SGX/tools/common/pf_util.h, Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
Protected FS previously used AES-GCM (with empty output argument, using the MAC as the derived key) as a KDF. This construction lacks any proof of correctness, thus this commit replaces AES-GCM with AES-CMAC as a KDF as per NIST recommendation.
Fixes #2386.
All tests must pass, especially FS tests (`make pf-test`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2390)
=> [Pal/Linux-SGX] Use AES-CMAC for key derivation in Protected Files

LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_handle.h, LibOS/shim/include/shim_table.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/dev/fs.c, LibOS/shim/src/fs/proc/fs.c, LibOS/shim/src/fs/proc/ipc-thread.c, LibOS/shim/src/fs/proc/thread.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/sys/fs.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/test/regression/getdents.c, LibOS/shim/test/regression/test_libos.py
This changes the filesystem `readdir` operation so that it only needs to call a callback. This is a big simplification for underlying filesystems: a lot of code was responsible for dynamically allocating the right amount of memory.
Additionally, the only piece of information required from `readdir` is a name, not file type or inode number. We perform a lookup on the underlying dentries anyway, so this prevents code duplication.
The directory handle stores an array of dentries, along with size and position in that array, instead of special `dot` and `dotdot` pointers. This simplifies the implementation of `getdents/getdents64` system calls, and also should allow for easier implementation of `lseek` on directory handles. 
(@dimakuv you asked about this recently - this commit does not …
=> Simplify getdents/getdents64

LibOS/shim/src/bookkeep/shim_process.c, LibOS/shim/src/shim_checkpoint.c, LibOS/shim/src/sys/shim_wait.c
Currently PAL handle used to communicate with the child process (e.g. to send checkpoint) is not needed after successful process creation and needs to be destroyed correctly.
This commit also adds missing `get_thread` and `put_thread` in `wait*` syscalls routines.
Run a couple of fork()+wait() and check list of host-OS fds (`/proc/[pid]/fd/`). Without this patch there will be 1 fd leaked per child process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2404)
=> [LibOS] Always close child PAL handle

LibOS/shim/test/regression/large_mmap.c, Pal/src/host/Linux-SGX/db_process.c, Pal/src/host/Linux-SGX/db_sockets.c
Long time ago, there was a quirk that OCALLs used 32-bit sizes (e.g., in `ocall_read`/`ocall_write`). This limitation was removed, but the checks for uint32 overflow remained. This led e.g. to failures during fork, when a checkpointed memory region exceeded 4GB and thus was deemed "invalid" to be sent to the child.
Fixes #2388 (probably?).
This PR also adds the case "send >4GB checkpoint" to `large_mmap` regression test. However, since this takes several minutes to execute on wimpy SGX machines, this case is commented out by default.
Uncomment it manually and re-run the regression suite. You'll see that it fails without this PR and succeeds with this PR.
--- …
=> [Pal/Linux-SGX] Remove 32-bit limit on buffer size in read/write

LibOS/shim/src/fs/chroot/fs.c
There was a bug that LibOS manipulated the offset (`file->marker`) on device files (with type `FILE_DEV`). This led to calls like
`DkStreamRead(.., /*offset=*/10, ..)` which ends up in PAL's device read function that errors out because the offset is not zero (as expected).
Note that this special handling was already implemented for `FILE_TTY` terminal devices, but we forgot about `FILE_DEV` generic devices.
All tests must pass. This was found on a private workload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2413)
=> [LibOS] Do not update offset on chroot `FILE_DEV` files

LibOS/shim/src/sys/shim_open.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/getdents_lseek.c, LibOS/shim/test/regression/test_libos.py
Follow up for #2383 (simplifying getdents). The directory handle has a `pos` field now, we might as well use it.
(By the way, it looks like `lseek` should not be implemented in underlying filesystems at all, and position should be stored in the handle, I will try to move in that direction.)
There is a new regression test, `getdents_lseek`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2406)
=> [LibOS] Support `lseek` for directories

Pal/src/host/Linux-SGX/db_misc.c
Previously, if the SGX enclave didn't use an XSAVE feature (by unsetting the bit in the SECS.ATTRIBUTES.XFRM mask), the sanity check failed if the XSAVE feature was available on the CPU. This check doesn't make sense: the SGX enclave may want to "hide" some CPU features, but this doesn't mean the enclave execution must be stopped.
This PR removes this incorrect check and instead forces the corresponding CPUID return values to zero.
For more information, please consult the Intel SDM. In particular, the `CPUID` instruction description (leaf `Processor Extended State Enumeration Sub-leaves (EAX = 0DH, ECX = n, n > 1)`), and SGX sections 37.7.1 and 41.7.
Fixes #2408.
--- …
=> [Pal/Linux-SGX] Force CPUID values of unused XSAVE features to zero

README.rst
Fosshost requires acknowledgement for their help (https://docs.fosshost.org/en/home/what-do-we-expect, pt. 3), which we intended to post on https://grapheneproject.io/, but the webmaster became unresponsive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2417)
=> Add acknowledgment for fosshost

Pal/include/arch/x86_64/pal-arch.h
When sanitizing `/sys/devices/system/node/node0/distance` path in graphene we compare the count of distances with number
of nodes present. But when SNC mode is enabled, we run out of the buffer to store the distances which results in incorrect distance count and the comparison fails. This PR increases the buffer size to hold all numa distances even for special cases like SNC.
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
All tests should pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2412)
=> [PAL] Fix sysfs numa sanitization when SNC is enabled

LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_handle.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/bookkeep/shim_vma.c, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/dev/fs.c, LibOS/shim/src/fs/eventfd/fs.c, LibOS/shim/src/fs/pipe/fs.c, LibOS/shim/src/fs/proc/fs.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/socket/fs.c, LibOS/shim/src/fs/sys/fs.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/shim_rtld.c, LibOS/shim/src/sys/shim_epoll.c, LibOS/shim/src/sys/shim_eventfd.c, LibOS/shim/src/sys/shim_exec.c, LibOS/shim/src/sys/shim_file.c, LibOS/shim/src/sys/shim_ioctl.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/src/sys/shim_socket.c, LibOS/shim/src/sys/shim_stat.c
(I think this finally unblocks the "mount semantics" refactoring! I'm checking that right now, but it's going to be a separate PR.)
This change replaces most usages of `shim_mount` with `shim_fs`. Graphene uses the `shim_mount` structure to represent a mounted filesystem, but in most cases we're only interested in the function table.
The main reason for this change is special treatment of sockets and FIFOs: before, we replaced the `fs` field (actually `shim_mount`) for their dentries, so that they are served by a different filesystem. However, that loses information about which part of the tree the dentry actually is in.
The new solution is to store both `shim_mount` and `shim_fs` for a dentry. This follows Linux, which stores both `super_block` and `inode_iperations` for an inode, and …
=> [LibOS] Split `shim_mount` and `shim_fs`

.ci/lib/stage-test.jenkinsfile, Pal/regression/Makefile, python/graphenelibos/manifest.py
Fixes: #2425 (Pal/regression seems broken after 13afef4313b3dfcc3fad73e5ecc685a2c133418f by @jurobystricky)
```sh
cd Pal/regression
make regression
make regression SGX=1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2428)
=> [Pal] regression: fix make regression without pal_lib=

Runtime/pal_loader
Currently this is broken for everything other than Linux-SGX in some circumstances, but I don't want to support or even explain those circumstances.
```sh
make
make SGX=1
./Runtime/pal_loader # should error out
```
Cc @vijaydhanraj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2430)
=> Break running from repo

Pal/src/host/Linux-SGX/enclave_framework.c, common/include/crypto.h, common/src/crypto/adapters/mbedtls_adapter.c
It was recommended to us to update from modp2048 Diffie-Hellman group (group 14) to modp3072 group (group 15). It is a trivial update.
All tests should pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2429)
=> [Pal/Linux-SGX] Update Diffie-Hellman parameters to use modp3072 group

LibOS/shim/include/shim_ipc.h, LibOS/shim/src/fs/proc/ipc-thread.c, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/ipc/shim_ipc_child.c, LibOS/shim/src/ipc/shim_ipc_pid.c, LibOS/shim/src/ipc/shim_ipc_ranges.c, LibOS/shim/src/ipc/shim_ipc_sync.c, LibOS/shim/src/ipc/shim_ipc_worker.c, LibOS/shim/src/sys/shim_sigaction.c, LibOS/shim/test/regression/sighandler_reset.c, common/include/api.h
Function `ipc_send_msg_and_get_response` is introduced, which sends the probided IPC message and waits for a response to it. The response could be anything and is returned by this function - it is the caller responsibility to interpret it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2433)
=> [LibOS] Remove IPC msg_with_ack and introduce message responses

LibOS/shim/include/shim_fs.h, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_fs_hash.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/sys/shim_pipe.c, LibOS/shim/src/sys/shim_socket.c
This changes the mount operation to create and attach new dentry instead of replacing an existing one. See the commit message for details.
I believe the current tests are enough.
Here is an example of the new dentry tree. `M` is a mountpoint dentry, with the actual new filesystem root attached under it.
```
[P67026:T1:busybox] [       V..  3] 040700 drwx M /
[P67026:T1:busybox] [chroot V.. 26] 040700 drwx *   /
[P67026:T1:busybox] [chroot V.S  2] 100000 ---- M     proc
[P67026:T1:busybox] [  proc V..  1] 040555 dr-x *       proc/
[P67026:T1:busybox] [chroot V.S  2] 100000 ---- M     dev
[P67026:T1:busybox] [   dev V..  2] 040555 dr-x *       dev/
[P67026:T1:busybox] [   dev V..  2] 020666 crw- M         tty
[P67026:T1:busybox] [chroot V..  3] 020600 crw- *           tty …
```
=> [LibOS] Change mount semantics

LibOS/shim/src/sys/shim_file.c, Pal/include/pal_internal.h, Pal/regression/AttestationReport.c, Pal/regression/File.c, Pal/regression/Memory.c, Pal/regression/manifest.template, Pal/src/db_memory.c, Pal/src/db_streams.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_memory.c, Pal/src/host/Linux-SGX/enclave_pages.c, Pal/src/host/Linux-SGX/enclave_untrusted.c, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux-SGX/sgx_internal.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux/db_main.c, Pal/src/host/Linux/db_memory.c, Pal/src/host/Linux/pal_linux.h, Pal/src/host/Skeleton/db_main.c
Previously, only the Linux-SGX PAL honored the manifest option `loader.pal_internal_mem_size`. The Linux PAL simply performed
`mmap(/*addr=*/NULL, ..)` when 64MB of the pre-allocated memory pool depleted, which led to memory corruptions (since LibOS was unaware of this PAL-internal mmap and could overwrite it, and vice versa).
This commit fixes Linux PAL's allocator to honor this limit. The whole virtual space of the process is split into two parts: the lower part is for LibOS consumption, the upper part is for internal PAL consumption, so there is no possibility for memory corruptions any more.
As part of this fix, PAL memory allocation routines have stricter checks on allocation arguments. As a side effect, PAL regression tests are modified to always use fixed memory addresses.
This was …
=> [Pal/Linux] Honor `loader.pal_internal_mem_size` limit

Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp
Seems we forgot to update this tool after SGX got into the kernel. Kudos to @vans163 for noticing this!
Closes #2427.
Run `is_sgx_available` on a system which uses the upstreamed SGX driver and check if "SGX driver loaded" says "true".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2438)
=> [Pal/Linux-SGX] tools: Support upstreamed driver in is_sgx_available

LibOS/shim/include/shim_internal.h, LibOS/shim/include/shim_thread.h, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/bookkeep/shim_thread.c, LibOS/shim/src/utils/log.c
Internal threads do not need IDs at all and now have `0` set as the thread ID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2458)
=> [LibOS] Remove internal threads IDs

Documentation/manifest-syntax.rst, LibOS/shim/test/regression/file_check_policy.c, LibOS/shim/test/regression/test_libos.py, Pal/src/host/Linux-SGX/enclave_framework.c
Previously, Linux-SGX PAL had a bug of creating any files from within the enclave, even though such files were not listed as allowed or trusted files/paths. This commit fixes this bug, and also disallows opening a trusted file for write/append (because this doesn't make sense and write operations are already disallowed for trusted files).
The `file_check_policy` LibOS regression test is augmented to test this bug fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2446)
=> [Pal/Linux-SGX] Disallow creating unknown files

Documentation/cloud-deployment.rst, Documentation/manifest-syntax.rst, Documentation/quickstart.rst
I'm still not sure about one option: `sgx.debug`. Is it actually possible to set it to `true` and accidentally ship such an enclave? This will be visible in the attestation, but maybe that's not enough?
In the future it would be good to have some kind of warning banner at the start of Graphene if it's insecure, which would be enabled in all debug builds, when using insecure/non-prod manifest settings, etc.
ps. I squashed in a few formatting fixes, reST was broken in a few places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2454)
=> [Docs] Ensure that insecure options are clearly marked as such 

Documentation/manpages/gsc.rst, Tools/gsc/config.yaml.template, Tools/gsc/templates/entrypoint.manifest.template, Tools/gsc/test/Makefile, Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest
Recently, our changes to the build system (moving to Meson, renaming tools, deprecating Makefiles) break GSC when it tries to use the latest master commits. Let's make GSC work again by fixing its config to the last known working commit (and reverting some GSC-related changes from the newer commits).
After this PR, no changes to core Graphene should touch GSC files!
Manually test GSC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2457)
=> [GSC] Fix Graphene version in GSC config file to last working commit

Documentation/cloud-deployment.rst
Seems that one of the invocations was wrong. Originally noticed by @codingwithblackcoffee, thanks!
Closes #2462.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2480)
=> [Docs] Fix invalid `ninja` invocation in cloud-deployment.rst

LibOS/shim/src/bookkeep/shim_process.c, LibOS/shim/src/shim_debug.c, common/include/list.h, common/include/memmgr.h, common/include/slabmgr.h
Seems we finally can do this, some time ago everything exploded after doing so :) Now it found only one use-after-free bug, which is also fixed in this PR.
CI in debug mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2470)
=> Erase memory on `free()` in debug builds

Documentation/tutorials/pytorch/index.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2455)
=> [Docs] Correct a path to libsecret_prov_attest.so in pytorch tutorial

LibOS/shim/include/shim_ipc.h, LibOS/shim/src/ipc/shim_ipc_signal.c
Previously Graphene (incorrectly) assumed that a `tgkill` IPC message is always sent to a process which PID matches the killed TGID (which could be false if TGID was incorrect).
Fixes #2488
`tgkill03` from LTP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2490)
=> [LibOS] Send PID alongside TID in tgkill IPC message

LibOS/shim/src/sys/shim_open.c, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/large_file.c, LibOS/shim/test/regression/test_libos.py
See recent issue #2478 (to be confirmed).
`lseek` used an int, I fixed it and added a test.
(We're planning to stop using `off_t` internally, but it's unrelated to the current bug).
There is a new regression test, `large_file`. Before the fix, it displayed:
```
testing length 0x7fffffff
testing length 0x80000001
large_file: lseek(fd, -1, 2) = -2147483648 (ffffffff80000000): Success
```
And it looks like the length `0xffffffff` actually causes `lseek` to return something resembling an error code, because I get:
```
testing length 0xffffffff
large_file: lseek(fd, -1, 2) = -1 (ffffffffffffffff): No such file or directory
```
(The test passes now).
--- …
=> [LibOS] Fix lseek with large offsets

Documentation/building.rst, Documentation/cloud-deployment.rst, Documentation/devel/debugging.rst, Documentation/quickstart.rst
Meson by default has --buildtype=debug, so currently, with two stacked
build systems and without explicit setting, half of the build was
non-debug (make) and the other half was debug (meson).
Execute the changed instruction. Ensure that the build is either fully debug or fully non-debug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2492)
=> [Docs] building.rst: Mention --buildtype

.ci/lib/config-docker.jenkinsfile, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/Makefile, LibOS/shim/test/regression/device_passthrough.c, LibOS/shim/test/regression/device_passthrough.manifest.template, LibOS/shim/test/regression/manifest.template, LibOS/shim/test/regression/test_libos.py
Previously, the generic `manifest.template` for all regression tests contained a mount point `/dev/kmsg` (device containing Linux messages). However, recent Ubuntu distros and some other distros (CentOS, RedHat) disallow unprivileged access to this device, and this test failed. This commit fixes this by splitting `/dev/kmsg` test away from the generic manifest file. Additionally, our PyTest script checks if access to `/dev/kmsg` is allowed and skips the `device` test if not.
Try on Ubuntu 21.04 or CentOS 8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2496)
=> [LibOS] regression: Use `/dev/zero` host device instead of `/dev/kmsg`

Pal/src/host/Linux-SGX/db_exception.c, Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/enclave_pf.c
This is a slightly simplified version of #2468 (please see its description for more details).
I talked with @boryspoplawski and @pwmarcz and decided that the proper solution for this should be making `log_*()` censor format string replace points, but then I looked at the `vfprintfmt()` code and gave up. So, for now let's at least fix the most dangerous messages.
There are a lot of changes to logging in protected files, because it seems that most of the messages there are actually warnings (i.e. Graphene continues to work correctly after printing them) and there also emit a lot of information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2497)
=> Strip confidential information from logs on "error" level (minimal version)

LibOS/shim/test/regression/cpuid.c, Pal/src/host/Linux-SGX/db_misc.c
Previously, Linux-SGX PAL failed on all CPUID leaves not mentioned in our internal CPUID table. This is not how the actual Intel CPUID instruction behaves: some CPUID leaves are explicitly reserved and always return zeros, and the rest CPUID leaves return the info as if they are the "highest basic information leaf".
This PR adds such handling to make our CPUID logic exactly the same as in the latest Intel SDM documentation.
Fixes #2439 .
Added more testing to the `cpuid` LibOS regression test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2440)
=> [Pal/Linux-SGX] Add handling for all reserved and unrecognized CPUID leaves

common/src/crypto/adapters/mbedtls_adapter.c
This PR fixes the following issues flagged by Klockwork scan of graphene repo
Pointer 'cipher_info' returned from call to function 'mbedtls_cipher_info_from_type' at line 254 may be NULL and will be dereferenced at line 257.
/home/intel/graphene_klockwork/graphene/common/src/crypto/adapters/mbedtls_adapter.c:257 | lib_AESCMACFinish()
Pointer 'cipher_info' returned from call to function 'mbedtls_cipher_info_from_type' at line 212 may be NULL and will be dereferenced at line 214.
/home/intel/graphene_klockwork/graphene/common/src/crypto/adapters/mbedtls_adapter.c:214 | lib_AESCMAC()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2483)
=> [Pal/Linux-SGX] Fix pointer check issues flagged by Klocwork

LibOS/shim/include/shim_fs.h, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/str/fs.c, LibOS/shim/src/sys/shim_poll.c, LibOS/shim/test/regression/poll.c, LibOS/shim/test/regression/test_libos.py
Found when investigating `stress-ng` (#2419).
The code assumed that all handles (other than TYPE_FILE and TYPE_DEV) had an associated PAL handle, which caused a crash when polling files from /proc. This change adds support for polling TYPE_STR, and also adds a check for PAL handle in all cases.
(I think poll deserves a bigger rewrite, this is just a quick fix).
* The procfs stress test (`stress-ng --procfs 8 --timeout 40s`) stopped crashing for me (see #2419).
* I rewrote `poll` regression test to be more thorough, it checks several types of files now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2498)
=> [LibOS] Fix poll() crashing on pseudo-files

LibOS/shim/src/fs/shim_namei.c, LibOS/shim/test/regression/mkfifo.c, LibOS/shim/test/regression/test_libos.py
Found while investigating #2419. I tried to make a proper fix in PR #2499, but that seems to be blocked by conflict with tmpfs/strfs code. Merging #2499 would probably make an existing memory leak worse, so I would like to take care of tmpfs and strfs first. In the mean time, here is the workaround for the actual crash.
I ticketed the proper fix as #2507 and intend to work on it.
This fixes a crash where we create a named pipe, remove it, and then try to create a normal file with the same name. Unfortunately, fixing the underlying problem (dentry reuse) is more problematic, so this is only a workaround for that specific case.
* Should fix the mknod crash in #2419 
* Note that the mknod stress test still fails, because our mknod doesn't create sockets, and (when these failures are ignored) …
=> [LibOS] Fix a crash after reusing dentry touched by `mknod`

LibOS/shim/src/bookkeep/shim_pid.c
Check the commit message and comment in code.
Hopefully fixes PR #2504
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2508)
=> [LibOS] Do not print errors on last TID release failure

LibOS/shim/src/sys/shim_file.c, LibOS/shim/test/ltp/ltp-sgx.cfg, LibOS/shim/test/ltp/ltp.cfg
Now sendfile emulation doesn't try to be fancy and use `mmap` but instead simply `read`s from input handle and `write`s into output handle. This is not performant but good enough for now.
This new code has some limitations, but we plan to fix them one by one soon-ish. For now we just want `sendfile()` to not fail on "normal" programs.
Closes #2501.
Fixes #2265.
Several LTP tests are enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2500)
=> [LibOS] Rewrite `shim_do_sendfile()` to make it simple

Documentation/building.rst, Documentation/quickstart.rst
When installed from sources, Graphene is put under `/usr/local/bin`. However, some Linux distros (notably CentOS) do not allow running apps from this directory, so users must manually add this directory to the `PATH` environment variable.
This PR adds a note on this in our documentation.
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2509)
=> [Docs] Add note on adding `/usr/local/bin` to `PATH` envvar

LibOS/shim/test/ltp/ltp.cfg
Previously, `recvmsg01` was enabled with only a handful of subtests required to pass. In this test, one of the subtests spawns a child process that crashes loudly (because of the bug in Graphene). It is better to completely disable this test than to have only "partially working" test in our CI.
Fixes #2265 
N/A.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2513)
=> [LTP] Disable `recvmsg01` because of the non-fatal crash

Documentation/pal/porting.rst, LibOS/shim/include/shim_ipc.h, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/ipc/shim_ipc.c, LibOS/shim/src/ipc/shim_ipc_pid.c, LibOS/shim/src/ipc/shim_ipc_sync.c, LibOS/shim/src/ipc/shim_ipc_vmid.c, LibOS/shim/src/ipc/shim_ipc_worker.c, LibOS/shim/src/meson.build, LibOS/shim/src/shim_checkpoint.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_exit.c, LibOS/shim/src/utils/log.c, Pal/include/pal/pal.h, Pal/include/pal_internal.h, Pal/regression/Bootstrap.c, Pal/src/db_main.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux/db_main.c, Pal/src/host/Linux/db_process.c, Pal/src/host/Linux/pal_linux.h, Pal/src/host/Linux/pal_security.h, Pal/src/host/Skeleton/db_main.c
Previously Graphene internal IDs were just equal to host PIDs, which was a security issue on SGX PAL.
Fixes #2087
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2526)
=> [LibOS] Make Graphene internal IDs managed by LibOS

LibOS/shim/test/ltp/manifest.template
Commit ee5acd1 from Stefan Berger fixed running LTP tests on CentOS/Fedora by identifying a correct path for coreutils' libstdbuf library. However, this commit missed one place in the manifest file (because Stefan doesn't test SGX-related options in the manifest).
For context, see https://github.com/oscarlab/graphene/pull/1617.
Fixes #2475.
Test LTP on CentOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2555)
=> [LTP] Fix path for `libstdbuf.so` on CentOS/Fedora

LibOS/shim/src/sys/shim_socket.c
Previously if there was some ancillary data in `struct msghdr` e.g. sent via `sendmsg`, Graphene would silently ignore it and move on. Now it explicitly errors out with a warning (ancillary data is not yet supported).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2557)
=> [LibOS] Error out on messages containing ancillary data

Examples/pytorch/pytorch.manifest.template
Signed-off-by: Przystawski <sebastian.przystawski@intel.com>
Without specifying Graphene metadata size this pytorch sample application
was not able to run because of "Out-of-memory in PAL" error.
Specifying "loader.pal_internal_mem_size" in manifest fix that issue.
Changes to be committed:
modified:   Examples/pytorch/pytorch.manifest.template
Added loader.pal_internal_mem_size = "128M" to pytorch manifest.template
Buld and run pytorch example according to the instructions
in https://github.com/sprzysta/graphene/blob/master/Examples/pytorch/README.md.
Example application should run without error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2512)
=> [Examples] Fix Out-of-memory in PAL

.ci/lib/stage-test-sgx.jenkinsfile
Previously, it was tested only on Ubuntu 18.04 (bionic) due to concerns over sending too many EPID requests to the Intel Attestation Service (IAS). This shouldn't be an issue anymore.
Trigger Jenkins several times to be sure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2534)
=> [CI] Test SGX remote attestation examples on Ubuntu 18.04 and 20.04

LibOS/shim/include/shim_utils.h, LibOS/shim/src/shim_debug.c, LibOS/shim/src/shim_init.c
This solves a small TODO: the global debug map list was not protected by any lock. I'm not sure if that ever caused problems, but now it should be correct.
In addition, I took the opportunity to convert the global variable name to `g_*`, and use standard `list.h` instead of ad-hoc lists.
Existing tests should be enough: they include GDB integration, as well as various fork and exec scenarios.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2560)
=> [LibOS] Use a lock in `shim_debug`

LibOS/shim/include/shim_fs.h, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/sys/shim_clone.c
Previously, the child process initialized `g_dentry_root` but restored all other dentries from a checkpoint. As a result, `g_dentry_root` was an isolated dentry. This worked only because the rest of the code used `g_process.root` which was checkpointed.
As mentioned above, this should not be noticeable from outside. However, if you do `dump_dcache(NULL)`, on this branch it will display the dentry tree copied from parent, and on `master` it will display an empty dentry tree.
You can also take a look at `g_dentry_root` in GDB: it should have `attached_mount`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2561)
=> [LibOS] Checkpoint `g_dentry_root`

LibOS/shim/src/bookkeep/shim_process.c, LibOS/shim/src/fs/shim_namei.c, Pal/include/arch/x86_64/Linux/pal_host-arch.h, Pal/include/arch/x86_64/pal-arch.h, Pal/src/host/Linux-SGX/Makefile, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_threading.c, Pal/src/host/Linux-SGX/sgx_tls.h, Pal/src/host/Linux/db_main.c, Pal/src/host/Linux/db_threading.c, Pal/src/host/Linux/pal_linux.h, common/include/api.h
This fixes a few things that broke recently under Clang. We need to run Clang on Jenkins, but I think that can wait until the end of Meson migration.
Build (run `make` and `ninja`) with `CC=clang CXX=clang++ AS=clang`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2570)
=> Fix compilation under Clang

.dir-locals.el
As discussed in #2566, we want README.md files to be wrapped at 80 columns, same as rest of documentation. This adds a directive for Emacs to understand that.
* Open Emacs, install markdown-mode if necessary (`M-x package-install`, `markdown-mode`)
* Open any README.md file in Emacs
* Try to wrap a paragraph with `M-q`. Emacs should wrap it at 80 columns.
* In Emacs 28+: display fill column (`M-x global-display-fill-column-indicator-mode`), it should be displayed at 80 columns in .md files (and at 100 colums for .c files).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2568)
=> [.dir-locals.el] Use 80 columns for Markdown files

LibOS/shim/src/fs/shim_fs.c
Graphene automatically mounts and populates `/proc`, `/sys` and `/dev`. The user may mount these directories (or files under these directories) from the host but Graphene will now loudly warn about this.
Manually add these mounts to the manifest and see how Graphene complains.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2567)
=> [LibOS] Warn on mounting host dirs/files shadowing sensitive directories

Examples/sqlite/README.md
This PR adds the missing `3` to the sqlite command. Otherwise, the readme works perfectly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2579)
=> [Examples] Fix SQLite command invocation in README

Documentation/devel/coding-style.rst, LibOS/shim/include/shim_fs.h, LibOS/shim/include/shim_handle.h, LibOS/shim/include/shim_types.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/eventfd/fs.c, LibOS/shim/src/fs/pipe/fs.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_fs_util.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/socket/fs.c, LibOS/shim/src/fs/str/fs.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/meson.build, LibOS/shim/src/shim_rtld.c, LibOS/shim/src/sys/shim_fcntl.c, LibOS/shim/src/sys/shim_file.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/test/ltp/ltp.cfg
**EDIT**: We introduce our own type, `file_off_t`, instead of using `loff_t`; see discussion.
This converts all internal `off_t` to `loff_t` (plus a few related changes, see commits). 
I'm planning bigger changes to FS regarding file position and size after that (currently we keep it in far too many places), but I want to have the right type first.
Note that this does not make us fully 32-bit ready: we would (at least) need to implement syscalls like `llseek` and `stat64`, because `lseek` and `stat` use `off_t`.
This is apparently what Linux uses internally everywhere, for both file size and offset, and I think they have good reasons:
* Initially I wanted to have an usigned type such as `uint64_t`, but it's much easier to check/assert if size or offset is >= 0, than worry about the …
=> Convert seek offsets to `file_off_t`

Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_epid.c
SigRLs are Signature Revocation Lists that can be separately fetched from Intel Attestation Service (IAS), to verify that the EPID private key of the user was revoked. Previously, we had a TODO comment to fetch these SigRLs and verify against them. However, this is not needed because the "verify attestation evidence" request to IAS (issued by RA-TLS) already forces IAS to check the EPID key against SigRLs. Thus, fetching SigRLs separately is just an optimization and not needed to be enforced in RA-TLS.
Please check https://api.trustedservices.intel.com/documents/IAS-API-Spec-rev-5.0.pdf, Section 3.2 for the details of "verify attestation evidence" end-point of IAS. There is an example of a revoked EPID group in Section 3.2.3.7. Similarly, the IAS attestation report will return …
=> [Pal/Linux-SGX] Remove TODO on fetching SigRLs from IAS in RA-TLS

Documentation/manpages/is_sgx_available.rst, Pal/src/host/Linux-SGX/tools/README.rst, Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp
Previously, `is_sgx_available` reported whether AESMD is *running* based on existence of the socket `/var/run/aesmd/aesm.socket`. In reality, the existence of this socket doesn't mean that AESMD is actually running but that it is only installed on the machine.
See https://github.com/oscarlab/graphene/issues/1998 for context. I went with the approach number 3 in here: https://github.com/oscarlab/graphene/issues/1998#issuecomment-736333951.
Fixes #1998.
Run `is_sgx_available` on any machine, including CentOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2573)
=> [Pal/Linux-SGX] `is_sgx_available`: report whether AESMD is installed

LibOS/shim/include/shim_fs.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/chroot/fs.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/sys/shim_file.c, LibOS/shim/src/sys/shim_getcwd.c, LibOS/shim/src/sys/shim_stat.c
This is a follow-up to previous changes that introduced the `type` field. This change removes the redundancy in data. It also simplifies the `state` bit field - hopefully, I can change it to an enum soon.
It's a small change but I didn't want to bundle it with others - it looks like it would be a pain to keep the commits separate.
This should be well covered by existing tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2587)
=> [LibOS] Remove `DENTRY_ISDIRECTORY`, `DENTRY_ISLINK`

LibOS/shim/include/shim_handle.h, LibOS/shim/src/sys/shim_open.c
Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>
I encountered an issue while executing a workload where the `read` call was returning error causing the `fread` operation in the application to fail. This is rootcaused to mismatching data types between `shim_do_read` (and `shim_do_write`) and `do_handle_read` (and `do_handle_write`) calls. The incoming argument `count ` in `read` and `write` calls is of data type `size_t` whereas `do_handle_read` and `do_handle_write` takes this `count` as `int` causing an overflow and resulting in error.
This PR is to fix this issue by changing the data type of the argument `count`  in `do_handle_read` and `do_handle_write` to `size_t`.
--- …
=> [LibOS] Use size_t in do_handle_{read,write}

Examples/apache/Makefile, Examples/bash/Makefile, Examples/blender/Makefile, Examples/busybox/Makefile, Examples/common_tools/download, Examples/curl/Makefile, Examples/gcc/Makefile, Examples/lighttpd/Makefile, Examples/memcached/Makefile, Examples/nginx/Makefile, Examples/nodejs/Makefile, Examples/openvino/Makefile, Examples/python/Makefile, Examples/pytorch/Makefile, Examples/r/Makefile, Examples/ra-tls-mbedtls/Makefile, Examples/ra-tls-secret-prov/Makefile, Examples/redis/Makefile, Examples/sqlite/Makefile, Examples/tensorflow-lite/Makefile, Examples/tensorflow-lite/label_image.manifest.template
Examples are supposed to be stand-alone and work with packaged Graphene. To this end, this commit removes the `GRAPHENEDIR` envvar and the associated includes of Graphene-internal Makefiles. This commit also copies the `download` bash script under `Examples/` so that it is closer to the actual examples (this will be handy when moving examples out of this core repository).
Ideally, `SGX_SIGNER_KEY` should be explicitly asked from the user, but for now we default to Graphene-internal `Pal/src/host/Linux-SGX/signer` for simplicity.
Also, `ra-tls-mbedtls` and `ra-tls-secret-prov` are still tightly coupled to Graphene-internal paths. This will be fixed when Linux-SGX PAL build is finally moved to Meson.
For more context, see:
- https://github.com/oscarlab/graphene/issues/2563
- …
=> [Examples] Decouple all examples from the core Graphene repo

LibOS/shim/src/fs/chroot/fs.c
A host-level named pipe is opened by PAL as a `pal_type_pipe` handle. Graphene did not handle this case, triggering a BUG(). Instead, we disallow accessing such files from LibOS.
Closes #570 (see the discussion).
Using `busybox` example and warning log level:
```
$ mkfifo x
$ graphene-sgx busybox stat x
...
[P1:T1:busybox] warning: trying to access 'file:./x' which is a host-level FIFO (named pipe); Graphene supports only named pipes created by Graphene processes
stat: can't stat 'x': Permission denied
```
On `master`, the same triggers "Illegal instruction during Graphene internal execution" (due to `BUG()`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2592)
=> [LibOS] Don't expose host-level named pipes to user

LibOS/shim/include/shim_fs.h, LibOS/shim/src/bookkeep/shim_handle.c, LibOS/shim/src/fs/pipe/fs.c, LibOS/shim/src/fs/proc/ipc-thread.c, LibOS/shim/src/fs/proc/thread.c, LibOS/shim/src/fs/shim_dcache.c, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_fs_hash.c, LibOS/shim/src/fs/shim_fs_pseudo.c, LibOS/shim/src/fs/shim_namei.c, LibOS/shim/src/fs/sys/cache_info.c, LibOS/shim/src/fs/sys/cpu_info.c, LibOS/shim/src/fs/sys/fs.c, LibOS/shim/src/fs/sys/node_info.c, LibOS/shim/src/fs/tmpfs/fs.c, LibOS/shim/src/shim_checkpoint.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/src/sys/shim_stat.c, LibOS/shim/src/utils/log.c
This change gets rid of the following `shim_qstr` instances:
- `shim_dentry.name`
- `shim_mount.path`, `shim_dentry.uri`
- parameter to `follow_link` callback
The remaining ones are mostly `shim_handle.uri` and URIs used by pipe filesystem, but it's somewhat harder to change them, so I wanted to push this first.
This should be well-covered by existing tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2585)
=> [LibOS] Convert some `shim_qstr` instances to C strings

LibOS/shim/test/ltp/ltp.cfg
`sendfile09` is already slow on my machine with SSD (2-5 seconds). So I can imagine how it exceeds the 30-second default timeout on our tiny NUCs with probably super-slow HDDs. Also recall that LTP tests are run in parallel in our CI, so the perf gets even worse.
I checked other `sendfile*` LTP tests, and they all operate on small data (up to 100 bytes). That's why they never timeout, but `sendfile09` does.
UPDATE: Added `fsync02` here, with timeout of 120 seconds. Looking at the sources of this test, I see this:
```c
/* fsync() has to finish within TIME_LIMIT. */
#define TIME_LIMIT 120
```
Jenkins. Can try several times to make sure we solved this issue.
--- …
=> [LTP] Increase timeout of slow `sendfile09` and `fsync02`

Examples/ra-tls-secret-prov/src/secret_prov_pf_client.c, Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
SGX Remote attestation and secret provisioning is performed via the `LD_PRELOAD = "libsecret_prov_attest.so"` trick. Previously, there was a bug in the `libsecret_prov_attest.so` library: its constructor was run before the `main()` code in each execve'd process. In multi-process apps that use execve syscall, this led to redundant remote attestation and secret provisioning requests to the Secret provisioning service.
Kudos to @yanzhichao who reported this bug. See https://github.com/oscarlab/graphene/issues/2583.
Fixes #2583.
I added a dummy `execve()` in the ra-tls-secret-prov example: run it, and without this PR you'll see two secre-provisioning requests. With this PR, there will be only one request.
--- …
=> [Pal/Linux-SGX] Suppress performing secret provisioning after execve

Pal/src/host/Linux-SGX/enclave_framework.c
This is already done by the `sgx_sign.py` script when generating the
final manifest; so the removed code was redundant.
Jenkins. Everything should just work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2606)
=> [Pal/Linux-SGX] Remove adding trusted files when parsing `loader.preload`

Pal/src/host/Linux-SGX/enclave_entry.S
Checks whether RIP is in range `[Locall_about_to_eexit_begin, Locall_about_to_eexit_end)` did not consider the case of calling `__restore_xregs`, which lead to incorrect handling of exception happening while being in `__restore_xregs` just before EEXIT while doing an ocall.
Fixes #2603 
Try running `poll_closed_fd` thousands of times (it takes a while). On current master it fails from time to time (after around ~4k times).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2608)
=> [Pal/SGX] Inline `__restore_xregs` in ocall EEXIT code

LibOS/shim/src/sys/shim_file.c, LibOS/shim/src/sys/shim_open.c, LibOS/shim/src/sys/shim_wrappers.c, LibOS/shim/test/ltp/ltp.cfg
Add some missing checks and tweak return values.
Fixes #2539. 
Fixes #2540.
Fixes #2548.
Two LTP tests are unblocked. The `chroot03` test still fails for unrelated reasons, but after commenting out `symlink()` in the setup should not produce `BUG()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2626)
=> Misc filesystem fixes

LibOS/shim/include/shim_internal.h, LibOS/shim/include/shim_utils.h, LibOS/shim/src/bookkeep/shim_vma.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/shim_rtld.c, LibOS/shim/src/sys/shim_clone.c, LibOS/shim/src/sys/shim_exec.c
* Remove searchable ELF map list (we only need to access two maps: executable and interpreter)
* Refactor interpreter loading code
* Convert some globals to `g_*` naming scheme
This is a byproduct of upcoming FS refactoring.
Existing tests should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2625)
=> [LibOS] Simplify RTLD code

Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux/db_main.c, Pal/src/printf.c
The logging subsystem (`log_error`) requires relocations to be applied before use, due to use of `log_level_to_prefix` array. This caused early calls to `log_error()` to crash.
To fix that, we apply relocations earlier in the startup process.
- **Compile PAL so that no relocations are necessary** - I'm not sure if that's possible if PAL is position-independent? Apparently GCC has [-static-pie](https://stackoverflow.com/questions/62586808/how-are-relocations-supposed-to-work-in-static-pie-binaries), but it just shifts the work of applying these relocations to runtime (by calling a glibc function)...
- **Compile PAL so that it's at a static position** - probably it's not worth it just for that?
- **Make `log_*` code position-independent**. Maybe that's worth doing regardless of this fix, …
=> [Pal/{Linux,Linux-SGX}] Fix early log messages crashing PAL

LibOS/shim/src/sys/shim_open.c
Fixes #2538. Return `-EINVAL` on encountering O_PATH flag in `open`/`openat`
Do the issue  repro steps mentioned in this PR #2538 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2614)
=> [LibOS] Return `-EINVAL` on encountering O_PATH flag in `open`/`openat`

Documentation/manpages/gsc.rst, Tools/gsc/config.yaml.template, Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template, Tools/gsc/templates/apploader.template, Tools/gsc/templates/entrypoint.manifest.template
Signed-off-by: Veena Saini <veena.saini@intel.com>
This PR allows GSC to work successfully with latest master. Meson build steps are included in gsc/templates/Dockerfile.ubuntu18.04.compile.template file. The output of meson build is stored inside */graphene/meson_build_output* directory and path to this output directory is included in $PATH and $PYTHONPATH environment variables. 
Few more changes:
(i) loader.preload variable in entrypoint.manifest.template points to meson build output sub-directory, i.e., */graphene/meson_build_output*/lib/x86_64-linux-gnu/graphene/.
(ii) graphene-sgx-sign and graphene-sgx-get-token binaries are included from meson build output sub-directory, i.e. ,
*/graphene/meson_build_output*/bin. 
GSC build and sign steps should pass, and resultant gsc image should …
=> [GSC] Update GSC for latest master build changes

Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/pal_linux.h
This function is split into several functions: initializing trusted files, initializing allowed files, and registering one file with
normalized path. This commit is in preparation for SGX allowed/trusted/protected files to be specified in TOML arrays.
Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2607)
=> [Pal/Linux-SGX] Refactor `init_trusted_files()`

LibOS/shim/src/sys/shim_socket.c, LibOS/shim/test/regression/test_libos.py, LibOS/shim/test/regression/unix.c
Previously, LibOS expected `addrlen` for UNIX domain sockets to be exactly the same as the size of `sockaddr_un` struct. This is not true in the common case: `addrlen` may be less, see `man unix`.
Fixes #2609.
Added a test case in our existing `unix.c` LibOS regression test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2620)
=> [LibOS] Relax check on UNIX domain socket's `addrlen` in `bind`

Pal/src/db_rtld.c
Fixes a warning/error in Pal/src/db_rtld.c that prevents building
with GCC 11.1.0.
Trying to compile with `GCC 11.1.0` results in the following warning/error:
```
../Pal/src/db_rtld.c: In function ‘map_elf_object_by_handle.constprop’:
../Pal/src/db_rtld.c:206:43: error: ‘(((char *)c + 16))[461168601842738789].mapend’ may be used uninitialized [-Werror=maybe-uninitialized]
206 |                 if (nloadcmds > 1 && c[-1].mapend != c->mapstart)
```
This pull request fixes that without making any changes in functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2651)
=> [Pal] Fix GCC -Wmaybe-uninitialized warning

Pal/gdb_integration/debug_map_gdb.py, Pal/gdb_integration/language_gdb.py, Pal/gdb_integration/pagination_gdb.py, Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb, Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx_gdb.py, Pal/src/host/Linux/gdb_integration/graphene_linux_gdb.py
I truly hate GDB :) It turns out that the scripts are interpreted with syntax which depends on the current *app* language. So, e.g. expressions in our signal handler in GDB script are parsed using C syntax if the signal happened when executing C code, but if the signal arrived in Rust code, then the expressions in same script code will be parsed as Rust...
Try to debug a Rust application in Graphene.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2652)
=> Fix GDB integration with non-C apps

.pylintrc, LibOS/shim/test/regression/.gitignore, LibOS/shim/test/regression/file_check_policy.c, LibOS/shim/test/regression/test_libos.py, Pal/regression/File.manifest, Pal/regression/normalize_path.c, Pal/src/host/Linux-SGX/db_files.c, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux-SGX/db_streams.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/enclave_pf.c, Pal/src/host/Linux-SGX/enclave_pf.h, Pal/src/host/Linux-SGX/enclave_tf.h, Pal/src/host/Linux-SGX/pal_linux.h, common/include/api.h, common/src/path.c
This PR moves all possible checks (file must be in a set of protected, trusted, allowed files from the manifest; trusted files cannot be created; etc.) before actual opening of the file in `file_open`. As a side effect, this fixes a bug when app wants to open an unknown file for write/append -- previously, Graphene would open such file, possibly truncate it and only then return error.
Also, this PR refactors `load_trusted_file` into `get_trusted_or_allowed_file` and `load_trusted_or_allowed_file`.
~~Must be rebased on top of #2446.~~
Originally found by @mkow.
All tests must succeed. Especially `file_check_policy` LibOS regression tests.
--- …
=> [Pal/Linux-SGX] Refactor `file_open` and `load_trusted_file` functions

Pal/src/host/Linux-SGX/enclave_ocalls.h, Pal/src/host/Linux-SGX/generated-offsets.c, Pal/src/host/Linux-SGX/linux_types.h, Pal/src/host/Linux-SGX/ocall_types.h, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux-SGX/sgx_enclave.c, Pal/src/host/Linux-SGX/sgx_enclave.h, Pal/src/host/Linux-SGX/sgx_main.c, Pal/src/host/Linux-SGX/sgx_perf_data.c, Pal/src/host/Linux-SGX/sgx_process.c, Pal/src/host/Linux-SGX/sgx_process.h, Pal/src/host/Linux-SGX/sgx_profile.c, common/include/api.h, common/src/network/inet_pton.c, common/src/string/ctype.c
The main thing I wanted to fix is a horrible `#undef __USE_POSIX199309` hidden somewhere in headers. Then the delicate header structure collapsed. This resulted in random header adjustments all over the place.
This was split from #2466 to merge earlier.
Jenkins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2631)
=> [Pal/Linux-SGX] Fix random header problems

Pal/src/host/Linux-SGX/protected-files/lru_cache.c, Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
Split off from #2645. This fixes two small issues that surfaced due to us enabling additional warnings (`-Wsign-compare`, `-Wnull-dereference`).
Jenkins should pass here, and in #2645 (which compiles this code with additional warnings enabled).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2668)
=> Fixes for warnings enabled by Meson

LICENSE.addendum.txt, LibOS/shim/src/bookkeep/shim_signal.c, LibOS/shim/src/fs/shim_fs_mem.c, LibOS/shim/src/ipc/shim_ipc_fs_lock.c, LibOS/shim/test/regression/Makefile, Pal/include/do-rel.h, Pal/src/host/Linux-SGX/protected-files/protected_files.c, Pal/src/host/Linux/db_memory.c, common/src/string/atoi.c, common/src/string/strlen.c
This is in preparation to enable UBSan (and Clang at the same time, because Clang's checks are much stronger).
See commit messages.
Note that these are just bugfixes in existing code. I will submit UBSan integration (and Jenkins configuration) in next PR.
The current tests should ensure there are no regressions. I also ran this code on a [draft branch](https://github.com/oscarlab/graphene/pull/2653) and it passes UBSan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2657)
=> Prepare for UBSan and Clang

Pal/src/host/Linux-SGX/db_streams.c, Pal/src/host/Linux-SGX/sgx_process.c
Following issues are addressed 
1)  Dynamic memory stored in 'application_path' allocated through function 'malloc' at line 161 can be lost at line 199 in 
graphene/Pal/src/host/Linux-SGX/sgx_process.c | sgx_init_child_process()
2) Dynamic memory stored in 'd1' allocated through function '_DkStreamSecureSave' at line 139 can be  lost at line 153 in  
graphene/Pal/src/host/Linux-SGX/db_streams.c | handle_serialize()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2658)
=> [Pal/Linux-SGX] Fix memory leak issues flagged by Klocwork

Documentation/manifest-syntax.rst, LibOS/shim/src/fs/shim_fs.c, LibOS/shim/src/fs/shim_fs_mem.c, LibOS/shim/src/shim_init.c, LibOS/shim/src/sys/shim_brk.c, Pal/include/pal_internal.h, Pal/src/host/Linux-SGX/db_main.c, Pal/src/host/Linux-SGX/db_misc.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/enclave_pf.c, Pal/src/host/Linux-SGX/sgx_main.c, common/include/api.h, common/src/string/atoi.c, common/src/string/toml_utils.c
And additionally remove some now-outdated warnings.
Try putting invalid entries in the manifest and check if/how parsing fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2659)
=> Stricten manifest size-str parsing

Pal/src/host/Linux-SGX/db_process.c, Pal/src/host/Linux-SGX/enclave_framework.c, Pal/src/host/Linux-SGX/pal_linux.h, Pal/src/host/Linux-SGX/protected-files/protected_files.c, common/include/api.h, common/include/crypto.h, common/src/crypto/adapters/mbedtls_adapter.c
Previously, Graphene bound the identity of the peer enclave to the SHA256 hash of generated session key -- `SHA256(K_e)` during Diffie-Hellman key exchange and SGX local attestation. However, the standard ISO KE protocol (after which we model our Graphene protocol) uses DH public keys instead of the session key -- `SIG_B(g_x, g_y, A)` and `SIG_A(g_y, g_x, B)` (notice the reversed order -- this is to deflect interleaving attacks). 
This PR changes Graphene's protocol implementation to more closely follow the ISO KE protocol.
This PR also adds more documentation on Graphene's protocol details.
UPDATE: Added memory scrubbing and reverse order in the SHA256 hashes to conform to the ISO KE protocol. Rebased as I need to change the commit message as well.
All tests must pass. You can manually …
=> [Pal/Linux-SGX] Perform `SHA256(g_x || g_y)` for SGX local attestation

Pal/src/host/Linux-SGX/protected-files/protected_files_format.h
Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>
We need a more generic protected file ID than the old `GRAPH_PF`. Note that protected files that were created before this change will become unusable.
The protected file system tests should work (The protected files that were created before this change will cease to work and are unusable).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2677)
=> Update File ID in header/metadata to GRAFS_PF

LibOS/shim/src/fs/shim_namei.c
Opening a directory with `O_CREAT` should fail with `-EISDIR` instead of success.
Fixes #2550.
Follow the steps to reproduce mentioned in issue #2550.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2671)
=> [LibOS] Return -EISDIR on opening a directory with O_CREAT flag
