LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/native/manifest.template
LibOS/shim/test/native/unix.c

I found that shim_do_bind has a bug.
When it is a local socket(AF_UNIX),
it just returned with success but it did not correctly handle remaining things.
I check that it worked with MySQL.

fix local socket bind bug

---

Pal/src/host/Linux-SGX/db_memory.c

Latest commit #3cf3bd2 commented out memset in _DkVirtualMemoryAlloc, not sure why, but this leaves Graphene hanging infinitely on our SGX machine..

Bugfix to prevent infinite hanging.

---

Pal/src/host/Linux-SGX/sgx-driver/graphene-sgx.h

When I check out tag sgx_driver_1.8 of the intel driver, the current master branch doesn't build properly.
This fix builds with sgx_driver_1.7, sgx_driver_1.8, and sgx_driver_1.9 for me.

Fix the build for linux driver 1.8

---

LibOS/shim/src/syscallas.S

This code generates a SIGSEGV when user's code executes a syscall with a negative index (such syscall is invalid, but shouldn't cause a SIGSEGV).

Fix signess bug in the syscall dispatcher

---

.travis.yml
Pal/src/host/Linux-SGX/debugger/sgx_gdb.c
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_enclave.h

This adds a proper definition of __assert to the SGX urts, as well as extends the travis job to always test that DEBUG=1 variants at least build - I hope catching this sort of issue in the future.

Fix assert for SGX=1 and DEBUG=1 (Issue #97)

---

Pal/src/host/Linux-SGX/pal_linux.h

Fix off-by-one error in __hex2str()

---

LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/test/apps/ltp/manifest.template
LibOS/shim/test/regression/30_mmap.py
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/mmap-file.c

A bugfix for issue #80. The migration is not complete when a file-backed VMA is larger than the file size, but the file size is not page-aligned. In Linux, if the file size is smaller than the mapped memory, accessing the remaining memory that is not backed by the file will trigger a SIGBUS. However, it is fine to access the remaining memory within the last page that still overlaps with the file, and won't trigger a SIGBUS. This area is commonly used in ELF binary to store uninitialized, static variables. To improve fork latency, Graphene chooses to truncate the migration size as the file size, but missed the memory which belongs to the last file-backed page. The migration size should be aligned up to the page size.

A bugfix for issue #80 (os.fork() sigfaults in Python)

---

LibOS/glibc-2.19.patch
LibOS/shim/include/shim_ipc.h
LibOS/shim/src/fs/shim_fs.c
LibOS/shim/src/ipc/shim_ipc_child.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_sandbox.c
LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/apps/ltp/PASSED
LibOS/shim/test/apps/ltp/manifest.template
LibOS/shim/test/native/tcp.c
Pal/lib/api.h
Pal/lib/graphene/config.c
Pal/src/db_main.c
Pal/src/host/FreeBSD/db_sockets.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux/db_sockets.c
Pal/src/pal_defs.h
Pal/src/security/Linux/manifest.c
Pal/src/slab.c
Scripts/regression.py

- Fix a severe bug caused by merging #87. The patch does not check the return values from get_config_entries_size(), while the return values can easily be negative (-PAL_ERROR_INVAL). Any usage of this function should carefully check the return values and also pass the size into get_config_entries() to prevent buffer overflow.
- Fix a minor bug in handling IPC disconnection. The callback ipc_child_exit() never receives a "term_signal" parameter. The callback is called when the pipe to a child process unexpectedly terminates, which can only mean the child process has crashed. I believe the proper signal to send is SIGKILL.
- Remove a compilation warning caused by type mismatch of __malloc().
**[Notice!]** Adding three bugfixes:
- Fixing socket implementation to accept ANY address (e.g., …

[Urgent!!] Bugs caused by merging #87

---

LibOS/shim/include/shim_checkpoint.h
LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_vma.h
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/ipc/shim_ipc_child.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_malloc.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_mmap.c
LibOS/shim/test/apps/ltp/FLAKY
LibOS/shim/test/apps/ltp/PASSED
Pal/src/host/Linux-SGX/db_memory.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_pages.c
Pal/src/pal.h
Pal/src/slab.c

Small fixups:
* Replaced `alloca` with `malloc` for potentially large buffers in `enclave_framework.c` (partially fixes #173).
* Many minor code readability improvements (e.g. removed a `while` loop implemented using `goto`...).
* Fixed int overflow in `calloc`.
* Fixed a few resource leaks (including two unreleased locks).
* Added `__attribute__((unused))` to a variable used in an ifdefed code to remove a compiler warning.
* Removed `print_vma_hash`, this function looks like it never worked (it doesn't even print anything?).
* Fixed many typos.

Fixes for the allocator/VMA code

---

LibOS/shim/src/elf/shim_rtld.c

The ubiquitous segfault in apache seems to be that the elf header goes away after a while, causing a segfault on checkpoint (for fork).  I suspect this may be related to #95 , as a lot of the elf code is set to PROT_NONE, and we may need to unset this parameter.
In particular, l_soname ends up pointing to inaccessible memory.
I am not sure this really fixes the root issue, but it does at least get apache running again on the non-SGX build.  I'd welcome any input on a better way to fix this.

Fix segfault in apache

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-SGX
LibOS/shim/test/apps/bash/.gitignore
LibOS/shim/test/apps/bash/Makefile
LibOS/shim/test/apps/bash/bash.manifest.template
LibOS/shim/test/apps/bash/cat.manifest.template
LibOS/shim/test/apps/bash/cp.manifest.template
LibOS/shim/test/apps/bash/date.manifest.template
LibOS/shim/test/apps/bash/ls.manifest.template

This PR fixes configuration errors when running Bash on SGX.

Fix manifests for Bash

---

Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/pal_linux.h
Pal/test/File.c
Pal/test/manifest.template

The PR includes a new option named "sgx.allow_file_creation", which is disabled by default. By turning on this option, users could allow the application to create the files which are not in trusted and allowed file lists. After the file is created, following open/read/write are allowed.

A manifest option allowing applications to create files which are not in trusted/allowed file lists

---

LibOS/shim/include/shim_table.h
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_sched.c
LibOS/shim/test/apps/ltp/PASSED
Pal/regression/00_Bootstrap.py
Pal/regression/Bootstrap.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux/db_main.c

This PR implements the missing sched_getaffinity system call at the library OS level. It also fixes some bugs in the Linux and SGX PAL for retrieving CPU information.

Implement sched_getaffinity system call

---

LibOS/shim/include/shim_signal.h

This seems like a pretty clear error in this definition.  I am not sure what a good unit test for the fix is, but I don't see a lot of downside to correcting this, and at least one user reported that this created problems.

Correct definition of bits per word, as reported in #196.

---

LibOS/shim/include/shim_profile.h

When compiling the SHIM folder with `PROFILING=1`, the compilation failed because shim_atomic.h is replaced with atomic.h.

Fixing the profiling feature in LibOS

---

Pal/src/host/FreeBSD/db_pipes.c
Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux/db_pipes.c

In some code paths, the pipe.nonblocking field is not initialized, which can lead to obvious problems after memory has been recycled for a bit.
It is not clear to me if there is an easy unit test, other than perhaps in a debugging mode with memory poisoning enabled.  I think this is a bit beyond the scope of this simple PR.

Apply the fix suggested for uninitialized pipe non-blocking (#219)

---

index.md

Adding this index.md file that just contains a meta refresh tag to forward people to the graphene project page on the main website.
Remove this when replacing with an actual website..

Create index.md with a redirect

---

README.md

Through a few users' feedback, current section of building Graphene-SGX is not quite intuitive and lack of  details instructions about how to run examples so the users can test Graphene-SGX is correctly installed. This PR reorganizing the flows and adding instructions of running built-in examples.

Update README by reorganize the section of building Graphene-SGX

---

LibOS/Makefile
LibOS/glibc-no-pie.patch

This PR addresses the issue reported by #117.
GCC 5 makes -fPIC and -pie the default options. Building GLIBC 2.19 with GCC 5/6/7/8 triggers the following compilation failure:
```
/usr/bin/ld: graphene/LibOS/glibc-build/csu/crt1.o: relocation R_X86_64_32S against symbol `__libc_csu_fini' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbegin.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[3]: *** [graphene/LibOS/glibc-build/iconv/iconvconfig] Error 1
make[2]: *** [iconv/others] Error 2
make[1]: *** [all] Error 2
```
This PR adds a GLIBC patch that detects …

 Addressing GLIBC building issue with GCC 5/6/7/8

---

LibOS/Makefile
LibOS/shim/Makefile
LibOS/shim/src/Makefile
LibOS/shim/test/benchmark/Makefile
LibOS/shim/test/inline/Makefile
LibOS/shim/test/native/Makefile
LibOS/shim/test/regression/Makefile
Pal/regression/Makefile
Pal/src/Makefile
Pal/src/Makefile.Host
Pal/test/Makefile

On Linux Desktop, ```gcc -dumpmachine``` will return ```x86_64-xxx-linux-gnu``` instead of ```x86_64-linux-gnu```.
OS: Ubuntu Desktop 16.04
gcc version: 5.3.0
```gcc -dumpmachine``` returns ```x86_64-unknown-linux-gnu```
OS: Ubuntu Server 16.04
gcc version: 5.4.0
```gcc -dumpmachine``` returns ```x86_64-linux-gnu```
OS: Manjaro Linux
gcc version: 5.5.0
```gcc -dumpmachine``` returns ```x86_64-pc-linux-gnu```

gcc -dumpmachine returns x86_64-xxx-linux-gnu

---

Pal/src/host/Linux-SGX/sgx_framework.c

a left shift operator applys on a literal number 1 cause overflow
so unsigned long long type suffix should be appended to that literal
that makes it has same type as xfrm and xfrm for safety
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/251)

No suffix to integer literals cause overflow

---

Pal/src/host/FreeBSD/db_streams.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux/db_streams.c

In the Pal source files
Pal/src/host/FreeBSD/db_streams.c:292
Pal/src/host/Linux-SGX/db_streams.c:282
Pal/src/host/Linux/db_streams.c:295
1)	The struct hdl_hdr is defined as local variable
2)	The ‘fds’ member of struct hdl_hdr is used without Initialization
3)	The pointer to struct hdl_hdr is assigned to iov[0]
4)	The iov is assigned to struct hdr as hdr.msg_iov
5)	Do syscall with struct hdr as one of parameters
The bug may cause the unexpected result from syscall.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/247)

Uninitialized hdl_hdr.fds bugfixes (#246)

---

LibOS/shim/test/apps/ltp/FLAKY
LibOS/shim/test/apps/ltp/PASSED

It has been flaky, and should not have gone back into CI without pretty exhaustive testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/263)

Take waitpid03 (back) out of CI. 

---

LibOS/shim/test/apps/ltp/PASSED

This LTP has been on the FLAKY list for some time.  It was erroneously added back to the PASSED list because it was believed to have been fixed by some unrelated changes.  It did not.
This test should only be reenabled after a credible bugfix and running in a loop to trigger whatever underlying heisenbug there is here.
This is causing #258 not to pass CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/266)

Take out futex_wait03, again

---

Pal/src/host/FreeBSD/db_ipc.c
Pal/src/host/Linux-SGX/db_ipc.c
Pal/src/host/Linux/db_ipc.c
Pal/src/host/Skeleton/db_ipc.c
Pal/src/pal_internal.h

In reviewing #257, it became clear that this function's definition is not consistent between headers and implementation.  Changing to a uint64_t.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/268)

Normalize this function's definition.

---

Pal/src/security/Linux/main.c

The Macro IS_ERR should not be used to test the result value of address type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/260)

Fix an error test on the result of mmap syscall

---

Pal/regression/00_Bootstrap.py
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux/db_main.c

This PR addresses the issues reported in  #165 .
It ensures that passing a binary or manifest that does not exist returns a sensible error message, and adds a PAL unit test for this case.
It also ensures that specifying a binary by manifest (at least with the .manifest.sgx extension on the SGX PAL) actually works.  This is somewhat complicated by the fact that the binary may be different than the manifest base name, and that it is ok to just preload libraries with no executable at all.  In the first case, we give loader.exec_uri precedence over inferring the binary from the manifest.  In the second case, we preserve the loading behavior as before with no executable, but add a warning that this is probably an error (unless you are @chiache :) ).
--- …

Fix various exec file specification issues

---

Pal/src/host/Linux-SGX/Makefile

This is for consistency and more robust make.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/328)

Linux-SGX: Makefile to use $(MAKE), not "make" command directly

---

LibOS/Makefile
README.md

This is a small patch taken from #237. The official glibc website occasionally failed and we need multiple mirrors to make sure the users can download glibc source code robustly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/279)

Adding multiple mirrors for downloading glibc

---

Pal/src/host/Linux-SGX/sgx_framework.c
Pal/src/host/Linux-SGX/sgx_internal.h
Pal/src/host/Linux-SGX/sgx_main.c

When the Intel SGX driver is not loaded, the SGX PAL shows the following warning message:
```
cannot open device /dev/gsgx, possibly the kernel module is not loaded.
```
This warning message is confusing because the Graphene-SGX driver is actually loaded. This PR fixes the code to show the proper warning messages. In addition, the PR also adds a warning message for the check for WRFSBASE instruction availability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/272)

Improving the warning messages in SGX PAL

---

Pal/src/host/FreeBSD/db_main.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux/db_main.c

Currently to get the number of cpus (logic cores), graphene uses cpuid with leaf 4 and extracts the values from EAX[26:31]. However, the number is not the correct value of cpu logic cores.  
According to SDM, "Bits 31 - 26: **Maximum number of addressable IDs for processor cores** in the physical package". The maximum number of addressable IDs for processor cores (not logic cores) is not necessarily equal to the number of logic cores the machine has. In practice, it often returns 8 on the platforms with 4 cores or 12 cores. So far at least causing the regression tests failed. 
To fix, we should use cpuid with leaf 0xb and subleaf 1, and extract the values from EBX[0:15] In SDM, this means "Bits 15 - 00: **Number of logical processors** at this level type." Subleaf 1 represents the number …

Using leaf 0xb and subleaf 1 to get the correct cpu (logic core) number

---

Pal/regression/06_AvxDisable.py
Pal/regression/AvxDisable.c
Pal/regression/AvxDisable.manifest.template
Pal/regression/Makefile
Pal/src/host/Linux-SGX/db_exception.c
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

By default, Graphene-SGX always enables AVX when generating XFRM attribute in SECS. There is no option to disable it. However, on some Intel platforms such as Intel NUC with SGX2 supported, AVX is not available, which causes the enclave creation failure raised up by the SGX driver. 
This PR adds an option named "sgx.disable_avx" to allow user to disable AVX in XFRM in manifest file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/218)

Adding a manifest option to allow graphene-sgx to run on non-avx platforms

---

Pal/src/host/FreeBSD/db_exception.c
Pal/src/host/FreeBSD/db_exception2.c
Pal/src/host/Linux-SGX/db_exception.c

Since save_return_point isn't used, so remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/413)

[Pal] remove unused save_return_point macro

---

Pal/src/host/Linux-SGX/sgx_main.c

In sgx_main.c, SGX_SECINFO_FLAGS_R is defined. which is unnecessary.
The constant is defined in sgx_arch.h.
It looks like accidental.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/421)

[Pal/Linux-SGX] remove duplicated unused def of SGX_SECINFO_FLAGS_R

---

LibOS/shim/src/sys/shim_sched.c

- [X ] Library OS (i.e., SHIM), including GLIBC
[LibOS] Add a check to sched_getaffinity that the user_mask_ptr is a valid user address.  Return -EFAULT if not, per the manual.  
This will make LTP test sched_getaffinity01,5 pass reliably.
--- …

[LibOS] Add a check to sched_getaffinity that user_mask_ptr valid

---

LibOS/Makefile

Now glibc patches are updated, glibc won't be re-build.
This patch adds patches and Makefile as dependencies of glibc so that
when patches or Makefile are updated, glibc will be re-build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/300)

LibOS/Makefile: improve handling of glibc patches

---

Runtime/Makefile

Since clean rule is first target, just "make" means "make clean" as default goal.
This is a surprise. usually "make" means "make all".
So move all rule to the first target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/366)

Runtime/Makefile: all goal should be default

---

LibOS/shim/src/ipc/shim_ipc.c

There is unnecessary unlock/lock causing a race. remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/312)

lookup_and_alloc_client(): race condition

---

Pal/lib/api.h
Pal/src/host/FreeBSD/db_threading.c
Pal/src/host/Linux/db_threading.c

It should be "& ~15", not "& ~16" to align to 16 bytes.
It seems typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/320)

Pal/Linux, FreeBSD: ~15 instead of ~16 for child stack alignment

---

LibOS/shim/include/shim_types.h

From Linux 4.18.0, it's defined int uapi/time.h.
This patch makes it compile with Linux 4.18.0 or later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/313)

shim_types.h: __kernel_timespec, __kernel_itimerspec

---

LibOS/shim/include/shim_ipc.h
LibOS/shim/include/shim_utils.h
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/sys/shim_exit.c

put_thread(self) to free resources by itself is problematic because
the exiting thread is still using them.
Actually put_thread(self) logic in ipc/async helper may cause SEGV
depending on who is the last to put_thread().
If the thread is the last one to free thread area, lock/unlock after
freeing thread area causes segv due to debug message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/321)

LibOS/ipc, async helper: keep refcount to helper thread on exit

---

Pal/src/host/Linux-SGX/Makefile.Test

define SGX_SIGNER_KEY only when not defined so that user can define
SGX_SIGNER_KEY as error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/327)

Linux-SGX/Makefile.Test: define SGX_SIGNER_KEY only when not defined

---

Pal/src/host/Skeleton/db_devices.c
Pal/src/host/Skeleton/db_files.c
Pal/src/host/Skeleton/db_pipes.c
Pal/src/host/Skeleton/db_process.c
Pal/src/host/Skeleton/db_rtld.c
Pal/src/host/Skeleton/db_sockets.c

After the PR that fixes the skeleton build on OS X, I realized that, at least on Ubuntu 14.04, it still doesn't compile.  So this PR fixes those errors and warnings (at least from 'make' in the Skeleton directory).
All of these issues amount to the signature not matching pal_internal.h, except for one bad include.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/355)

Compilation and warning fixes for the PAL Skeleton on Linux

---

Pal/src/pal_internal.h

- [X ] Common PAL code
Add a reference to the PAL-internal open() function explaining where the possible argument values for access, share, create, and options are defined.  Explicating that the arguments will be passed through from DkStreamOpen.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/460)

[Doc] Minor documentation fix

---

LibOS/shim/src/fs/shim_dcache.c
LibOS/shim/src/fs/shim_namei.c

Fixes #157 
Fixed incorrect reference counting in LibOS/fs
Standard test suite.
Define `DEBUG_REF` to see refcounts in debug output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/459)

[LibOS] Fix ref counting in path lookup/dcache

---

LibOS/shim/src/sys/shim_clone.c

The final initialization of child thread of clone is done by
clone_implementation_wrapper(). Until the initialization completes,
child shim_thread shouldn't be exposed to other thread.
Otherwise other thread can access uninitialized shim_thread.
For example, other thread tries to send signal to that thread by
walking thread_list and access uninitialized member of shim_thread.
Defer add_thread() until initialization is complete.
- Other styling issues may be …

[LibOS] clone shouldn't expose child thread until its init

---

LibOS/glibc-2.19/syscalldb.h

Linux x86 syscall convention clobbers %rcx and %r11.
%rcx can be used instead of %rbx without save/restore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/337)

glibc: optimize SYSCALLDB

---

LibOS/shim/src/syscallas.S

Now syscalldb in normal path on return include jmp.
jmp can be eliminated and penalize error path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/338)

glibc: optimize syscalldb for normal path

---

LibOS/Makefile

Keep Success.build file by .SECONDARY instead of .INTERMEDIATE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/341)

shim/Makefile: don't build glibc unnecessarily

---

LibOS/shim/src/syscallas.S

libsysdb.so is complied as pic so GOT should be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/345)

LibOS: syscallas.S should use GOTPCREL call instead of absolute call

---

LibOS/glibc-2.19/syscalldb.h

For trivial system call, sysdeps/unix/syscall-template.S is used to generate
system call stub functions. which ignores redzone.
Teach it redzone.
Also use %rcx instead of %rbx without pushq/popq as %rcx is clobbered
register as system call abi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/342)

LibOS/glibc: syscall-template.S ignores redzone

---

LibOS/shim/src/shim_async.c

use after free issue, after tmp is freed, rv = tmp->expire_time - install_time is trying to access the member expire_time of release tmp buffer
[482631]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/356)

[LibOS] Fix use-after-free in install_async_event()

---

LibOS/shim/include/shim_internal.h

Variable  n is used without initilization.
If if (!DkObjectsWaitAny(1, &e->event, NO_TIMEOUT)) condition is true,
then code will skip the assignment of n with n = DkStreamRead(e->event, 0, 1, &byte, NULL, 0);
and might finish the while loop. n should be properly initialized to prevent potenical undefined behavior
[482723]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/358)

[LibOS] Fix an uninitialized value n in wait_event

---

LibOS/shim/src/bookkeep/shim_handle.c

get_new_handle_map will return a pointer for new_map, which could be NULL after examing the implementation of get_new_handle_map function.
In this case, accessing new_map->fd_top will cause undefined behavior. We need to add a check for new_map before accessing its member.
if the code error out and function return the error, allocated new_map is not freed, causing potencial information leakage
[482567]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/359)

[LibOS] Fix the storage leaks pointed by new_map in case of malloc fails to fd_new

---

LibOS/shim/test/native/manifest.template

PR #215 removed file `exec_victim.c` under `test/native`. However, there were still some residual references to this non-existent file in the `manifest`, which broke the build. This PR removes these residual references.
Note: this only affects the build of SGX PAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/391)

[Build] Remove residual references to nonexistent exec_victim

---

Pal/src/host/FreeBSD/db_main.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux/db_main.c

Fixes a bug which was exposed by #464 (which changed the heap layout slightly). Strings in PAL_CPU_INFO were not null-terminated, but (un)luckily before #464 there were always zeros after the allocations, so the bug hasn't got exposed.
```Bash
cd Pal/regression
../../Runtime/pal_loader ./Bootstrap
```
This should output `CPU vendor` and `CPU brand` without any garbage appended, even after modifying the initial heap layout with some additional allocations (e.g. by merging this branch with #464).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/465)

Null-terminate PAL_CPU_INFO strings

---

LibOS/shim/src/fs/shim_fs.c

ret is declared without initialization. It depends on (ret = (*walk) (mount, arg) for the initial assignment;
however, the list might be NULL and the assignment can not be performed leaving ret in un-initialized state.
Thus ret should be properly initialized in this case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/354)

[LibOS] Don't use uninitialized return value in walk_mounts()

---

Pal/src/host/Linux-SGX/enclave_entry.S

For consistency, add operation suffix in enclave_entry.S
.S files in other graphene code use operation suffix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/394)

[Pal/Linux-SGX] add operation suffix in enclave_entry.S

---

Pal/src/host/Linux-SGX/sgx_entry.S

For consistency, add operation suffix in sgx_entry.S
Other .S files in graphene use operation suffix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/395)

[Pal/Linux-SGX] add operation suffix in sgx_entry.S

---

Pal/src/host/FreeBSD/db_exception.c
Pal/src/host/FreeBSD/db_exception2.c
Pal/src/host/Linux-SGX/db_exception.c
Pal/src/host/Linux/db_exception.c

_DkGenericEventTrigger isn't used by other .o files.
So make it static.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/340)

Pal/host: static'fy _DkGenericEventTrigger

---

LibOS/shim/src/elf/shim_rtld.c

new_phdr is allocated with malloc, if seek file or read file failed, the function will goto call_lose that will return NULL.
However, before returning NULL, there is no check inside call_lose to check if new_phdr was allocated successfully or not,
causing potencial resource leakage of new_phdr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/353)

[LibOS] Fix a memory leak in __map_elf_object() about variable pointer new_phdr

---

LibOS/shim/src/sys/shim_exec.c

new_shargs used without initialization, could cause undefined behaviors as its contents are passed to other variables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/361)

[LibOS] Fix uninitialized value new_shargs.first

---

LibOS/shim/src/elf/shim_rtld.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/369)

[LibOS] Variable len is used without initilization

---

LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_pipe.c

remove abuse of __alloca() with normal variable on stack.
This patch cleans up abuse of __alloca().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/399)

[LibOS] remove unnecessary __alloca()

---

Pal/src/db_rtld.c

cached_file is a PAL_HANDLE, which in the case of out will be released by _DkObjectClose(cached_file).
In the normal case, before returning &obj->map, this resource allocated within the function should
also be released to prevent it leaking out side of the function scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/401)

[PAL] Fix the missing of closing the cached_file

---

LibOS/shim/src/sys/shim_poll.c

polls was constructed by nfds, with last index as nfds - 1. When calling __do_poll, nfds was passed as a parameter and used as index to refer polls as npolls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/351)

[LibOS] Improve the for condition expression to avoid dereference

---

LibOS/shim/src/Makefile

they are missed on "make clean" somehow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/363)

shim/src/Makefile: remove build files(libsyscalldb.*) on make clean

---

Jenkinsfiles/ubuntu-16.04.dockerfile

The dockerfile instruction RUN will create new layers
when it is executed, original codes will increase the size of
the final image and causes potential cache issues.
So we need to employ shell tricks to keep the layers as small as possible.
Like #307.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/373)

Jenkinsfiles: Optimize the docker file for ubuntu

---

Pal/src/host/FreeBSD/db_process.c
Pal/src/host/Linux-SGX/sgx_process.c
Pal/src/host/Linux/db_process.c

As dup2() system call closes target file descriptor, close() right
before dup2() doesn't make sense. or worse, it opens a window for race
condition.
So remove close() right before dup2()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/375)

Pal/{Linux, Linux-SGX, FreeBSD}: remove close() right before dup2()

---

Pal/src/host/Linux/db_exception.c

action.sa_flags will only be initialized in the truth branch, while in the false branch,
only sa_handler is initialized. Before action.sa_flags |= SA_NOCLDWAIT,
action.sa_flags should be properly initialized (in this case 0x0u)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/402)

[PAL] Fix uninitialized field action.sa_flags

---

Pal/src/host/Linux-SGX/sgx_exception.c

In case of SIGFPE in host, 0 is passed as event_num.
it should be PAL_EVENT_DIVZERO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/407)

[Pal/Linux-SGX] calculate event_num correctly for SIGFPE

---

LibOS/shim/src/fs/proc/info.c

The type for /proc/cpuinfo and /proc/meminfo should be a regular file, not a directory.  This addresses issue #308 (xgboost doesn't work in python).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/408)

Set the correct file type (regular file) for /proc/cpuinfo 

---

Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/security/Linux/main.c

There is no point to map manifest file as writable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/409)

Pal/Linux-SGX: map manifest file as read only

---

Pal/src/host/Linux-SGX/sgx_tls.h

grp and thread member of struct enclave_tls is actually typed.
So use correct type for them instead of void *.
Also the use of void * to hide implementation is poor and not
type-safe. The right way is to hide the definition of struct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/415)

[Pal/Linux-SGX] use type for enclave_tls instead of void*

---

Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/sgx_enclave.c

`ocall_table[]` array contains function pointers to untrusted OCALL functions (which actually issue syscalls).
Previously, this array was `void* ocall_table`, i.e., function pointers were type-casted to `void*`.
This PR changes the type of entries to a proper function signature `int (*sgx_ocall_fn_t)(void*)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/417)

[Pal/Linux-SGX] Use proper sgx_ocall_* function signature for ocall_table

---

LibOS/shim/src/elf/shim_rtld.c

As x86-64 unix ABI, %rdx on user program entry is a function pointer
which is registered as atexit. It should be zeroed unless LibOS needs
it. Otherwise random %rdx as function pointer is called by atexit and
can result in error. typically SEGV.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/425)

[LibOS] zero %rdx on entry of user program

---

Pal/src/db_streams.c
Pal/src/host/FreeBSD/db_devices.c
Pal/src/host/FreeBSD/db_pipes.c
Pal/src/host/FreeBSD/db_sockets.c
Pal/src/host/Linux-SGX/db_devices.c
Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux/db_devices.c
Pal/src/host/Linux/db_pipes.c
Pal/src/host/Linux/db_sockets.c
Pal/src/host/Skeleton/db_devices.c
Pal/src/host/Skeleton/db_pipes.c
Pal/src/host/Skeleton/db_sockets.c

Fixes  #463.
See  #463.
Please verify that I patched all relevant places which depend on those functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/464)

Fix parse_stream_uri and parse_device_uri semantics

---

LibOS/shim/include/shim_handle.h
LibOS/shim/include/shim_table.h
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_futex.c

Futex word is int, not unsigned int.
So it should use int * instead of unsigned int *.
Also add fallthrough directive for lint to eliminate warning.
I believe fallthrough of switch clause is intentional, not bug.
just run any tests which uses futex. LibOS/shim/test/native/futextest.pthread.c
--- …

[LibOS] fix futex signature

---

Pal/src/host/Linux-SGX/sgx_framework.c

ECREATE does not require SECS.{mrsigner, mrenclave} to be initialized. SECS.mrenclave is computed dynamically and SECS.mrsigner is populated based on the SIGSTRUCT during EINIT ([see pp21 for ECREATE and pp34 for EINIT](https://software.intel.com/sites/default/files/managed/48/88/329298-002.pdf).
Graphene-SGX should just continue to work after the change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/470)

Leave SECS.{mrenclave, mrsigner} uninitialized prior to ECREATE.

---

LibOS/shim/src/shim_async.c

before DkThreadExit(), allocated resource local_objects were not freed, causing resource leakage of local_objects content
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/360)

[LibOS] Fix the storage of local_objects leaks in shim_async_helper

---

LibOS/shim/src/sys/shim_futex.c

No need to check NO_TIMEOUT twice when FUTEX_WAIT_BITSET.
No need to check NO_TIMEOUT twice when FUTEX_WAIT_BITSET, so remove duplicate codes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/478)

[LibOS] shim_futex.c:Remove duplicate codes in FUTEX_WAIT_BITSET

---

Tools/gsce

The dockerfile instruction RUN will create new layers
when it is executed, original codes will increase the size of
the final image and causes potential cache issues.
So we need to employ shell tricks to keep the layers as small as possible.
The detail:
https://docs.docker.com/v17.09/engine/userguide/eng-image/dockerfile_best-practices
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/307)

Clean up and optimize the integration of docker container and graphene-SGX

---

LibOS/shim/src/shim_async.c

Fix dereferencing the 'tmp' after it is released issue and some code style issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/368)

[LibOS] Fix dereferencing variable after it is released.

---

LibOS/shim/src/sys/shim_stat.c

This issue may cause SegFault if pass null to state,
and miss the validation by test_user_memory(...) if not null.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/259)

Fix null test and write test issues about the stat parameter

---

.dir-locals.el

Add a single, project-level emacs style configuration.
There is absolutely no reason not to have a style file for the project so that emacs will do the right thing.
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/491)

Dir locals file for emacs

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-Debug

The Jenkins test that runs Python on Linux PAL does not have a timeout (see job hang 189).  This test needs a timeout in case things go wrong.
Just run a normal Jenkins job.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/479)

Put a timeout on the Python test.

---

Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Fix typos.
One typo only affects a debug message. The other two are field names which aren't used (But are covered by the SGX tests anyway).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/500)

[Pal/Linux-SGX] Fix "encalve" typos

---

LibOS/shim/src/bookkeep/shim_signal.c
Pal/regression/01_Exception.py
Pal/regression/Exception.c
Pal/src/db_exception.c
Pal/src/host/FreeBSD/db_exception.c
Pal/src/host/FreeBSD/db_exception2.c
Pal/src/host/Linux-SGX/db_exception.c
Pal/src/host/Linux-SGX/sgx_exception.c
Pal/src/host/Linux/db_exception.c
Pal/src/pal.h
Pal/test/Exception.c

Fixes #480.
See #480.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/490)

[PAL] Rename PAL_EVENT_DIVZERO to PAL_EVENT_ARITHMETIC_ERROR

---

Pal/src/host/FreeBSD/db_memory.c
Pal/src/host/Linux-SGX/db_memory.c
Pal/src/host/Linux/db_memory.c

Remove misleading or old comments in `_DkVirtualMemoryAlloc`. See commit messages for details.
That the mapping in Linux/FreeBSD is usually shared and not private as the comment suggested is fine, tight?
Only doc change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/502)

Remove old/misleading comments in _DkVirtualMemoryAlloc

---

Pal/src/host/Linux-SGX/enclave_ocalls.c

OCALL_EXIT should never return. But the outside might try to trick the enclave, so add an infinite loop to ocall_exit to catch this.
This is probably exploitable but I didn't spend time to analyze which of the current usages was actually exploitable.
AFAICS it's hard to add a test which simulates a malicious host with the current code. So no test case provided. If you want to play with it you can change `sgx_ocall_exit` in `sgx_enclave.c`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/522)

[Pal/Linux-SGX] Ensure that ocall_exit never returns

---

README.md

The variable with the path to the enclave siging key is called SGX_SIGNER_KEY not SGX_ENCLAVE_KEY.
Fix the README.
Only doc change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/499)

[README] Fix enclave siging key variable name

---

Pal/regression/02_Memory.py

This is an alternative to PR #503. It just documents the reason why those tests will fail.
Doc only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/521)

[Pal/regression] Document why memory permission/dealloc test fail on SGX

---

Pal/regression/02_Memory.py
Scripts/regression.py

There are different reasons why a regression test failure should be ignored, so rename the option to avoid confusion if the test isn't flaky. See #503 for initial discussion.
Also move the output to the same line as the 'Fail' message.
Run the PAL regression tests and see improved output (currently only really relevant on SGX).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/520)

[Scripts/regression] Rename 'flaky' to 'ignore_failure'

---

Pal/regression/03_Process.py
Pal/regression/Process.c

If the broadcast stream is not opened this most likely means that
there's no configured multicast route so add a helpful warning. Also no
point in trying to read/write from/to a non-existent stream.
Resolves #501.
Run PAL regression tests with and without a configured multicast route.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/507)

[Pal/regression] Handle unopened broadcast stream

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/sgx_main.c

The pal_sec struct has fields with enclave information (mrenclave,
mrsigner, enclave_attributes). Their initialization had two problems:
- mrenclave and mrsigner were read from the enclave_secs struct, but
those field were never populated so they were always zeroed bytes.
This broke the fork detection in db_process.c.
- The enclave trusted the data initialized by pal_loader (i.e. outside
the enclave). This is a problem for example when used to check for
forks in db_process.c (Part of #509).
Fix this by reading those values from a self report early inside the
enclave.
This fixes a bunch of regression tests which before failed since creating processes based on the same manifest were broken (since the MRENCLAVE was zeroed).
--- …

[Pal/Linux-SGX] Initialize enclave info in pal_sec inside enclave

---

Pal/src/host/FreeBSD/db_rtld.c
Pal/src/host/FreeBSD/pal.map
Pal/src/host/FreeBSD/pal_security.h
Pal/src/host/Linux/db_rtld.c
Pal/src/host/Linux/pal.map
Pal/src/host/Linux/pal_security.h
Pal/src/host/Skeleton/pal.map
Pal/src/pal.h
Pal/src/security/Linux/pal-sec.map

_r_debug symbol is interface for for debugger, like gdb, to understand
how dynamic loading is happening. So it's not used by dependent
library or executable. So there is no point to put _r_debug into GLIBC
version space for export. Put it into its own version (PAL_PRIVATE).
Then, the next patch will reduce glibc modification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/293)

Pal: re-version _r_debug from GLIBC to PAL to reduce glibc patch

---

LibOS/shim/src/shim_checkpoint.c

On EINTR/EAGAIN of DkStreaRead/DkStreamWrite, retry the PAL call
instead of error out.
Especially when it runs under debugger, EINTR often happens.
This patch makes debug easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/314)

LibOS/shim/src/shim_checkpoint.c: retry DkStreamRead/DkStreamWrite

---

LibOS/shim/include/shim_tls.h
LibOS/shim/src/.gitignore
LibOS/shim/src/Makefile
LibOS/shim/src/asm-offsets.c
LibOS/shim/src/syscallas.S
Makefile.rules

Auto generate offset constants for assembly.
replace magic number with symbolic constants in
LibOS/shim/src/syscallas.S.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/344)

LibOS: asm offset generation

---

.gitignore
LibOS/shim/src/Makefile
Pal/src/Makefile
Pal/src/host/FreeBSD/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux/Makefile
Pal/src/security/Linux/Makefile

For prepossessed file, .i for .c and .s for .S are commonly used.
not .e.
This patch adds rules to produce .i/.s file in addition to .e.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/329)

Makefile: add targets for .i and .s

---

LibOS/shim/src/Makefile
LibOS/shim/src/shim.lds
Pal/src/host/Linux-SGX/Makefile.am
Pal/src/host/Linux-SGX/enclave.lds

For consistency use ENTRY(shim_start) in linker script, not command
line option of -e shim_start.
This also helps to understand how link is done. only shim.lds needs
to be read. don't have to dig into Makefile for command line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/339)

shim/Makefile: don't use -e for ld, but use ENTRY in linker script

---

Pal/src/db_rtld.c
Pal/src/pal_internal.h

This patch remove unnecessary goto in db_rtld.c.
At the same time pal errno is adjusted as wrong (posigive) error no
is passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/371)

PAL/db_rtld.c: remove unnecessary goto

---

LibOS/shim/include/shim_tls.h
LibOS/shim/src/utils/printf.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/420)

[LibOS] use struct debug_buf instead of void * in shim_tcb_t

---

Pal/src/host/Linux-SGX/enclave_entry.S

On sgx entry, there is a window where %rsp is not setup to trusted
area yet. If async event(host signal) arrives during that window,
stack is setup wrongly to untrusted area
This patch closes that window so that stack within enclave is setup
correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/526)

[Pal/Linux-SGX] enclave_entry.S: close window where %rsp is invalid

---

LibOS/glibc-2.19.patch

This patch reduces glibc modification of __libc_r_debug rename.
There is no need to rename _r_debug to __libc_r_debug.
Or am I missing something
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/294)

glibc-2.19.patch: reduce __libc_r_debug hack

---

Pal/src/security/Linux/Makefile
Pal/src/security/Linux/internal.h

Now pal-Linux isn't created in Pal/src any more.
Adjust its directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/411)

[Pal/Linux/security] adjust pal loader directory

---

Pal/src/host/Linux-SGX/db_exception.c
Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/pal_linux_defs.h
Pal/src/host/Linux-SGX/sgx_arch.h
Pal/src/host/Linux-SGX/sgx_entry.S
Pal/src/host/Linux-SGX/sgx_exception.c
Pal/src/host/Linux-SGX/sgx_internal.h

SGX_HAS_FSGSBASE has been hardcoded to 1 since the beginning.
Also the Intel SDM doesn't mention that the FS/GS handling in SGX can be
unavailable on some hardware.
So just drop it.
Closes #545.
SGX regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/553)

[Pal/Linux-SGX] Drop unused SGX_HAS_FSGSBASE flag

---

Pal/src/host/Linux-SGX/db_misc.c

> db_misc.c: In function _DkRandomBitsRead:
> db_misc.c:64:26: warning: this statement may fall through [-Wimplicit-fallthrough=]
>                      rand >>= 16;
>                      ~~~~~^~~~~~
> db_misc.c:65:17: note: here
>                  case 1:
>                  ^~~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/558)

[Pal/Linux-SGX] db_misc.c warning

---

LibOS/shim/include/shim_fs.h
LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/sys/shim_msgget.c
LibOS/shim/test/regression/30_futex.py
LibOS/shim/test/regression/30_mmap.py
LibOS/shim/test/regression/90_large-mmap.py
Pal/regression/00_Atomics.py
Pal/regression/05_Process.py
Pal/regression/06_AvxDisable.py
Pal/src/db_streams.c
Pal/src/pal.h

I noticed some of the unit tests are not checking and propagating the unit test return codes, so Jenkins will ignore failures.  This fixes that issue, except for the reference monitor tests, which is a whole other thing.
Regular Jenkins tests suffice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/533)

Ensure unit tests actually return a failure message

---

LibOS/shim/test/regression/epoll_wait_timeout.c

LibOS: Add missed exception handler and remove unused variable
Goto libos/shim/test/regression
make regression
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/540)

LibOS: Add error handling and remove unused variable in epoll_wait regression test

---

LibOS/shim/src/fs/shim_namei.c
LibOS/shim/test/regression/40_proc_path.py
LibOS/shim/test/regression/proc-path.c
LibOS/shim/test/regression/proc-path.manifest.template

If input absolute path, it will get wrong my_dent.
This issue looks like a typo, missing parentheses after the "else".
If input absolute path, it will get wrong value of my_dent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/477)

[LibOS] shim_namei.c: Fix input absolute path error

---

LibOS/shim/src/bookkeep/shim_signal.c

this patch cleans up shim_signal.c without logic change.
- remove unnecessary goto
In this file, goto is abused unnecessarily.
- remove unnecessary macro
Two macros, is_internal, internal_fault can be inline function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/302)

LibOS: code clean up of shim_signal.c

---

LibOS/shim/include/shim_checkpoint.h
LibOS/shim/include/shim_internal.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/fs/shim_dcache.c
LibOS/shim/src/fs/shim_fs.c
LibOS/shim/src/ipc/shim_ipc_nsimpl.h
LibOS/shim/src/ipc/shim_ipc_sysv.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_debug.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_malloc.c
LibOS/shim/src/shim_parser.c
LibOS/shim/src/shim_random.c
LibOS/shim/src/sys/shim_brk.c
LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/src/sys/shim_msgget.c

This patch adds printf format check and fixes most of found issues.
ADD_CP_ENTRY was given up due to type issue.
It requires to change function signature. So I didn't address it at
this time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/380)

LibOS: add check printf format

---

Pal/lib/stdlib/printfmt.c

Adds `%i` support to printf (Alias of `%d`).
Use "%i" with `printf` & co. Since there are no tests for printf I didn't implemented a test for this simple change. I you think there should be tests for printf I can add some.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/537)

[Pal] Add %i support to printf

---

Pal/src/host/Linux-SGX/debugger/sgx_gdb.c

warning of implicit declaration of syscall/pread/pwrite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/557)

[Pal/Linux-SGX] warning

---

LibOS/glibc-2.19/syscalldb.h

indirect call of memory value is usable. So we don't have to
load pointer value for callq.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/546)

[LibOS] glibc-2.19/syscalldb.h: use callq indirect call with memory

---

LibOS/shim/src/syscallas.S

libsysdb.so is compiled as pic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/547)

LibOS/syscallas.S: shim_table should be referenced through GOT

---

Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Using hashlib.sha256 directly produces the same result, makes the code
easier to review and significantly faster.
Run SGX regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/572)

[Pal/Linux-SGX] Drop hashlib wrapper in pal-sgx-sign

---

Jenkinsfiles/Linux-SGX

This enables the PAL regression tests for SGX. This PR depends on PR #511. See also #498 (the other issues/PRs linked there won't lead to hard failures).
Run it on Jenkins. I did not test it myself since I don't have a Jenkins setup handy at the moment. But the change is pretty trivial so this is low risk and easy to revert or fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/518)

[Jenkins] Enable PAL regression tests on Linux-SGX

---

Pal/src/host/FreeBSD/db_memory.c
Pal/src/host/Linux-SGX/db_memory.c
Pal/src/host/Linux/db_memory.c
Pal/src/host/Skeleton/db_memory.c
Pal/src/pal_internal.h

- Changed `size` parameter type of `_DkCheckMemoryMappable` from `int` to `uint64_t` to enable using large memory chunks (`int` overflowed).
Run regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/608)

[Pal] Use size_t instead of int for size parameter

---

LibOS/shim/src/start.S

callq can take memory address directly.
it's unnecesary to load the address to register.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/586)

[LibOS] start.S: remove unnecessary movq

---

Scripts/regression.py

[Scripts/regression] Treat timeouts as failure
Modify a regression test to output the expected text but never terminate. This should be treated as test failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/610)

[Scripts/regression] Treat timeouts as failure

---

LibOS/shim/src/asm-offsets.c
Pal/include/pal/asm-offsets-build.h
Pal/src/asm-offsets-build.h
Pal/src/host/Linux-SGX/.gitignore
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/asm-offsets.c
Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/sgx_arch.h
Pal/src/host/Linux-SGX/sgx_entry.S
Pal/src/host/Linux-SGX/sgx_tls.h

This patch auto-generates asm offsets for Pal/Linux-SGX and uses them.
Also to share the generation logic among Pal and LibOS, header file for
it is created under Pal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/551)

[Pal/Linux-SGX] generate asm offsets and use them

---

Pal/src/host/FreeBSD/pal.map
Pal/src/host/Linux/pal.map
Pal/src/host/Skeleton/pal.map
Pal/src/security/Linux/pal-sec.map

dynamic symbol of _dl_debug_state is interface for debugger. Not
for depdent library or executable. So there is no point to put in
GLIBC version. this patch put _dl_debug_status symbol to PAL_PRIVATE.
So that the next patch eliminates rename in glibc. _dl_debug_status
-> __libc_dl_debug_status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/295)

Pal: make _dl_debug_status versioned to PAL_PRIVATE not  GLIBC

---

LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/fs/shim_namei.c
LibOS/shim/src/sys/shim_open.c
LibOS/shim/test/regression/30_getdents.py
LibOS/shim/test/regression/getdents.c
LibOS/shim/test/regression/getdents.manifest.template

- Properly set `shim_dentry.type` field in all cases (fixes incorrect `d_type` field in directory enumeration).
- Added standalone regression test for `getdents` syscall since the LTP one fails (`symlink` is unimplemented).
- Run the regression test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/569)

[LibOS] Properly set shim_dentry.type

---

Pal/src/host/Linux-SGX/asm-offsets.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_memory.c
Pal/src/host/Linux-SGX/db_threading.c
Pal/src/host/Linux-SGX/enclave_ecalls.c
Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/sgx_api.h
Pal/src/host/Linux-SGX/sgx_tls.h

This PR contains a bunch of fixes/hardening/cleanup around the enclave entry code. See single commits for details.
This admittedly breaks the "Address a single problem" rule. I didn't split it up yet, since it affects mostly the same code part and some changes depend on each other. So it's probably easier to review in one go. If you like it split up, please tell me which parts you would like to have separated.  
Those changes are hard to write tests for, see #543 for some ideas.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/544)

Misc enclave entry improvements

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/pal_security.h
Pal/src/host/Linux-SGX/sgx_main.c

Don't get PAL load address and name from urts. Part of issue #509.
Should I also drop `enclave_addr` and `enclave_image` from the `pal_sec` struct, since they are now effectively unused? I'm in favor of doing so, but I'm not sure since `pal_sec` is used both as argument passing from urts to enclave as well as global PAL state.
Run SGX regression test to see that it doesn't break things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/577)

[Pal/Linux-SGX] Don't get PAL load address and name from urts

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/pal_security.h
Pal/src/host/Linux-SGX/sgx_main.c

exec_fd and manifest_fd were already mostly unused. Drop them to make it
more obvious that they are never used to read the executable or
manifest from the urts.
Part of issue #509.
Run SGX regression tests to see that it doesn't break things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/582)

[Pal/Linux-SGX] Drop effectively unused manifest/exec fd

---

LibOS/shim/src/utils/printf.c

When debug buf reached to the end, it should be reset to the start after
output.
This can happen with string longer than 255.
debug_printf("%s",
"string-without-newline-longer-than-debug_buf-DEBUGBUF_SIZE=255"...);
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/585)

[LibOS] debug_fputch buffer overflow

---

Pal/src/db_main.c

When pal hit error in config file, show the file name for user.
Sometimes it's difficult to identify corresponding config file
when fork/exec are involved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/615)

[Pal] show file name on config file error

---

LibOS/shim/test/regression/30_mmap.py
Pal/regression/00_Atomics.py
Pal/regression/00_Bootstrap.py
Pal/regression/02_Memory.py
Pal/regression/04_Ipc.py
Pal/regression/06_AvxDisable.py

[*/regression] Use uniform and cleaner SGX environment check
As suggested by @yamahata in PR #612.
Run Pal/shim regression tests. SGX detection should still work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/616)

[*/regression] Use uniform and cleaner SGX environment check

---

Pal/src/host/Linux-SGX/signer/pal-sgx-sign

The current logic tries to retrieve mrenclave from target executable.
It should get it from .sig.
LibOS/shim/test/native/exec_fork
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/613)

[Pal/Linux-SGX] signer should retrieve mrenclave from .sig

---

LibOS/shim/src/sys/shim_getpid.c

Not the address to set tid on thread creation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/581)

[LibOS] set_tid_address() sets the address to clear tid on thread exit

---

Pal/src/host/Linux-SGX/sgx_exception.c
Pal/src/host/Linux/db_exception.c

In file Pal/src/host/Linux-SGX/sgx_main.c:88:
` action.sa_restorer = restore_rt; `
restore_rt is a function written in assembly which is assigned as the location after signal handler returns. Ideally, this code will be compiled into assembly like this:
`lea    -0x165(%rip),%rax        # 0x5577c22000e0 <restore_rt>`
However, on centos, the compiler for some reason, generated code like this:
`mov    -0x165(%rip),%rax        # 0x5577c22000e0 <restore_rt>`
This leads the semantic fundamentally different, causing segmentation fault at runtime. The potential reason could be the compiler with different configuration has different understanding about assigning "assembly function" to C-based structures.
The PR fixes this issue by explicitly wrapping the assembly with a C-based function.
---
This …

Rewriting the code which potentially generates incorrect assembly for signal handler returns

---

LibOS/shim/test/native/exec_fork.manifest.template
LibOS/shim/test/native/script.manifest.template

tcp reads tcp.c. this patch also adds it to manifest.template to make tcp work.
LibOS/shim/test/native/{exec_fork, script, tcp}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/614)

[LibOS/test/native] add manifest template to make exec_fork, script work

---

Pal/src/host/Linux-SGX/Makefile.Test

Makefile.Test unnecessarily recreates .manifest.sgx of
commented sgx.trusted_children because it processes commented
lines in .manifest.sgx.
Teach Makefile.Test to skip commented out lines. in .manifest.sgx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/607)

[Pal/Linux-SGX] Makefile.Test processes comment out lines

---

LibOS/shim/src/sys/shim_socket.c

struct un_conn isn't used anywhere. So remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/599)

[LibOS] remove unused struct un_conn in shim_socket.c

---

LibOS/glibc-2.19.patch

_dl_debug_state has hidden visibility. So there is no afraid to be
used mixed by Pal. So we can remove the modification to glibc
_dl_debug_state -> __libc_dl_debug_state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/296)

glibc-2.19.patch: remove _dl_debug_state rename

---

README.md

Our current readme isn't clear about support@ being publicly archived. This PR tries to fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/628)

Clarify in the readme that support@ is publicly archived

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_thread.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/shim_malloc.c
LibOS/shim/src/sys/shim_exit.c
LibOS/shim/src/utils/printf.c
LibOS/shim/src/utils/strobjs.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/603)

[LibOS] use static inline function instead of cpp macro

---

Pal/src/host/Linux-SGX/db_exception.c

Set PAL_ERRNO to PAL_ERROR_INTERRUPTED when interrupted by host signal.
Current Linux-SGX PAL signal handling unwinds all inner PAL frames if host signal interrupts Graphene while it waits on a long syscall. Because PAL frames are unwound, all inner logic of PAL setting `PAL_ERRNO = PAL_ERROR_INTERRUPTED` (using the `_DkRaiseFailure()` flow) is skipped. This PR retrofits this logic.
This particular bug was found in `LibOS/shim/test/apps/lmbench/lmbench-2.5/bin/linux/bw_tcp` test under SGX.
Execute the test case `TCP socket bandwidth` of lmbench under Linux-SGX PAL. If manually:
```sh
lmbench-2.5/bin/linux$ SGX=1 ./pal_loader ./bw_tcp -s  # start server in one window
lmbench-2.5/bin/linux$ SGX=1 ./pal_loader ./bw_tcp 127.0.0.1  # start client in another window
lmbench-2.5/bin/linux$ SGX=1 …
```

[Pal/Linux-SGX] Set PAL_ERRNO to PAL_ERROR_INTERRUPTED

---

Pal/src/host/Linux-SGX/sgx_process.c

This PR forces untrusted SGX PAL to propagate untrusted environment variables to untrusted child process.
Propagating untrusted environment variables to the child process does not harm security of enclaves. This propagation is required for e.g. debugging multi-process applications and for network proxy settings.
Note that trusted environment variables are correctly passed from parent enclave to child enclave using the checkpoint/restore protocol.
Debug any multi-process process with GDB and check environment variables of the child inferior:
```sh
inferior 2
show environment
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/631)

[Pal/Linux-SGX] Propagate untrusted environment variables to untrusted child process

---

Pal/src/host/Linux/db_files.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/pal_host.h

When fork emulation, the first exec file must be mapped to the
same address of the parent process.
If ASLR is enabled, the address can be different from the parent
without address specified. Then forked process can result in SEGV.
Pass the address for exec file to be mapped from parent process
to the child process. and use that address.
At the same time, file handle isn't initialized fully in
pal_linux_main(), so is initialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/372)

Pal/Linux: specify loaded address of exec in child process

---

Pal/lib/api.h
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/ecall_types.h
Pal/src/host/Linux-SGX/enclave_ecalls.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/pal_linux_defs.h
Pal/src/host/Linux-SGX/sgx_api.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_enclave.h
Pal/src/host/Linux-SGX/sgx_main.c

With this change we check all parameters from the urts which we can
verify (This is only true if the other PR we depend on are merged, see
code comments).
We can't verify some parameters like our 'uid' or 'manifest_name'. Here
we have to take the value the urts has passed to us and need to be
careful wherever we use them.
To keep the verification code simple we change the 'arguments' and
'environments' parameters from argv style arrays with pointers to
strings to a continuous NUL-delimited string.
TODO: Needs fix for enclave range check from PR #544!
Run SGX regression test to see that it doesn't break things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/590)

[Pal/Linux-SGX] Check ECALL_ENCLAVE_START parameters

---

LibOS/Makefile
LibOS/buildglibc.py
LibOS/shim/src/Makefile
Makefile.rules
Pal/src/Makefile

Currently cp to Runtime dir is used. Sometimes it is confusing when
binary re-build under Pal or LibOS. So symlink is better. Use symlink
instead of cp to populate Runtime dir.
This patch create ln_sf rule and use it instead of cp. and applies to
other recipe with cp.
In this context, creating symlink of glibc libraries is mess. this
patch also cleans it up to use Makefile instead of embedding the logic
into python script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/367)

Makefile: Use symlink instead of cp to populate Runtime dir

---

Pal/src/host/Linux-SGX/sgx_thread.c

Add more user friendly message when the number of thread is
too small for user program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/552)

[Pal/Linux-SGX] more friendly message when thread is lacking

---

Scripts/regression.py

[Scripts/regression] Improved subprocess handling
This fixes two problems with subprocess handling:
1. Use subprocess.communicate to avoid that the pipe can fill up.
2. Use a process group to ensure that we also kill the subprocess'
children in case of a timeout.
Note: This does not cover the case that the child returns successfully
but leaves other child processes running. AFAICS this is not easy since
subprocess.communicate() wait(2)s for the process so the pid is no
longer guaranteed to be valid to kill. So we leave this to the outside
environment (Jenkins or whatever).
Run regression tests. To test the timeout case set it manually to something too small.
--- …

[Scripts/regression] Improved subprocess handling

---

Pal/regression/02_Thread.py
Pal/regression/Thread2.c
Pal/regression/Thread2.manifest.template
Pal/src/host/Linux/clone-x86_64.S

See commit messages. This replaces PR #611.
Run the regression test. For me without the fix it hangs on 'Linux', but you need PR #610 to reliable notice this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/612)

[Pal] Test thread cleanup and fix it for 'Linux'

---

.dir-locals.el

For Makefile, tab is needed.
For .S file, tab is used. (one exception is shim/src/syscall.S. other .S uses tab)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/617)

[.dir-locals.el] add makefile-mode and asm-mode

---

Pal/src/host/Linux-SGX/db_devices.c
Pal/src/host/Linux-SGX/db_events.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_misc.c
Pal/src/host/Linux-SGX/db_mutex.c
Pal/src/host/Linux-SGX/db_object.c
Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux-SGX/db_process.c
Pal/src/host/Linux-SGX/db_rtld.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux-SGX/db_threading.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/pal_linux_error.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_process.c

Fixes #515.
This patch makes ocall return value to linux errno instead of pal errno.
As the side effect, _DkEventWaitTimeout() is fixed so that it returns
timeout. https://github.com/oscarlab/graphene/pull/438
_DkEventWaitTimeout() of Pal/Linux-SGX doesn't return. ETIMEDOUT and
ETRAYAGAIN are different meaing for futex(WAIT). but unix_to_pal_error()
combines into PAL_ERROR_TRYAGAIN. futex ocall doesn't provide enough info.
So make ocall return unix error number and have the callers of ocall
convert unix errno into pal errno.
--- …

[Pal/Linux-SGX] make ocall return linux errno instead of pal errno.

---

LibOS/shim/test/apps/ltp/Makefile

The version of automake used by ltp and the one in host doesn't
necessarily match. If they don't, the following error shows up for
make to fail.
issue aclocal and automake for such cases.
> configure.ac:4: error: version mismatch.  This is Automake 1.15.1,
> configure.ac:4: but the definition used by this AM_INIT_AUTOMAKE
> configure.ac:4: comes from Automake 1.15.  You should recreate
> configure.ac:4: aclocal.m4 with aclocal and run automake again.
> Makefile:78: recipe for target 'm4/Makefile.in' failed
--- …

[LibOS] ltp automake version doesn't always match

---

Pal/src/host/Linux-SGX/enclave_ocalls.c

Fixes #442.
In Pal/src/host/Linux/SGX/encalve_ocalls.c, the ocall_sock_recv and
ocall_sock_send will copy the respective buffer arguments to the
untrusted host process by adjusing the stack.  In the case of
ocall_sock_recv, this occurs in the line
ms->ms_buf = ALLOC_IN_USER(buf, count);
and in the case of ocall_sock_send, the line
ms->ms_buf = COPY_TO_USER(buf, count);
Note that both ALLOC_IN_USER and COPY_TO_USER will eventually call
enclave_framework.c's sgx_ocalloc function, which adjusts the stack.
The problem, of course, is that if if the buffer is too big, the stack
will overflow.
The fix is to apply the same check that ocall_read and ocall_write do;
that is, if the buffer to be allocated is too large to fit on the stack,
call ocall_alloc_untursted to allocate som untrusted heap …

bugfix: ocall_sock_send and ocall_sock_recv can overflow stack.

---

Pal/src/host/Linux-SGX/asm-offsets.c
Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/sgx_arch.h

[Pal/Linux-SGX] Clear "extented state" (FPU regs & co) before EEXIT
They could contain sensitive information.
Run regression tests to see that it doesn't break things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/626)

[Pal/Linux-SGX] Clear "extented state" (FPU regs & co) before EEXIT

---

LibOS/shim/src/.gitignore
LibOS/shim/src/generated-offsets.c
Makefile.rules
Pal/include/pal/asm-offsets-build.h
Pal/include/pal/generated-offsets-build.h
Pal/regression/03_Process.py
Pal/src/generated-offsets-build.h
Pal/src/host/Linux-SGX/.gitignore
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Before this change some important memory areas, for example tcs and tls
were not measured. With this change all mapped enclave memory is
measured.
Closes #505.
In the current form this has the downside that it slows down enclave startup a lot. For very quick applications like the regression tests this is quite bad. I will take a look if measuring all pages with one syscall like in the old graphene kernel driver helps. Otherwise an option would be to not measure the heap but instead zero it directly after enclave startup (also not tested yet if or how much this helps).
Run SGX regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/573)

[Pal/Linux-SGX] Measure all memory

---

LibOS/shim/include/shim_thread.h
LibOS/shim/include/shim_utils.h
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_exec.c

x86-64 ABI requires 16bytes alignment of stack on calling
function.
To conform the ABI, align stack on starting entry point
of the application binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/299)

LibOS: 16bytes align of stack on starting user binary

---

Pal/regression/02_Event.py
Pal/regression/Event.c

This adds a regression test for the timeout handling when waiting for events. PR #438 fixes waiting with a timeout.
See above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/519)

[Pal/regression] Test timeout handling when waiting for events

---

LibOS/shim/test/regression/Makefile
Pal/regression/00_Bootstrap.py
Pal/regression/02_Misc.py
Pal/regression/Makefile

On weaker machines (Intel NUCs and SGX-enabled laptops), SGX regression tests take longer than 5 seconds because Graphene measures/zeroes all enclave memory at startup. Increase the timeout for SGX regression tests to 20 sec.
Regression tests should not fail with timeout on weak machines when running `make SGX_RUN=1 regression`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/649)

[*/regression] Increase timeout of regression tests

---

LibOS/shim/src/sys/shim_clone.c

Some runtime uses clone(CLONE_VFORK | CLONE_VM | SIGCHLD) for vfork().
emulate clone(CLONE_VFORK | CLONE_VM | SIGCHLD) as vfork().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/645)

[LibOS] emulate clone(CLONE_VFORK | CLONE_VM | SIGCHLD) as vfork()

---

LibOS/shim/src/sys/shim_sleep.c
LibOS/shim/test/native/pause.c
Pal/src/host/FreeBSD/db_threading.c
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux/db_threading.c

error of DkDelayExecution call should be checked by PAL_NATIVE_ERRNO.
not return value. and pause return value is always EINTR. not 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/565)

[LibOS] pause() exits without waiting

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/pal_security.h
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_tls.h
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Don't get manifest addr/size from urts.
Instead we use the fact that the manifest is always placed at the top of
the enclave address range. The manifest size is stored inside the TLS
like we have already done for the enclave size.
Part of issue #509.
Depends on PR #573 to make sense.
Run SGX regression test to see that it doesn't break things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/580)

[Pal/Linux-SGX] Don't get manifest addr/size from urts

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_tls.h
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Don't get exec addr/size from urts.
Instead pass them through the measured TLS.
Part of issue #509.
This depends on #573 (but is based on master to make the reviewable.io diff more useful).
I will cleanup the argument handling of `pal_linux_main` in a separate PR, which will also remove the TOCTOU bug which this change has, because is uses `sec_info`.
Run regression tests to see that it doesn't break things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/588)

[Pal/Linux-SGX] Don't get exec addr/size from urts

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_tls.h
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Don't get heap min/max from urts
Instead pass them through the measured TLS.
Part of issue #509.
This depends on #573 (but is based on master to make the reviewable.io diff more useful).
I will cleanup the argument handling of `pal_linux_main` in a separate PR, which will also remove the TOCTOU bug which this change has, because is uses `sec_info`.
Run SGX regression tests to see that it doesn't break things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/589)

[Pal/Linux-SGX] Don't get heap min/max from urts

---

LibOS/shim/src/elf/shim_rtld.c
Pal/lib/atomic.h
Pal/src/db_rtld.c
Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux/db_misc.c

initialize rflags on function entry where necessary according to sysv x86-64 abi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/643)

initialize rflags according to sysv x86-64 abi

---

LibOS/shim/src/fs/proc/fs.c
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/test/regression/40_proc.py
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/proc.c

In the old dcache code, readdir and opendir worked "by accident".  The dcache rewrite now requires an open method.  This broke /proc.  The changes in this PR fix /proc.
Unit test included (adapted from native directory).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/497)

Fix readdir on /proc

---

Pal/regression/AtomicMath.c
Pal/regression/Bootstrap.c
Pal/regression/Exception.c
Pal/regression/File.c
Pal/regression/Ipc.c
Pal/regression/Memory.c
Pal/regression/Misc.c
Pal/regression/Semaphore.c
Pal/regression/Thread.c
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_framework.c
Pal/src/host/Linux-SGX/sgx_thread.c
Pal/src/pal_debug.h
Pal/test/Cpuid.c
Pal/test/Exception.c
Pal/test/Fork.c
Pal/test/Process.c
Pal/test/Tcp.c
Pal/test/Udp.c

Add __attribute__((formapt(printf))) check to pal_printf and
fix found format error.
No need test as this patch because It's tested by compiler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/430)

[Pal/Linux-SGX] add format check to pal_printf and fix format error

---

Pal/src/host/Linux-SGX/db_exception.c
Pal/src/host/Linux-SGX/sgx_enclave.c

remove abuse of __alloca() with normal stack variable.
This patch cleans up abuse of __alloca().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/398)

[Pal/Linux-SGX] remove unnecessary __alloca()

---

Pal/src/Makefile.Test
Pal/src/host/Linux-SGX/Makefile.Test

Use := to get the directory in which Makefile lives.
Otherwise the directory will be the directly which lastly included.
Not the current one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/656)

[Pal] Makefile.Test use := to get directory

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/sgx_api.h

OCALL security hardening:
- Time-Of-Check-To-Time-Of-Use (TOCTOU) vulnerability is closed by first copying untrusted values inside enclave and then operating on these copied values; see COPY_FROM_USER
- Pointer/integer overflow is closed by comparing against a trusted maximum value in COPY_FROM_USER
- Untrusted stack overflows during OCALLOC/ALLOC_IN_USER/COPY_TO_USER are closed by checking for NULL return values
These vulnerabilities were independently discovered and disclosed by David Oswald, Jo van Bulck, and others.
Fixes #549.
All regression tests should run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/622)

[Pal/Linux-SGX] OCALL security hardening

---

LibOS/shim/src/sys/shim_poll.c

Fixes #389.
The function shim_do_poll has an error on the line that reads:
fds[i].revents |= (fds[i].events & (POLLERR|POLLHUP));
Per the manpage, POLLERR and POLLUP are returned in `revents` and
ingnored in `events`.  Indeed, programs hsould not be setting, and
typically don't set -- `events` with these values.
The effect of this bug is, among others, that a process will never get a
disconnect evetn fro a peer socket.
Change shim_do_poll to obey POSIX semantics with regard to returning POLLERR and POLLUP regardless of whether the descriptor had them set as events.
--- …

bugfix: shim_do_poll incorrectly setting revents wrt POLLERR and POLLHUP

---

Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/sgx_exception.c

The enclave is set as TCS.nssa = 2, one for page fault for host OS,
one for host signal to bounce into enclave. .Lhandle_exception assumes
that TCS.cssa == 1. uRTS can maliciously inject async signal
nestedly. In that case, it should fall into fail loop because the code
assumption was broken. Mask host async signal(SIGINT, SIGTERM and
SIGCONT) on signal.
TCS.nssa = 2 is enough because even if we set TCS.nssa = N > 2 and
allow nested async host signal. But if it nested up to
TCS.cssa = N - 1, the situation is same.
Please remember that .Lhandle_exception is called in signal context to
set up the actual exception handler with specified signal masked and
returns back from signal handler to normal execution. And then the
actual exception handler in enclave is triggered as normal execution …

[Pal/Linux-SGX] disallow nested async host exception in enclave_entry

---

LibOS/shim/include/shim_table.h
LibOS/shim/include/shim_utils.h
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/generated-offsets.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/start.S
LibOS/shim/src/sys/shim_exit.c
LibOS/shim/src/syscallas.S
Pal/src/db_threading.c
Pal/src/host/Linux-SGX/sgx_entry.S
Pal/src/pal.h
Pal/src/security/Linux/main.c
Pal/src/user_start.S

System V AMD64 ABI requires %rsp to be aligned to 16 before calling C functions. This PR fixes (hopefully) all places where this is violated. When doing this, it additionally removes dead code from `shim_init()`.
Fixes #231.
Run standard tests + some binaries which use SSE/AVX.
@smherwig Could you test this patch? (as you had a reproduction sample).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/655)

Align stack to 16 when calling C from asm

---

Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/sgx_graphene.c
Pal/src/host/Linux/db_events.c
Pal/src/host/Linux/db_sockets.c

Some _Dk functions returns positive error code accidentally.
It should return negated error value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/439)

[Pal] return value is -PAL_ERROR_XXX

---

LibOS/shim/test/regression/30_futex.py
LibOS/shim/test/regression/futex-timeout.c

Before PR #554, futex() syscall incorrectly failed if user-supplied timeout expired (also see PR #438). This patch adds test on futex() with timeout.
Run LibOS regression tests and ensure `Futex Timeout Test` succeeds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/650)

[LibOS/regression] Add futex-timeout test

---

Pal/src/host/Linux-SGX/enclave_entry.S

[Pal/Linux-SGX] Fix enclave_entry comment
The comment is only true for EENTER. ERESUME restores the saved state
from the SSA.
Only doc change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/654)

[Pal/Linux-SGX] Fix enclave_entry comment

---

LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/syscallas.S

Linux system call preserves %rflags. So does LibOS.
- add rflags to shim_regs
- save/restore rflags on entry/leaving syscalldb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/660)

[LibOS] preserve %rflags on syscalldb

---

Pal/src/host/Linux-SGX/enclave_entry.S

This is follow up of https://github.com/oscarlab/graphene/pull/643
Clear rflags.DF right before calling C function.
Clear rflags when setting up exception handler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/659)

[Pal/Linux-SGX] cld before calling C function. follow up

---

LibOS/glibc-2.19.patch
LibOS/shim/src/sys/shim_clone.c

[LibOS] make clone ABI match to kernel
Currently child thread ret ip is taken from new child stack.
But it can be get from parent thread context. Such a hack isn't
needed.
Now the modification to clone.S is not needed any more. So remove it.
run the current regression test which uses clone syscall.
LibOS/shim/test/regression/futex tests
--- …

[LibOS] make Libos clone abi same to kernel

---

LibOS/shim/src/fs/proc/info.c
LibOS/shim/test/regression/40_proc_cpuinfo.py
LibOS/shim/test/regression/proc_cpuinfo.c

Some Linux applications will find the substring, ‘cpu cores’ in
/proc/cpuinfo to get the number of CPU cores.  To avoid those
applications to run into some issues, make /proc/cpuinfo format to be
the same as Linux kernel.
Signed-off-by: Biao Lu <biao.lu@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/568)

[LibOS] /proc/cpuinfo format to be same as kernel

---

Pal/src/host/FreeBSD/pal_host.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux/pal_host.h
Pal/src/host/Skeleton/pal_host.h

MAX_FDS is defined as 3, fds[MAX_FDS] is a 3-element array.
While i in for loop looping from 0 to MAX_FDS, will cause out-of-boundry read for generaic.fds which is a 2-element array.
The generic.fds defiend in pal_host.h should be correctly sized to match with both fds[MAX_FDS] and accommodate for the for loop.
Also fixed another out-of-boundary access for pipeprv
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/362)

[PAL] Fix an out of bounds read on generic.fds[]

---

Pal/lib/network/hton.c
Pal/src/pal_rtld.h

Previously, `htonl/htons()` used `BYTE_ORDER` macro which for some reason was set to `BIG_ENDIAN`. This PR fixes this issue by changing to the macro `__BYTE_ORDER` used in the rest of the code and correctly set to `LITTLE_ENDIAN` on x86 machines.
Fixes #677.
Not applicable. Trivial change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/679)

[Pal] Fix htonl/htons() byte-order macro to __BYTE_ORDER

---

LibOS/shim/include/shim_internal.h
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_exit.c
LibOS/shim/test/regression/00_bootstrap.py
LibOS/shim/test/regression/init_fail.c
LibOS/shim/test/regression/init_fail.manifest.template
Pal/src/db_exception.c
Pal/src/slab.c

Return proper process exit code when shim initialization fails (it's currently always 0).
Also fix PAL exit code on abnormal termination.
Fixes #666
The new `init_fail` regression test should pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/676)

[LibOS/PAL] Return proper exit code on abnormal process termination

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_types.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/generated-offsets.c
LibOS/shim/src/syscallas.S

If syscall instruction is trapped by SIGSYS or SIGILL, emulate it
by making it call to syscalldb function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/561)

[LibOS] emulate syscall instruction

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_vma.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/sys/shim_getrlimit.c
LibOS/shim/src/sys/shim_mmap.c
LibOS/shim/test/regression/30_stat.py
LibOS/shim/test/regression/stat_invalid_args.c

Previously, `test_user_memory(addr, size)` and `test_user_string(addr)` failed on Linux-SGX PAL. These two functions are supposed to check if the user-supplied buffer/string are accessible inside LibOS.
The original implementation had only one option: these functions setup a segfault handler to catch memory errors (see `tcb.test_range` and `memfault_upcall()`) and access one byte of each page in the user-supplied buffer/string. If some byte is inaccessible, then an exception is raised which is caught by the segfault handler. The handler checks the faulting address (stored in `siginfo_t.si_addr`) and redirected back to the function (so it …

[LibOS] Support of SGX PAL for test_user_memory/string

---

LibOS/shim/src/sys/shim_exec.c
LibOS/shim/test/regression/00_bootstrap.py
LibOS/shim/test/regression/exec_invalid_args.c

[`execve()`](http://man7.org/linux/man-pages/man2/execve.2.html#ERRORS) syscall must fail with EFAULT when `filename` is a NULL pointer.
This PR adds the check  in `shim_do_execve()` to return EFAULT when `file` argument is NULL. Before this PR, `shim_do_execve()` would call `path_lookupat(NULL, file, ...)` which expects non-NULL `file`. This would lead to segfault.
`cd LibOS/shim/test/native && SGX=1 ./pal_loader ./get_time.m` fails with segfault before this PR. With this PR, the same program runs without errors.
--- …

[LibOS] execve now returns EFAULT on null file 

---

LibOS/shim/include/shim_handle.h
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/src/sys/shim_getrlimit.c

Accept all rlimit resource type to make application happy.
The actual restriction is another story.
from shell ulimit -a etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/670)

[LibOS] accept all rlimit resources for [gs]etrlimit

---

Pal/src/host/FreeBSD/db_process.c
Pal/src/host/Linux/db_process.c

The code that handles the failure of child process creation has been misplaced outside of the scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/404)

[PAL] Fix misplacing the handling code for child process in DkProcessCreate

---

LibOS/shim/include/shim_internal.h
LibOS/shim/src/Makefile
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/shim_object.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_migrate.c
LibOS/shim/src/sys/shim_semget.c
LibOS/shim/src/sys/shim_wait.c

DkObjectsWaitAny can be interurpted and return NULL.
some logics in LibOS aren't aware of such behavior.
Retry DkObjectsWaitAny on such interruption.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/305)

LibOS: retry DkObjectsWaitAny on interrupt

---

LibOS/shim/include/shim_thread.h
LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_exec.c

In shim_tcb_t and struct shim_thread, some void* can be replaced with
shim_tcb_t, __libc_tcb_t and struct shim_thread.
Also update related code to use them instead of void *.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/370)

LibOS: replace void * with shim_tcb_t, __libc_tcb_t, shim_thread

---

Pal/lib/atomic.h

In atomic operand, actual modified memory is already specified as "m" or "+m".
There is no point of "memory" clobber.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/687)

[Pal/Lib] atomic: remove unnecessary "memory" clobber

---

LibOS/shim/test/regression/getdents.c
Pal/src/host/FreeBSD/db_sockets.c
Pal/src/host/Linux-SGX/debugger/sgx_gdb.c
Pal/src/host/Linux/db_sockets.c

remove remaining warning.
My gcc version is
> gcc --version                                                                                         13:23
> gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
Depending on your gcc version, more fix would be needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/688)

remove remaining warnings.

---

LibOS/shim/src/sys/shim_clone.c

It's non-sense to introduce new variable for same one.
Just remove nonsense variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/692)

[LibOS] clone_implementation_wrapper remove nonsense arg

---

LibOS/shim/src/syscallas.S
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/sgx_entry.S

Before, GDB did not know about enclave stack frames when debugging untrusted OCALL functions. This patch bridges untrusted stack to its corresponding enclave stack by utilizing CFI asm directives and setting RBP to point to the first enclave stack frame.
This functionality is only enabled if Graphene-SGX is built with DEBUG flag. Without DEBUG, RBP is cleared to prevent leakage of the address of enclave stack.
This commit also adds some missing CFI directives to .S files (not related to enclave-untrusted stack bridge).
Build `LibOS/shim/test/native/sleep` executable and run under GDB:
```c
$ GDB=1 SGX=1 ./pal_loader sleep
(gdb) b sgx_ocall_sleep
(gdb) r
<... GDB hits breakpoint ...>
(gdb) bt
#0  sgx_ocall_sleep (pms=0x7ffe7d2b4400) at sgx_enclave.c:593
#1  0x000055882286f5b9 in sgx_entry …
```

[Pal/Linux-SGX] Instruct GDB to bridge enclave-untrusted stacks

---

LibOS/shim/include/shim_internal.h
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/syscallas.S

To match Linux syscall abi, make syscall_wrapper preserve %rflags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/683)

[LibOS] preserve rflags by syscall_wrapper

---

Pal/src/host/Linux-SGX/enclave_entry.S

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/696)

[Pal/Linux-SGX] enclave_entry.S fix stack on exception and ocall

---

LibOS/shim/include/shim_table.h
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_mmap.c
LibOS/shim/test/apps/ltp/PASSED

implements mincore system call
ltp includes tests for mincore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/427)

[LibOS] implement mincore() system call

---

LibOS/Makefile
LibOS/glibc-2.19.patch
LibOS/glibc-arch-fork.patch
LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/sys/shim_clone.c

fix shim_do_clone(!CLONE_VM) and use it for fork instead of modifying glibc fork function. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/690)

use clone(!CLONE_VM) for fork instead of modifying glibc

---

LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/sys/shim_sigaction.c
LibOS/shim/test/regression/30_sigaltstack.py
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/sigaltstack.c

sigaltstack doesn't check SS_DISABLE, SS_ONSTACK. this patch teach it
to sigaltstack emulation and test program.
Signal delivery on sigaltstack is another story. This patch only
fixes parameter checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/566)

[LibOS] sigaltstack check SS_DISABLE and SS_ONSTACK wrongly

---

LibOS/shim/src/sys/shim_getcwd.c

getcwd() system call should return string length including
last NUL. off-by-one bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/710)

[LibOS] getcwd() return string length including last NUL

---

LibOS/shim/include/shim_fs.h
LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_types.h
LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/fs/proc/fs.c
LibOS/shim/src/fs/shim_dcache.c
LibOS/shim/src/fs/shim_fs_hash.c
LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/native/manifest.template
LibOS/shim/test/regression/80_unix.py
LibOS/shim/test/regression/unix.c
Pal/src/host/Linux-SGX/sgx_enclave.c

Fixes #390. Closes #593.
Source code in `shim_fs_hash.c` contained an incorrect casting from `uint64_t` to `uint32_t`. While fixing this issue, the whole code of this file was cleaned up (and other files calling its functions).
Additionally, this PR fixes the issue #390 by replacing this incorrect pattern:
```c
data->pipeid = dent->rel_path.hash >> 32;
```
with the new helper-function cast:
```c
data->pipeid = hashtype_to_idtype(dent->rel_path.hash);
```
All tests must succeed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/708)

[LibOS] Cleanup of shim_fs_hash.c and fix of socket's pipeid

---

Pal/src/host/Linux-SGX/ecall_types.h
Pal/src/host/Linux-SGX/enclave_ecalls.c
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_enclave.h
Pal/src/host/Linux-SGX/sgx_main.c

> [ host/Linux-SGX/sgx_main.o ]
> sgx_main.c: In function load_enclave:
> sgx_main.c:673:18: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
>      while (env_i < env_size) {
>                   ^
> cc1: all warnings being treated as errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/723)

[Pal/Linux-SGX] remove sign compare warning with DEBUG=1

---

LibOS/shim/src/syscallas.S
Pal/src/host/Linux-SGX/debugger/sgx_gdb.c
Pal/src/host/Linux-SGX/debugger/sgx_gdb.h
Pal/src/host/Linux-SGX/enclave_entry.S

After merging PR #688, GDB stopped working. It seems to be a legit bug in GDB. To circumvent this bug, I ended up refactoring the whole sgx-gdb plugin. The code is hopefully readable now, and the bug is gone.
Debug any executable. E.g., build `LibOS/shim/test/native/sleep` executable and run under GDB:
```c
$ GDB=1 SGX=1 ./pal_loader sleep
(gdb) b sgx_ocall_sleep
(gdb) r
<... GDB hits breakpoint ...>
(gdb) bt
#0  sgx_ocall_sleep (pms=0x7ffe7d2b4400) at sgx_enclave.c:593
#1  0x000055882286f5b9 in sgx_entry ()    // <-- untrusted world
#2  0x000000000bd8b610 in __morestack ()  // <-- bridge between untrusted and enclave
#3  0x000000000bd87bec in ocall_sleep (microsec=0x0, microsec@entry=0xba54b78) at enclave_ocalls.c:995  // <-- enclave world
#4  0x000000000bd82d59 in …
```

[Pal/Linux-SGX gdb] Cleanup of ptrace-ldpreloaded library

---

LibOS/Makefile

(1) Removing unnecessary dependencies
(2) Need to abort if one of the patches isn't applied properly
(3) Preventing repeated patching and building (fix #725)
(4) Clean up and repatch the GLIBC source when the dependencies are updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/726)

[GLIBC] Fix the Makefile rules for building GLIBC

---

LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/shim_init.c
Pal/src/db_rtld.c

glibc start up routine tries to read AT_RANDOM address and segv.
This patch teaches LibOS AT_RANDOM and initialize 16 bytes area with
random value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/684)

[Pal, LibOS] pass AT_RANDOM

---

LibOS/shim/include/shim_defs.h
LibOS/shim/include/shim_thread.h
LibOS/shim/include/shim_utils.h
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_exec.c
Pal/src/db_rtld.c

Previously, PAL initialized a subset of ELF aux vectors on binary start
and passed them to LibOS. However, LibOS initializes ELF aux vectors on
its own, without consulting PAL's ones. This commit removes the ELF auxv
logic from PAL and simplifies logic in LibOS.
Closes #736 and #738.
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/740)

[Pal, LibOS] Remove passing of ELF aux vectors from PAL to LibOS

---

LibOS/shim/src/fs/shim_fs.c

The mount->cpdata field is not reset to NULL; hence, the checkpoint callback is only called the first time a process forks.
Fixes #595.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/596)

bugfix: fix shim_fs.c's BEGIN_CP_FUNC

---

LibOS/shim/include/shim_vma.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/test/regression/30_getcwd.py
LibOS/shim/test/regression/getcwd.c

Previously the check on correct memory region under Linux-SGX (called is_in_one_vma()) only checked that the whole memory region fits into one VMA. In some cases (e.g. DATA and BSS sections), memory regions can span several adjacent VMAs. This commit refines the check and renames it to is_in_adjacent_vmas(). It also adds a LibOS test.
Fixes #747.
The commit adds a LibOS regression test `getcwd.c`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/748)

[LibOS] Take into account adjacent VMAs on correct-memory check

---

LibOS/shim/include/shim_profile.h
LibOS/shim/src/ipc/shim_ipc.c
LibOS/shim/src/shim_init.c
Pal/lib/atomic.h

atomic_inc + atomic_read isn't atomic.
atomic_add/inc_return is needed for atomicity.
Introduce atomic_add/inc_return and use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/311)

atomic.h: add atomic_inc_return, atomic_add_return

---

LibOS/shim/src/bookkeep/shim_vma.c

code clean up to remove abused goto in shim_vma.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/730)

[LibOS] remove abused goto in shim_vma.c

---

LibOS/shim/test/regression/exec_invalid_args.c

elimiate the following warnings.
> [ exec_invalid_args ]
> exec_invalid_args.c: In function main:
> exec_invalid_args.c:20:25: warning: passing argument 2 of execve from incompatible pointer type [-Wincompatible-pointer-types]
>      r = execve(argv[0], badptr, good_envp);
>                          ^~~~~~
> In file included from exec_invalid_args.c:4:0:
> /usr/include/unistd.h:554:12: note: expected char * const* but argument is of type char *
>  extern int execve (const char *__path, char *const __argv[],
>             ^~~~~~
> exec_invalid_args.c:24:36: warning: passing argument 3 of execve from incompatible pointer type [-Wincompatible-pointer-types]
>      r = execve(argv[0], good_argv, badptr);
>                                     ^~~~~~
> In file included from …

[LibOS] remove warning in exec_invalid_args.c

---

LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/shim_init.c

remove duplicated unused migrated_shim_addr because it's unused.
remove definition of __load_address because it's defined by linker script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/739)

[LibOS] remove duplicaated unused migrated_shim_addr

---

LibOS/shim/include/shim_utils.h
LibOS/shim/src/shim_async.c
LibOS/shim/src/sys/shim_alarm.c

shim_async_helper() has race conditions and unprotected access.
- next_event can be freed by install_async_event() while sleeping with
DkObjectsWaitAny(). So the list should be traversed.
- Currently local object list is allocated as 31 + 1 length.  But event
list can be longer than that. In such case, allocate longer array
dynamically.
- next_event isn't updated on some execution path
- latest_time isn't updated properly,
- removed ugly gotos.
- This patch also removes suspicious optimization with next_event and
dynamically lengthen local_object_list when the list becomes long.
--- …

[LibOS] shim_async clean up

---

LibOS/shim/include/shim_thread.h
LibOS/shim/include/shim_tls.h
LibOS/shim/src/Makefile
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/generated-offsets.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_sigaction.c
LibOS/shim/src/syscallas.S

move shim_tls::{sp, ret_ip, syscall_nr} to shim_regs as clean up.
Those register values are not tls, but register values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/704)

move shim_tls::{sp, ret_ip, syscall_nr} to shim_regs

---

LibOS/shim/test/regression/30_syscall-redirect.py
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/syscall.c

Add a test program which include syscall instruction to test
SIGILL hook logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/414)

[LibOS/test/native] add test program to include syscall instruction

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_utils.h
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/sys/shim_exec.c
Pal/src/db_process.c
Pal/src/db_threading.c

stack trampoline instead of changing stack in the middle of function by switch_stack()
The changing stack with extended assembler in the middle of function is fragile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/648)

stack trampoline instead of switch_stack in the middle of function

---

Pal/src/db_main.c
Pal/src/db_rtld.c
Pal/src/host/FreeBSD/db_threading.c
Pal/src/host/Linux-SGX/db_threading.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_threading.c
Pal/src/host/Linux/pal_linux.h
Pal/src/host/Skeleton/db_threading.c
Pal/src/pal_internal.h
Pal/src/pal_rtld.h

This patch add noreturn to _DkThreadExit/pal_main/start_execution
and minor code adjustment for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/757)

[Pal] add noreturn to _DkThreadExit/pal_main/start_execution

---

LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/sys/shim_brk.c

This PR fixes a few broken integer overflow checks which were introduced in #741. There were basically two problems: signed overflows inside the checks (which are UB) and using `a + b < 0` to check for an overflow (which misses a lot of cases).
Both can be solved using gcc builtins (and this is probably the only way to implement those checks correctly).
Quoting https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html#Integer-Overflow-Builtins:
> These built-in functions promote the first two operands into infinite precision signed type and perform addition on those promoted operands. The result is then cast to the type the third pointer argument points to and stored there. If the stored result is equal to the infinite precision result, the built-in functions return false, …

Fix integer overflow checks

---

LibOS/shim/src/Makefile
Makefile.configs
Pal/lib/Makefile
Pal/src/Makefile
Pal/src/host/FreeBSD/Makefile
Pal/src/host/FreeBSD/Makefile.am
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/Makefile.am
Pal/src/host/Linux/Makefile
Pal/src/host/Linux/Makefile.am
Pal/src/host/Skeleton/Makefile
Pal/src/host/Skeleton/Makefile.am
Pal/src/security/Linux/Makefile

introduce Makefile.configs as single place to allow override
config variables CC, AS, AR and LD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/758)

[Makefile] introduce Makefile.configs for configuration

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-SGX
LibOS/Makefile
Pal/regression/Makefile

Jenkins just does single-process builds; make it go faster with -j.
SGX build doesn't work with parallel builds; fix that too.
make -j
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/700)

Enable parallel make in jenkins, fix parallel make for SGX

---

Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/generated-offsets.c

This patch is a preparation for future modification.
There are subtle area right before eexit for ocall, right after
eenter from ocall where %rsp points to untrusted area.
This patch makes .Lhandle_exception skip those subtle area
so that exception handler, _DkExceptionHandler, doesn't have to
handle it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/640)

[Pal/Linux-SGX] don't interrupt during ocall eexit/eenter

---

Jenkinsfiles/Linux-Debug
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/shim_debug.c

For reasons I do not recall, we were not testing apache in the Debug/Linux build.  Re-enable this test.
This just copies the apache test from the Linux CI job to the Linux-Debug job.
Standard Jenkins run.  Assuming this passes, it should be part of the standard routine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/574)

[Testing/CI] Run apache in the Debug CI job

---

Pal/src/host/Linux/Makefile
Pal/src/host/Linux/Makefile.am

Just a cleanup, nothing really changes (the flag was removed and then re-added in the Makefiles before this PR).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/800)

[PAL/Linux] Clean up -Wsign-compare flags

---

Pal/src/host/FreeBSD/db_streams.c
Pal/src/host/Linux/db_streams.c

On EINTR or ERESTART, it accesses uninitialized header wrongly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/630)

[Pal/{Linux, FreeBSD}] _DkReceiveHandle access uninitialized header

---

LibOS/shim/src/utils/printf.c

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/779)

[LibOS] remove unused struct debugbuf

---

LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_thread.c

rs_running_thread wrongly initialize __libc_tcb_t as shim_tcb.
Correctly initialize __libc_tcb_t.shim_tcb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/771)

[LibOS] make rs_running_thread initialize __libc_tcb_t.shim_tcb

---

Jenkinsfiles/ubuntu-16.04.dockerfile
LibOS/shim/test/regression/00_openmp.py
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/openmp.c
LibOS/shim/test/regression/openmp.manifest.template

Previously, OpenMP apps failed to run under Graphene-SGX because it did
not support raw system calls (used inside of OpenMP lib, in particular
the futex() syscall). Since recently, Graphene-SGX has support for raw
syscall execution. This commit adds a test showing that OpenMP works.
Fixes #567.
This PR adds LibOS regression test `openmp`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/749)

[LibOS/regression] Add OpenMP simple for-loop test

---

LibOS/shim/test/Makefile
LibOS/shim/test/native/Makefile
LibOS/shim/test/regression/00_bootstrap.py
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/bootstrap-c++.cpp
LibOS/shim/test/regression/manifest.template

Fix the Makefile and manifest template in `LibOS/shim/test/native` and `/shim/test/regression` for C++ program. 
Run the test program:
cd LibOS/shim/test/regression
./pal_loader bootstrap-c++` or `./pal_loader SGX bootstreap-c++`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/801)

[LibOS] Support C++ programs in SHIM test directories

---

Pal/src/db_rtld.c

Prior code pushed to the head, but code referencing it iterated in-order, so we add to tail to preserve order. Affects order of `loader.preload` libraries.
Signed-off-by: Alex Merritt <mail@alexmerritt.us>
ELF binaries loaded by Pal are placed into the `loaded_maps` list. Current code pushes new libraries as `link_map` structures to head of list. When one requires in-order traversal of the objects (e.g., coming from `loader.preload` key in the manifest file), one must iterate from the end of the list to maintain order.
This patch pushes new libraries to the tail of `loaded_maps` to preserve the order as specified in `loader.preload` from the manifest file.
Execute all existing tests.
--- …

[Pal] Append ELF binaries to tail of loaded_maps

---

Pal/src/host/FreeBSD/pal_host.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux/pal_host.h

Previously changing MAX_FDS could silently corrupt macros responsible for manipulating handle's flags bitmap, this PR fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/808)

[PAL] Make PAL_HANDLE flags macros MAX_FDS-aware

---

Pal/src/host/Linux-SGX/sgx_main.c

- Better exception handling and freeing of resources
- Better diagnostic messages
- Removing macros TRY and SET_AREA for readability
- Less gotos and more uniform label names
This PR started as a follow-up to #422 and ended up with a significant cleanup of `sgx_main.c`.
Closes #422.
All tests must run as usual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/781)

[Pal/Linux-SGX] Cleanup of sgx_main.c

---

LibOS/shim/include/shim_internal.h
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_parser.c
LibOS/shim/src/utils/printf.c
Pal/lib/api.h
Pal/lib/assert.h
Pal/lib/stdlib/printfmt.c
Pal/regression/Ipc.c
Pal/src/db_exception.c
Pal/src/host/Linux-SGX/db_rtld.c
Pal/src/host/Linux-SGX/sgx_graphene.c
Pal/src/host/Linux-SGX/sgx_internal.h
Pal/src/pal_internal.h
Pal/src/printf.c
Pal/src/security/Linux/internal.h
Pal/src/security/Linux/printf.c
Pal/test/Ipc.c
Pal/test/Pipe.c

Normally vprintf takes va_list, not va_list *.
Adjust its signature and add function attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/780)

[Pal, LibOS] fix vprintf signature

---

LibOS/shim/src/fs/shim_namei.c

open with O_CREAT fails for existing files.
Fixes inappropriate O_CREAT|O_EXCL flags check and missing goto
Fixes #571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/821)

[LibOS] Fix O_CREAT|O_EXCL flags checks in open()

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/shim_malloc.c

Fixes #512. Closes #455.
This PR removes the unnecessary `SIGNAL_DELAYED` flag embedded in `tcb.context.preempt` but never actually needed. This flag is set to indicate that there is at least one signal which is delayed (pending). `handle_signal()` checked if this flag is not set as a performance optimization (because `__handle_signal()` correctly doesn't deliver any signals if there are none, but must iterate through signal log). The only time this flag would be checked was in `__system_malloc()` for a rare case when malloc (for an internal Graphene object) is interrupted by a signal. This event is so rare that it doesn't make sense to keep `SIGNAL_DELAYED`.
By removing `SIGNAL_DELAYED`, we eliminate a data race on this flag. Consequently, #450 may be simplified significantly. And #455 …

[LibOS] Remove unnecessary SIGNAL_DELAYED flag 

---

Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/sgx_arch.h

See commit messages.
BTW: Is there a reason why we use `cld` after EENTER but `movq $0, SGX_GPR_RFLAGS(%rbx)` (i.e. all flag bits) for `_DkExceptionHandler`?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/802)

Follow up to PR #640 (Fix "cld" on entry and small cleanup)

---

LibOS/shim/src/shim_async.c

There is a race between creating async helper thread and the tread
exiting.
When the asyc helper breaks while-loop, install_async_event() thinks
the helper is alive and skip to create_async_helper().
In this case while async events is installed, there is no async
helper thread.
Check the condition for async helper to exit with lock held.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/817)

[LibOS] resolve race between creation/deletion async helper

---

Pal/src/host/Linux-SGX/enclave_entry.S

%rdx, %rbp, %r8-%r15 is cleared twice unnecessarily on sgx_ocall.
So eliminated the first ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/820)

[Pal/Linux-SGX] eliminate duplicate register clear on sgx_ocall

---

Pal/src/host/Linux-SGX/sgx_process.c
Pal/src/host/Linux/db_process.c

With vfork(), parent/child shares the stack. So the child has
to be careful to not modify parent's local variable.
Introduce dedicated function to allocate child local variables.
NOTE: compiler can use same stack location for different local variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/768)

[Pal/Linux-SGX] allocate dedicate stack for vfork() child

---

LibOS/shim/src/sys/shim_alarm.c

signal_alarm() @ shim_alarm.c is used only locally.
So make it static.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/827)

[LibOS] make signal_alarm static

---

LibOS/shim/include/shim_handle.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/fs/shim_namei.c
LibOS/shim/src/sys/shim_open.c
LibOS/shim/test/regression/30_stat.py
LibOS/shim/test/regression/fstat_cwd.c
LibOS/shim/test/regression/stat_invalid_args.c

This PR is needed for #809.
In LibOS, a `shim_handle` contains a union structure `info` to store the FS-specific information. In [`fs/chroot/fs.c`](https://github.com/oscarlab/graphene/blob/7ac25ca5560523a48226abfb3b70f252387e8df7/LibOS/shim/src/fs/chroot/fs.c),  `handle->info` is exclusively intepreted as a `shim_file_handle`. However, in [`fs/namei.c:598-616`](https://github.com/oscarlab/graphene/blob/7ac25ca5560523a48226abfb3b70f252387e8df7/LibOS/shim/src/fs/shim_namei.c#L598-616), if the dentry being opened represents a directory, the code will treat `handle->info` as a `shim_dir_handle`. As a result, it corrupts the content of `shim_file_handle`, causing unexpected failure at run time.
One symptom of this bug is that if you open a directory (e.g., the current directory) and then use …

[LibOS] shim handle corruption caused by ambiguous interpretation 

---

Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/sgx_exception.c
Pal/src/host/Linux-SGX/sgx_graphene.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_thread.c

This is a follow up of 4f7841e14.
ocall should return -ERRNO on error. So on signal, it should return -EINTR
instead of -PAL_ERROR_INTERRUPTED.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/829)

[Pal/Linux-SGX] return -EINTR instead of -PAL_ERROR_INTERRUPTED

---

LibOS/shim/include/shim_defs.h
LibOS/shim/include/shim_vdso.h
LibOS/shim/src/Makefile
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/vdso/.gitignore
LibOS/shim/src/vdso/vdso-data.S
LibOS/shim/src/vdso/vdso-note.S
LibOS/shim/src/vdso/vdso.c
LibOS/shim/src/vdso/vdso.lds
Makefile.configs
Makefile.rules

this patch adds vDSO support.
Create vDSO page which contains necessary symbols
(__vdso_{gettimeofday, clock_getime, time, getcpu})
with empty definition.
On startup, stwist its symbol value to use
the actual definitions, (__shim_{gettimeofday, clock_gettime, time,
getcpu})
Thus, glibc modification to not use vdso can be removed.
The next patch removes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/318)

LibOS: vDSO support

---

LibOS/shim/include/shim_checkpoint.h
LibOS/shim/src/bookkeep/shim_signal.c

gcc-8 complains
> bookkeep/shim_signal.c: In function __handle_one_signal:
> bookkeep/shim_signal.c:622:19: error: cast between incompatible function types from __sighandler_t {aka void (*)(int)} to void (*)(int  siginfo_t *, void *) {aka void (*)(int,  struct siginfo *, void *)} [-Werror=cast-function-type]
>          handler = (void (*) (int, siginfo_t *, void *)) act->k_sa_handler;
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/762)

[LibOS] remove warning cast-function-type with gcc-8

---

LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/fs/shim_fs.c
LibOS/shim/src/fs/shim_namei.c

__path_lookupat(start!=NULL, path=absoluate) is wrongly handled to lookup
at start dir. Not root dir. resolution should start root directly of the
thread.
ltp test cases with xxxat variants. e.g. openat(), statat() etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/671)

[LibOS] fix __path_lookupat(start!=NULL, abspath)

---

Pal/src/host/Linux-SGX/sgx_exception.c
Pal/src/host/Linux-SGX/sgx_internal.h
Pal/src/host/Linux-SGX/sgx_process.c
Pal/src/host/Linux/db_exception.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/pal_linux.h

To avoid vfork child from corrupting parent memory, block async signal
before vfork().
This PR depends on #768 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/770)

[Pal/{Linux, Linux-SGX}] block async signal during vfork

---

Pal/src/host/Linux-SGX/enclave_ocalls.c

ocall_gettime can return -EINTR. Loop on EINTR case.
So assert(!ret) in _DkSystemTimeQuery() should be correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/843)

[Pal/Linux-SGX] ocall_gettime loops ocall_gettime on EINTR

---

LibOS/buildglibc.py
Pal/src/host/Linux-SGX/debugger/pal-gdb.py
Pal/src/host/Linux/pal-gdb.py

This patch converts remaining python2 scripts to python3.
The counterpart in `graphene-tests` is https://github.com/oscarlab/graphene-tests/pull/10. That PR should be merged before this PR (and this PR's pointer to graphene-tests must be updated during final rebase).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/707)

convert python2 script to python3

---

LibOS/shim/include/shim_handle.h
LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/test/regression/large_dir_read.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux/db_files.c

Fixes bugs preventing large directories from being listed  + rewritten related functions for speed and clarity.
Probably fixes #471
There's a regression test added, I'll enable it after #833 gets merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/840)

[LibOS,Pal/{Linux,Linux-SGX}] Fix issues with large directory listing

---

LibOS/shim/include/shim_table.h
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_stat.c

This patch implements newfstatat system call.
ltp fstatat01
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/672)

[LibOS] implement newfstatat system call.

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

This PR uses the variables introduced in https://github.com/oscarlab/graphene-tests/pull/15 to reduce the run time of Apache and Lighttpd in Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/864)

Tune the run time of Apache and Lighttpd tests

---

LibOS/shim/src/bookkeep/shim_signal.c

Related Issue #858
Signed-off-by: Alex Merritt <mail@alexmerritt.us>
Fixes #858 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/863)

[LibOS] assert check context == NULL

---

LibOS/shim/include/shim_signal.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/sys/shim_alarm.c
LibOS/shim/src/sys/shim_ioctl.c
LibOS/shim/src/sys/shim_sigaction.c

This PR fixes #529. Just as @dimakuv investigated, the root cause of this bug is the interruption of `read()` on the pipe between the parent and child processes. The emulation of `read()` is interrupted by the host-level signal sent from the IPC helper in order to deliver the SIGCHLD signal from the terminated child process. The `clone03` test does not expect `read()` to be interrupted because SIGCHLD is set to be ignored by default.
The quick fix presented in this PR is to skip the delivery of a signal if the target thread is set to ignore the said signal. This fix should at least stabilize `clone03` and prevent similar corner cases to happen again. However, this fix does not prevent the target thread from being interrupted by **other** signals (e.g., a SIGINT from the host). We may need …

[LibOS] Fixing LTP test clone03

---

LibOS/shim/src/sys/shim_epoll.c

- Fixes #765 
- Added a `put_handle(hdl)` line in the `shim_do_epoll_ctl`  function (in the 'delete' section of the case statement to ensure proper bookkeeping of handle usage)
- Moved line `put_handle(epoll_hdl)` for better code readability 
I tested it on my (non-open-source app), can be checked by code review, would need an elaborate event based communication app to test (currently not covered by regression tests).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/797)

[LibOS] Fix handle leak in epoll_ctl (issue #765)

---

Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
LibOS/shim/include/shim_defs.h

The Apache test on SGX deterministically hit an ongoing problem with fork - that the cpstore location was creating conflicts.  In the short-term, disable CPSTORE randomization, to reduce the risk of address space conflicts.  In the longer term, we will need to clean up cpstore.
This makes Apache work on Linux-SGX, and probably reduces the likelihood of other heisenbugs.  
This also includes a few whitespace fixes to the Jenkinsfile.
Fixes #826 
Run the SGX Jenkins pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/859)

Turn on CPSTORE_DERANDOMIZATION, fixes apache on SGX.

---

Pal/lib/graphene/config.c

Stripping the trailing whitespaces in manifest files. A few examples:
```
loader.debug_type = inline # none
loader.debug_type = inline <newline>
loader.debug_type = inline<tab>
``` 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/875)

[PAL] Skip the trailing whitespaces in the manifest files

---

LibOS/shim/src/fs/str/fs.c

fs/str/fs.c has suspicious && which seems to be & for bit operation.
Replace && with &.
This was found by code inspection. Not by any test.
So someone testing strfs, please test it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/877)

[LibOS] replace suspicious && with &

---

LibOS/shim/include/shim_handle.h
LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_table.h
LibOS/shim/include/shim_vma.h
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_brk.c
LibOS/shim/src/sys/shim_fork.c
LibOS/shim/src/sys/shim_getrlimit.c

This PR is required by #809 
This PR reimplements `getrlimit`/`setrlimit` and adds `rlimit64`. `rlimit64` is necessary for new versions of glibc since `getrlimit`/`setrlimit` are changed into just wrapper of rlimit64. Specifically, this PR implements some basic functionality of RLIMIT_DATA and RLIMIT_STACK.
Run the `brk01` test in LTP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/830)

Implement rlimit64, getrlimit, and setrlimit for real

---

Pal/Makefile
Pal/src/Makefile

`make clean` failed on the current master branch because of a remaining rule in `Pal/src/Makefile`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/874)

[PAL] Reference monitor code cleanup

---

Pal/regression/test_pal.py

Previously, test_000_symbols PAL regression test compared all lines in
stderr against a list of expected values (prefixed with "Dk...").
However, SGX PAL in debug mode outputs additional SGX-related
information in stderr which broke the test. This commit fixes this by
checking only lines which start with "Dk...".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/876)

[Jenkins/Pal] Fix test_000_symbols test on debug SGX pipepine

---

Pal/src/host/Linux-SGX/db_devices.c
Pal/src/host/Linux/db_devices.c

The static function, dev_attrcopy() in db_devices.c is unused.
remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/878)

[Pal/{Linux, Linux-SGX}] remove unused dev_attrcopy()

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/syscallas.S
Pal/lib/atomic.h

preempt_enable/disable(), __preempt_enable/disable() and other
functions touch shim_context::preempt with normal instruction. For
example preempt++ or preempt-- isn't atomic. Async signal can come
between such instructions and the integrity of preempt can be broken.
make shim_context::preempt atomic_inc and the logic is rewritten by
using atomic operation.
Fixes #449
Please preserve the following …

[LibOS] issue 449: use atomic for shim_context::preempt

---

Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_tls.h
Pal/src/host/Linux-SGX/signer/pal-sgx-sign
Pal/src/host/Linux/db_exception.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_threading.c
Pal/src/host/Linux/pal_linux.h
Pal/src/pal.h

Introduce PAL_TCB common structure among Pal/Linux and Pal/Linux-SGX
so that LibOS can stash its tcb into PAL TCB.
This patch is preparation for static linked binary support where
LibOS tcb can be embedded into application per thread structure.
SHIM_TCB_USE_GS is introduced as compile time option to enable/disable
this feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/555)

[Pal/{Linux, Linux-SGX}] introduce PAL_TCB as common structure

---

LibOS/shim/src/sys/shim_access.c
LibOS/shim/src/sys/shim_fs.c
LibOS/shim/src/sys/shim_open.c

This patch is followup of https://github.com/oscarlab/graphene/pull/671
With #671, absolute path check is handled unformly by __path_lookupat().
Now absolute path check in each system call isn't needed, so remove it.
LTP test cases for xxxat() syscalls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/673)

[LibOS] remove abspath check from xxxat() syscalls

---

Pal/src/host/Linux-SGX/db_sockets.c

(This is a re-submission of #776 which I broke due to incorrect push to the remote repo. This is already rebased to latest master and must be merged.)
Fixes (only partially) #674: Initializing variable `sock_options `to all zero, except `sock_options.reuseaddr`, which is initialized to 1. This for `tcp_connect`, `tcp_listen`, and `tcp_accept`, `udp_bind`, and `udp_connect `in `Pal/src/host/Linux-SGX/db_sockets.c`
All tests must run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/892)

[PAL] Fix initialization of variables sock_options in db_sockets.c

---

LibOS/shim/src/Makefile
LibOS/shim/src/vdso/.gitignore
LibOS/shim/src/vdso/vdso.c
Makefile.rules

segv in vDSO because relocation isn't applied when vDSO is mapped.
In fact relocation in the code isn't necessary.
So suppress relocation by the use of GOT entry with static symbol.
plus minor code clean up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/885)

[LibOS/vDSO] eliminate relocation

---

LibOS/shim/src/shim_parser.c

show exit signal number for clone as symbol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/887)

[LibOS] parser: teach parse_clone_flags() clone signal number

---

LibOS/shim/test/regression/large_dir_read.c
LibOS/shim/test/regression/manifest.template
LibOS/shim/test/regression/test_libos.py
Pal/src/host/Linux-SGX/enclave_framework.c

Enables (already present) large directory read regression test (LibOS)
Fixes a bug that forbade to open files even though parent directory was in sgx.allowed_files in manifest (Pal/Linux-SGX)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/884)

[LibOS/tests,Pal/Linux-SGX] Enable large_dir_read regression test, bugfix subdir check

---

LibOS/shim/test/regression/getsockopt.c

rv is uninitialized. initialize it to 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/888)

[LibOS] regression/getsockopt return 0 on success.

---

Pal/src/host/Linux-SGX/sgx_enclave.c

get_sockopt() is expected to initialize it.
For now initialize it with constants to avoid uninitialized value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/890)

[Pal/Linux-SGX] get_sockopt() initialize opt with constant

---

Pal/src/host/Linux-SGX/debugger/gdb
Runtime/pal_loader

So that gdb can be run under emacs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/893)

[pal_loader] teach pal_loader emacs gud mode

---

Pal/src/host/Linux-SGX/db_rtld.c

the loading address should be %p instead of 0x%p which results in
something like 0x0xabcdefg (double leading "0x").
then gdb fails to parse it.
remove redundant 0x so that gdb can parse it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/900)

[Pal/Linux-SGX] fix argument for ocall_load_debug()

---

Pal/regression/Makefile
Pal/test/Makefile

The PAL loader cannot relocate the executables. As a result, a position-independent executable (per the default GCC setting on Ubuntu 18.04) will crash if no other loader (e.g., the GLIBC loader) is involved. Since the PAL tests are only for internal testing purposes, we don't have to add relocation to the PAL loader but to make these tests position-dependent (adding `-no-pie` to CFLAGS).
Run the whole regression test under 18.04 or 16.04.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/901)

Force -no-pie when building PAL tests

---

Makefile.rules

Don't depend on locale settings when parsing readelfs output.
Test with a non English locale and see that the "no reloc" check still works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/902)

[Makefile] Don't depend on locale settings when parsing readelf

---

Jenkinsfiles/Linux-18.04

Fixes commit bdb58741eca22f368175149856983e0d877739e1 "[Jenkins] Test the build of graphene-ipc module"
Jenkins should no longer complain about "Syntax error: Unterminated quoted string"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/908)

[Jenkins] Use shell comment in Jenkins shell script

---

LibOS/shim/include/shim_table.h
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/src/sys/shim_poll.c
Pal/src/db_object.c
Pal/src/host/Linux-SGX/db_events.c
Pal/src/host/Linux-SGX/db_mutex.c
Pal/src/host/Linux-SGX/db_object.c
Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux/db_events.c
Pal/src/host/Linux/db_mutex.c
Pal/src/host/Linux/db_object.c
Pal/src/host/Linux/pal_host.h
Pal/src/host/Linux/pal_linux.h
Pal/src/pal.h
Pal/src/pal_internal.h

According to the manpage (http://man7.org/linux/man-pages/man2/epoll_wait.2.html), the `timeout` parameter for system call `epoll_wait()` and `epoll_pwait()` are both in milliseconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/651)

[LibOS] Fix the timeout resolution for epoll_wait() and epoll_pwait()

---

Pal/lib/api.h
Pal/lib/graphene/path.c
Pal/regression/Makefile
Pal/regression/normalize_path.c
Pal/regression/test_pal.py
Pal/src/db_main.c
Pal/src/host/FreeBSD/db_main.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux/db_main.c

Rewritten `get_norm_path` and `get_base_name` as they contained some bugs and added tests for them.
Enable relative manifest path
Fixes #819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/894)

[Pal] Fix path normalization bugs

---

LibOS/Makefile
LibOS/buildglibc.py

remove replacing logic of PARALLELMFLAGS in buildglibc.py
instead use $(MAKE) PARALLELMFLAGS="-j `nproc`"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/913)

[LibOS] remove PARALLELMFLAGS hack of buildglibc.py

---

LibOS/shim/include/shim_thread.h
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_exec.c

__libcc_tcb_t is leaked. It should allocated from stack.
Fixes #897.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/898)

libos execve memory leak

---

LibOS/shim/src/bookkeep/shim_signal.c

[LibOS] teach append_signal() how to handle SIG_IGN/SIGCHLD
This patch is follow up for #832, "[LibOS] Fixing LTP test clone03".
When signal is masked ans handler = SIG_IGN, it shouldn't queue
signal to avoid memory leak.
If signal is SIGCHLD, it can be discarded even if it's masked.
Reference:
- Linux implementation: do_notify_parent() @ linux/kernel/signal.c
- Standards:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/_Exit.html
With glibc-2.19, kill12 is broken due to the its emulation.
It may or may not success depending on which, SIGCHLD from parent or
child nanosleep, is earlier.
If SIGCHLD is earlyer, it success.
If child nanosleep is earlier, it hangs.
With the following changeset, glibc is updated so that the issue
doesn't exit.
Related:
glibc patch
> commit …

clone03 fix followup

---

LibOS/shim/include/shim_handle.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/sys/shim_dup.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_fs.c
LibOS/shim/src/sys/shim_migrate.c
LibOS/shim/src/sys/shim_open.c
LibOS/shim/src/sys/shim_pipe.c

Inside `struct shim_handle` `opened` reference counter is used incorrectly.
Additionally at this moment it guards the same resource (handle) as `ref_counter`,
making it obsolete.
This patch removes `opened` counter and moves `close_handle` logic into
`put_handle` - there should be no way of closing underlying file if there still exist handle references.
Fixes #910 and partially #903
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/911)

[LibOS] Remove `opened` reference counter from `struct shim_handle`

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-Debug

Jenkins already runs a recursive submodule update. So no need to do this
again manually.
See that the Jenkins jobs still work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/922)

[Jenkins] Don't update LTP submodule twice

---

LibOS/Makefile
LibOS/glibc-2.19-remove-vdso.patch
LibOS/glibc-2.19.patch

Now vDSO is supported, so remove the modification to glibc
not to use vDSO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/319)

Vdso glibc

---

Jenkinsfiles/ubuntu-16.04.dockerfile

The gipc build test can fail in Jenkins if the correct kernel headers are not installed.  This can get out of date after an upgrade on the host, but the docker image is still wrong.
Going to manually test on waldorf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/927)

[CI] Make sure the right kernel version is installed

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

See https://github.com/oscarlab/graphene-tests/pull/24.
Jenkins on 18.04 should now proceed a bit further than before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/928)

[LibOS] test/apps: Fix up apache and lighttpd tests

---

LibOS/Makefile
LibOS/shim/Makefile

fix parallel make warning during glibc building
> make[3]: warning: -jN forced in submake: disabling jobserver mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/930)

fix makefile parallelmake of glibc

---

Pal/src/db_main.c
Pal/src/host/FreeBSD/db_main.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/pal_security.h
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux/db_devices.c
Pal/src/host/Linux/db_files.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Linux/pal_linux.h
Pal/src/pal_internal.h

Add code to figure out whether hyperthreads are enabled, so that one can detect the total number of cores on the system.
Run the Bootstrap PAL regression on a HT system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/868)

Fix cpuid parsing on a system with hyperthreads

---

Pal/src/host/Linux-SGX/sgx_framework.c

On host exec, file descriptors for /dev/isgx and /dev/gsgx are
leaked.
So set CLOSEXEC for them to be closed when emulating fork/exec
by using host exec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/936)

[Pal/Linux-SGX] set CLOSEXEC on /dev/isgx, /dev/gsgx

---

README.rst

#241 has already addressed the compatibility issues for GCC 6/7/8/9, so we don't need this warning anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/934)

Update gcc requirement in README.md

---

LibOS/shim/include/shim_defs.h
LibOS/shim/src/shim_checkpoint.c

This PR removes the warning ``WARNING: no physical memory support, process creation may be slow`` when GIPC (Bulk IPC feature) is not supported. This warning message has caused quite a few confusing for the users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/935)

[LibOS] Disable the warning when GIPC is not supported

---

LibOS/shim/include/shim_fs.h
LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/fs/shim_dcache.c
LibOS/shim/src/fs/shim_fs.c
LibOS/shim/src/fs/shim_namei.c
LibOS/shim/src/sys/shim_access.c
LibOS/shim/src/sys/shim_fs.c
LibOS/shim/src/sys/shim_open.c
LibOS/shim/src/sys/shim_stat.c

Unfortunately current implementation of fs does not allow for renaming anything but regular files.
Fixes some issues from #903 constrained by above statement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/943)

[LibOS] Rewrite rename* syscalls

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile

Fix the specific kernel header version to test graphene IPC build against, at least within one ubuntu release.  In the Jenkins pipelines, the kernel seems to be getting out of sync with the headers, I believe because of an upgrade on a worker node that doesn't flush the cached image.
Switch from testing the build of whatever version is in 'uname -r' to a reasonable, static default of the kernel headers.
Just run the Linux 16.04 and 18.04 pipelines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/983)

Just fix the specific header version within an ubuntu release

---

Pal/regression/Makefile

Other executable doesn't need avx, and it causes failure on platform
that doesn't support avx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/987)

[Pal] regression: only enable -mavx for AvxDisable

---

Pal/regression/Makefile
Pal/test/Makefile

when clean, dependency should not be calculated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/988)

[Pal/Linux-SGX] fix make SGX=1 clean

---

Pal/lib/graphene/config.c

If a backslah ('\') was encountered in a quoted ('"') value in a manifest,
it was getting deleted, but since the manifest is mapped read-only it caused
a segfault.
Removed this faulty behavior, now values are passed exactly as seen in
a manifest file, e.g. `loader.env.XXX = "\xY"Z"` passes a environmental
variable `XXX` with a value `"\xY"Z"`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/974)

[Pal] Delete '\' removal in read_config

---

Pal/src/host/Linux-SGX/debugger/gdb

Previously, the GDB wrapper of Graphene-SGX used "set auto-load safe-path GDB_SCRIPT". This contradicts newer GDB versions which have a libpthread-2.27.so-gdb.py script in a different system dir. Thus, our wrapper overwrote the native GDB safe-path and broke GDB. This commit ensures that our wrapper only adds paths to safe-path.
Try GDB on any executable under Ubuntu 18.04 (where PIE executables are default): `cd LibOS/shim/test/native && GDB=1 SGX=1 ./pal_loader helloworld`. GDB should not complain (without this PR, it says something like `warning: File "/usr/share/gdb/auto-load/lib/x86_64-linux-gnu/libpthread-2.27.so-gdb.py" auto-loading has been declined by your auto-load safe-path set to "graphene/Pal/src/host/Linux-SGX/debugger/pal-gdb.py".`).
--- …

[Pal/Linux-SGX] gdb wrapper: use add-auto-load-safe-path

---

Pal/src/db_rtld.c

Previously, there was a latent bug in db_rtld.c: add_elf_object() --
the mapstart variable was incorrectly initialized to zero. This led to
PIE executables (which typically have two LOAD segments, the code
segment starting with 0x0 and the GOT/PLT/dynamic segment starting with
e.g. 0x200000) to incorrectly set mapstart to the higher-LOAD-segment
address (and not the code address). This in turn confused GDB which
tried to add executable symbols from the wrong offset.
This commit fixes this bug by initializing mapstart to the highest
possible value ("~0") and removing the check for zero. This is similar
to what the Glibc code does. Also, mapend is fixed in a similar way.
Try GDB on any executable under Ubuntu 18.04 (where PIE executables are default): `cd LibOS/shim/test/native && GDB=1 …

[Pal] db_rtld.c: Fix GDB on PIE executables by fixing mapstart/mapend

---

LibOS/shim/test/regression/mmap-file.c

It has undefined behavior and causes test failure.
Add some work around.
TODO: remove undefined behavior and update test case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/996)

[LibOS] work around of mmap-file.c in regression

---

LibOS/shim/src/shim_parser.c

The parser logic checks the arguments of syscalls and prints strings in debug output. Previously, our code base only contained "const char *" as strings. Recently, we started migration to "const char*" (no-space) style. This broke the parser logic, so this commit adds an additional check on what it means for a C type to be a string.
All tests should run. One can try any application that does something like `open("somefile", O_RDONLY)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1002)

[LibOS] shim_parser.c: Additionally specify string as "const char*"

---

LibOS/shim/src/sys/shim_fs.c
Pal/src/host/Linux-SGX/enclave_ocalls.c

This PR:
- Fixes a typo in handle_copy() which led to failed sendfile().
- Allows to write/send from buffer in untrusted memory.
Note that previously, ocall_write() and ocall_sock_send() disallowed to write/send data from a buffer allocated in untrusted memory (as it was considered an impossible scenario). However, sendfile() logic may write an allowed regular file (which is mmapped in untrusted memory) directly to a socket.
Build `apps/lighttpd` and run via `make start-graphene-server` (under SGX). Run `curl localhost:8000` (you may need to change the IP address in manifest/curl). Without this PR, it will fail with `sendfile failed:Permission denied 3`. With this PR, curl will correctly show `Test OK!` (contents of the web-server file `index.html`).
Fixes #998, #903, #909, and #951.
--- …

Fix sendfile() syscall under Linux-SGX

---

Pal/regression/AvxDisable.manifest.template
Pal/regression/test_pal.py
Pal/src/host/Linux-SGX/sgx_framework.c
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Our current signer always signs SGX manifests in such a way that it requires AVX, even if the application doesn't use AVX.  This creates problems on some SGX v2 systems (NUCs) that don't support AVX.
Change the default behavior for AVX to be off by default.
In a future PR, we will change this behavior to enabled, but not required, by default.
Run a Jenkins pipeline on such a node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/999)

[SGX] Switch from requiring AVX making it optional by default.

---

Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux/db_files.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Linux/pal_host.h

Previously, read()/write() for both trusted and allowed files were emulated in the same manner: using mmap/memcpy/munmap. This led to insidious data races in multi-process applications like Apache: one process would mmap a file and access it during read/write emulation, while another process would ftruncate the same file (this leads to SIGBUS as per mmap man page). This happens even for allowed files which do not require the complicated mmap/memcpy/munmap emulation (this logic was introduced primarily for trusted-file checksum verification).
This commit separates the emulation of trusted files and allowed files. The former still use mmap/memcpy/munmap (slightly optimized for performance), the latter use lseek+read/write (similar to Linux PAL). This requires new OCALL ocall_lseek(). Also, …

[Pal/Linux-SGX] Emulate reads/writes to allowed and trusted files differently

---

Makefile.rules

Previously, Makefile.rules tried to find the absolute path to pal-symbols file using the MAKEFILE_LIST make variable. However, because Makefile.rules is included from other Makefiles, this led to
incorrect path ("graphene/Pal/src/host/Linux/Pal/src/pal-symbols"). This commit switches from MAKEFILE_LIST to PAL_DIR.
Without this PR, doing `make SGX=1` and then `make` (i.e., first build with Linux-SGX PAL, then with Linux PAL) broke with error:
```
sed: can't read /home/dimakuv/graphene/Pal/src/host/Linux/Pal/src/pal-symbols: No such file or directory
```
With this commit, `make SGX=1 && make` must succeed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1009)

[LibOS] Makefile.rules: Specify correct path to pal-symbols

---

Documentation/oldwiki/Graphene-Manifest-Syntax.md
LibOS/shim/test/regression/test_libos.py
Pal/lib/api.h
Pal/lib/string/strendswith.c
Pal/regression/test_pal.py
Pal/src/db_main.c
Pal/src/db_rtld.c
Pal/src/pal_rtld.h

Before argv[0] was treated specialy and was changed to a value
from manifest file. Now this happens only if binary was ran as
a manifest i.e. `./pal_loader path_to_manifest_file`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/971)

[Pal] Change the way argv[0] is handled

---

LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/sys/shim_brk.c
Pal/lib/api.h
Pal/src/db_main.c
Pal/src/host/FreeBSD/db_main.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_pages.c
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/signer/pal-sgx-sign
Pal/src/host/Linux/db_main.c
Pal/src/host/Skeleton/db_main.c
Pal/src/pal.h
Pal/src/pal_internal.h

Add a memory gap around the memory area of the executable like we already do for other memory areas.
Run regression test to see that it doesn't break things. Look at output of `pal-sgx-sign` to see added memory gaps above/below the executable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/620)

[Pal/Linux-SGX] Add memory gap around 'exec' area

---

CONTRIBUTING.md
Documentation/manpages/pal_loader.rst
Documentation/oldwiki/Debugging-Graphene.md
Documentation/oldwiki/Graphene-SGX-Quick-Start.md
Documentation/oldwiki/Introduction-to-Graphene-SGX.md
Documentation/oldwiki/Introduction-to-Graphene.md
Documentation/oldwiki/Run-Applications-in-Graphene-SGX.md
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
LibOS/Makefile
LibOS/shim/Makefile
LibOS/shim/test/Makefile
LibOS/shim/test/Makefile.Test
Makefile
Pal/Makefile
Pal/regression/Makefile
Pal/src/Makefile
Pal/src/Makefile.Host
Pal/src/host/Linux-SGX/Makefile.Test
Pal/src/host/Linux-SGX/sgx_main.c
Pal/test/Makefile
README.rst
Runtime/Makefile
Runtime/pal_loader
Scripts/Makefile
Scripts/regression.py

For detection of SGX/non-SGX (for example in regression tests) always
use the SGX environment variable. To generate launch/EINIT tokens use
the the new 'sgx-tokens' Make target.
Depends on oscarlab/graphene-tests#35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/961)

[Makefile] Drop SGX_RUN

---

LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/src/sys/shim_socket.c

Two bug fixes here:
*    [LibOS] Do not get/put handles when adding/removing from epoll
Previously, Graphene explicitly incremented refcount of a handle added to/removed from epoll, in epoll_ctl(EPOLL_CTL_ADD/EPOLL_CTL_DEL). However, according to epoll(7), closing a file descriptor causes the FD (handle) to be removed from all epoll sets. In other words, adding/removing a handle to/from epoll must not count towards refcount of the handle. Otherwise the handle remains dangling in the epoll set even if it was close()'d (this particular case led to Nginx segfault). This commit removes get/put of handle during epoll add/remove.
*    [LibOS] Allow repeated listen() on the same socket
Typically, listen() is called only once by the application, to mark the socket as passive for listening for …

Nginx specific network fixes

---

Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_threading.c

Pal/Linux allocate initial thread for PAL thread by _DkVirtualMemoryAlloc() whose result may overlap with pal_control.user_address. LibOS may corrupts such stack and typicall PAL thread can result in SEGV.
use malloc() to allocate initial stack for PAL thread.
Also fix memory leak of PAL_HANDLE for thread.
Pal/regression/Memory
thread suddenly dies(SEGV) in PAL during accessing PAL_TCB_LINUX because PAL_TCB_LINUX(especially PAL_TCB_LINUX.common.self) is overwritten by LibOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1024)

[Pal/Linux] use malloc to allocate PAL thread stack

---

Pal/src/host/Linux/db_threading.c

It frees stack signal and pal tcb, signal handle can't be run correctly.
So block async signal.
If async signal arrive in _DkThreadExit() it can SEGV.
For test Pal/test/Yield can be used. It sometimes hangs with the following message
> *** An unexpected memory fault occurred inside PAL. Exiting the thread. (PID = 19881, TID = 19894, RIP = +0x000102b6) ***
Pal/test/Yield
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1038)

[Pal/Linux] block async signal on thread exiting

---

Pal/lib/graphene/config.c

The check should happen *AFTER* walking through the training
spaces before equal mark.
Bug fix
Before the patch applied:
```
Cannot read manifest: equal mark expected
Invalid manifest: file:helloworld.manifest.sgx
```
After the patch applied:
```
Cannot read manifest: stream ended at key portion
Invalid manifest: file:helloworld.manifest.sgx
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1016)

[Pal] Fix parsing the key ending at space

---

LibOS/shim/include/shim_handle.h
LibOS/shim/src/bookkeep/shim_handle.c

Rewritten `set_new_fd_handle` for clarity + a bug fix.
Fixes #919
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1029)

[LibOS] Change minimal file descriptor number to be 0

---

Pal/src/host/Linux-SGX/sgx_framework.c

The format of enclave signature should strictly match the spec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1042)

[Pal/Linux-SGX] Sanity check the size of specified signature file

---

Pal/src/host/Linux-SGX/sgx_main.c

[Pal/Linux-SGX] Refactor main function of pal_loader
- Avoid opening manifest file twice
If the specified file is a manifest, its fd can be sent to load_enclave()
directly.
- Kill hard-coding constant
Use static_strlen(foo) instead.
- Add error handling
Check the return value of alloc_concat(), and use strendswith() to prevent
from buffer underflow caused by short base name of input file path.
- Enhance readability
Include renaming variables and comment changes
Bug fix
```
Cannot open manifest test.manifest.sgx
```
With the patch applied:
```
Cannot open manifest file: test.manifest.sgx
USAGE: /root/graphene/Runtime/pal-Linux-SGX [executable|manifest] args ...
```
bash regression also goes pass.
--- …

[Pal/Linux-SGX] Detect invalid manifest.sgx earlier

---

Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Currently, sgx.static_address is not recorded in generated
.manifest.sgx file if preparing to launch a PIE executable.
```
sgx.static_address = 0
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1045)

[Pal/Linux-SGX] pal-sgx-sign: Always output sgx.static_address in .manifest.sgx

---

LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_signal.c

With compiler optimization, test_user_memory() doesn't work as expected.
Add compiler barrier and fixes the function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1039)

[LibOS] fix test_user_memory() regarding to compiler optimization

---

LibOS/shim/include/shim_vma.h
LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_malloc.c
LibOS/shim/test/regression/fdleak.c
LibOS/shim/test/regression/test_libos.py

A sequence of open(), read(), close() led to a situation where the underlying host FD would never be released. The fix no longer associates the PAL handle with the VMA structure, resulting in a different code path where the ref counting on the PAL handle actually drops to 0 and the underlying host FD is correctly released.
I've added a simple regression test that fails without this patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1033)

Fix and test case for resource leak on file close.

---

Pal/src/host/Linux/db_sockets.c

For reasons that have long been forgotten, Linux PAL set SO_LINGER with a zero timeout before closing the socket. [Among other things](https://stackoverflow.com/questions/3757289/tcp-option-so-linger-zero-when-its-required), this leads to ab (Apachebench) reporting failed requests when running nginx/lighttpd on Graphene, because the TCP connection is not closed cleanly.
Run ab against nginx/lighttpd. Without this fix, you will likely see failed requests. With this patch, all requests should succeed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1051)

No longer set SO_LINGER on socket.

---

Runtime/pal_loader

This fixes regression from #961.
Run `pal_loader SGX` instead of `SGX=1 pal_loader`. Sometime. Someday.
Even better, run that regularly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1052)

[PAL] fix pal_loader SGX invocation

---

Pal/src/host/Linux/db_misc.c

_DkSystemTimeQuery should return realtime. Not MONOTONIC.
CLOCK_MONOTONIC returns from unspecified starting point.
apps/bash/date.manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1059)

[Pal/Linux] Make _DkSystemTimeQuery return REALTIME, not MONOTONIC

---

LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_object.c
Pal/lib/crypto/adapters/mbedtls_adapter.c
Pal/lib/crypto/adapters/mbedtls_adapter.h
Pal/lib/crypto/adapters/mbedtls_dh.c
Pal/regression/normalize_path.c
Pal/src/Makefile
Pal/src/db_main.c
Pal/src/host/FreeBSD/db_main.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux/db_main.c
Pal/src/pal-symbols
Pal/src/pal_error.c
Pal/src/pal_error.h
Pal/src/pal_internal.h
Pal/test/Failure.c

Most errors returned from mbedtls functions were not converted to PAL errors.
This commit adds a separate PAL error code block for crypto errors.
Run standard tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1047)

[Pal] Fix errors returned from mbedtls crypto adapter

---

LibOS/shim/src/sys/shim_exit.c
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/abort.c
LibOS/shim/test/regression/exit_group.c
LibOS/shim/test/regression/exit_group.manifest.template
LibOS/shim/test/regression/test_libos.py

Exit due to signal produced a return code of 0. This correctly propagates the return code on exiting from a signal.
Closes #841.
Test case is provided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1034)

Fix return code on exit due to signal

---

LibOS/shim/src/sys/shim_clone.c
LibOS/shim/test/regression/futex.c

Added logic to check for (CLONE_VM | CLONE_THREAD) or (CLONE_VM | CLONE_VFORK) in clone(). Updated the general flow for checking flags in shim_clone().
This PR accompanies [#46](https://github.com/oscarlab/graphene-tests/pull/46) in graphene-tests.
Regression tests still work. Uncovered a "bug" in futex regression test which called clone() only with CLONE_VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1061)

Rework checking of supported clone() flags.

---

LibOS/shim/src/shim_init.c
Pal/src/host/Linux-SGX/pal_linux_error.h
Pal/src/host/Linux/pal_linux_error.h
Pal/src/pal_error.c
Pal/src/pal_error.h

Some hosts do not support IPv6 (e.g., Docker can be configured without it). In this case, socket() host syscall will return EAFNOSUPPORT. Some applications rely on this error code (e.g., Redis), so Graphene must propagate this error code all the way to the application. This commit makes LibOS and Linux/Linux-SGX PALs aware of this error code.
**Note:** This PR closes #1032 from @pangzi85480. I have no permission to access his repo, so I duplicated the rebased and ready-to-merge commit into this branch.
Run regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1077)

[LibOS, Pal/{Linux,Linux-SGX}] Add EAFNOSUPPORT error code

---

LibOS/shim/src/elf/dl-machine-x86_64.h
LibOS/shim/src/elf/shim_rtld.c
Pal/lib/string/strlen.c
Pal/src/db_rtld.c
Pal/src/dl-machine-x86_64.h

We don't need this micro-optimization which just obfuscates the sources for negligible performance gains. (Un)likeliness of branches in almost all cases should be derived from profiling, not from hand-written hints, using profile-guided optimization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1071)

Don't use __builtin_expect

---

LibOS/shim/include/shim_thread.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/src/ipc/shim_ipc_pid.c
LibOS/shim/src/sys/shim_alarm.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_futex.c
LibOS/shim/src/sys/shim_getpid.c
LibOS/shim/src/sys/shim_ioctl.c
LibOS/shim/src/sys/shim_sigaction.c
LibOS/shim/src/sys/shim_wait.c

There were some places that put_thread calls were missing. This caused
reference counter never reaching 0, hence struct never being freed
and effectively leaking memory.
This fixes only one of issues causing #969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1067)

[LibOS] Add missing put_thread calls

---

LibOS/shim/src/fs/shim_namei.c
LibOS/shim/test/regression/fopen_cornercases.c

Applications like OpenVINO sometimes do open("") and expect ENOENT. This corner case is correctly handled by Linux, so Graphene must have the exact same semantics. Previously, open("") under Graphene resulted in success, and subsequent read() failed.
The LibOS test `fopen_cornercases` was updated to include this test. So simply running LibOS regression tests checks this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1065)

[LibOS] Return ENOENT on open_namei(path = "")

---

Documentation/oldwiki/Graphene-SGX-Manifest-Syntax.md
LibOS/shim/test/regression/fopen_cornercases.c
LibOS/shim/test/regression/manifest.template
LibOS/shim/test/regression/test_libos.py
Pal/src/host/Linux-SGX/enclave_framework.c

Previously, `*stubptr` was not initialized to NULL in the corner case of a file created from inside of the SGX enclave. This led to a subsequent failure in logic which tried to mmap an empty file (because it observed that `*stubptr` contained some value).
This obvious bug doesn't seem to deserve a separate test. But this is the minimal test to reproduce the bug. Add this to the manifest:
```
sgx.allowed_files.testfile123 = file:tmp/testfile123
sgx.allow_file_creation = 1
```
Write this example:
```
int main(int argc, const char** argv) {
int fd = openat(AT_FDCWD,"tmp/testfile123",O_WRONLY|O_CREAT|O_TRUNC,0666);
printf("fd = %d\n", fd);
...
```
Graphene-SGX prints an error like this:
```
fd = -1
```
--- …

[Pal/Linux-SGX] load_trusted_file(): fix uninitialized pointer

---

Pal/src/host/Linux-SGX/sgx_thread.c

Remove "unmap TCS..." output message. This message is always printed (even in non-debug mode) whenever an application thread exits (and thus a TCS is remapped for reuse). It confuses too many people these days. Simply remove it as we don't experience any issues with SGX threads/TCSes these days.
Everything should work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1073)

[Pal/Linux-SGX] Remove "unmap TCS..." output message

---

Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

This PR simply moves the needle: updates the hash of the graphene-tests repo to contain the new Bash example.
Jenkins Bash-regression test must succeed as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1060)

[LibOS] test/apps: Rewrite Bash example

---

Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Previously, the "sgx.static_address" field was overwritten by the pal-sgx-sign tool in the manifest, even if the manifest author explicitly specified it as 0 or 1. Sometimes, it is important to keep sgx.static_address as the manifest author intended. This PR adds a check to overwrite sgx.static_address only if not specified in manifest.
This bug triggers in the following case:
- One program will call another program (e.g., `python` will execve `bash`)
- As part of execve, Graphene-SGX will create a checkpoint and allocate it in the child at exactly the same address as in the parent
- Now if the parent program (`python`) is a non-PIE executable, it will have its `sgx.static_address = 1`. This will force Graphene to create the manifest which starts the enclave at e.g. addresses `0 - 4GB`.
- …

[Pal/Linux-SGX] Do not overwrite sgx.static_address in manifest

---

Documentation/oldwiki/Graphene-SGX-Manifest-Syntax.md
Pal/regression/AvxDisable.c
Pal/src/host/Linux-SGX/sgx_framework.c
Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

This PR allows setting the AVX, AVX512, and MPX bits in SIGSTRUCT.xfrms dynamically *UNLESS* the features are specifically enabled by `sgx.require_[avx|avx512|mpx]=1` options in the manifest. If the bits are set in SIGSTRUCT.xfrms but the CPU feature(s) are not available on the platform, the enclave initialization (`EINIT`) should fail. In addition, the xfrms and xfrmmask field in the INITTOKEN must match with SIGSTRUCT.
This should fix the remaining issues described in #999.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1014)

Enable AVX/AVX512/MPX dynamically and add sgx.require_[avx|avx512|mpx] syntax

---

Pal/src/host/Linux-SGX/enclave_entry.S

This PR contains two fixes in `enclave_entry.S`:
1. Fix offset of MXCSR "reset" XSAVE area. Before EEXIT, Graphene-SGX resets the extended state (XSAVE) area to the default state (of mostly zero bytes). This prevents the leakage of  x87/SSE/AVX/MPX register values inside the enclave. However, the previous default state had an incorrectly calculated offset of MXCSR. This commit fixes the offset of MXCSR. (This particular error manifested in spurious "Numeric underflow (#U)" SSE hardware exceptions on OpenVINO.)
2. Reset FXSAVE extended state on EENTER. Previously, the FXSAVE extended state (ST, XMM, MXCSR registers) was not cleared on EENTER (i.e., enclave-thread enter). This could lead to maliciously crafted ST/XMM registers propagating into the enclave and subverting execution. This …

[Pal/Linux-SGX] Fixing XSAVE estended state on EENTER/EEXIT

---

LibOS/shim/src/shim_init.c
LibOS/shim/test/regression/bootstrap.c

Reorder argv strings in initial user stack in a way that the former string is located at lower address.
Reorders the location of `argv` and `envp` strings in user stack when they are copied during `populate_user_stack()`. After this patch, following equations should hold:
```
argv[0] < argv[1] < .. < argv[argc - 1];  (increasing order)
argv[i + 1] - argv[i] == strlen(argv[i]) + 1;  (compact)
``` 
I found the need for change when I tried to run node.js in Graphene. As soon as the process starts, `libuv` complained at below check (https://github.com/libuv/libuv/blob/v1.32.0/src/unix/proctitle.c#L62):
```c
process_title.str = argv[0];
process_title.len = argv[argc - 1] + strlen(argv[argc - 1]) - argv[0];
assert(process_title.len + 1 == size); /* argv memory should be adjacent. */
``` …

[LibOS] Reorder argv in user stack

---

Documentation/oldwiki/Graphene-SGX-Manifest-Syntax.md
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/file_check_policy.c
LibOS/shim/test/regression/file_check_policy_allow_all_but_log.manifest.template
LibOS/shim/test/regression/file_check_policy_strict.manifest.template
LibOS/shim/test/regression/test_libos.py
LibOS/shim/test/regression/trusted_testfile
LibOS/shim/test/regression/unknown_testfile
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/pal_linux.h

RFC
- Comments all sgx.trusted_files.foo and sgx.allowed_files.foo.
- Write down sgx.file_policy = audit
- Sign and generate token
- Launch application with pal-loader
- Observe the audit message about file accesses.
- According to the output, record the files as trusted or allowed in manifest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1022)

[Pal/Linux-SGX] Implement new manifest syntax sgx.file_policy

---

Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04

Graphene with SGX is currently experiencing random segfaults and the
testsuite is unstable. For now, the tests are still run, but the
returncode is ignored.
Also fixes bionic SGX pipeline, which was apparently broken but its
results are ignored and this problem was missed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1094)

[CI] Ignore LTP results under SGX

---

Runtime/pal_loader

In certain case, e.g, a container runtime for production delivery,
the make and gcc programs may be not available. In this case, detect
PAL_HOST according to the base name of libpal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1083)

[PAL] pal_loader: Detect PAL_HOST if make is unavailable

---

README.rst

This PR simply moves the needle to point to https://github.com/oscarlab/graphene-sgx-driver/pull/8. This is to remove a dependency on Python2 (by re-writing the script in Python3).
Fixes #1097.
All test should run correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1101)

[Pal/Linux-SGX] Rewrite link-intel-driver.py in Python3

---

LibOS/shim/src/Makefile
LibOS/shim/src/sys/shim_clone.c
Pal/src/host/Linux-SGX/debugger/sgx_gdb.h
Pal/src/host/Linux-SGX/sgx_main.c

Two fixes found during performance-testing OpenVINO on huge servers:
1. [LibOS] Use -O2 optimization level when building in non-debug mode.
2. [Pal/Linux-SGX] Increase MAX_DBG_THREADS constant from 64 to 1024.
Explanation for the second fix:  an internal Graphene structure for GDB metadata limits the number of enclave threads to MAX_DBG_THREADS. Previously, it was set to 64, which was enough for typical platforms. However, powerful servers have hundreds of logical cores. Graphene-SGX failed with error on such servers. This commit increases the limit to 1024 (should be more than enough for all modern platforms).
All tests should continue running.
Fixes #1040. 
--- …

Misc optimizations: use O2 for non-debug builds, allow up to 1024 enclave threads

---

LibOS/shim/src/sys/shim_pipe.c

Error return was not being set, when set_new_fd_handle fails, in shim_pipe.c
Bug was found during code review by Dmitrii.
Regression testing, should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1099)

Error return was not being set, when set_new_fd_handle fails, in shim_pipe.c

---

LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/abort_multithread.c
LibOS/shim/test/regression/test_libos.py

Previously, there was a bug that SIGTERM and SIGINT sent from the host OS killed only one thread but not the whole process (including child processes). Additionally, SIGABRT of the application also killed only one thread instead of the whole process. This commit fixes this.
Maybe I need to introduce a LibOS test to spawn several threads, and one of them calls `abort()`. Without this PR, it will hang. With this PR, it will kill all threads and finish.
This bug was found and fixed while debugging TensorFlow. So at least one program is affected by this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1079)

[LibOS] Fix SIGABRT, SIGTERM, SIGINT to kill the whole process

---

LibOS/shim/test/regression/test_libos.py

In trying to bring up a NUC as a Jenkins worker, we found we needed a larger timeout on the large-mmap unit test.  Go ahead and bump this up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1076)

Increase large-mmap timeout

---

Pal/lib/api.h

Per description of macro->"check if the var is exactly the same as the static string".
Fix the check in macro->strcmp_static, to check if both str and var are of same length.
Without this strlen check, memcmp, can scan outside the length of var argument.
Regression should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1108)

Add string length check in strcmp_static macro.

---

LibOS/shim/include/shim_fs.h
LibOS/shim/include/shim_handle.h
LibOS/shim/include/shim_table.h
LibOS/shim/src/Makefile
LibOS/shim/src/fs/eventfd/fs.c
LibOS/shim/src/fs/shim_fs.c
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_eventfd.c
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/eventfd.c
LibOS/shim/test/regression/test_libos.py
Pal/src/db_streams.c
Pal/src/host/FreeBSD/pal_host.h
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/db_eventfd.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux/Makefile
Pal/src/host/Linux/db_eventfd.c
Pal/src/host/Linux/pal_host.h
Pal/src/host/Skeleton/Makefile
Pal/src/host/Skeleton/db_eventfd.c
Pal/src/host/Skeleton/pal_host.h
Pal/src/pal.h

1. For Inter-process communication, between processes or threads within a process, similar to pipes. 
2. Eventfd can also be used by linux kernel to signal user-space applications. 
Refer to man-page, for more details->[http://man7.org/linux/man-pages/man2/eventfd.2.html]
**Option1->Eventfd’s counter, simulated using pipes:**
Design: There are many ways to simulate. One way described here. Write on eventfd, will write # of bytes equal to the value of counter in buffer. Read on eventfd, will read the pipe’s buffer, until pipe is empty, and return counter(equal to # of bytes read).
Cons->In general, simulating eventfd on top of pipes was in-efficient and limited, since eventfd counter, can be lot more than pipe's buffer. Not feasible to support second usage listed above
**Option2->Eventfd’s …

Changes to support eventfd in graphene.

---

Pal/src/host/Linux-SGX/sgx_main.c

If the path of executable file is inferred, add the key word "inferred"
to emphasize this fact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1127)

[Pal/Linux-SGX] Avoid confusing message about the path of executable file

---

Pal/src/host/Linux-SGX/sgx_framework.c
Pal/src/host/Linux-SGX/sgx_internal.h
Pal/src/host/Linux-SGX/sgx_main.c

Clear up the responsibilities between create_enclave() and its caller.
create_enclave() now assumes its caller picks a suitable base address and size according to SGX's requirements. Use create_enclave()'s secs parameter for in and outputs to reduce total number of arguments (not sure if this violates some Graphene coding standard). Also, I believe the code tacitly assumes that create_enclave()'s mmap creates the mapping at whatever address we provide. Hence, I changed the secs->base = addr into an assert().
Regression tests still pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1126)

Clean up interaction between initialize_enclave() and create_enclave()

---

Jenkinsfiles/Linux-SGX

This patch corresponds to
https://github.com/oscarlab/graphene-sgx-driver/pull/10
Once graphene-sgx-driver/pull/10 is merged, workaround to avoid error by distclean
should be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1132)

[Pal/Linux-SGX]: use distclean for sgx-driver

---

LibOS/shim/src/ipc/shim_ipc_helper.c

Before exiting, the IPC helper is supposed to wait for 0.5s for all in-flight IPC messages to reach their destinations (e.g., child processes). Otherwise, the destination processes may become abandoned zombies. Previously, this was achieved by `DkThreadDelayExecution(500)`. However, this function uses
microseconds not milliseconds, thus, Graphene actually waited only for 0.005 seconds (which is not enough under heavy system-wide load). This commit fixes this time-unit bug.
This bug was found while debugging non-deterministic failures of several LTP tests (`recvmsg01`, `recvfrom01`, `waitpid03`, etc) on Jenkins-18.04/Jenkins-Debug-18.04 pipelines. Hopefully this pipelines won't fail so often now.
I will try ~10-20 retests on Jenkins and see how it goes.
--- …

[LibOS] shim_ipc_helper.c: Actually wait for 0.5 seconds on IPC exit

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_thread.h
LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/elf/shim_rtld.c
LibOS/shim/src/generated-offsets.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_fork.c
LibOS/shim/src/sys/shim_migrate.c
LibOS/shim/src/sys/shim_sigaction.c
LibOS/shim/src/sys/shim_vfork.c
LibOS/shim/src/syscallas.S
LibOS/shim/src/utils/printf.c
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/futex.c
LibOS/shim/test/regression/futex.manifest.template
Pal/src/pal.h

For static binary support, %fs register can't be used for shim tls
because it's already used by libc.
Use part of PAL TCB TLS to stash shim tls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/556)

[LibOS] use %gs for libos tcb

---

LibOS/glibc-patches/glibc-2.19.patch
LibOS/glibc-patches/glibc-2.23.patch
LibOS/glibc-patches/glibc-2.27.patch

[LibOS/glibc] remove struct shim_tcb embedded in glibc tcb
By https://github.com/oscarlab/graphene/pull/556, struct shim_tcb
embedded in glibc tcb isn't needed any more. Remove it from glibc patches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1135)

remove shim tcb embedded in glibc tcb

---

LibOS/shim/include/shim_table.h
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_mmap.c

This call is used by libnuma. Always returning success seems to be enough.
This is probably not needed at all, but I'll leave this here for future. This was detected when working on Python3 with NumPy (it loads libnuma which does `mbind()`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1123)

[LibOS] Add dummy implementation of Linux-specific mbind()

---

Pal/src/host/Linux-SGX/db_files.c

Previously, if a file marked as sgx.trusted_files was empty, Graphene-SGX still tried to mmap it. However, mmap with zero length fails, so Graphene-SGX refused such empty files. In some cases (e.g. Python's `__init__.py` files) trusted files indeed must be empty. This commit allows to open empty trusted files.
Python's PR (https://github.com/oscarlab/graphene-tests/pull/29) must run correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1145)

[Pal/Linux-SGX] Do not fail on empty sgx.trusted_files

---

Pal/src/db_events.c
Pal/src/db_ipc.c
Pal/src/db_mutex.c
Pal/src/db_object.c
Pal/src/db_process.c
Pal/src/db_streams.c
Pal/src/db_threading.c
Pal/src/pal.h

Trivial cleanup: remove unused `TRACE_HEAP` macro and code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1151)

[Pal] Remove unused TRACE_HEAP macro and code

---

Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/sgx_arch.h

When the AC flag is set, any unaligned data access forces an #AC exception. This constitutes a subtle side channel, similar to other controlled-channel attacks (e.g., page fault attacks on SGX enclaves).
These vulnerability was discovered and disclosed by David Oswald, Jo Van Bulck, and others. More details can be found in their paper "A tale of two worlds: Assessing the vulnerability of enclave shielding runtimes" (https://people.cs.kuleuven.be/~jo.vanbulck/ccs19-tale.pdf and https://github.com/jovanbulck/0xbadc0de).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1150)

[Pal/Linux-SGX] Clear the Alignment Check (AC) flag in RFLAGS upon enclave entry

---

Pal/regression/nonelf_binary
Pal/regression/nonelf_binary.manifest.template
Pal/regression/test_pal.py
Pal/src/host/Linux-SGX/sgx_main.c

Signed-off-by: jack.wxz <jack.wxz@alibaba-inc.com>
1. check that the binary file is not smaller than the elf-head size,
2. check if the binary is in elf format.
1. set exec to a posix shell:
loader.exec = file:/tmp/non-elf
2. /tmp/non-elf:
```
#!/bin/sh
exec /bin/ls -DOHMYGODTHISISERROR
dasfsafsa
asdf
asf
```
3. run testcase will cause a segmentation fault,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1146)

Avoid segmentation fault errors when loading non-elf files.

---

LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/sigprocmask.c
LibOS/shim/test/regression/test_libos.py

In set_signal_mask(), remove the mask of SIGKILL and SIGSTOP.
Signed-off-by: jack.wxz <jack.wxz@alibaba-inc.com>
In signal processing, SIGKILL and SIGSTOP cannot be ignored.
This causes the multi-thread program to call exit() but hang: because the SIGKILL is ignored.
testcase added to LibOS/shim/test/regression/test_libos.py
```
def test_404_sigprocmask(self)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1159)

[LIBOS]In set_signal_mask(), remove the mask of SIGKILL and SIGSTOP.

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_tcb.h
LibOS/shim/include/shim_thread.h
LibOS/shim/include/shim_tls.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/generated-offsets.c
LibOS/shim/src/ipc/shim_ipc_helper.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/shim_checkpoint.c
LibOS/shim/src/shim_debug.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/shim_parser.c
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_fork.c
LibOS/shim/src/sys/shim_vfork.c
Pal/src/host/Linux-SGX/db_threading.c

As follow up of #556 , more code clean up.
- remove dead code in shim_thread.h
- rename shim_tls.h -> shim_tcb.h
- rename shim_tls_check_canary to shim_tcb_check_canaryo
- move fs_base from shim_thread to shim_tcb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1143)

[LibOS] gs tcb cleanup

---

Pal/src/host/Linux-SGX/enclave_entry.S

Previously, Case A in the in-enclave exception handler in enclave_entry.S incorrectly set RDI register to -EINTR (to indicate interrupted syscall) of the current CPU context, instead of setting RDI register of the interrupted CPU context (which is accessed via SGX_GPR_RDI). This led to very rare data races that hanged the interrupted thread/corrupted its memory, because -EINTR incorrectly propated to SGX_GPR_RSI that holds external event (signal number) and this led to buffer overflows.
This was once a part of PR #1162 but I decided to split that one in several new PRs.
Since this fixes a data race, the bug manifested itself in multi-threaded tests with Pthreads and signals. In particular, LibOS tests `abort_multithread` and `spinlock` are good candidates for stress …

[Pal/Linux-SGX] Correctly propagate arguments to _DkHandleExternalEvent()

---

LibOS/shim/src/Makefile
Pal/lib/Makefile

This PR is a rebase of #1163. That PR used a master branch in the forked repo, and I screwed up in the process of rebase & push. Anyway, #1163 is closed now, and this PR is its rebase.
Previously, Graphene libraries were built using `wildcard` make function. The output of this function (list of files) is non-deterministic (list items can be in any order). This results in different SGX measurements on rebuilds.
In some build environments (e.g., a dedicated Graphene container), it is important to keep these measurements deterministic. This commit achieves this by removing wildcards and explicitly specifying required files.
--- …

[Makefiles] Link Graphene libraries in a fixed order

---

Pal/src/host/Linux-SGX/db_pipes.c

During Graphene initialization, a "server" pipe is created by the IPC thread. Previously, upon app exit, Graphene's Linux-SGX PAL removed this named pipe. However, this is not needed and led to occasional segfaults. (Note that Linux PAL never had this code). This commit simply removes the offending code.
This bug was first found here: https://github.com/oscarlab/graphene/issues/1117#issuecomment-549642291. The fix (same as in this PR) was subsequently incorporated in this PR: https://github.com/oscarlab/graphene/pull/1128 (see commit fc2039674d2b71af3e924cbbdc6d94634a933142).
Currently, our master branch fails on LibOS tests `test_403_signalexit_multithread` and `test_404_sigprocmask` due to this bug. This only happens on Graphene-SGX built in *debug* mode (thus it was not catched by our …

[Pal/Linux-SGX] db_pipes.c: fix segfault due to redundant deletion of pipe

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile

We are missing Nginx from Jenkins tests for no good reason. This PR adds it to all Jenkins pipelines.
The corresponding PR in graphene-tests is https://github.com/oscarlab/graphene-tests/pull/55.
Jenkins must run Nginx now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1176)

[Jenkins] Add Nginx test to all Jenkins pipelines

---

LibOS/shim/include/shim_defs.h
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/test/regression/exec_same.c
LibOS/shim/test/regression/test_libos.py

The execve() syscall starts a new executable in the *same* process. Previously, Graphene followed this convention *only* for non-SGX PALs. If PAL was Linux-SGX, Graphene silently terminated the process and created a new one.
This deviation from standard execve() behavior resulted in the host shell becoming detached from the Graphene-SGX process. In turn, this led to our Bash example (on Ubuntu 18.04, bash version 4.4.19) "terminating" early from the point of view of Jenkins, and SGX-18.04 pipeline failed.
This commit allows Graphene-SGX to execve() in the same process, but only if it is the same executable (as in the Bash example). It is still impossible to execve() in the same process for a different executable since this requires a new SGX enclave measurement and thus demands a new …

[LibOS] Allow Graphene-SGX to occupy the same process on execve()

---

LibOS/shim/src/shim_checkpoint.c
LibOS/shim/test/regression/eventfd.c
LibOS/shim/test/regression/test_libos.py
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux/db_streams.c
Pal/src/pal_internal.h

Changes to support fork operation on eventfd descriptor.
Also fixing couple of issues in migration process from parent to child,
that were uncovered while working on this.
Thanks to Dmitrii, to help root-cause the issue.
Added new function->eventfd_using_fork in LibOS/shim/test/regression/eventfd.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1157)

Changes to support fork operation on eventfd descriptor.

---

LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/shim_parser.c

`test_user_memory` did not work correctly with NULL pointer + fixes #1189
LTP and LibOS regression with debug = inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1192)

[LibOS] Add user pointer test in debug pipe parser

---

Pal/lib/Makefile
Pal/lib/pal_crypto.h

Graphene moved to mbedTLS due to licensing issues, and all WolfSSL files were deleted from the repo long time ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1191)

[Pal/lib] Remove lingering mentions of WolfSSL

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04
LibOS/shim/test/Makefile
LibOS/shim/test/fs/.gitignore
LibOS/shim/test/fs/Makefile
LibOS/shim/test/fs/README.md
LibOS/shim/test/fs/common.c
LibOS/shim/test/fs/common.h
LibOS/shim/test/fs/common_copy.c
LibOS/shim/test/fs/copy_mmap_rev.c
LibOS/shim/test/fs/copy_mmap_seq.c
LibOS/shim/test/fs/copy_mmap_whole.c
LibOS/shim/test/fs/copy_rev.c
LibOS/shim/test/fs/copy_seq.c
LibOS/shim/test/fs/copy_whole.c
LibOS/shim/test/fs/delete.c
LibOS/shim/test/fs/manifest.template
LibOS/shim/test/fs/open_close.c
LibOS/shim/test/fs/read_write.c
LibOS/shim/test/fs/seek_tell.c
LibOS/shim/test/fs/stat.c
LibOS/shim/test/fs/test_fs.py
LibOS/shim/test/fs/truncate.c

First of all, these tests were originally designed for my protected files implementation. @mkow convinced me to "backport" them so they can also be used for "normal" files. Protected file tests now build upon this PR, hence some things may appear strange (like testing various file sizes).
These tests perform common FS operations in various ways:
- open/close
- read/write
- create/delete
- read/change size
- seek/tell
- memory-mapped read/write
- copy directory in different ways
To run, call `make test` in `LibOS/shim/test/fs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1062)

[LibOS] Add tests for some typical FS use cases

---

Documentation/oldwiki/Signal-Handling-in-Graphene.md
Pal/src/host/Linux-SGX/db_exception.c

Graphene-SGX has two logical paths: (1) starting from `_DkHandleExternalEvent()` if thread received a signal while not in enclave mode, and (2) starting from `_DkExceptionHandler()` if thread was in enclave mode (both in `db_exception.c`).
`_DkExceptionHandler()` contained two racy bugs pertaining to the frame variable. Bugs are described in detail in issue #230. The frame tries to find the outer-most enclosing `Dk*` PAL function, but since `_DkExceptionHandler()` happens during enclave-mode execution, there may be no such frame at all. That is why `_DkExceptionHandler()` always calculates and passes further the enclave context. Thus, the frame is not needed at all and can be removed, thus eliminating the corresponding bugs. As a result, an intermediate function …

[Pal/Linux-SGX] Remove calculation of frame from _DkExceptionHandler()

---

README.rst

Our README contains this incorrect command:
```
sudo sysctl vm.mmap_min = 0
```
It should be:
```
sudo sysctl vm.mmap_min_addr = 0
```
Fixes https://github.com/oscarlab/graphene/issues/1198.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1200)

[README] Fix "vm.mmap_min_addr" line

---

LibOS/shim/src/bookkeep/shim_thread.c

shim_thread::signal_handles[].action is __kernel_sigaction, not struct shim_signal_handle.
the copy size was wrongly 8 byte.
Because the first member of __kernel_sigaction is signal handler (un?)fortunately,
signal handler is copied. That's the reason why this issue hasn't been revieled.
ltp kill12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1202)

[LibOS] copy signal handler on get_new_thread()

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-18.04-apps
Jenkinsfiles/Linux-SGX-apps

This PR (1) splits Jenkins-SGX into two pipelines and (2) adds Redis tests to all pipelines.
More details:
1. [Jenkins] Split SGX pipelines into two: tests and apps. Previously, it took more than 30-45 minutes to run one SGX pipeline. This commit splits that SGX pipeline into two: one runs LibOS/PAL tests and LTP tests, the other one runs only application examples. The times to run each of these pipelines are roughly the same. Splitting SGX pipelines decreases wait time for Jenkins in half.
2. [Jenkins] Add Redis test to all Jenkins pipelines. Redis is tested with select() syscall on 16.04 pipelines and with epoll() on 18.04 pipelines.
The corresponding PR is https://github.com/oscarlab/graphene-tests/pull/60.
All pipelines must succeed.
--- …

[Jenkins] Split SGX pipelines and add Redis

---

LibOS/shim/include/shim_internal.h
LibOS/shim/include/shim_thread.h
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/ipc/shim_ipc_child.c
LibOS/shim/src/shim_async.c
LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_clone.c
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_exit.c
LibOS/shim/src/sys/shim_futex.c
LibOS/shim/test/regression/test_libos.py
Pal/src/host/Linux-SGX/sgx_thread.c

Previously, there was a data race on `thread::is_alive` between one thread checking whether it is the last thread alive via `check_last_thread()` and another thread exiting via `thread_exit()`. The former checks if `is_alive` is true, the latter sets it to false. However, the exiting thread will truly exit only after it called `DkThreadExit()`, thus the race on `is_alive` led to scenarios where two threads believe to be the last threads alive and compete on terminating Async Helper/IPC threads and exiting the whole process.
This PR introduces `cleanup_thread()` called by Async Helper to set `is_alive` to false and delete the thread, freeing its resources. The data race is thus removed, and shim_thread object leak is prevented.
Additionally, I found a bug in thread-exiting in Linux-SGX …

[LibOS] Remove the data race on thread::is_alive

---

LibOS/shim/include/shim_fs.h
LibOS/shim/src/fs/shim_namei.c
LibOS/shim/test/regression/host_root_fs.c
LibOS/shim/test/regression/host_root_fs.manifest.template
LibOS/shim/test/regression/test_libos.py

This PR does two things:
1. [LibOS] Allow inaccessible files during `getdents()`. Previously, if user performed `getdents()` on a directory containing inaccessible files (because user doesn't have permission), whole getdents failed with `-EACCES`. This is incorrect behavior: files must still be listed. This commit fixes the root cause of this bug by marking inaccessible files as `DENTRY_NEGATIVE`.
2. [LibOS/regression] Add test for host root FS. Graphene support a special "root FS" parameter in the manifest: `fs.root`. This commit adds a test that uses this parameter.
This PR is in response to https://github.com/oscarlab/graphene/issues/1179. It looks like Graphene supports host-root out of the box (bar a tiny fix in this PR). To close #1179, we'll need more tests on real applications …

[LibOS/regression] Add test for host root FS

---

.pylintrc

Test classes and functions are named TC_01_Example and test_012_example,
respectively. Those are not conforming to the usual style enforced by
pylint but that's okay.
There should not be any pylint problems against `test_{pal,libos}` test modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1222)

[CI] fix linting test names

---

Pal/src/host/FreeBSD/db_pipes.c
Pal/src/host/FreeBSD/db_process.c
Pal/src/host/FreeBSD/db_streams.c
Pal/src/host/FreeBSD/pal_freebsd_defs.h
Pal/src/host/FreeBSD/pal_host.h
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_process.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/pal_security.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_platform.c
Pal/src/host/Linux-SGX/sgx_process.c
Pal/src/host/Linux/db_pipes.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Linux/pal_host.h
Pal/src/host/Linux/pal_linux_defs.h

The main objective of this PR is to replace host-level pipes with UNIX domain socketpairs.
This is in preparation for follow-up encrypted IPC PRs.
Graphene already emulates pipes via UNIX domain socketpairs. The only place where Graphene still uses host pipes is in `DkCreateProcess()`, for communication and checkpoint send/receive between parent and child. UNIX domain socketpairs are more convenient than pipes and allow bidirectional communication, which is useful for IPC encryption via SSL/TLS. This commit replaces all lingering uses of pipes with socketpairs.
This PR also removes some dead code:
1. Graphene now has a reworked parent-child verification and SGX local attestation protocol. Remove the dead commented-out code that is not needed anymore, along with unused macros.
2. Remove …

Replace pipes with socketpairs

---

LibOS/shim/test/inline/fork.c
LibOS/shim/test/inline/helloworld.c
LibOS/shim/test/inline/vfork.c
LibOS/shim/test/native/fs.c
LibOS/shim/test/native/kill.c
LibOS/shim/test/native/script.c
LibOS/shim/test/regression/exec.c
LibOS/shim/test/regression/proc-path.c
Pal/src/host/Linux-SGX/test-sgx.c

Fixes some bloopers in our tests regarding return values (e.g. missing `return 0` at the end of `main()`).
Should fix failures such as [this one](https://leeroy.cs.unc.edu/job/graphene-sgx/3034/testReport/junit/test_libos/TC_40_FileSystem/test_010_path/) (`subprocess.CalledProcessError: Command '['proc-path']' returned non-zero exit status 139`, but no other errors on the output).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1237)

[LibOS] tests: Fix missing/wrong return values from main()

---

Documentation/oldwiki/Graphene-Manifest-Syntax.md
LibOS/shim/src/sys/shim_eventfd.c
LibOS/shim/test/regression/eventfd.manifest.template

Eventfd emulation currently relies on the host, thus eventfd syscalls are disallowed by default due to security concerns. To use them, they must be explicitly allowed through `sys.allow_insecure_eventfd` in manifest.
LibOS regression test `eventfd` now has its own manifest file with `sys.allow_insecure_eventfd = 1`. One can remove this line and see how this test fails with `eventfd failed: Function not implemented`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1233)

[LibOS] Disallow eventfd emulation by default

---

Pal/regression/test_pal.py
Pal/src/host/Linux-SGX/enclave_platform.c
Pal/src/host/Linux-SGX/sgx_attest.h
README.rst

This PR adds `sgx.ra_accept_configuration_needed` manifest option to handle the case when SGX remote attestation from IAS returns status `CONFIGURATION_NEEDED` (which means that this SGX platform is not known to be compromised but has e.g. hyper-threading enabled).
See #1231 and https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/798777.
Fixes #1231.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1232)

[Pal/Linux-SGX] Add sgx.ra_accept_configuration_needed manifest option

---

LibOS/shim/src/fs/str/fs.c
LibOS/shim/test/regression/str_close_leak.c
LibOS/shim/test/regression/test_libos.py

Fixes a resources leak where repeatedly opening and closing files in, for example, proc, led to memory exhaustion.
This PR comes with a regression test. Regression should still pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1219)

Correctly release resources during str_close().

---

Documentation/oldwiki/PAL-Host-ABI.md
LibOS/shim/include/shim_handle.h
LibOS/shim/include/shim_internal.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/src/sys/shim_poll.c
LibOS/shim/test/regression/poll.c
LibOS/shim/test/regression/ppoll.c
LibOS/shim/test/regression/pselect.c
LibOS/shim/test/regression/select.c
LibOS/shim/test/regression/test_libos.py
Pal/src/db_object.c
Pal/src/host/Linux-SGX/db_object.c
Pal/src/host/Linux/db_object.c
Pal/src/host/Linux/db_pipes.c
Pal/src/host/Skeleton/db_object.c
Pal/src/pal-symbols
Pal/src/pal.h
Pal/src/pal_internal.h

- [Pal/{Linux,Linux-SGX}] Cleanup of db_object.c:
- Remove _DkObjectWaitOne() and incorporate its special-case of
waiting on single mutex/event in _DkObjectsWaitAny().
- Refactor _DkObjectsWaitAny() for readability.
- Remove unused DEFAULT_QUANTUM and TRACE_HEAP_LEAK.
- [LibOS] Comprehensive cleanup of poll()/ppoll()/select()/pselect()
- [LibOS] Comprehensive cleanup of epoll_create()/epoll_ctl()/epoll_wait()
- [Pal/Linux-SGX] db_pipes.c: fix segfault due to redundant deletion of pipe
- [LibOS, Pal/{Linux,Linux-SGX}] Better emulation of polling; improves the emulation of polling mechanisms (select, pselect, poll, ppoll, epoll_wait) and cleans up the corresponding code:
- New DkObjectsWaitEvents() PAL interface, replaces the inefficient DkObjectsWaitAny() interface. This interface closely …

[LibOS,Pal] Rewrite poll and ObjectWait logic from scratch

---

LibOS/shim/src/fs/shim_namei.c
LibOS/shim/src/sys/shim_fs.c

These bugs caused some LTP test to fail at cleanup
Fixes #1023
One of the test failing in #1023 was actually another issue: https://github.com/oscarlab/graphene/issues/1248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1240)

[LibOS] Fix some bugs related to O_DIRECTORY handling

---

LibOS/shim/src/fs/chroot/fs.c
LibOS/shim/src/fs/shim_namei.c
LibOS/shim/test/regression/file_size.c
LibOS/shim/test/regression/readdir.c
LibOS/shim/test/regression/test_libos.py

1. chroot_open(): update ino after creating a new file
2. chroot_write(): update file size after writing a file of buf_type != FILEBUF_MAP
1. chroot_open(): update ino after creating a new file
2. chroot_write(): update file size after writing a file of buf_type != FILEBUF_MAP
```
cd LibOS/shim/test/regression/ 
make regression
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1213)

bugfix for filesystem

---

LibOS/shim/include/shim_checkpoint.h

Checkpoint's total memory size is stored in `shim_cp_store::mem_size` field. Previously, this field was of type `int`. When a process allocates more than 2GB of memory and then tries to spawn a child,
the checkpoint send/receive fails due to int overflow of `mem_size`. This PR simply changes mem_size type to `size_t`. This is enough to make the bug go away on e.g. a huge Python app with TensorFlow.
This bug was triggered on a huge Python app with TensorFlow. Generally, this bug is triggered on huge apps. I don't think it deserve a separate test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1264)

[LibOS] Fix type of checkpoint's total memory size variable

---

LibOS/shim/src/bookkeep/shim_vma.c
LibOS/shim/src/sys/shim_mmap.c
LibOS/shim/test/regression/mprotect_file_fork.c
LibOS/shim/test/regression/test_libos.py

`VMA_TAINTED` flag was not applied in `mprotect`. 
Added a regression test for it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1258)

[LibOS] Add VMA_TAINTED in mprotect

---

.ci/run-pylint

From Ubuntu 19.10 pylint3 was replaced with pylint.
use pylint if pylint3 is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1269)

[CI] run-pylint: use pylint if pylint3 is missing

---

Pal/src/host/Linux-SGX/sgx_main.c

Previously, Graphene-SGX always tried to initialize communication with AESM enclaves (Launch Enclave, Quoting Enclave, etc.) on startup. This is only needed for SGX Remote Attestation (RA). This commit disables AESM init if the manifest doesn't explicitly specify need for SGX RA.
This allows non-provisioned SGX machines to run Graphene locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1270)

[Pal/Linux-SGX] Init communication with AESM only when app requests RA

---

Pal/src/host/Linux-SGX/db_eventfd.c
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_object.c
Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux-SGX/db_process.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux/db_eventfd.c
Pal/src/host/Linux/db_files.c
Pal/src/host/Linux/db_main.c
Pal/src/host/Linux/db_object.c
Pal/src/host/Linux/db_pipes.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/db_sockets.c
Pal/src/host/Linux/pal_host.h
Pal/src/host/Linux/pal_linux_defs.h

Previously, `WRITABLE` flag in PAL was used as a performance optimization to skip host-based `ppoll()` syscall. However, `ppoll()` is used anyway to update the `READABLE` flag. Therefore, there is no performance cost to update `WRITABLE` via the same `ppoll()`, and we can remove complex logic of updating `WRITABLE` on each write/send. Also, now Graphene has proper emulation of select/poll/epoll via `DkStreamsWaitEvents()`, so there is no performance benefit for caching `WRITABLE` anyway.
As a preparation for the above, this PR also contains a commit with clean-up: Clean up and make uniform the `attrquerybyhdl()` callback for stream PAL handles: process, socket, pipe, and eventfd. This includes using `ioctl(FIONREAD)` to query the number of bytes available for reading and using `ppoll()` …

[Pal] Remove WRITABLE flag from PAL handles

---

LibOS/shim/include/shim_handle.h
LibOS/shim/include/shim_types.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/sys/shim_epoll.c
LibOS/shim/src/sys/shim_open.c
LibOS/shim/src/sys/shim_poll.c
LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/regression/poll_many_types.c
LibOS/shim/test/regression/tcp_msg_peek.c
LibOS/shim/test/regression/test_libos.py

The main purpose of this PR is to add `MSG_PEEK` emulation in LibOS during `recv()`. I also had to fix a couple small bugs in poll and epoll to be able to test it with Nginx in SSL/TLS mode.
The commit summary:
- [LibOS] Allow `MSG_PEEK` on `recv()`. Previously, Graphene failed if `recv()` contained `MSG_PEEK` flag. This resulted in many TLS-based applications failing, including Nginx, Apache, and Lighttpd in SSL/TLS mode. This commit adds emulation of `MSG_PEEK` at LibOS level. A simple TCP test case is provided.
- [LibOS] Allow poll/ppoll/select/pselect on regular and dev files. Previously, Graphene incorrectly handled poll/ppoll/select/pselect of regular and dev files like `/dev/urandom`: it tried to perform an actual host-OS poll on these files. However, poll of such files must be …

[LibOS] Allow MSG_PEEK on recv() + small bug fixes

---

LibOS/shim/test/native/manifest.template
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/signer/pal-sgx-sign

Path to enclave file had been a fixed string that is determined at build time. Therefore Runtime binares were not allowed to move their location.
This commit adds sgx.enclave_file manifest option to specify the uri of libpal-Linux-SGX.so.
Modified `sgx_main.c` of Linux-SGX PAL to be aware of the new `sgx.enclave_file` manifest option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1254)

[Pal/Linux-SGX] Add manifest option sgx.enclave_file

---

LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/regression/getsockopt.c
LibOS/shim/test/regression/test_libos.py

Previously in Graphene, some `getsockopt()` syscalls, e.g. TCP_NODELAY, failed because an underlying PAL handle was't created for the LibOS handle until `bind()` was called. Thus, a sequence of `accept()` and `getsockopt()` failed. This commit fixes this by returning default socket options (possibly augmented with setsockopt values). Test case is also provided.
Fixes #644. Fixes #754.
LibOS test `getsockopt` is augmented with an additional case of TCP_NODELAY that fails without this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1257)

[LibOS] Allow all getsockopt() before bind()

---

Pal/src/host/Linux-SGX/sgx_thread.c
Pal/src/host/Linux/db_threading.c

Previously, Graphene's PALs specified `CLONE_PTRACE` flag on any thread creation. This led to debuggers (GDB, strace, other ptrace-based debuggers) always tracing child threads, even if they did not subscribe to such events (debuggers usually use `PTRACE_O_TRACECLONE` and similar flags to start tracing child threads/processes). This PR removes `CLONE_PTRACE` flag such that debuggers have a chance to ignore child threads; this improves stability and performance of ptracing.
This bug was found when working on a custom ptrace-based debugger on a machine with a huge number of cores (~100 logical cores). Even though I was only interested in one (main) thread, the debugger suddenly ptraced all 100 spawned threads, and this led to awful performance. This PR allows to pass the decision on what to …

[Pal/{Linux,Linux-SGX}] Remove CLONE_PTRACE flag on thread creation

---

.dir-locals.el

update .dir-locals.el aware of COMIMT_EDITMSG for 80 columns
What column is desired for our graphene project?
Typically 72 columns for message body(50 for subject line) is recommended. We can chose our own.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1274)

make .dir-locals.el aware of COMMIT_EDITMSG for 80 column

---

LibOS/.gitignore
Pal/src/host/Linux-SGX/quote/.gitignore

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1280)

add generated-cacert.h and glibc-build to .gitignore

---

Pal/lib/Makefile

`Pal/lib/config.h` was not listed as dependency anywhere in the Makefile, so any change to it broke building process (of course it works when you ~download code for the first time~ run `make -C Pal/lib distclean`, like Jenkins does).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1281)

[Makefile] Fix lack of config.h dependency in lib/Makefile

---

Pal/lib/Makefile

Previous commit fixed the dependency on crypto/config.h (it must be copied into mbedtls include directory). However, config.h with default and incorrect settings already exists in mbedtls include
dir after its download, and Graphene needs to replace it with our version of configuration. This commit simply removes default config.h on first build of mbedTLS to force the dependency introduced in the previous commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1282)

[Makefile] Remove mbedtls's config.h on first build in lib/Makefile

---

Pal/src/host/Linux-SGX/enclave_entry.S
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/generated-offsets.c
Pal/src/host/Linux-SGX/sgx_tls.h

When reviewing PR #1238 I notice that with in the current version of `enclave_entry.S` we can get rid of the code emulation in `.Lsetup_exception_handler` when we avoid using two variables to keep track of the "we prepared for an ocall" state.
This PR is on top of #1238 to make reviewing and merging easier (So remember to look at the right diff).
Should not break any regression tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1266)

[Pal/Linux-SGX] Unify SGX_OCALL_PREPARED and SGX_STACK

---

Pal/src/host/Linux-SGX/db_exception.c
Pal/src/host/Linux-SGX/enclave_xstate.c

PR https://github.com/oscarlab/graphene/pull/1238 was merged. But it accidentally prints debug information even in non-debug mode. This is annoying and confuses people. This PR simply changes debug level to not show this info in non-debug mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1285)

[Pal/Linux-SGX] Do not show SGX context debug info in non-debug build

---

LibOS/shim/src/sys/shim_socket.c
LibOS/shim/test/regression/tcp_ipv6_v6only.c
LibOS/shim/test/regression/test_libos.py
Pal/src/host/Linux-SGX/db_pipes.c
Pal/src/host/Linux-SGX/db_sockets.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_linux_error.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux/db_sockets.c
Pal/src/host/Linux/pal_linux_error.h
Pal/src/pal.h

Previously, PALs in Graphene set `IPV6_V6ONLY = 1` on socket creation in case of IPv6 protocol. This setting made Graphene silently ignore connection requests from IPv4 clients. In particular, this made
Apache web server with SSL/TLS unresponsive to clients. There is no reason to have this explicit setting, so this commit removes it.
All tests must pass. Another of my PRs will introduce Apache with SSL/TLS that fails without this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1276)

[Pal/{Linux,Linux-SGX}] Remove IPV6_V6ONLY flag on socket creation

---

Pal/src/host/Linux-SGX/db_memory.c

Linux-SGX PAL uses `pal_vmas[PAL_VMA_MAX]` array to keep track of allocated internal-PAL memory regions. Previously, Graphene only added items to this array (during DkVirtualMemoryAlloc) but never removed them from the array (during DkVirtualMemoryFree). Also, the code used an assert() instead of proper error handling, which led to Heisenbugs in non-debug builds.
This PR fixes this but in a rather inefficient way. Memory allocation in SGX is sub-par and will need a complete rewrite.
Redis under SGX with 100 clients must work now:
```
~/graphene/LibOS/shim/test/apps/redis$ ./src/src/redis-benchmark -h 127.0.0.1 -p 6379 -c 100 -n 1000000 -t get,set
```
--- …

[Pal/Linux-SGX] Update internal-PAL pal_vmas when freeing memory

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-SGX
Jenkinsfiles/Linux-SGX-apps
LibOS/Makefile
LibOS/shim/Makefile
LibOS/shim/src/Makefile
LibOS/shim/test/Makefile
LibOS/shim/test/Makefile.Test
LibOS/shim/test/native/Makefile
Makefile
Pal/Makefile
Pal/lib/Makefile
Pal/regression/Makefile
Pal/src/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux/Makefile
Pal/src/host/Skeleton/Makefile
Pal/test/Makefile
Runtime/Makefile
Scripts/Makefile

Before there were no target that cleaned up downloaded sources. To match
the 'apps' Makefiles add a distclean target.
Run `make distclean` and/or see Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1288)

[Makefile] add distclean target

---

.ci/run-shellcheck
LibOS/Makefile
Pal/lib/Makefile
Pal/src/host/Linux-SGX/Makefile
Scripts/download

Instead of implementing downloading of external resources in every
Makefile again, use a one script. This script adds the following
features:
- Always check the download against a known SHA-256 hash.
- Support caching of downloaded resource (set DL_CACHE=/some/dir).
- Allow offline builds if all files are cached. If DL_OFFLINE=true the
build will never attempt to download something.
Matching PR: https://github.com/oscarlab/graphene-tests/pull/70.
Building should work as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1291)

Improved download handling

---

Jenkinsfiles/Linux
Jenkinsfiles/Linux-18.04
Jenkinsfiles/Linux-Debug
Jenkinsfiles/Linux-Debug-18.04
Jenkinsfiles/Linux-SGX-18.04-apps
Jenkinsfiles/Linux-SGX-apps
Jenkinsfiles/ubuntu-16.04.dockerfile
Jenkinsfiles/ubuntu-18.04.dockerfile
LibOS/shim/include/shim_handle.h
LibOS/shim/src/bookkeep/shim_handle.c
LibOS/shim/src/fs/dev/fs.c

For device handles, `info.dev.dev_ops` contains function pointers into LibOS. They may become invalid due to relocation of LibOS text section in the child process on fork. This commit forces an update of these function pointers.
In particular, this bug was found on Ubuntu 18.04 while working on Apache with SSL/TLS. For some reason, LibOS text segment (`libsysdb.so`) is relocated in another place in memory in the child process, so Apache tried to access `/dev/urandom` that ended up in a function pointer that pointed to the old (parent's) value in memory, and we had a segfault. See https://github.com/oscarlab/graphene-tests/pull/68.
Closes #1277.
Apache with SSL/TLS must pass now (included as a separate commit in this PR).
--- …

[LibOS] Update TYPE_DEV handles with correct function pointers in dev_ops

---

LibOS/shim/include/shim_signal.h
LibOS/shim/include/shim_thread.h
LibOS/shim/src/bookkeep/shim_signal.c
LibOS/shim/src/bookkeep/shim_thread.c
LibOS/shim/src/sys/shim_sigaction.c
LibOS/shim/src/sys/shim_sleep.c

shim_signal_logs::{head, tail} aren't initialized correctly.
and shim_signal_logs::logs aren't freed on thread exit. (memory leak)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1294)

[LibOS] properly initialize/free shim_thread::shim_signal_logs

---

.ci/prfilter

This is a tiny followup to PR #976: It drops pal_loader from the ignore list in 'prfilter'.
Run CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1299)

[CI] Runtime/pal_loader has been cleaned up, remove from ignore list

---

Runtime/pal_loader

GDB support was not working, this is why.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1318)

[Runtime] Fix pal_loader bash script typo

---

LibOS/glibc-patches/glibc-2.23.patch
LibOS/glibc-patches/glibc-2.27.patch

Delete INLINE_SYSCALL_ASM and its related macros. It's same as INLINE_SYSCALL.
Also the changes to INLINE_SYSCALL are unnecessary churn now.
It seems like legacy from old patches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1304)

[LibOS] remove INLINE_SYSCALL_ASM and related changes

---

LibOS/shim/include/shim_table.h
LibOS/shim/src/shim_syscalls.c
LibOS/shim/src/sys/shim_ioctl.c

The second argument to ioctl is unsigned long, not int.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1307)

[LibOS] change ioctl(, int cmd) to ioctl(, unsigned long cmd)

---

LibOS/shim/src/Makefile

There is no code depending OMIT_FRAME_POINTER.
Remove it. If it's wanted, simply specify CFLAGS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1312)

[LibOS] Makefile remove OMIT_FRAME_POINTER

---

LibOS/shim/include/shim_thread.h

add_thread_to_queue() should use struct wake_queue_node* instead of void*.
add_thread_to_queue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1308)

[LibOS] use right type, struct wake_queue_node*, instead of void*

---

Pal/src/host/Linux-SGX/sgx_exception.c

unset_sighandler() is broken. SIG_DFL can't be struct sigaction.
delete the function instead of fixing it because it's unused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1316)

[Pal/Linux-SGX] eliminate an unused function, unset_sighandler()

---

.ci/run-pylint

- exclude .py from glibc, ltp.
- ignore error of return code of command
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1301)

[CI] run-pylint: exclude .py from external source

---

LibOS/shim/include/shim_checkpoint.h
LibOS/shim/src/sys/shim_exec.c
LibOS/shim/src/sys/shim_fork.c
LibOS/shim/src/sys/shim_migrate.c

BEGIN_MIGRATION_DEF() is used to define nested function unnecessarily.
make them normal(non-nested) function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1310)

[LibOS] eliminated unnecessary nested function

---

LibOS/shim/src/Makefile
Pal/lib/Makefile
Pal/src/Makefile
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux/Makefile

The current Makefiles are unnecessary too smart to avoid (too small, I think)
duplication. It resulted that it's hard to understand what files are listed.
Instead, use plain explicit listing.
Also append .o to objs variables. Usually obj means .o file, not the base name
of file. It was confusing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1314)

[Makefile] list object files in plain manner

---

.ci/prfilter
.ci/run-shellcheck
Documentation/oldwiki/Graphene-SGX-Quick-Start.md
Documentation/oldwiki/Introduction-to-Graphene-SGX.md
Documentation/oldwiki/Introduction-to-Graphene.md
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/sgx_framework.c
README.rst

Previously, Graphene SGX driver tried to stay compatible with Intel SGX drivers of versions 1.8 and lower. This inflated GSGX driver codebase significantly. Given that Intel SGX driver v1.8 was released in 2017, we can deprecate it and only allow drivers v1.9+ (including DCAP driver).
Corresponding PR is https://github.com/oscarlab/graphene-sgx-driver/pull/12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1328)

[Pal/Linux-SGX] Remove support for Intel SGX drivers version 1.8-

---

Pal/include/lib/slabmgr.h

the size was wrongly calculated STARTUP_SIZE. which should be size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1334)

[Pal/lib] fix slabmgr initialization

---

Pal/regression/test_pal.py

Before this commit the attestation regression test was run even if there
was no SPID/key configured.
Run Pal regression tests on SGX without setting a RA SPID/key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1289)

[Pal/Linux-SGX] Skip attestion test if no RA key is configured

---

Pal/src/host/Linux-SGX/enclave_ecalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/sgx_tls.h

So that the number of ocall can be reduced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1320)

[Pal/Linux-SGX] cache mmap of untrusted area for read/write/recv/send

---

LibOS/shim/src/fs/dev/fs.c
LibOS/shim/src/fs/pipe/fs.c
LibOS/shim/src/fs/proc/fs.c
LibOS/shim/src/fs/proc/info.c
LibOS/shim/src/fs/proc/ipc-thread.c
LibOS/shim/src/fs/proc/thread.c
LibOS/shim/src/fs/shim_namei.c
LibOS/shim/src/fs/socket/fs.c
LibOS/shim/src/sys/shim_fs.c

Some defines (e.g. `S_IFREG`) where missing if some includes where moved around (e.g. `linux/stat.h`) - this PR fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1349)

[LibOS] Fix header import order issue

---

LibOS/shim/include/shim_handle.h
LibOS/shim/src/fs/chroot/fs.c

This patch makes chroot_read/write() simply call DkStreamRead/Write()
for regular file and eliminate mmap trick.
The mmap trick actually causes overhead(one extra memory copy) on Pal/Linux-SGX.
It can be done in Pal/Linux-SGX cleanly.
(which is the future TODO. comment is added there)
The current execution flow is
- if it's not mapped yet,
- find the unmapped region and
- map the file to the region if necessary
Please notice that LibOS passes address for mapping region to Pal.
Pal/Linux-SGX has to copy memory because the region is in enclave.
- memcpy
Its goal seems trying to avoid memory copy and mmap/munmap unnecessary.
In Pal/Linux-SGX, actually DkStreamMap() does one more memory copy in read case
because LibOS passes mapping address for it.
In Pal/Linux case, Either way do only one …

[LibOS] chrootfs: remove mmap logic to read/write

---

Scripts/Makefile.Host

remove leading tab to fix the following error with SGX_RUN=1
> Scripts//Makefile.Host:16: *** recipe commences before first target. Stop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1352)

[Makefile] fix Makefile.Host

---

Pal/src/host/Linux-SGX/Makefile.manifest
Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py

- pal-sgx-sign: add 'key' to dependecy
- cleanup Makefile.manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1321)

[Pal/Linux-SGX] add 'key' to dependency calculation

---

Pal/src/db_main.c
Pal/src/db_rtld.c
Pal/src/pal_internal.h

Pal/Linux-SGX doesn't properly parse exec file and as a result exec_map isn't initialized correctly. As a result Pal/regression doesn't  work on Pal/Linux-SGX.
To be honest, I don't understand why Pal/regression is working on the current CI.
Fix the logic of parsing to make Pal/regression work on Pal/linux-SGX.
As side effect, several struct link_map initialization are fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/845)

[Pal, Pal/Linux-SGX] make Pal/regression work on Pal/Linux-SGX

---

Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/pal_linux.h

eliminated unnecessary mmap/mumap file in untrusted area.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1323)

[Pal/Linux-SGX] optimize opening trusted file

---

LibOS/shim/src/fs/proc/info.c
Pal/include/host/Linux-common/bogomips.h
Pal/include/lib/api.h
Pal/include/pal/pal.h
Pal/lib/stdlib/printfmt.c
Pal/src/host/Linux-SGX/Makefile
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-common/bogomips.c
Pal/src/host/Linux/Makefile
Pal/src/host/Linux/db_main.c

This PR adds bogomips entry to `/proc/cpuinfo`, which is used by some applications (e.g. blender).
Additionally this introduces code shared between PAL-Linux and PAL-Linux-SGX which is first step in removing copy-pasted code in them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1348)

[LibOS,Pal/{Linux, Linux-SGX}] Add bogomips to /proc/cpuinfo

---

Pal/src/host/Linux-SGX/enclave_ocalls.c

#1320 introduced a memory corruption where `__atomic_compare_exchange_n` read a 64-bit value into a 32-bit variable. See https://reviewable.io/reviews/oscarlab/graphene/1320#-M1IhbFd7WaTSxNBCI00.
Yes, GCC seems to be really terrible at type checking in builtins...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1354)

[Pal] Fix memory corruption introduced by #1320

---

LibOS/shim/include/shim_internal.h
Pal/include/lib/api.h
Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_memory.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux-SGX/enclave_pages.c
Pal/src/host/Linux-SGX/enclave_pages.h

Previously, Linux-SGX logic of allocating/freeing enclave pages was complicated and hard to read. This PR refactors this code for readability (`enclave_pages.c`), without changes in functionality.
This PR is a preparation for performance optimizations in memory allocation logic in Linux-SGX. For performance optimizations, see https://github.com/oscarlab/graphene/pull/1332.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1336)

[Pal/Linux-SGX] Refactor memory management of enclave pages

---

.ci/run-pylint

This PR adds a PyTorch example. The corresponding PR is https://github.com/oscarlab/graphene-tests/pull/66.
Since PyTorch installation is huge (~1GB on hard drive and 4GB of enclave size), we don't test in Jenkins. However, this was tested on several machines with Ubuntu 16.04/18.04.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1356)

[LibOS] test/apps: Add PyTorch example

---

LibOS/shim/src/Makefile
LibOS/shim/src/shim.lds
LibOS/shim/src/vdso/vdso.lds

fix syntax error in shim.lds and vdso/vdso.ld and remove useless option,
-dyanmic-link, for ld option which gnu ld ignores.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1306)

[LibOS] fix syntax error shim.lds vdso/vdso.lds

---

Pal/src/host/Linux-SGX/db_files.c
Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_memory.c
Pal/src/host/Linux-SGX/enclave_pages.c
Pal/src/host/Linux-SGX/enclave_pages.h

This PR contains three commits:
1. [Pal/Linux-SGX] Remove pal_vmas array to consolidate VMA logic in enclave_pages.c. Previously, Linux-SGX PAL contained a hack to bookkeep PAL-internal VMAs in the pal_vmas array with 64 VMAs. This limit led to out-of-PAL-memory errors for bigger applications, e.g., with huge number of trusted files. This commit removes the hack with pal_vmas and merges all its logic into the existing VMA bookkeeping logic in `enclave_pages.c`. This eliminates the PAL-internal limit and also improves performance, since there is no need to traverse an additional array (pal_vmas).
2. [Pal/Linux-SGX] Get rid of recursive deadlock of malloc(heap_vma_object). In Linux-SGX PAL, bookkeeping of enclave pages relies on a list of heap-VMA objects. Previously, these objects …

[Pal/Linux-SGX] Consolidate memory allocation logic and work around bugs

---

Pal/src/host/Linux-SGX/enclave_platform.c
Pal/src/host/Linux-SGX/sgx_attest.h
Pal/src/host/Linux-SGX/sgx_platform.c

This PR makes `sgx_quote_t` definition compatible with the SGX SDK.
Attestation test must pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1368)

[Pal/Linux-SGX] Make quote struct the same as in SGX SDK

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_platform.c
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/pal_security.h
Pal/src/host/Linux-SGX/sgx_api.h
Pal/src/host/Linux-SGX/sgx_arch.h
Pal/src/host/Linux-SGX/sgx_internal.h
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_platform.c

Summary of commits in this PR:
- [Pal/Linux-SGX] Rename aesm_targetinfo to qe_targetinfo.
- [Pal/Linux-SGX] sgx_arch.h: Update sgx_report_body_t struct
- [Pal/Linux-SGX] sgx_api.h: Improve comments and fix formatting
- [Pal/Linux-SGX] Introduce generic sgx_get_report() and fix formatting
This PR is the first in the series of Remote Attestation PRs (re-worked #1284). Also see issue #1365.
All tests must pass. This PR is only formatting/renaming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1366)

[Pal/Linux-SGX] Assorted SGX-related fixups

---

Pal/src/host/Linux-SGX/ecall_types.h
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/enclave_platform.c
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/sgx_attest.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_internal.h
Pal/src/host/Linux-SGX/sgx_platform.c

New `sgx_get_quote()` OCALL allows to retrieve the SGX Quote from the Quoting Enclave. The retrieved quote is based on this enclave's SGX report and corresponds to this enclave. The caller of this OCALL may forward the quote to the remote user for remote attestation. A follow-up commit will introduce the actual callers.
This PR is the second in the series of Remote Attestation PRs (re-worked #1284). Also see issue #1365.
It is better to merge it after #1366 (but not necessary).
All tests must pass. Technically, this PR has no tests (the changes introduced here are dead code by themselves) since it is only a prerequisite for the follow-up PR.
--- …

[Pal/Linux-SGX] Introduce sgx_get_quote() OCALL

---

LibOS/shim/src/shim_init.c
LibOS/shim/src/sys/shim_exec.c
Pal/include/pal/pal.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux/db_process.c

Previously, Graphene emulated execve() by silently terminating the intermediate process and creating a new child one. For example, `bash -c ls` would spawn a new Graphene process with `ls` and exit the unnecessary "intermediate" process `bash`. This deviation from standard execve() behavior resulted in the host shell becoming detached from the Graphene process.
This commit simply forces this intermediate process to wait() until the child terminates. This way the host shell stays attached, and all timings and pipes behave correctly.
Fixes #1364. Also see #1181.
The corresponding PR in graphene-tests is https://github.com/oscarlab/graphene-tests/pull/77.
Bash example (in graphene-tests) was updated to remove `sleep 1`. Note that without this PR, removing `sleep 1` would result in failing …

[LibOS,Pal] Force intermediate process to wait for child after execve()

---

Pal/src/host/Linux-SGX/db_main.c
Pal/src/host/Linux-SGX/db_process.c
Pal/src/host/Linux-SGX/db_streams.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/enclave_ocalls.h
Pal/src/host/Linux-SGX/ocall_types.h
Pal/src/host/Linux-SGX/pal_host.h
Pal/src/host/Linux-SGX/pal_linux.h
Pal/src/host/Linux-SGX/pal_security.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_process.c
Pal/src/host/Linux/db_process.c
Pal/src/host/Linux/db_streams.c
Pal/src/host/Linux/pal_host.h

In process-type PAL handle, there were two underlying host FDs: `stream` and `cargo`/`cargo_fd`. The first one was used to send the checkpoint and other messages between parent and child, whereas
the second one was used to send PAL handles via cmsg ancillary data Linux mechanism. In reality, `cargo`/`cargo_fd` can be replaced with `stream` in all scenarios. This PR does that.
This commit is a prerequisite for Encrypted IPC. See also https://github.com/oscarlab/graphene/pull/1377 and https://github.com/oscarlab/graphene/issues/1235.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/1378)

[Pal/{Linux,Linux-SGX}] Remove cargo host-level file descriptor

---

Documentation/manifest-syntax.rst
LibOS/shim/test/regression/Makefile
LibOS/shim/test/regression/multi_pthread_exitless.manifest.template
LibOS/shim/test/regression/test_libos.py
Pal/include/lib/spinlock.h
Pal/regression/Makefile
Pal/regression/Thread2_exitless.manifest.template
Pal/regression/test_pal.py
Pal/src/host/Linux-SGX/ecall_types.h
Pal/src/host/Linux-SGX/enclave_ecalls.c
Pal/src/host/Linux-SGX/enclave_framework.c
Pal/src/host/Linux-SGX/enclave_ocalls.c
Pal/src/host/Linux-SGX/pal_linux_defs.h
Pal/src/host/Linux-SGX/rpc_queue.h
Pal/src/host/Linux-SGX/sgx_api.h
Pal/src/host/Linux-SGX/sgx_enclave.c
Pal/src/host/Linux-SGX/sgx_exception.c
Pal/src/host/Linux-SGX/sgx_internal.h
Pal/src/host/Linux-SGX/sgx_main.c
Pal/src/host/Linux-SGX/sgx_thread.c

This PR succeeds PR #405. It is largely based on the old PR, but is rebased to the current master, and thus some fixes are not needed anymore. No logic was changed.
This PR adds the ability to invoke system calls in an "exitless" fashion (aka asynchronously), similar to solutions from [Eleos by Orenbach](https://dl.acm.org/citation.cfm?id=3064219) and [SCONE by Arnautov et al](https://dl.acm.org/citation.cfm?id=3026930).
New directive `sgx.rpc_thread_num = X` in the manifest instructs Graphene-SGX to create X outside-enclave RPC threads that spin-wait for syscalls (and any OCALLs in general) on a shared queue. In-enclave threads do not exit the enclave now but instead enqueue the syscall in the queue and wait for it to be processed by an RPC thread. Not to waste CPU resources, enclave …

[PAL/Linux-SGX] Add exitless system calls (new version)

---

Documentation/pal/host-abi.rst
Pal/include/pal/pal.h
Pal/src/db_misc.c
Pal/src/host/Linux-SGX/db_misc.c
Pal/src/host/Linux/db_misc.c
Pal/src/host/Skeleton/db_misc.c
Pal/src/pal-symbols
Pal/src/pal_internal.h

New `DkAttestationQuote()` API retrieves the attestation quote from the underlying host-OS attestation mechanism. Currently, it is implemented only for Linux-SGX PAL and stubbed for all other PALs. The Linux-SGX implementation retrieves the SGX quote via `sgx_get_quote()` which communicates with the Quoting Enclave via AESM service. The caller of this new API may forward the obtained quote to the remote user for remote attestation.
This is a part of Remote Attestation PRs. Based on and supersedes #1284. Also see issue #1365.
A follow-up PR will introduce the pseudo-FS interface to actually use this API.
All tests must pass. No new tests are added (will be in a follow-up PR).
--- …

[Pal] Introduce DkAttestationQuote() API for quote retrieval
